### ISSUE TITLE
Implement youtube-related options

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#10]
- [x]  Browsing playlists
- [x]  Browsing related videos
- [ ] Reading comments
- [x] Loading playlists as queues
- [x] Saving playlists locally for later use

**Comment by nukeop** [comment]
Nobody wants to read youtube comments, forget it. The rest works fine.

**Comment by dev-techmoe** [comment]
Hello  
Can you tell me how to load playlists as queues from YouTube? Seems I'm not found this feature in nuclear app... Thank you
