### ISSUE TITLE
Heading to Typescript

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#1002]
Nuclear aims to be a Typescript project.
We are welcome PR to help convert any JS module to TS.
This issue is used for tracking the process.

Guideline: https://nukeop.gitbook.io/nuclear/contributing/converting-to-typescript

**Comment by nukeop** [comment]
Wait a sec, there should be guidelines for converting to Typescript before we accept contributions on that (preferrably in the docs).

**Comment by HaiDang666** [comment]
Ops, I will unpin this until doc finishes

**Comment by VijayKumarKTG** [comment]
Hi @nukeop and @HaiDang666 ! I want to contribute to this.

**Comment by nukeop** [comment]
You can find guidelines here: https://nukeop.gitbook.io/nuclear/contributing/converting-to-typescript

Please also follow our general contribution guidelines, and let us know which part you'd like to work on first.

**Comment by VijayKumarKTG** [comment]
@nukeop! Whenever I'm trying to run `npm install`, it is showing the error `Failed at the nuclear@0.6.16 postinstall script.` but I can run the test without any error. I'm using node v12.22.3  and npm v6.14.13. I want to change the components in the components folder under package/app/app/ directory.

**Comment by nukeop** [comment]
If you didn't install dependencies, how come the tests run?

**Comment by VijayKumarKTG** [comment]
All the dependencies has been installed but the error is occurring while running the post-install script.

**Comment by HaiDang666** [comment]
I got this problem before, it because the c++ compiler in my mac device was broken. But not sure is it the same as u

**Comment by nukeop** [comment]
Do you have any details? Like what exactly has failed?

**Comment by nukeop** [comment]
> I got this problem before, it because the c++ compiler in my mac device was broken. But not sure is it the same as u

There could be a million reasons that this happens, without an error log or any other information like platform, we can't say anything for sure.

**Comment by VijayKumarKTG** [comment]
Here are some errors messages.
```cannot execute  cause=exit status 1
                    out=
    > sqlite3@4.2.0 install /home/vijaykumar/code/opensource/nuclear/node_modules/sqlite3
    > node-pre-gyp install --fallback-to-build
                    errorOut=node-pre-gyp WARN Using request for node-pre-gyp https download 
    node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/electron-v12.0-linux-x64.tar.gz 
    node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and electron@12.0.11 (electron-v12.0 ABI, glibc) (falling back to source compile with node-gyp) 
    node-pre-gyp ERR! node -v v12.22.3
    node-pre-gyp ERR! node-pre-gyp -v v0.11.0
    node-pre-gyp ERR! not ok 
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the sqlite3@4.2.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by nukeop** [comment]
I don't know what platform you're using, but you have to review the requirements for development, notably you need to install `Your platform's build tools required to recompile native dependencies`: https://nukeop.gitbook.io/nuclear/developer-resources/development-process

**Comment by VijayKumarKTG** [comment]
I'm using ubuntu. OK, I'll review again the requirements.

**Comment by HaiDang666** [comment]
> @nukeop! Whenever I'm trying to run `npm install`, it is showing the error `Failed at the nuclear@0.6.16 postinstall script.` but I can run the test without any error. I'm using node v12.22.3 and npm v6.14.13. I want to change the components in the components folder under package/app/app/ directory.

btw, specify which exactly component/part you gonna work so other contributor can avoid overlap and also make ur PR doesn't contain massive change.

**Comment by amendezm** [comment]
Hello @nukeop. Can I contribute to this??

**Comment by nukeop** [comment]
Sure, you can work on it, just let us know which part you'll be covering.

**Comment by Hardik-hi** [comment]
@HaiDang666 @nukeop I have made the PR. Kindly review.

**Comment by Gauravsharma-20** [comment]
Hey @nukeop @HaiDang666 I have migrated `packages/ui/lib/components/Loader` to typescript 

Link to PR: https://github.com/nukeop/nuclear/issues/1002

**Comment by YajanaRao** [comment]
Hi @nukeop @HaiDang666 I have migrated `packages/app/app/components/Navbar` to typescript:

Link to PR: #1062

**Comment by MiguelAMLucero** [comment]
Hey @nukeop I migrated some files from `packages/ui/stories/components` to typescript. 
PR: #1142

**Comment by Gauravsharma-20** [comment]
Hey @nukeop @HaiDang666 migrated 4 components of `packages/ui/lib/components` to Typescript
Link to PR: #1148

**Comment by apisandipas** [comment]
Hello @nukeop . Is it ok if i take on the  TS conversion of `packages/ui/lib/components/AlbumPreview/index.jsx`?

**Comment by HaiDang666** [comment]
yes, you can take it @apisandipas

**Comment by apisandipas** [comment]
@HaiDang666 After looking at @Gauravsharma-20 PR above, it looks like they started work on this component. I've very interested in contributing all the same, so I'll keep poking around.

**Comment by nukeop** [comment]
Thanks, feel free to look at other components in the `ui` package. Or let me know if you'd like me to recommend you some task to handle.

**Comment by apisandipas** [comment]
@nukeop Could you recommend a task?

**Comment by nukeop** [comment]
We've recently found an issue where local files saved in playlists load remote streams instead of local files - do you think you could help debug this? If that's not your cup of tea, let me know what kind of task you'd like to take and I'll give you something else.

**Comment by apisandipas** [comment]
@nukeop I can give that a look. Thanks. Is there a ticket open for this?

**Comment by nukeop** [comment]
There's only ~15% of JS code left, I think we can close this now. We don't need to focus specifically on this transition anymore and PRs can just keep converting files to TS if they touch that area of the code.
