### ISSUE TITLE
Feature: New metaprovider for iTunes music 

### ISSUE THREAD

**Issue by Ivan12273** [nukeop/nuclear#1005]
Hello again!, this issue is related to this one: https://github.com/nukeop/nuclear/issues/966

I was thinking that it would be a good idea to also implement the iTunes Music API to get tracks, albums, and cover images. iTunes has a huge repertoire of music, almost all albums and tracks have cover images, descriptions, dates and genre included.

![image](https://user-images.githubusercontent.com/42753018/124522817-25a29680-ddba-11eb-8c8b-c6565564526a.png)

If there is no problem, I could work on this.

**Comment by nukeop** [comment]
Do you need an API key for it to work?

**Comment by Ivan12273** [comment]
> Do you need an API key for it to work?

No, the iTunes API does not need an API key, it would be the same as the podcast.

**Comment by nukeop** [comment]
Ok, can it search for artists? It would be great to use it as a metadata source.

**Comment by Ivan12273** [comment]
Yes, it can :)

**Comment by nukeop** [comment]
Sounds great 👌🏿

**Comment by HaiDang666** [comment]
resolved #1009
