### ISSUE TITLE
Polygondwanaland plays wrong song.

### ISSUE THREAD

**Issue by decsolst** [nukeop/nuclear#1018]
**Fill in the form to describe your problem**
I have a problem with: Polygondwanaland (Song)
It happens when: I click play on the song Polygondwanaland
My OS is: Linux (Manjaro)
I'm using Nuclear version: 0.6.15

**Additional context**
When attempting to play the song Polygondwanaland, Nuclear instead plays the song Crumbling Castle, the first track on the album Polygondwanaland.

**Comment by HaiDang666** [comment]
I sometime have this problem when album name and track name is the same

**Comment by nukeop** [comment]
Plays correctly now. nice taste.
