### ISSUE TITLE
Improve the downloads feature a bit

### ISSUE THREAD

**Issue by tio-trom** [nukeop/nuclear#1020]
For one, adding a download button to the player would be useful. At times you listen to a playlist from somewhere and you want to download the music that plays. How you do that?

Second: what if you add an option like "sync my favorite music to my offline library"? So all of your favorite songs/playlists auto-download locally.

**Comment by nukeop** [comment]
You can download the currently playing track from the queue menu.
We're planning to replace all track lists with the table that's currently being used for playlist management, that should handle the second case.
