### ISSUE TITLE
Songs save as webm

### ISSUE THREAD

**Issue by TROMsite** [nukeop/nuclear#1021]
Linux + Nuclear 0.6016

Is this intentional?

**Comment by nukeop** [comment]
Yes, they're saved as whatever format it's originally in.

**Comment by TROMsite** [comment]
Shouldn't make more sense to force an audio format?

**Comment by nukeop** [comment]
We'd need to include an audio converter with the program which would increase complexity and broaden the scope.

**Comment by TROMsite** [comment]
I understand!
