### ISSUE TITLE
Add search 

### ISSUE THREAD

**Issue by tio-trom** [nukeop/nuclear#1022]
Would be very useful to add a search form to playlists, favorites and the queue.

**Comment by nukeop** [comment]
This should be added to the track table component.

**Comment by thaditi** [comment]
Hi @nukeop. I would like to work on this issue. Can you please explain about this feature?

**Comment by nukeop** [comment]
This is the track table component: https://github.com/nukeop/nuclear/tree/master/packages/ui/lib/components/TrackTable

It will need a search box added somewhere at the top (your choice where exactly). Typing in that search box should filter the tracks in the table. Try reusing existing components, or fall back onto Semantic UI components: https://react.semantic-ui.com/elements/input/

Please review the development process instructions if you're unsure how to build the project:
https://nukeop.gitbook.io/nuclear/developer-resources/development-process

And please also check our contribution guidelines:
https://nukeop.gitbook.io/nuclear/contributing/contribution-guidelines

**Comment by thaditi** [comment]
Yes. I have read all the instructions and guidelines. I would like to work on this.

**Comment by nukeop** [comment]
Ok, I assigned you.

**Comment by nukeop** [comment]
Closed by https://github.com/nukeop/nuclear/commit/da982ff94d1b78313b8ddd6046fdd0a6870daca3
