### ISSUE TITLE
Loading many favorite tracks makes Nuclear unusable for minutes

### ISSUE THREAD

**Issue by tio-trom** [nukeop/nuclear#1023]
Arch linux + latest Nuclear version.

If I have hundreds of songs in the favorites and I click the PLAY button on top of the list, it takes minutes to load them and to allow me to play any. Shouldn't the PLAY simply add all songs to queue immediately and then play a song out of them? Why is it taking so long?

**Comment by HaiDang666** [comment]
When a song is added to queue Nuclear starts to search stream source immediately, so when hundreds of songs come it cause the problem, there is someone working on this problem.

**Comment by nukeop** [comment]
Tracks now load one by one.
