### ISSUE TITLE
Improved neck quality

### ISSUE THREAD

**Issue by UnixCro** [nukeop/nuclear#1025]
Hello,

I did not like the translation from English into German in the readme file, I have improved it and will change something if there are any further abnormalities. I would be happy if you could have a look.

https://github.com/UnixCro/Kuerzlich/blob/main/nuclear%20german.md

By the way: Everything that has to do with translation errors, incorrect sentence structure, incorrect punctuation, grammatical errors, spelling errors or the like, I will write in this "Issue post"

**Comment by nukeop** [comment]
Very nice, thank you. Could you open a pull request?

**Comment by UnixCro** [comment]
Thank you for your prompt reply. Unfortunately I don't know how to do that, that's why I pointed out a link. You can compare it or someone else and get your own idea. I have completely edited the ReadMe wherever there was grammar or spelling errors. Since I like nuclear a lot and would like to improve it, I will continue to look out whether German sentences might not be better worded.

**Comment by nukeop** [comment]
Okay, I'll copy that into the repo later. Unfortunately, this way the change won't be attributed to you.

**Comment by UnixCro** [comment]
I noticed that when you select a language in the ReadMe, a translated text appears. But flags are displayed again, if you press the new flag from the translated text again, you get a 404 error message.


https://user-images.githubusercontent.com/70098046/126705718-1e042161-5de3-4854-82ed-5793f8445c0e.mov

**Comment by nukeop** [comment]
You're right, in some cases the translators did not make the links relative to the docs folder. It's usually not a big deal,  because we can assume that you will only go from the main readme to the one in your language, and won't switch to a different language.

**Comment by nukeop** [comment]
I added your changes and fixed the links.
