### ISSUE TITLE
Error while doing npm install

### ISSUE THREAD

**Issue by renanreboredo** [nukeop/nuclear#103]
While I was doing ```npm install```, the following error appeared:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for enzyme-adapter-react-16@^1.5.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'nuclear'
npm ERR! notarget npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rebores/.npm/_logs/2018-08-30T12_52_18_601Z-debug.log
```

And when I tried to do yarn, it showed me that the package 1.5.0 didn't existed for me, and suggested for me to install one of the versions, up to 1.3.0, of the enzyme-adapter-react-16.

And not to mix package managers, someone can help me setup the project with npm? I'd really like to contribute here!

**Comment by nukeop** [comment]
Yeah it looks like @greenkeeper[bot] messed up the update. You can change this to 1.3.1 in package.json and it should install correctly. I'll disable the bot since it's not the first time it made a mistake.
