### ISSUE TITLE
UI/UX: Order Discography Chronologically

### ISSUE THREAD

**Issue by ChrisCates** [nukeop/nuclear#104]
Overall, the Nuclear App is pretty great.

However, I feel that the core layout of Spotify in comparison to the thumbnails in the current app are pretty important.

![screen shot 2018-09-22 at 2 55 30 pm](https://user-images.githubusercontent.com/1561091/45920787-1e27d200-be99-11e8-84d7-3e544136941b.png)

The thumbnail layout is convenient and nice in a lot of contexts... But usually, I prefer browsing artists based on their chronological order of discography... There should be a button or tab to do so.

**Comment by trekiteasy** [comment]
I haven't changed the thumbnail layout but ordered albums by reverse chronological order (the latest at the top)

**Comment by nukeop** [comment]
is the year a number?

**Comment by trekiteasy** [comment]
Yes, an integer, not a date (using discogs data model as it was the one used in the view).

**Comment by nukeop** [comment]
nice, important to remember if we ever decide to move to a unified track model
