### ISSUE TITLE
UI/UX: Loading screen states when downloading albums

### ISSUE THREAD

**Issue by ChrisCates** [nukeop/nuclear#105]
When I try to queue an entire album.
It will just go to the logo loading screen state.

Ideally, it should show the current status of the download... How many songs were downloaded so far...

I tried downloading Tokyo Police Club's "Forcefield" Album... And, it has been stuck in that state for 10 minutes...

So there should also be a cancel button too.

**Update**

I noticed that if I try to play something before it is downloaded. It will be stuck in the loading screen state... So this is actually a bug that needs to be fixed.

**Comment by ChrisCates** [comment]
@nukeop is there a branch I can check out? This is a pretty critical bugfix.
Kind of already sold on this over Spotify...

**Comment by nukeop** [comment]
Which release are you using now?

**Comment by ChrisCates** [comment]
https://github.com/nukeop/nuclear/releases
0.4.3

**Comment by nukeop** [comment]
In 0.4.3, if Discogs returns invalid paramters, it should display an error message. Every redirect to loading screen is a bug (you can press Ctrl-R to get out of it). I'll take a look after work to see if it can be fixed today. If it is, I'll try to build a new release. For completeness, what system are you using this on?

**Comment by ChrisCates** [comment]
Mac OS High Sierra.
I can test on Windows 10 or Arch Linux too.

**Comment by nukeop** [comment]
Ok, I'll get to the bottom of this later.

**Comment by nukeop** [comment]
Looks like there were some problems with Discogs API, it's possible that your problem could be fixed now. If it's not, let me know.
