### ISSUE TITLE
Drop down menu on right of search bar gets hidden

### ISSUE THREAD

**Issue by Hardik-hi** [nukeop/nuclear#1050]
**Platform:** Windows 

**Nuclear version:** v0.6.16

**Description of the issue:**

![nuclear_ui_error](https://user-images.githubusercontent.com/55993168/132957005-010c6015-4dfa-4873-9569-cd233e6421b5.gif)

When searching in the search bar the drop down menu to the right gets hidden behind the search history pane. It is accessible when the user clicks outside the history pane.

**Possible solution** Decrease the width of the search history pane or maybe move the dropdown menu to the right.

**Comment by Hardik-hi** [comment]
I can try working on this issue though.

Can I proceed? @nukeop @HaiDang666 ?

**Comment by nukeop** [comment]
Thanks for reporting, sure, please take it. You just need to adjust the z-levels of these elements.

**Comment by Hardik-hi** [comment]
@nukeop Gotcha!
