### ISSUE TITLE
Download not happening

### ISSUE THREAD

**Issue by capkirk88** [nukeop/nuclear#1059]
**Platform:**

MX-19.4_x64 patito feo base: Debian GNU/Linux 10 (buster)

**Nuclear version:**

0.6.16

**Description of the issue:**

The 'Downloads' tab just shows all tracks as 'Waiting'. 
![Screenshot_2021-10-01_14-18-57](https://user-images.githubusercontent.com/91725809/135592444-7b787692-61fb-4a25-bdb0-eba8adb69f63.png)

**Comment by nukeop** [comment]
Can you include the tracks being downloaded in the screenshot?

**Comment by capkirk88** [comment]
Sure, here you go. 
![Screenshot_2021-10-01_15-00-04](https://user-images.githubusercontent.com/91725809/135598100-dc65875e-3110-4643-8015-6fbeca2ae33d.png)

**Comment by capkirk88** [comment]
Sorry re-commenting, here's the downloads I've not manually paused - same issue. 

To be clear it seems to be happening irrespective of the tracks involved. I tried it with other tracks too. 


![Screenshot_2021-10-01_15-01-23](https://user-images.githubusercontent.com/91725809/135598259-7a8a999d-95df-4afa-b163-7c877b532a7c.png)

**Comment by nukeop** [comment]
Thanks, this view needs to report errors/stuck downloads better.

**Comment by AhamedBilal** [comment]
![Screenshot_20211019_122133](https://user-images.githubusercontent.com/45702667/137858399-09ef259f-f431-482b-9952-21c60b30d7bb.png)

music download not working
