### ISSUE TITLE
Last track does not work as expected when shuffling

### ISSUE THREAD

**Issue by Trial-In-Error** [nukeop/nuclear#1067]
**Platform:**
Windows 10

**Nuclear version:**
0.6.16

**Description of the issue:**
When shuffle is enabled, last track draws a new, random track instead of pulling out the last played track. For instance, if I'm on shuffle and finish listening to track A, then shuffle moves to track F, and I click back, I could get track C (when I would expect track A again).

**Comment by nukeop** [comment]
The order of shuffled songs is not remembered, they are randomly picked every time.

You can use the "Shuffle when going back" setting to change this behavior: https://github.com/nukeop/nuclear/blob/657fdafb8ae847a7d80cfd2f584a433efbabb609/packages/core/src/settings/index.ts#L72

This way, when you click back when shuffle is active, it will go the previous song in the queue. It's still not what you're describing though, but it's as designed.

**Comment by Trial-In-Error** [comment]
Would you welcome a PR that changed this behavior? Or is it one of:
- not perceived as desirable
- a colossal undertaking?

My usual use-case for this behavior is:
- I didn't know I wanted to listen to this track on repeat, but I do, so once it finishes, I want to hit back to return to it
- I've skipped 2 or 3 tracks in a row and then skip past something I'm interested in, and would like to return to it
