### ISSUE TITLE
Add an "add all" button to the artist top tracks list

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#107]
I recently pushed a commit that adds this button : [084e8346f86af9e4cafc8b9791308aa2e9ec42a3](https://github.com/trekiteasy/nuclear/commit/084e8346f86af9e4cafc8b9791308aa2e9ec42a3)

**Comment by nukeop** [comment]
Thanks for the contribution, would you like to open a pull request?

**Comment by trekiteasy** [comment]
#108 Pull request
