### ISSUE TITLE
Led Zeppelin - Stairway to Heaven 

### ISSUE THREAD

**Issue by AdhaarSharma** [nukeop/nuclear#1072]
![Screenshot (43)](https://user-images.githubusercontent.com/66046037/137438562-c5dee8bb-d706-463f-8f7e-5c42c42282ea.png)

**Comment by HaiDang666** [comment]
Which stream provider did you use?

**Comment by AdhaarSharma** [comment]
It could not find a working stream provider. And I faced similar issue while trying to play different songs.

**Comment by HaiDang666** [comment]
How did you add the track to nuclear by direct youtube link or importing by json file

**Comment by AdhaarSharma** [comment]
I searched using Nuclear Search and pressed play.

**Comment by HaiDang666** [comment]
Just try to search with your keyword, it worked fine. Maybe it was a problem with the youtube stream link. How ab other track?

**Comment by AdhaarSharma** [comment]
I tried downloading songs. The songs are downloaded and they do work fine. The problem only arises when I try to play directly.
