### ISSUE TITLE
Download status is always "Started", it doesn't update correctly.

### ISSUE THREAD

**Issue by JFMugen** [nukeop/nuclear#1098]
**Platform:*Win 10*

**Nuclear version:*0.6.17*

**Description of the issue:*Even when the song is downloaded, it shows it as "Started" and because of that, clear finished tracks doesn't work as well*

**Comment by 1lluzi0nzz** [comment]
nukeop, would adding a localized 'Downloading' & 'Completed' status resolve this issue?

**Comment by nukeop** [comment]
There already is a status for this, but it's updated incorrectly

**Comment by 1lluzi0nzz** [comment]
Ah, I see there is a few statuses now.  Can I take this?

**Comment by nukeop** [comment]
Fixed on master
