### ISSUE TITLE
Implement more music sources

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#11]
- [ ]  bandcamp
- [x] soundcloud
- [ ] vimeo
- [ ] ~~spotify (?)~~
- [ ] ~~deezer (?)~~
- [ ] mp3monkey
- [ ] Yandex Music (?)
- [ ] Subsonic
- [ ] Google Play Music
- [ ] Local library
- [x] Jamendo Music
- [ ] MPD (work in progress)

Suggestions welcome

**Comment by nukeop** [comment]
Spotify and Deezer likely won't work, there's too much work involved in extracting the audio streams, at least for now.

Looking at mp3monkey instead.

**Comment by sojusnik** [comment]
[Yandex Music](https://music.yandex.ru/) would be nice.

**Comment by abeudin** [comment]
Subsonic :)

**Comment by nukeop** [comment]
> Yandex Music would be nice.

Yandex closed the music API some time ago, this might be hard to do.



> Subsonic :)

I'll look into it. Do you mean connecting to your own Subsonic server?

**Comment by mjackson** [comment]
Have you looked into Google Play Music? Or does it always require a subscription?

**Comment by nukeop** [comment]
> Have you looked into Google Play Music? Or does it always require a subscription?

Not yet, but it's worth adding

**Comment by g5codyswartz** [comment]
Watching vimeo's network it seems to stream (I imagine spotify does this same technique as well as fb + youtube I imagine?)

Found this guy though which seems to be fairly recent: https://www.npmjs.com/package/vimeo-downloader

**Comment by nukeop** [comment]
> Watching vimeo's network it seems to stream (I imagine spotify does this same technique as well as fb + youtube I imagine?)

The way I wanted it to work was that you would log into Spotify (or Deezer) from Nuclear, and tap into search and streaming. However, Spotify offers no such api and while it would be possible to fool the servers by spoofing requests to make them look they're coming from the web player, it's also very difficult because of heavy use of proprietary Javascript code which makes reverse engineering troublesome.

I haven't looked into vimeo yet but if it's similar to youtube's streaming, it will be added soon.

**Comment by nukeop** [comment]
Vimeo has been added.

**Comment by 0verk1ll** [comment]
It might be interesting to add www.archive.org. They have many live recordings of concerts available for free along with other audio.

**Comment by 0verk1ll** [comment]
http://freemusicarchive.org/ also provides a large quantity of free music.

**Comment by jmicgz** [comment]
Netease xiami and qq music
Api here https://github.com/LIU9293/musicAPI

**Comment by nukeop** [comment]
Music search works through discogs and a little bit of last.fm now.
For streams, I'm developing a plugins system, which only has Youtube for now. 0.5.0 release will focus on adding more sources.

**Comment by FabianLauer** [comment]
I might be able to help out with a [Jamendo](https://www.jamendo.com/start) integration if interested (am a former employee). API docs can be found [here](https://developer.jamendo.com/v3.0).
@nukeop WDYT?

**Comment by nukeop** [comment]
I think I'll be changing to a model where you have a number of search providers (Discogs, Musicbrainz, Soundcloud, etc), and separately, a number of stream providers (Youtube, Soundcloud, etc, and now possibly this).

I see it's not hard to get a stream to the song once you know what you're looking for. I see there's a non-commercial API available, but the limit is 35k requests per month, which might not be enough (a couple hundred users a month times a couple of requests per person and we'll rapidly approach this limit). I could try to add it and show an error message when we're rate limited. Normally I'd do something dodgy to try to work around the limit but I'd rather not do it when the service is nice enough and not that big.

If you feel like it, you could try to add support for it. The best place to add API-related functions is here: https://github.com/nukeop/nuclear-core . Of course I won't limit you if you've got better ideas how to organize it. If you'd rather not do the implementation part, I'll take a look at it myself at some point.

**Comment by RenonDis** [comment]
Integrating a subsonic client could play very nicely with subsonic-compatible servers, such as https://funkwhale.audio . Thanks for the hard work btw :)

**Comment by trekiteasy** [comment]
I implemented a Jamendo stream search plugin (https://github.com/nukeop/nuclear/commit/bb3ef3fabc874f9b71f4c11eca960efc89492ca9).
As sted by @nukeop , there is a 35K/month API call that we'll reach way too quickly to keep using it as we do today.

**Comment by nukeop** [comment]
As a last resort we could rotate between a number of keys, but that's not a permanent solution either.

**Comment by trekiteasy** [comment]
Not sure why, but in the dev console on jamendo side, it says 500K hits /month which is a bit better than what is said in the "plans" page.

**Comment by nukeop** [comment]
I think we're unlikely to hit even 100K monthly. Not worth it to worry about this now, then.

**Comment by arnitkun** [comment]
mp3monkey is down for now.

**Comment by arvigeus** [comment]
Is is possible to integrate with Youtube Music? (the new Google streaming service)

**Comment by nukeop** [comment]
> Is is possible to integrate with Youtube Music? (the new Google streaming service)

Does it require logging in?

**Comment by arvigeus** [comment]
Yes, it does.
