### ISSUE TITLE
"Shuffle on previous track" option doesn't work

### ISSUE THREAD

**Issue by JFMugen** [nukeop/nuclear#1101]
**Platform: *Win 10*

**Nuclear version: *0.6.17*

**Description of the issue: *"Shuffle on previous track" option doesn't work. Whether its on or off, it always shuffles on the previous track. *

**Comment by nukeop** [comment]
Does not reproduce; if you see it occurring you'll need to provide more information.

**Comment by JFMugen** [comment]
I thought it would work with memory (and should work with memory) but looks like it is not a bug so... up to you ^^
