### ISSUE TITLE
Songs not playing; JS error in main process

### ISSUE THREAD

**Issue by Chroxify** [nukeop/nuclear#1109]
**Platform:**
Arch Linux 

**Nuclear version:**
V. 0.6.17

**Description of the issue:** 
![image](https://user-images.githubusercontent.com/65873518/143292601-baaca191-f26d-434b-bfc4-36321d9e41ff.png)
Always receiving the error above when trying to play a song.
After clicking okay it just appears again and the song doesn't play.

**Comment by Kleysley** [comment]
This happens on Manjaro, Debian, Mint too. I couldn't get it to work.

**Comment by nukeop** [comment]
Duplicate of #1081
