### ISSUE TITLE
Loop button not working

### ISSUE THREAD

**Issue by CYAXXX** [nukeop/nuclear#1112]
Platform: Windows10

Nuclear version: 0.6.17

**Comment by nukeop** [comment]
What happens when you try to use it?

**Comment by CYAXXX** [comment]
nothing just it stop working

**Comment by nukeop** [comment]
Does the whole application crash?

**Comment by CYAXXX** [comment]
no

**Comment by nukeop** [comment]
So... what happens? Does it not loop? What do you expect to happen?

**Comment by CYAXXX** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/85353920/144048546-b61d73d5-904d-44eb-aa90-b44ddf0df8f1.png)

**Comment by nukeop** [comment]
Ok, so the problem here is that there is only one track in the queue. In this case it does loop back, it just doesn't resume playback.

**Comment by CYAXXX** [comment]
Actually the same happens while having many tracks in the queue.  😣

**Comment by nukeop** [comment]
Does not reproduce in my case.

**Comment by CYAXXX** [comment]
I hope that in the next version this issue gonna disappear somehow🤷🏿‍♂️

**Comment by nukeop** [comment]
I'm looking into it right now, should be gone soon

**Comment by CYAXXX** [comment]
Thank you 👍🏿

**Comment by prorounak2005** [comment]
I am facing the same problem here - :( 
![image](https://user-images.githubusercontent.com/69617708/152510838-daf9a8c9-f3ad-42fc-b63e-eebe5f07a139.png)

**Comment by CYAXXX** [comment]
@prorounak2005 oh it's not only on windows 👀

**Comment by CYAXXX** [comment]
> Happens in macOS (Monterey 12.2) as well.
> 
> ### How to reproduce:
> * Play 1 song in an empty queue
> * Enable the loop button
> * Wait until the song has finished
> 
> ### Expected behaviour:
> * Continuous playback loop/repeat of available songs in the queue
> 
> ### Actual behaviour:
> * Works just like the expected behaviour when there is more than 1 song in the queue
> * If there is only 1 song in the queue however, playback simply stops after the song has finished (the issue)
> 
> <img alt="image" width="1552" src="https://user-images.githubusercontent.com/69845406/153543139-475d5521-2f65-47f0-bfbc-eb7c54936bea.png">

Hi @nukeop , seems like many people having this issue can you please this take a look here.

**Comment by prorounak2005** [comment]
> @prorounak2005 oh it's not only on windows eyes

Yup I use Archlinux , Windows and linux mint. I am facing the same problem in all operating systems. :(

**Comment by prorounak2005** [comment]
Now it doesn't even loop but it goes to next song :(
