### ISSUE TITLE
Skip to next track automatically after unsuccessfully trying a track for a while (simpler version of #1082)

### ISSUE THREAD

**Issue by forteller** [nukeop/nuclear#1115]
Hi. Thank you for an amazing application! It gives me a lot of joy in my day to day.

What's not so joyful, as I'm sure you already know well enough, is every time the playback stops because of "Could not find a working stream etc". I saw in #1082 that you couldn't do an automatic reroll, and that's totally fine by me. All I would want to make Nuclear almost perfect is if it could just try to play the track for a little while, then time out and automatically skip to the next track on the list. 

Maybe this could at least be a temporary work around until you find out how to solve the real issue?

Thanks a lot!

**Comment by nukeop** [comment]
When there's an error saying there are no usable streams found, it means it found a stream url but got an error while trying to load it (e.g. Youtube returns a valid url but the video is geoblocked). So retrying after a few seconds will fail too. I think the best course of action is to keep trying with the subsequent streams, and skip the track altogether after 3 retries.

**Comment by forteller** [comment]
Yes, exactly my point. Just skip after some time to the next track. The same should happen on the tracks that don't give an error message, but just keeps spinning, with a green background. When that happens for me on the last track, no new track is added automatically, so I can't manually skip to the next one. So a new track should be added to the end of the list when playing the second to last track, or when starting the last track, and then if it just spins for a while, then automatically skip to the next. Thanks!

**Comment by nukeop** [comment]
Can you give an example of a track that keeps loading, and which provider has this behavior? I haven't seen that.

**Comment by forteller** [comment]
Thanks for your fast replies!

For me it happens quite often on the last track in my list. But not every time, and consistently the same track. Yesterday I added all tracks from the Snail Mail popular tracks list to my playlist and started playing from the start. It happened on the last track (Automate). Today I added all the same tracks and started playing from the third to last track, and it played the last track just fine and added automatically a new track it also played fine, but then it added another track (last girl by Soccer Mommy) which just stood there, spinning. I don't know if where on the playlist I start playing is relevant, just wanted to add all details.

Here's a screenshot. It's been like this for many minutes, and from previous experience I know it will just stay like this forever.

![Screenshot from 2021-12-04 18-10-50](https://user-images.githubusercontent.com/343561/144718290-09f1637b-38da-4225-a4e1-5680117ab609.png)

**Comment by forteller** [comment]
Just FYI: I let it run, and it's still spinning :D

**Comment by nukeop** [comment]
Generally it should start playing within less than 2-3s. If it doesn't, it likely won't start at all. However, if there's an error, it should also display it. So if it keeps loading the stream url is probably faulty, but in a way that doesn't return an error, similarly to how websites can appear to be loading if your connection is spotty. You can see what exactly is happening if you press `ctrl+shift+I` and check the network tab.

**Comment by forteller** [comment]
Now when I tried again, no new track was added at the end at all. 

Here's the network tab:
![Screenshot from 2021-12-05 01-28-01](https://user-images.githubusercontent.com/343561/144728870-c241dab1-ae99-4bc7-b55a-5c12e668038b.png)

The instance is https://invidious.snopyta.org – which I haven't changed at any time, so I guess it's the default. Is that what you meant with the provider?

Also, I forgot to say I'm using version 0.6.16, because .17 gives me an error message in a pop-up for every track I play.

Does this help you?

**Comment by nukeop** [comment]
Are you using invidious or youtube as the stream provider?

The stream is searched for when you add a track to the queue, so if you didn't add it it will not appear in the network tab.

**Comment by forteller** [comment]
I just use all the default settings.

Here's a screenshot from when a new track gets added at the end, as it should, but just keeps spinning forever:

![Screenshot from 2021-12-05 01-48-23](https://user-images.githubusercontent.com/343561/144729186-69bc44d9-72e5-4e30-aea6-2292a904a851.png)

**Comment by nukeop** [comment]
I'm seeing increased response times from sponsorblock api, maybe that's what causes it. Worth investigating if downloading these segments should block playing the track altogether.

**Comment by forteller** [comment]
No idea if it helps, but here's another one, just in case. This happens all the time to me. Thanks again for your work! :)

![Screenshot from 2021-12-06 01-51-59](https://user-images.githubusercontent.com/343561/144771350-671d3f23-8513-46a6-aef7-806ed7e58303.png)

**Comment by nukeop** [comment]
Streams are now rerolled automatically.
