### ISSUE TITLE
Crash with SIGSEGV on start on Debian Sid

### ISSUE THREAD

**Issue by different55** [nukeop/nuclear#112]
Tried to run with both the .AppImage and the .deb, even installed 410 packages of node to build it myself. All crash on start with SIGSEGV. I'm not sure how to get any extra info from the crashes so let me know what you need me to do.

**Comment by nukeop** [comment]
I hear there's a problem with certain versions of glibc affecting Electron, could you tell me what version you're using?

**Comment by different55** [comment]
2.28 currently, seems like there's an update to it though (2.28-4 -> 2.28-5) in Debian's repos so I'll see if that does anything.

**Comment by nukeop** [comment]
Yeah, apparently you're affected by that issue then, it's mentioned here: https://github.com/electron/electron/issues/13972

(The OP talks about Arch but the distro doesn't matter really)

Not sure if I can do anything about it.

**Comment by different55** [comment]
Gotcha, sounds like we can go ahead and close this one then. Thanks!

**Comment by perlun** [comment]
@nukeop The fix is to upgrade to Electron 2.0.8 or newer.

**Comment by mkg20001** [comment]
Running it with strace shows selinux related files being missing to cause the error

```
stat("/etc/gnutls/default-priorities", 0x7ffeeac463b0) = -1 ENOENT (No such file or directory)
statfs("/sys/fs/selinux", 0x7ffeeac46390) = -1 ENOENT (No such file or directory)
statfs("/selinux", 0x7ffeeac46390)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/filesystems", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "nodev\tsysfs\nnodev\trootfs\nnodev\tr"..., 1024) = 433
read(3, "", 1024)                       = 0
close(3)                                = 0
madvise(0x10535cbfa000, 8192, MADV_DONTNEED) = 0
access("/etc/selinux/config", F_OK)     = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0xdbf060} ---
+++ killed by SIGSEGV (core dumped) +++
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by perlun** [comment]
@mkg20001 This is not necessarily the case. What you're seeing is that reading the SELinux config file failed, but the actual _cause_ of `SIGSEGV` is reading unmapped memory or similar.

Try running with `gdb process-name` instead; it willl show you the exact line that's causing the crash. `bt` will give you a low-level stack trace.

**Comment by fasetto** [comment]
@nukeop So, is there anything we can do ?
I have the same seg fault problem.

**Comment by nukeop** [comment]
If you try running current development version it should work for you. Let me know if it doesn't. If you can't/don't want to run that, wait for the next release.

**Comment by fasetto** [comment]
Yeah. It worked,  thanks.
