### ISSUE TITLE
I cannot erase a specific artist in favorite artists List

### ISSUE THREAD

**Issue by LimEunSang** [nukeop/nuclear#1120]
**Platform:**
Windows 10

**Nuclear version:**
0.6.17

**Description of the issue:**
![bug_1](https://user-images.githubusercontent.com/86942472/144881641-b6976497-1031-4b53-9760-5ac8a9697c0c.PNG)
It won't be deleted from the list.
It can be added but not deleted.
It's the same when I restart the player.
This is the artist
![bug_2](https://user-images.githubusercontent.com/86942472/144881939-60589c8c-cf62-4639-a3c2-72cf481a049b.PNG)

**Comment by HaiDang666** [comment]
I think the problem is artist's name is empty. I'm working on this.

**Comment by nukeop** [comment]
Can't reproduce with this information.
