### ISSUE TITLE
Integrate with the system media control

### ISSUE THREAD

**Issue by Huy-Ngo** [nukeop/nuclear#1123]
**Platform:** Linux

**Nuclear version:** 0.6.16

**Description of the issue:** Currently, the music doesn't seem to be integrated to the system media controller. As a result, I can't use pause/play or next button to control the music or use media controller in Plasma tray.

**Comment by nukeop** [comment]
To the contrary, MPRIS support has been integrated for a long time: https://github.com/nukeop/nuclear/blob/master/packages/main/src/services/%40linux/system-api.ts

I use KDE and control it through that media menu.

**Comment by Huy-Ngo** [comment]
I see, it seems I'm not using the latest version. I'll update it and try again

**Comment by Huy-Ngo** [comment]
FWIW It seems to be a flatpak/snap problem. Just downloaded the deb and it works fine.
