### ISSUE TITLE
Playlist in list playlist view should be the same height.

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#1129]
**Platform: MacOS**

**Nuclear version: v0.6.16**

**Description of the issue:**
﻿﻿Playlist in list playlist view should be the same height.
<img width="634" alt="Screen Shot 2021-12-29 at 09 29 58" src="https://user-images.githubusercontent.com/12780733/147621873-f145125e-9994-4394-8f40-3695671681c6.png">

**Comment by wonntann** [comment]
Him, I would like to assist on this issue. Could you please provide reproducible steps that caused this issue and perhaps a code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
I see that you are on a MacOS, I am using Linux so I can try to help the best I can.

**Comment by HaiDang666** [comment]
Step to reproduce: 
- search with youtube watch URL (ex: https://www.youtube.com/watch?v=WStvRDdxdWY)
- add to queue
- save as playlist
- create an empty playlist   

You can see the height of playlist item is different

**Comment by wonntann** [comment]
Great, thanks, I was able to replicate. I am currently looking in the packages directory for the style code, however, I'm not sure if this is the correct step that I should take. Do you mind pointing me into the right direction? Thanks

**Comment by HaiDang666** [comment]
I just found that the UI is totally updated in the lasted commit, now it shows as a table. I can not test again cos the fetching youtube doesn't work anymore, need to be investigated.

**Comment by nukeop** [comment]
Yeah this view is deprecated now. It's been rewritten completely, so they're in a drag and drop table.
