### ISSUE TITLE
this.onVisualisationData is not a function uncaught error when resizing the app window while on the visualizer page

### ISSUE THREAD

**Issue by Kritsos** [nukeop/nuclear#1131]
**Platform:**
Windows 10
Version: 20H2
OS Build: 19042.1415

**Nuclear version:**
0.6.17

**Description of the issue:**
When on the visualizer page while a song is being played, if you resize the app's window until the visualizer is hidden and then resize it again to its normal size you get a "this.onVisualisationData is not a function" error and you are returned to the previous page you were on. Also the song you are playing gets a "Could not find a working stream using this source" error although it keeps playing. This happens on songs played both from my local library and my favorite tracks.

Steps to reproduce the bug:
1. Start playing a song from any source.
2. Go to the visualizer page and choose any one of the themes.
3. Resize the app's window until the visualizer is completely hidden.
4. Resize the app's window back to its normal size to get the error.

Below I am attaching a video file of me reproducing the bug:

https://user-images.githubusercontent.com/72339454/147750201-93996412-a878-4d2e-bf27-a9b3b9dba1be.mp4

**Comment by Kritsos** [comment]
I was able to reproduce the bug in Ubuntu 20.04.3 too.

**Comment by nukeop** [comment]
Not sure how the visualizer causes this but it's caused by this piece of code: https://github.com/nukeop/nuclear/blob/a8d1c02bc19fefebf26c14ec9fa04ab0f176e7f3/packages/app/app/containers/SoundContainer/index.js#L209

It's possible to pass `undefined` here which causes this bug.

**Comment by Kritsos** [comment]
Thank you for your answer, I thought this bug had to do something with the visualizer because i can cause it to happen only with the visualizer page.

**Comment by wizard-28** [comment]
Any updates on this?
