### ISSUE TITLE
Website not responsive for mobile devices

### ISSUE THREAD

**Issue by Nirbhayparmar** [nukeop/nuclear#1139]
**Platform:**
Website on mobile devices

**Nuclear version:** NA

**Description of the issue:**
When we go to the nuclear.js.org, it not responsive website. It can not adapt to the size of the screen.
![IMG_20220111_215325](https://user-images.githubusercontent.com/62185337/148981326-a91c35ca-a263-451e-b291-aa28d0bb27f3.jpg)

**Comment by nukeop** [comment]
I know, I just don't care about mobile phones.
