### ISSUE TITLE
Form Submission Using HTTP [Website "Bug"]

### ISSUE THREAD

**Issue by benyanke** [nukeop/nuclear#114]
![image](https://user-images.githubusercontent.com/4274911/51202617-c5a39700-18c4-11e9-9805-a98290259aed.png)

When submitting my email (`POST` "http://tech.us15.list-manage.com/subscribe/post?u=9d6b789c87d2e7d4ba8fc55dc&id=ebca2aa438"), this is sent over http which is both insecure and also pops up errors in firefox. If it doesn't show errors in other browsers, I suspect it soon will, with the way things are going.

**Comment by nukeop** [comment]
This is a problem with Firefox, which displays an unnecessary warning.
The endpoint to which the would-be subscriber's email is sent is provided by mailchimp. Maybe I could try changing it to https, but as it stands now, there is little reason to, save for getting rid of this warning on Firefox.

**Comment by benyanke** [comment]
"which displays an unnecessary warning"

Arguable, considering it's insecurely sending as HTTP. The warning isn't arbitrary, it's there for a reason.

That being said, it still works for me when I adjust to https, so there should be no downsides.

**Comment by nukeop** [comment]
In this case, there's little risk or difference between using HTTP/HTTPS, but that's what the browser overlords get to decide for us. I'll change the link and close this issue then.
