### ISSUE TITLE
Songs without an image cannot be right clicked when in the queue

### ISSUE THREAD

**Issue by Kritsos** [nukeop/nuclear#1140]
**Platform:**
Windows 10
Version: 20H2
OS Build: 19042.1415

**Nuclear version:**
0.6.17

**Description of the issue:**
When right clicking on a song in the queue you get a small window showing information on the source from which the song is playing. However songs that don't have an image and come with this default one
![default_image_song_bug](https://user-images.githubusercontent.com/72339454/149365906-e74c3799-2cae-4eca-afaf-53fd19aebaef.png)
cannot be right clicked and no information on the source is shown.

**Comment by nukeop** [comment]
Thanks for reporting this, that's pretty bad.

**Comment by nukeop** [comment]
It looks like it could happen if there are no streams found for a particular track. I can't reproduce it in tests.

However, I found an issue with deprecated options passed to popper, which handles the popups, and it might be causing issues, so I'm going to fix that.
