### ISSUE TITLE
Infinite loading pages between similar artists pages

### ISSUE THREAD

**Issue by Kritsos** [nukeop/nuclear#1147]
**Platform:**
Windows 10
Version: 20H2
OS Build: 19042.1466
and
Ubuntu 20.04.3

**Nuclear version:**
0.6.17

**Description of the issue:**
When going from one artist page to another through the similar artists panel the page changes just fine. However if i press the back button the page changes to an infinite loading page and i have to press the back button again to get to the starting artist page. This happens with the forward button too where beginning from the starting artist page when you press the forward button you get an infinite loading page and only when you press it again do you get the next artist page. The number of infinite loading pages is equal to the number of artists you visit, meaning there is an infinite loading page for each jump from one artist page to another through the similar artists panel. 

Steps to reproduce the bug:
1. Go to an artist page.
2. Go to another artist page from the similar artists panel.
3. Click on the back button to get an infinite loading page and click on it again to get to the starting artist page.
4. Now click the forward button to get an infinite loading page and click on it again to get to the second artist page.
5. Repeat these steps again from the second artist.

Showcase of the bug:

https://user-images.githubusercontent.com/72339454/150659466-e84abb0d-6b3c-4919-9fd2-a1baec38869d.mp4

**Comment by nukeop** [comment]
Fixed by #1600
