### ISSUE TITLE
Non-standard window controls are still visible even after turning off frameless mode

### ISSUE THREAD

**Issue by sprite-1** [nukeop/nuclear#115]
I turned off the frameless mode in hopes that it would make the non-native window controls go away, but it's still showing up which makes the whole thing kind of redundant.

It also doesn't remember the last window position and size on exit.

![image](https://user-images.githubusercontent.com/33685433/51207860-fb895f80-1946-11e9-9f9a-f038360ac647.png)

**Comment by nukeop** [comment]
Good point, I'll change this.

**Comment by sprite-1** [comment]
Is a new build coming soon? :open_mouth:

**Comment by nukeop** [comment]
Could be, once we close everything from 0.5.0: https://github.com/nukeop/nuclear/projects/2
I'm trying to squeeze in support for MPD and local files before releasing the major version. Maybe a 0.4.4. bugfix & improvements release before that.
