### ISSUE TITLE
Javascript error in Ubuntu

### ISSUE THREAD

**Issue by j0ker70** [nukeop/nuclear#1150]
I have recently downloaded the .deb(nuclear-v0.6.17.deb) file from releases and installed nuclear on my Ubuntu 20.04 machine. But whenever I try to play a song, a new window pops up and it shows an error as shown in the screenshot below. 
![image](https://user-images.githubusercontent.com/28401403/151435848-72523585-9a0d-4b6e-8d08-d963d24a2e79.png)

**Comment by nukeop** [comment]
Thanks for reporting. This is already fixed on master, so it will be gone in the next release.

**Comment by j0ker70** [comment]
> Thanks for reporting. This is already fixed on master, so it will be gone in the next release.

Is there anything that I can do now to get it working?

**Comment by nukeop** [comment]
You can either build binaries from master, or wait for the next release (which should be soon).
