### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by QAwO** [nukeop/nuclear#1156]
**Platform:Manjaro**

**Nuclear version:0.6.17**

**Description of the issue: 
![image](https://user-images.githubusercontent.com/96601386/151637411-e20f23ac-0ec9-488e-9e34-24124d550ea6.png)
![image](https://user-images.githubusercontent.com/96601386/151637432-38c72e81-76b4-4e99-926b-b63005ca37e1.png)
![image](https://user-images.githubusercontent.com/96601386/151637460-a70d666d-c01e-4d80-986b-391d65474b61.png)
![image](https://user-images.githubusercontent.com/96601386/151637477-f5c83b80-eaa7-492c-b108-d30352525d42.png)
![image](https://user-images.githubusercontent.com/96601386/151637501-64092abd-4e1f-4816-a567-657134374fa4.png)
Everytime i click anything in the app it opens a JavaScript error, But the app works just fine if i click ok in the error, I Get this error many times before it closes and the apps continues to play, I Have all dependencies installed and i tried the app image, Tar.gz and im using the aur version right now**

**Comment by nukeop** [comment]
Duplicate, fixed on master
