### ISSUE TITLE
Use soundcloud search instead of discogs

### ISSUE THREAD

**Issue by makeworld-the-better-one** [nukeop/nuclear#116]
I understand not using Youtube search because it will pull up a lot of stuff that's not music. But Discogs won't pull up more obscure musicians, ones that are big enough to be on Spotify, but started on SoundCloud maybe, such as [Samsa](https://soundcloud.com/iamsamsa/). The SoundCloud searching API reference is [here](https://developers.soundcloud.com/docs/api/guide#search). Much music is aggregated and added to SoundCloud, and it would be good to see this as a search function.

**Comment by mknepper** [comment]
I thought Discogs holds pretty much every release ever? Or are you speaking of Soundcloud specific stuff?

**Comment by makeworld-the-better-one** [comment]
@mknepper It's on Spotify so I assumed it was Discogs problem, but the dude is a Soundcloud rapper... Either way it makes sense to have Soundcloud search. But it's kinda a me problem I guess.

**Comment by nukeop** [comment]
Discogs is pretty inaccurate to be honest, and filled to the brim with poisoned data.
Searching for specific songs/videos on Soundcloud/Youtube is how this used to work, but I decided against it so I can have a Spotify-like search where you don't have to worry about finding a source for the song you want. This could be included as a sort of an advanced search, but I'm not sure how to reconcile this with things like scrobbling, displaying artist/title in the queue, etc.

**Comment by makeworld-the-better-one** [comment]
@nukeop Just having a little option beside the search bar of where to search would be nice. It could be default set to discogs, but the user could change it. And then if no results come up, or at the bottom of the results page, there could be a little message notifying the user to change it if they can't see what they want.

**Comment by nukeop** [comment]
Yeah, I think that could make sense. I'll look into adding it. Soundcloud provides artist name and title for all tracks, right?

**Comment by makeworld-the-better-one** [comment]
@nukeop Thanks, and I think it does, yes. If you don't mind, could mention this thread whenever this gets added, or if you fully decide to add it?

**Comment by mknepper** [comment]
Well, that makes sense. Come to think of it, Soundcloud has some pretty neat features. If there's anything I can do to help, let me know.

**Comment by rayrrr** [comment]
A lot of stuff in the universe of music isn't on SoundCloud, but is in Discogs...pretty much everyone but SoundCloud rappers, believe it or not. Discogs data is messy because it's crowdsourced. That means this crowd could help clean it up. Keep Discogs search!

**Comment by mknepper** [comment]
That's a good point. Is there a way to keep both? Soundcloud and Discogs? I feel like Soundcloud would limit you to whatever exists on Soundcloud only.

**Comment by nukeop** [comment]
Yeah, it was suggested in another thread to keep both and add a dropdown to the search box. I'm thinking of switching to separately defined search providers and stream providers.

**Comment by makeworld-the-better-one** [comment]
It was suggested by me, in the fourth reply in this thread. I don't think getting rid of it is a good idea, but having both or multiple available is.
