### ISSUE TITLE
Dont play music

### ISSUE THREAD

**Issue by Gufoski** [nukeop/nuclear#1160]
**Platform: Linux**

**Nuclear version: 0.6.17**

**Description of the issue: hi everyone, i downloaded the aur version and it keeps giving me these errors, do you have some advice?
![Screenshot_2022-01-30-09-24-23_1920x1080](https://user-images.githubusercontent.com/98683323/151690780-9cc7c680-71f7-4e01-b143-99524eeebe65.png)
![Screenshot_2022-01-30-09-24-39_1920x1080](https://user-images.githubusercontent.com/98683323/151690782-942e62d0-086b-4887-a762-9de60afd00a9.png)
![Screenshot_2022-01-30-09-24-59_1920x1080](https://user-images.githubusercontent.com/98683323/151690784-faec0dec-63d1-41e0-96e7-2b04ed44e695.png)
**

**Comment by gaurav219** [comment]
Yeah, I too got these messages.

Maybe, it's related to some dependency issues?

**Comment by damymetzke** [comment]
I get the same message with the latest flatpak version. But it still allows music to play, I just get a pop-up each time a new song plays.
OS: Debian (10)
Version in flatpak: 0.6.17

**Comment by gaurav219** [comment]
> I get the same message with the latest flatpak version. But it still allows music to play, I just get a pop-up each time a new song plays. OS: Debian (10) Version in flatpak: 0.6.17

I saw in DT's video, flatpak's version works fine besides the download part.

I use the [AUR](https://aur.archlinux.org/packages/nuclear-player-bin/) version

**Comment by Gufoski** [comment]
> Yeah, I too got these messages.
> 
> Maybe, it's related to some dependency issues?

I have no idea :/

**Comment by Gufoski** [comment]
> I get the same message with the latest flatpak version. But it still allows music to play, I just get a pop-up each time a new song plays. OS: Debian (10) Version in flatpak: 0.6.17

idk, I'm sorry for this problem because in itself the project seems interesting

**Comment by damymetzke** [comment]
> I saw in DT's video, flatpak's version works fine besides the download part.
This was the case one version back, the latest update introduced the bug.

**Comment by mikfar** [comment]
I had the same issue on the AUR version.
I tried to the Snap version and while the music plays, I get the same error between every song but with all the characters rendered as squares for some reason.

**Comment by gaurav219** [comment]
> I had the same issue on the AUR version. I tried to the Snap version and while the music plays, I get the same error between every song but with all the characters rendered as squares for some reason.

Wow!! Snap overperforms maintained packages. :P

**Comment by nukeop** [comment]
Already fixed on master
