### ISSUE TITLE
[CODE OF CONDUCT] Missing the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [nukeop/nuclear#1165]
**Issue Description:**

As this doesn't go with any introduced issue template, I am using a simple box here. The project is currently missing the **Code of Conduct** which defines standards for how to engage in a community. It also outlines procedures for addressing problems between members of your project's community. <i>from GitHub Docs </i>

Therefore if you want to add the Code of Conduct, then I would like to add a PR including the `CODE_OF_CODUCT.md` file in the root branch, and in that case, I would also need an address (email address) to enlist that in the file. Please do let me know what do you think about that.

**Comment by nukeop** [comment]
There is no code of conduct deliberately, and there will not be. It's even featured in the readme.
