### ISSUE TITLE
Don't attempt to play section titles

### ISSUE THREAD

**Issue by MithicSpirit** [nukeop/nuclear#1168]
**Platform:** Linux (Arch, using flatpak install)

**Nuclear version:** 0.6.16 (according to `flatpak info org.js.nuclear.Nuclear`)

**Description of the issue:** 
Nuclear attempts to play section titles as if they were songs. For example:

1. Set the metadata provider to Discogs 
2. Search for "Requiem", then find and click on [this result](https://www.discogs.com/master/115159-Mozart-Anna-Tomowa-Sintow-Helga-M%C3%BCller-Molinari-Vinson-Cole-Paata-Burchuladze-Wiener-Singverein-Wie)
3. Hit play, the "tracks" `Requiem D-Moll KV 626`, `I. Introitus`, `II. Kyrie`, etc. will be included in the queue

The issue with this is that these are not real tracks, but rather just section titles. In the [Discogs page](https://www.discogs.com/master/115159-Mozart-Anna-Tomowa-Sintow-Helga-M%C3%BCller-Molinari-Vinson-Cole-Paata-Burchuladze-Wiener-Singverein-Wie) of this album they show up as bold with a darker background to show that. I have only tested this problem on with the Discogs provider, though it may also be present on others.

**Comment by sewe2000** [comment]
I can confirm the bug exists also in the AUR version.

**Comment by sewe2000** [comment]
OK, I've fixed this bug in my nuclear version. Now I need to learn how to make a test for that. Here's a screenshot of search results which I've got:
![image](https://user-images.githubusercontent.com/59435262/172062194-3064124e-00c8-4e56-9375-9a375132bff1.png)

**Comment by nukeop** [comment]
Going to be tracked in #1671 from now on
