### ISSUE TITLE
Is there a Proxy setting ? 

### ISSUE THREAD

**Issue by Postroggy** [nukeop/nuclear#1169]
as you know, many websites are blocked by GFW, I wondered if there is a proxy setting that would be very elegant

**Comment by nukeop** [comment]
What's GFW?

**Comment by Postroggy** [comment]
The Great Firewall

**Comment by nukeop** [comment]
I don't know what that is but it doesn't sound like it's in the scope of this program to handle that.

**Comment by Postroggy** [comment]
> I don't know what that is but it doesn't sound like it's in the scope of this program to handle that.

Yep, this is beyond what the service this Program does. `nuclear` seems like doesn't provide an interface that user can customize their way of accessing the internet.
BTW， we can use proxy traffic to visit the website which is blocked by our government.

**Comment by 18601673727** [comment]
This feature is very much needed for Chinese users.

**Comment by nukeop** [comment]
I don't think it's the responsibility of a music player to help you circumvent your particular government's technological security measures. You can use a vpn and iptables if you need to reroute traffic.

**Comment by 18601673727** [comment]
@nukeop Yes, despite all those downloading apps & browser apps, a proxy configure UI plus certain params to backend is mission impossible.

**Comment by Postroggy** [comment]
@nukeop Yes, you're made a really awesome app, but I think it would be even better if you could provide a configurable proxy interface. I mean if there is a chance to add this feature that would be better.

**Comment by nukeop** [comment]
Can't you just reroute all your traffic through a proxy? Why should individual programs need these settings and be involved in the network layer?

**Comment by 18601673727** [comment]
Because not everybody living in a free world listening to free music

**Comment by nukeop** [comment]
Not my problem

**Comment by Postroggy** [comment]
> Can't you just reroute all your traffic through a proxy? Why should individual programs need these settings and be involved in the network layer?

Alright,  Thanks for your kind reply,.and I translate your project README.md , Hope it will help. : )

**Comment by willshion** [comment]
just add a butten/selection plz！！！！

**Comment by NePoCz** [comment]
Since this is an electron app, you can simply suppy the "--proxy-server=server:port" flag when starting the app:
https://www.electronjs.org/docs/api/command-line-switches#--proxy-serveraddressport
