### ISSUE TITLE
Segfault on start

### ISSUE THREAD

**Issue by SplittyDev** [nukeop/nuclear#117]
Starting the AppImage for the first time shows the usual "do you want to integrate ... with your desktop environment" modal. After that, it consistently crashes. The deb release shows the same issues.

Platform: Ubuntu 18.10 64-bit

```
./nuclear-0.4.3-x86_64.AppImage
[1]    5067 segmentation fault (core dumped)  ./nuclear-0.4.3-x86_64.AppImage
```

**Comment by SplittyDev** [comment]
Seems like it.

I found a workaround for Ubuntu 18.10:
https://launchpad.net/~maarten-fonville/+archive/ubuntu/ppa/

Closing this since you can't do anything about it

**Comment by payonpowbl** [comment]
@nukeop Update the electron. This is the fix.
