### ISSUE TITLE
HTML tags showing up literally

### ISSUE THREAD

**Issue by SpaceWAGdev** [nukeop/nuclear#1174]
**Platform:**
Windows 11
Version 21H2 (OS Build 22000.434)

**Nuclear version:**
0.6.17

**Description of the issue:**
The album title's HTML tags aren't rendering 
and are instead interpreted literally.

![image](https://user-images.githubusercontent.com/74885358/151885859-33075b35-5ead-47f1-8c28-11e03fd644df.png)

**Comment by nukeop** [comment]
Already fixed on master
