### ISSUE TITLE
Javascript error each time a song is 'touched'

### ISSUE THREAD

**Issue by TriggerDingus** [nukeop/nuclear#1175]
Linux - Pop OS 21.10
Nuclear 0.6.17
When I select an album, I receive a Javascript error for every song added to the playlist from that album. I then receive the same Javascript error every time it advances to the next song while playing the playlist. I have two machines with Nuclear installed and this behavior is the same on both machines.

![Screenshot_20220112-145908](https://user-images.githubusercontent.com/75340371/151899047-6f70de29-b35c-4d0e-b633-1f3d45e74cd6.png)

**Comment by nukeop** [comment]
Duplicate, fixed on master
