### ISSUE TITLE
Listening history

### ISSUE THREAD

**Issue by FIXMBR** [nukeop/nuclear#1177]
Listening history would be handy, keeping a list of recently played songs even if you cleared the queue. Also it could be used for listening stats.

**Comment by nukeop** [comment]
This is a good idea, the implementation will of course need to keep the history on the local machine.

**Comment by HaiDang666** [comment]
I have 2 questions:
  - Is the history stored in the same file as config and playlists?
  - Does it need a setting to limit the history length?

**Comment by itayweb** [comment]
Hey @nukeop , can I work on it? I'll consider what @HaiDang666 mentioned

**Comment by HaiDang666** [comment]
I assigned it to you.

**Comment by TheThinker277** [comment]
Hi @nukeop , Is this issue closed?

**Comment by nukeop** [comment]
Yes it is, the previous person never got back to us.

**Comment by Cor4zon** [comment]
Hi! Can i take this issue?

**Comment by nukeop** [comment]
Does @TheThinker277 still want it?

**Comment by nukeop** [comment]
Implemented
