### ISSUE TITLE
Nuclear not working on flatpak NixOS

### ISSUE THREAD

**Issue by jakobneufeld** [nukeop/nuclear#1178]
**Platform:**
NixOS installed with flatpak with no issues
**Nuclear version:**
0.6.17
**Description of the issue:**
The app works OK, but everytime I play or pause I get this annoying error popup. The app does not crash, it just appears.
![image](https://user-images.githubusercontent.com/24791219/152014801-078859f0-1dfe-42d6-a236-d10c93a3a52b.png)

**Comment by nukeop** [comment]
Flatpak is updated now
