### ISSUE TITLE
Playlist Removing all duplicated songs

### ISSUE THREAD

**Issue by chrisemke** [nukeop/nuclear#1183]
**Platform:** 
Linux: Manjaro linux
Kernel: 5.16.4-1-MANJARO
Electron: v16.0.8

**Nuclear version:** Nightly

**Description of the issue:** When you add the same song 2 times or more in a playlist and try to remove one, it removes all the same song

**Comment by chrisemke** [comment]
I've recorded a video showing the bug

https://user-images.githubusercontent.com/63082743/152160927-48a5a7a5-432d-4622-b421-2869f8cc6e47.mp4

**Comment by Gavin-Sun555** [comment]
Can this be worked on?

**Comment by nukeop** [comment]
Sure, would you like to be assigned?

**Comment by Gavin-Sun555** [comment]
Yes, I would like to be assigned.

**Comment by nukeop** [comment]
Alright, thanks for taking this.
