### ISSUE TITLE
Livestream does not mute

### ISSUE THREAD

**Issue by chrisemke** [nukeop/nuclear#1185]
**Platform:**
Linux: Manjaro linux
Kernel: 5.16.4-1-MANJARO
Electron: v16.0.8

**Nuclear version:** Nightly

**Description of the issue:** When I try to mute the livestream (0% volume) it keeps playing at low volume

I recorded an example video of the bug:

https://user-images.githubusercontent.com/63082743/152163218-61a0111d-f286-4728-91d2-191277971cd6.mp4

**Comment by maxyoumj0** [comment]
I'm unable to replicate this bug. Could you please describe how you encounter that bug?

**Comment by sahilmehra2412** [comment]
Not able to replicate the issue.

**Comment by LAS3RBOY** [comment]
There should be a Feature where if you click on that sound icon it should stop playing the music which is an alternative to lowering the volume.
