### ISSUE TITLE
Match Songs by Length

### ISSUE THREAD

**Issue by nathanharper** [nukeop/nuclear#1188]
Would it be difficult when finding audio sources to cross check the track length with what was found in Discogs, and prioritizing closer length matches? I'm finding that often I'll get a live track or, if an album has a title song it will load the a track containing the entire album rather than the song. I realize that by its nature this is never going to be perfect, but I think that trying to match the track duration would go a long way.

**Comment by nukeop** [comment]
I'm already working on that on the branch https://github.com/nukeop/nuclear/tree/feature/improved-search-accuracy

I will also include other heuristics that you can see described by the test cases I created yesterday.

**Comment by nathanharper** [comment]
@nukeop awesome! thanks, i'll close
