### ISSUE TITLE
Local HTTP server for returning info and accepting commands

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#120]
Useful for integration with other programs and services.

Some possible examples:

* `POST http://localhost:8080/nuclear/next-track`
Switch to next track

* `GET http://localhost:8080/nuclear/now-playing`
Get playback info, e.g.
```json
{
  "artist": "Yes",
  "track": "Roundabout",
  "album": "Fragile",
  "duration": 510,
  "cover": "https://upload.wikimedia.org/wikipedia/en/c/c0/Fragile_%28Yes_album%29_cover_art.jpg"
}
```
* `POST http://localhost:8080/nuclear/shuffle`
```json
{
  "status": true
}
```
Enables random playback.

**Comment by vilanz** [comment]
@nukeop Interesting, should this be hidden beneath some switch?

**Comment by nukeop** [comment]
Yeah, as a way of integrating the program with any external tools. For example, you could then easily add playback info to polybar, or create a dmenu script for interacting with the player, or write all sorts of CLI utilities.

**Comment by nukeop** [comment]
Implemented by @charjac
