### ISSUE TITLE
Fix icon size for macOS clients

### ISSUE THREAD

**Issue by mariobrostech** [nukeop/nuclear#1201]
**Platform:** macOS Big Sur

**Nuclear version:** 0.6.17

**Description of the issue:** The macOS app icon displays too large and looks out-of-place when compared to other apps on the system. The issue is most pronounced in the Dock but can also be seen in Launchpad and the Applications folder. I've attached a screenshot as an example below:
<img width="210" alt="Screen Shot 2022-02-08 at 2 23 01 PM" src="https://user-images.githubusercontent.com/17557442/153060320-36b6ac75-443d-443b-ad37-23c6540e7cbe.png">

Any fixes would be highly appreciated!

**Comment by nukeop** [comment]
We use the same standard size of icons on every platform. If there's some manual padding added by other programs then it's a stupid design choice by Apple which should be fixed on the system level instead of requiring third party developers to make special adjustments for their platform.

**Comment by mariobrostech** [comment]
From a very rudimentary inspection, it appears as if one of the major differences is the size of the icon. Apple's Pages app (pictured in the center of my prior screenshot) uses a 256x256 icns file, while Nuclear appears to use a 512x512 icns file. I have very little dev experience, so I'm not sure if I'd need to recompile the app to make this change, but if that's required, then I'd be more than happy to look into doing to see if that's the cause. I'm not sure what kind of padding is used with other apps, but I could upload the Pages icns file to be used as a point of reference.

**Comment by nukeop** [comment]
It's 512x512 according to these guidelines: https://www.electron.build/icons
I think it's just for detail - it's scaled to the required size by the system.

**Comment by mariobrostech** [comment]
Ok, that makes sense. I was honestly just guessing. I'll have another look later today to see if anything stands out as being blatantly different between the two icons. If there's someone who knows a bit more about UI than I do, they're more than happy to chime in while I dig into this further.

**Comment by mariobrostech** [comment]
Got it! I'll have a look and will let you know if I come across anything that might be helpful.

**Comment by nukeop** [comment]
Fixed on master. There's a new icon with the built-in padding.
![image](https://user-images.githubusercontent.com/12746779/167745985-4cd1f6e7-d94f-4204-acf7-4c38efb056ae.png)
