### ISSUE TITLE
quotes show on track titles in Best new tracks

### ISSUE THREAD

**Issue by protodrew** [nukeop/nuclear#1203]
**Platform:**
linux (deb)
**Nuclear version:**
6.17
**Description of the issue:**
quotes show around all song titles in the Best new tracks section

![image](https://user-images.githubusercontent.com/42788583/153064393-59e5d211-aa99-4ac6-ac87-c5ae68ef2d8e.png)

**Comment by nukeop** [comment]
They started showing up like this here: https://pitchfork.com/reviews/best/tracks/

**Comment by mina-bk** [comment]
Hello, I'm new to this project and would like to contribute! I noticed this issue is also prevalent on Nuclear's latest build MacOs package. I have a proposed solution ready. I just need to test it. Is this issue still open? and if so, can I claim it?

**Comment by nukeop** [comment]
Sure, but this issue should be solved here: https://github.com/nukeop/pitchfork-bnm
And then the dependency should be updated in Nuclear.

**Comment by nukeop** [comment]
Fixed now.
