### ISSUE TITLE
Pressing playlist causes program to stall

### ISSUE THREAD

**Issue by rudrrayan** [nukeop/nuclear#1206]
**Platform:**
EndeavourOS

**Nuclear version:**
I have tried both the nightly appimage and latest version, as well as the AUR bin version

**Description of the issue:**
When I press the playlist button (The play button for playing through a playlist) the screen goes grey and the terminal shows the error
renderer > t.toLowerCase is not a function

**Comment by ifuckinghatetheantichrist** [comment]
Check this issue
https://github.com/nukeop/nuclear/issues/1231

**Comment by nukeop** [comment]
Fixed in #1231
