### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Flerris** [nukeop/nuclear#1208]
**Platform: Windows 10 20H2**

**Nuclear version: 0.6.17**

**Description of the issue: When I try to listen to my songs from the playlist, the application freezes, but if I open the same music through the search, everything works as it should.**

**Comment by nukeop** [comment]
Can you please attach the playlist?

**Comment by Flerris** [comment]
[1.zip](https://github.com/nukeop/nuclear/files/8047643/1.zip)

**Comment by rudrrayan** [comment]
yes I am having this issue as well. I posted an issue for this just before, and it is still persistent even with the nightly builds or compiled versions on the AUR. The error, specifically, is t.toLowerCase is not a function

**Comment by nukeop** [comment]
Playlists were refactored recently so it should no longer be a problem
