### ISSUE TITLE
Error happens every music playback.

### ISSUE THREAD

**Issue by craudiomilho** [nukeop/nuclear#1211]
**Platform:**

Debian Testing

**Nuclear version:**

0.6.17 (Flatpak)

**Description of the issue:**
![Screenshot_20220214_220835](https://user-images.githubusercontent.com/82006827/153973797-92f52d8b-59f9-43f1-978c-ec1b415d7512.png)

A message like " A Java script error occurred in the main process" happen when the music will start.

**Comment by nukeop** [comment]
Duplicate #1081
