### ISSUE TITLE
Improve documentation for building Nuclear

### ISSUE THREAD

**Issue by mariobrostech** [nukeop/nuclear#1212]
Hi,

While trying to compile Nuclear for the first time, I came across a few inconsistencies in your build instructions that I hope you'll consider fixing.

Specifically, when following the [compilation instructions](https://nukeop.gitbook.io/nuclear/developer-resources/development-process), you recommend using the following command to clone the repository: `git clone git@github.com:nukeop/nuclear.git`. This command doesn't work if you aren't signed into your GitHub account. For maximum compatibility, the command should be `git clone https://github.com/nukeop/nuclear.git` instead.

I didn't see a repository with the source code for your documentation. If I did, I would've made a pull request there. Is there any reason why that repository doesn't exist?

Also, I had a few other problems building, but I haven't had time to look into them to determine whether or not those are my fault, an issue with the build instructions, or something else. I'll post them in comments to this issue if they continue to be a problem.

Thanks in advance!

**Comment by nukeop** [comment]
The repository with the docs is here: https://github.com/NuclearPlayer/nuclear-docs/

I'd like to keep the cloning command with ssh, since this is mainly made for contributors, and it makes it easier to commit code this way, you don't have to enter the password every time.

**Comment by mariobrostech** [comment]
Sorry, I didn’t see that repo when I was looking for it. Thanks for sharing it, and I’ll be sure to open any future issues there.

Also, I had no idea about what you’re saying with the SSH cloning command, but that totally makes sense. I’m going to close this issue now that you’ve answered my question and pointed me to the right place for reporting future documentation issues.

Thank you!
