### ISSUE TITLE
Real-time 432 Hz Tuning

### ISSUE THREAD

**Issue by neve132** [nukeop/nuclear#1213]
Feature request: A button/toggle to enable real-time 432 Hz tuning -
in VLC I have to go the advaced settings to tune:
https://roelhollander.eu/en/432-tuning/real-time-auto-pitching-video-player/

I should work livestreams ideally.
Thanks.

**Comment by nukeop** [comment]
Thanks for the suggestion, is it needed because people upload videos tuned down so they evade the content detection on youtube?
