### ISSUE TITLE
Playlist deleting bug

### ISSUE THREAD

**Issue by uqlel** [nukeop/nuclear#1222]
**Platform:**
Windows 11
**Nuclear version:**
[2dd909](https://github.com/nukeop/nuclear/releases/tag/2dd909)
**Description of the issue:**
When I've accidentally added the two same songs, i've deleted one and other deleted automatically. I've added it once again and I saw that I've it three times in this playlist. When i've deleted it, half of my playlist was deleted :cry:

**Comment by nukeop** [comment]
I could reproduce the first half (deleting a duplicated track deletes all of the duplicates), couldn't reproduce the rest.
