### ISSUE TITLE
Nuclear playing wrong musics.

### ISSUE THREAD

**Issue by rnpereira** [nukeop/nuclear#1223]
**Platform:**
Linux Manjaro

**Nuclear version:**
2dd909

**Description of the issue:**
I searched for a band, Naxatras, and the results came ok. The albuns were there, the music's names and time were displaying correct, but when I tried to play a song, it played a different song, from a different artist, despite showing me the albun's cover.
![Captura de tela de 2022-03-10 00-24-01](https://user-images.githubusercontent.com/72388096/157582533-e9a39fa7-51a4-40b6-b477-74f805e4cea4.png)
You can see on the image that the song I'm playing is 3 minutes long, while the original song is 11 minutes long.

I tried a few artists and the results were all the same.

**Comment by nukeop** [comment]
Which streaming source are you using?

**Comment by rnpereira** [comment]
I was using Audius. Didn't change anything, because I didn't know how it worked. 
Now I changed to bandcamp, and the song is right. but I cannot play all the songs. I know they are there as I've listened several times. If I use youtube I can play all the songs at least for this album I'm listening to at the moment.
Here's the link of the album at  [bandcamp](https://naxatras.bandcamp.com/album/iii)
Do I close this issue and open another one specific for the missing songs?

**Comment by nukeop** [comment]
If the songs are not available in a particular source there's nothing we can do unless somebody uploads them. Youtube usually yields the best results, but the other providers are needed for some niche artists.

**Comment by rnpereira** [comment]
Sure, but since the song is available at bandcamp, why nuclear cant play it?
Songs  4 and  5 dont play on nuclear, but I can play on bandcamp.
![Captura de tela de 2022-03-11 00-28-11](https://user-images.githubusercontent.com/72388096/157796688-f34036a0-88fe-4d30-b2d0-d49e62aac8e0.png)

**Comment by BinaryGenius** [comment]
Same issue here I keep getting really random youtube videos it breaks the whole vibe of listening to music. One minute I'm listening to someone sing their heart out the next I'm listening to body builder podcasts.

**Comment by nukeop** [comment]
Please open a new issue with the incorrectly retrieved tracks and we'll see what can be done.
