### ISSUE TITLE
Mac m1 arm support?

### ISSUE THREAD

**Issue by DanMossa** [nukeop/nuclear#1224]
Hello! I'm curious if there have been discussions on releasing a native m1 build?

Thanks!

**Comment by nukeop** [comment]
This is possible using electron builder: https://github.com/electron-userland/electron-builder/issues/5392

Needs to be configured and it should be pretty easy

**Comment by nukeop** [comment]
Implemented by #1336

**Comment by fulldecent** [comment]
Can this issue please be reopened since this feature is not shipped and, I believe, it is still in the project scope?

**Comment by nukeop** [comment]
Right, I reverted the PR but never reopened this issue.

**Comment by nukeop** [comment]
There's a new arm64 package for M1 macs.

**Comment by fulldecent** [comment]
Result of the new binary, trying on M1 Mac.

![Screenshot 2024-07-23 at 10 54 03](https://github.com/user-attachments/assets/38b9582b-163f-4d41-bb02-9772e8aef750)
