### ISSUE TITLE
Create New Playlist on Enter

### ISSUE THREAD

**Issue by Drew-Daniels** [nukeop/nuclear#1228]
I noticed that when creating a new playlist, the form is not able to be submitted on Enter. I think adding this would be a nice feature so users wouldn't be forced to manually click the Save button rather than press Enter.

![image](https://user-images.githubusercontent.com/62859552/159094431-c61d0287-f02b-4d99-bf9e-706d80bad55d.png)

**Comment by nukeop** [comment]
Good idea, thanks for reporting

**Comment by huangworld** [comment]
take

**Comment by rechavarria** [comment]
Hi! This feature is also missing on the macOS version and I would like to start working on this issue if possible.

**Comment by nukeop** [comment]
Ok, I assigned you. This is platform independent so it will be missing everywhere.

**Comment by nukeop** [comment]
Implemented
