### ISSUE TITLE
Errors are not getting logged

### ISSUE THREAD

**Issue by sourpatched** [nukeop/nuclear#1230]
**Platform:**
flatpak
**Nuclear version:**
January 28, 2022 Version 0.6.17
**Description of the issue:**
Getting so many errors but none show up in logs and can not copy the errors to report them.

**Comment by nukeop** [comment]
If they don't show up in the logs where do you see them?

**Comment by sourpatched** [comment]
Within the app, It doesn't allow me to copy the error.

This is one many of the errors
![Screenshot from 2022-03-21 08-35-51](https://user-images.githubusercontent.com/99369884/159186979-155a814b-1a5b-40e8-97d0-c306dbd2b51d.png)

**Comment by nukeop** [comment]
This error is now gone
