### ISSUE TITLE
"t.toLowerCase is not a function" when try and play a song in a playlist

### ISSUE THREAD

**Issue by kjukmar2** [nukeop/nuclear#1231]
Platform: Linux Mint 20.3

Nuclear version: 0.6.17; Appimage with AppimageLauncher

Description of the issue: I can't say that I really if I do things correctly, but it appears to be riddled with problems at my machine. At the very start of the appimage (and the .deb package previously) there's is an "Cannot read property 'sourceName' of undefined" error. But now a more serious issue appeared. The appimage just crashes when it tries to play one particular song (https://www.youtube.com/watch?v=T_3TY8Cx03w) when it's in a playlist, but by itself that song can be played perfectly fine. I tried running the appimage in the terminal, and it reported 2 "t.toLowerCase is not a function" errors at the same time when I replicated the bug. I am really at a loss, as so far the player has been doing wonders.
![Screenshot_20220320_163027](https://user-images.githubusercontent.com/101963516/159151024-51be81c9-b1d9-4121-ab79-e439f22ff21e.png)

**Comment by nukeop** [comment]
Needs investigation and debugging

**Comment by huangworld** [comment]
Claim this.

**Comment by weiji-li** [comment]
I will be working with @huangworld on this issue.

**Comment by kjukmar2** [comment]
I want to add a little something. I first encountered the bug when i copy-pasted the link to youtube music video in the app's built-in search bar. During now i have tried looking up the same song just in the app, and the problem persisted. I also want to add that this problem seems to be caused by other songs by this artist.

**Comment by nukeop** [comment]
I don't think that matters since pasting a link to a youtube video doesn't do anything special, it just searches for this string in the selected search provider.
