### ISSUE TITLE
Save songs in audio format instead of video

### ISSUE THREAD

**Issue by JamesClarke7283** [nukeop/nuclear#1233]
Songs should be in formats such as mp3,ogg,opus when downloaded.
We don't need the song video/webm file for a song. just the audio counterpart.

**Comment by nukeop** [comment]
Webm is just a container format, what is inside is only audio. When searching for streams on youtube, Nuclear rejects all streams that contain more than audio. It lets you select audio-only formats, and we only pick the one with the highest available quality.

**Comment by JamesClarke7283** [comment]
> Webm is just a container format, what is inside is only audio. When searching for streams on youtube, Nuclear rejects all streams that contain more than audio. It lets you select audio-only formats, and we only pick the one with the highest available quality.

This causes problems, because when i copy the music to my phone, most music players do not index it.
Maybe you could convert it to a pattent free format(like you did with video format webm) such as opus/ogg, which is audio.

**Comment by nukeop** [comment]
Transcoding is on the to-do list, but it introduces a lot of problems (mainly related to bundling ffmpeg on different platforms and reducing quality).

**Comment by JamesClarke7283** [comment]
> Transcoding is on the to-do list, but it introduces a lot of problems (mainly related to bundling ffmpeg on different platforms and reducing quality).

I am glad its being worked on.
Also, with FLAC i think you won't lose quality as its lossless. I may be wrong about trans-coding to FLAC reducing quality.

**Comment by nukeop** [comment]
There's no source yet that downloads FLAC though. They all use lossy compression.

**Comment by TommyHrablo** [comment]
I´d like to see if possible using premium account (YT Music or Spotify - depends on what Nuclear are running atm.) To grab and save the best quality.

**Comment by nukeop** [comment]
Like I said in the other thread, this would require access to youtube API, which implies having a youtube account and a registered "app". No go.

**Comment by TommyHrablo** [comment]
> Like I said in the other thread, this would require access to youtube API, which implies having a youtube account and a registered "app". No go.

Thank you for your answer and explanation

**Comment by nukeop** [comment]
Transcoding added in https://github.com/nukeop/nuclear/commit/ac8bdac813613e02826bb58fde73a7353908e96e
