### ISSUE TITLE
CI creating new tags without changing the version number

### ISSUE THREAD

**Issue by maxadamo** [nukeop/nuclear#1237]
**Platform:** Ubuntu

**Nuclear version:** 0.6.17

**Description of the issue:** 
I try to download the latest Deb package, created through `Gitub Action`, but for instance, the latest tag called `2dd909` is still a Debian package version 0.6.17. 
If I use `apt install` it does not perform the update and it says: `nuclear is already the newest version (0.6.17)`
If I use `dpk -i` it works but it says: `Unpacking nuclear (0.6.17) over (0.6.17)`

**Comment by nukeop** [comment]
I think this is ebcause i.deb takes the version number from package.json, and it needs to be changed there for it to work correctly. On AUR, I had to add the current timestamp to the version number because it expects monotonously rising versions.

**Comment by nukeop** [comment]
Fixed now
