### ISSUE TITLE
Add support for Android 

### ISSUE THREAD

**Issue by LifeIsStrange** [nukeop/nuclear#124]
Please :)

**Comment by nukeop** [comment]
https://github.com/nukeop/nuclear-mobile

Watch this in the future...

**Comment by sepiropht** [comment]
Awesome project! I really need to be part of this. React-native is a good choice.

**Comment by vilanz** [comment]
@nukeop "in the future"? Is mobile a priority currently? I must admit I'm way too excited about helping with this, as it's what I've been wanting for like, forever.

**Comment by nukeop** [comment]
Android release is not a priority, because I do not own an Android phone and would need to get one (or an emulator) to start developing. If there's demand though, it might influence my priorities, but first I'd need to move more functionality into the core package (nuclear-core).

I planned to do start the work around version 0.7.0.

**Comment by LifeIsStrange** [comment]
@sepiropht actually i find react native to seems cool but not being yet production ready, for exemple it has subpar modern CSS support (e.g no CSS grid), and does not support many important features such as multithreaded js (web workers, as async promise js is single threaded)

**Comment by sepiropht** [comment]
@LifeIsStrange Not production ready ? react-native is used by some big player like airbnb, instagram ...
What are other options swift/kotlin or maybe flutter ?

**Comment by LifeIsStrange** [comment]
@sepiropht production ready is a relative term, with enough workforce, you can redevelop some of the many missings browsers features of react native, and through external libraries uses (but a lot are underdevelopped/documented/tested) and through workarounds, you can product almost anything with react native. But if you have an advanced frontend, and you have no massives ressources, you may hit the react native bugs/missing features and be in difficulties, probably needing to simplify the front/layout.

As for airbnb they have dropped react native, i'm not saying it is a bad technology if you fit the common pattern, but it's risky if your front is not so casual.
Using a webview with https://github.com/GoogleChromeLabs/carlo and eventually webassembly (rust or c++) is battle tested and featureful. A massive advantage is that it allow you to reuse a billion of existing libraries instead of reinventing the wheel, it also allow to share code with the desktop and TV.

others options like flutter seems to me even less mature (and needs you to learn a langage with no future (dart), and doing full native through swift kotlin does not allow to share code between Ios/android and should be far less productive.
webviews still allow through api to launch native components like notifications or camera.

There are some optional frameworks that can be used to accellerate development with a webview, mostly IONIC, and the usueal bootstrap, react/jquery/vue/redux, materialize for meterial design, scss, etc

**Comment by sepiropht** [comment]
I haven't heard before of carlo. Does this work on mobile ? It seems to me that is more like a alternative for electron.
I don't like dart either but google use it a lot for his products (fushia, google ads). Flutter and tooling around it look amazing. 
How could you be so sure that dart has no future ?
I want to believe you, i prefer reason but dart/google/fushia seems already too strong, no ?

**Comment by Coderdude112** [comment]
> https://github.com/nukeop/nuclear-mobile
> 
> Watch this in the future...

@nukeop, I'm assuming this changed as the repo isn't there anymore. Do you have plans on bringing it back?

**Comment by nukeop** [comment]
I added my answer to the FAQ: https://nukeop.gitbook.io/nuclear/faq#is-there-an-android-ios-version

**Comment by Coderdude112** [comment]
Oh gosh and it's the first FAQ. My god do I feel dumb

Sorry & have an amazing day!

**Comment by NicTanghe** [comment]
Hello the reason started that the Google App Store doesn’t except it is kind of weird ?
Why not Just distribute using f-droid ?

**Comment by Korb** [comment]
> Why not Just distribute using f-droid?

One reason is enough:

> I don't have a smartphone and I'm not planning to get one
