### ISSUE TITLE
Can't play a playlist that has over 30 songs 

### ISSUE THREAD

**Issue by southernpoint** [nukeop/nuclear#1244]
**Platform:** Windows 10 Version 21H1 

**Nuclear version:** 2dd909 

**Description of the issue:** Whenever I try playing a playlist that has more than 30 songs, the app suddenly goes empty in a way.
Playing a playlist with less than 30 songs works though as shown in the video that I will send.
[https://cdn.discordapp.com/attachments/570599293585457152/962319100904882266/2022-04-09_14-51-50.mp4](url)

**Comment by nukeop** [comment]
That sounds pretty specific, are you sure it's because it has more 30 songs?

**Comment by Kugelblitz29** [comment]
> That sounds pretty specific, are you sure it's because it has more 30 songs?
i have the same issue but with a playlist that has 15 songs

**Platform:** Windows 10 Version 21H2
**Nuclear version:** f5ec0d

**Comment by AsianKoala** [comment]
>  I find that for 20+ added tracks it can take 10's of minutes to resolve them. And it is obviously worse when you add 1400 tracks :-). 

Yep I have this same problem for my main playlist of ~400 songs. nuclear tries to load everything and ends up with >50% CPU usage, as well as slowing down my network.

**Comment by tio-trom** [comment]
Same here, when you try to load more than say 50 songs at once, Nuclear goes nuclear :D - it tries to pre-load them all....I think this is a major issue.

**Comment by nukeop** [comment]
The tracks will now load one by one.
