### ISSUE TITLE
Unable to remove ghost Favourite Artists.

### ISSUE THREAD

**Issue by KitsunesForce** [nukeop/nuclear#1249]
**Platform:**
MacOS - Monterey
**Nuclear version:**
Latest
**Description of the issue:**
Unable to remove multiples of a Favourited Artist.
Other Artists are able to be removed, however, a mislabeled Artist is unable to be removed
<img width="525" alt="SS 2022-04-10 at 3 29 59 PM" src="https://user-images.githubusercontent.com/103147980/162636438-84d79be7-4c65-46b9-b272-816437ccc7c6.png">
.

**Comment by nukeop** [comment]
Do you know how these entries were created? You could probably remove them manually from the config.

**Comment by KitsunesForce** [comment]
> Do you know how these entries were created? You could probably remove them manually from the config.

Yes, I searched the artist Frank Carter & The Rattlesnakes through Discogs, and incorrected added an artist I thought was the one I was looking for.

How may I find the config file you're referring to on MacOS to manually remove the entries.

Thank you so much for the fast reply, and amazing software.

**Comment by nukeop** [comment]
On Mac, it's in ` ⌁/Library/Application Support/nuclear/config.json`. It's a text file and favorites are stored under the key called "favorites". You should be able to delete these entries from there.

**Comment by KitsunesForce** [comment]
> On Mac, it's in ` ⌁/Library/Application Support/nuclear/config.json`. It's a text file and favorites are stored under the key called "favorites". You should be able to delete these entries from there.

Worked like a charm.
Thanks a lot for the speedy support, ticket market as closed.
