### ISSUE TITLE
[Arch] most music won't load.

### ISSUE THREAD

**Issue by Papergami45** [nukeop/nuclear#125]
The program runs and starts fine, but any music I try to play simply shows a pulsating Nuclear logo filling up the whole window. Left this for a good 10 minutes and got nothing. Bit confused, maybe I'm missing a prerequisite or something? Is audio supposed to be playing here?

Edit: Did get one song to play, but tried playing another and error repeated. Now that song won't play. Issue with pulling from certain sources?

**Comment by saadshahd** [comment]
Happens to me in Ubuntu

**Comment by saadshahd** [comment]
same as #122

**Comment by rosolowski** [comment]
The same on mac

**Comment by nukeop** [comment]
Should be fixed now.
