### ISSUE TITLE
Local library not updating

### ISSUE THREAD

**Issue by dann1kid** [nukeop/nuclear#1255]
**Platform:** 
win10

**Nuclear version:**
setup.52769a.exe

**Description of the issue:**
![image](https://user-images.githubusercontent.com/40342734/163440670-804854de-45df-4b43-ad42-9b7a5e57f433.png)

**Comment by nukeop** [comment]
Is F:/music_vk.py a file or a folder? How many tracks do you have there?

**Comment by dann1kid** [comment]
> Is F:/music_vk.py a file or a folder? How many tracks do you have there?
Yes, 982

![image](https://user-images.githubusercontent.com/40342734/163582532-3f79709d-ee86-4b13-b01c-10b923ca22af.png)

**Comment by baduts** [comment]
Geting the same error on Linux, error is: 
ipc api › error in event set-localfolders => End-Of-Stream ipc api › Error: End-Of-Stream 

I'll have a look and see if i can fix this

**Comment by dann1kid** [comment]
Its works! Thank you 😏
