### ISSUE TITLE
Nuclear results are different from yt-dlp and cannot find the song I can find with yt-dlp

### ISSUE THREAD

**Issue by LeChatNoir666** [nukeop/nuclear#1265]
**Fill in the form to describe your problem**
I have a problem with: AronChupa - LLama in my living room
It happens when: searching
My OS is: (Windows)
I'm using Nuclear version: Newest (installed today)

Great tool so far!
But today I found out, that the search can't find the song im looking for.

I've "made" a simple YT-Player as batch for the Win Command Line like:

```
set /p "input=Lied oder Gruppe? "
yt-dlp.exe --quiet --force-overwrites -f best.2 ytsearch:"/%input%, 1" -o - | bin\ffplay.exe -loglevel quiet -i - -fs -autoexit
```

And if I search with it for "llama in my living room" it plays the right video:
https://www.youtube.com/watch?v=l-sZyfFX4F0

If I search with Nuclear I can't find this song.
All I get is a live(?) version which don't sounds good and some remixes.

Tried to search for 
"llama in my living room" 
"aronchupa llama in my living room"
"AronChupa, Little Sis Nora - Llama In My Living Room"
aso...

Even if I click on the artist and let me show all songs I don't get the version linked above.

What I'm doing wrong?

**Comment by nukeop** [comment]
What version do you get? For youtube, we don't use the top video returned from ytdl, we apply some heuristics first. If you let me know what video you're getting I'll be able to tune the heuristics so they return the correct one.

**Comment by LeChatNoir666** [comment]
Wow! Fast answer! Impressing! :)

How I can tell you which version I get?
I can't find a link or so on the video...

I've made a screenshot...
It might help.

![Search_Result_llama](https://user-images.githubusercontent.com/59604462/163845060-dadf3c2a-3739-4c52-8c40-3abc00149b44.png)

**Comment by LeChatNoir666** [comment]
The 2nd one is also the wrong version.
It's an remix...

Also I've tried:
"AronChupa Little Sis Nora Llama In My Living Room"
"AronChupa, Little Sis Nora - Llama In My Living Room"
"AronChupa, Little Sis Nora Llama In My Living Room"

Then I'll get no result.

Btw...
If I click on a song to list in a library how can i get rid of the menu other than pressing ESC key?

**Comment by LeChatNoir666** [comment]
I found an old version of Nuclear on my PC (0.6.10) and it looks like it found the right version if I search for "llama in my living room".
I'm not 100% sure because the strange thing is, the song starts at 1:11 and can't be started from beginning... :D

**Comment by nukeop** [comment]
>  I'm not 100% sure because the strange thing is, the song starts at 1:11 and can't be started from beginning... 
It's because sponsorblock cuts out non-music segments, in this case it's an intro to a music video.

**Comment by LeChatNoir666** [comment]
Oh... ic...
It's not really an ad but the blocker think it is i guess... :)

So there is a huge difference how your famous player blocks ads and how yt-dlp blocks it, or?
