### ISSUE TITLE
bandcamp plugin doesn't work (fedora flatpak)

### ISSUE THREAD

**Issue by piotrowskiadam** [nukeop/nuclear#1271]
**Platform:**
Fedora 35
**Nuclear version:**
2dd909 (Flathub version)
**Description of the issue:**
When bandcamp plugin is selected as the default music source the song doesn't play  and loading only keeps on spinning. Works again when switched to youtube plugin however the databases of artists, albums etc. are different in these services

**Comment by nukeop** [comment]
Should be fixed now.
