### ISSUE TITLE
Theme Support?

### ISSUE THREAD

**Issue by wadkarkundan** [nukeop/nuclear#1277]
I want to know if it is possible to change the theme of the player to go with my setup?
Gnome 42 and installed via Flatpak

**Comment by nukeop** [comment]
It's not possible currently, and Semantic UI doesn't really have good theming support, so it would require a lot of extra work. It's not on my roadmap, unless someone decides to contribute it.

**Comment by wadkarkundan** [comment]
> It's not possible currently, and Semantic UI doesn't really have good theming support, so it would require a lot of extra work. It's not on my roadmap, unless someone decides to contribute it.

thanks and no problem at all I love the UI and app.
