### ISSUE TITLE
Advanced ways to search YouTube

### ISSUE THREAD

**Issue by foblys** [nukeop/nuclear#1286]
I keep my music offline and have developed two strategies to find good quality tracks to download. I know little TS, so I won't promise to implement much, but I figured I'd share my thoughts anyway.

Example of a typical scenario: A search for `imagine dragons enemy` on YT gives `https://www.youtube.com/watch?v=omVvuL0lOes` and `https://www.youtube.com/watch?v=D9G1VOjN_84`. The first is a lyrics video with an additional outro (blocked by SponsorBlock, but still audible). The second one is a music video with additional sound before and after.

Adding `topic` to the search instead gives `https://www.youtube.com/watch?v=vxa8ShIm9yw` as the first result, an official and completely clean track. This is often the case for songs from well-known artists.

Another way is to add `lyrics` as a search term. These videos often have outro music and, in some cases, silence in the beginning. This can often be mitigated by picking the shortest one. In the above example, selecting the shortest one from the top three when adding `lyrics` gives a track without anything extra before or after. This strategy also works best for well-known artists. It should be noted that this sometimes results in a low quality track, but in my experience that is quite rare.

What are your thoughts? Are these good ideas to implement?

**Comment by nukeop** [comment]
We already do some heuristics on the search results: https://github.com/nukeop/nuclear/blob/9a004152fc15d4b8cc147f75fba66ceee0260d16/packages/core/src/rest/heuristics.ts

You can see the ways we determine the best track to pick by reading the tests: https://github.com/nukeop/nuclear/blob/9a004152fc15d4b8cc147f75fba66ceee0260d16/packages/core/src/rest/heuristics.test.ts
