### ISSUE TITLE
I cannot upload favorites from last.fm, need help

### ISSUE THREAD

**Issue by gaerea** [nukeop/nuclear#1288]
**Platform:**
Linux

**Nuclear version:**
2ec701

**Description of the issue:**
New guy to nuclear, just installed it. Trying to import from last.fm for the fist time. Also new to last.fm, just registed so i could have a pseudo account in nuclear, i think a account or a way to import/ export or have an account is missing in the app.

That said, i get Done 0/0 imported when i import. I don't know what im doing wrong.

![nuclear0_0](https://user-images.githubusercontent.com/102356922/172010198-222730fb-d510-4616-afde-1741c3fb1d5b.png)

![last fm](https://user-images.githubusercontent.com/102356922/172009383-0fe1b4c1-523e-4c35-8a0f-81c627701f88.png)

![last fm2](https://user-images.githubusercontent.com/102356922/172009397-d507b9bd-168e-4277-aeef-18487e6023f0.png)

![last fm3](https://user-images.githubusercontent.com/102356922/172009401-ed2c676d-c21b-4c0d-8573-5d5f91d428ba.png)

**Comment by nukeop** [comment]
We've changed the import function to allow importing any number of favorites.
