### ISSUE TITLE
Local library browser unusably laggy after importing. Also, search is broken.

### ISSUE THREAD

**Issue by MFG38** [nukeop/nuclear#1290]
**Platform:** Windows 10 21H2

**Nuclear version:** 9f77fc

**Description of the issue:**
The local library browser became very slow and unresponsive after importing my local music library of ~4,000 tracks. Using the browser was a slog with the software taking a solid second to respond to scrolling the mouse wheel a single notch.

Also, the search function in the local library browser is broken. Even though the software supposedly imported my entire music library successfully, it seemed like it only gave search results when it wanted to. I tried it with a few different band names - bands I **knew** were in my library - and only one actually returned any results. The other queries I tried returned no results whatsoever.

On a perhaps unrelated final note, a look at Task Manager gave me readings of the software using ~1.4GB of my 16GB of RAM. And that was when simply browsing the local library and not playing anything. I don't know if this is specific to the local library browser - didn't benchmark it against the other features - but either way, using that much memory is inexcusably high when Windows Media Player uses less than 50MB. This software is going to need some serious optimizations (at least on the local library side of things) to become usable.

**Comment by nukeop** [comment]
Windows Media Player is a different program with a different set of features. Library indexing was never optimized for larger libraries since the focus of the program is on streaming.

**Comment by MFG38** [comment]
Surely it *could* be optimized for larger libraries, though, eh? You know, give it equal attention and all that. I get that the streaming is the focus, but that shouldn't come at *this* high a performance cost for people like me who just happen to prefer their music locally. If I'm given the option to use my local library, I will, and I expect it to work.

**Comment by nukeop** [comment]
It definitely can be optimized and improved, and I thought it could be implemented as a native Node module in C or maybe Rust. At this point it doesn't even update the scanning status correctly. But currently, I don't find it interesting enough to work on it myself. So if anyone wants to contribute this functionality, I will be more than happy to review the code and merge it.

**Comment by Korb** [comment]
Import settled on the value of `22173/46345` and then does not move. In the process manager, the application is almost inactive.

Perhaps, at the beginning of scanning, when there is a more specific number of audio files, the application should warn the user about a possible dramatic decrease in performance and to refuse the user to use this application to play local files from the media text.

Nuclear Music Player v0.6.31 x64
Microsoft Windows 10.0.19045.4651
