### ISSUE TITLE
GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by cybertelx** [nukeop/nuclear#1297]
**Platform:**
- Pop!_OS 22.04
- NVIDIA MX150
- NVIDIA driver 455

**Nuclear version:**
[3f9007](https://github.com/nukeop/nuclear/releases/tag/3f9007) 

**Description of the issue:**
Nuclear process crashes because of GPU process apparently, appimage & deb.
Using `--no-sandbox` as an argument seems to work to prevent this issue.

```
(node:54514) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
[54514:0630/205745.096138:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

Searching this up online shows that it may be fixable by upgrading Electron.

Edit: Flatpak works

**Comment by nukeop** [comment]
Do you remember where you've seen this? We're on a pretty recent Electron version and GPU acceleration has worked for a long time (e.g. visualizer uses it)

**Comment by cybertelx** [comment]
What do you mean?

(Also, flatpak seems to work just fine)
