### ISSUE TITLE
Freedom issue: dependency on chromium via electron

### ISSUE THREAD

**Issue by JamesClarke7283** [nukeop/nuclear#1299]
**Platform:**
All
**Nuclear version:**
All
**Description of the issue:**

Your package has some freedom issues due to its dependency on electron. This prevents it from being fully free/libre software.

See relevant issue here:
https://labs.parabola.nu/issues/1167

I know this is an ethical issue but not directly a user "error", but since the issue which arises from a technical dependency and needs technical intervention i listed it as a "bug".

# Why this s problematic for a free/libre licensed package

I disagree with this statement [Here](https://github.com/nukeop/nuclear/blob/master/docs/electron.md) on people who dislike electron, while Memory issues is a technical detail, one that does not bother me either as if its libre software people can change it, but the only requirement for it to be free is its entirely free software. 

Its only, the dependency on non-free components which i consider an issue, from the standpoint of This being a free software application, this may be classed as not entirely libre as by proxy of the library, the [Four freedoms](https://www.gnu.org/philosophy/free-sw.html#four-freedoms) Are restricted.

This is why all [FSDG complient](https://www.gnu.org/distros/free-system-distribution-guidelines.en.html) distros don't allow electron applications because they are non-free by proxy. And its really unfortunate this issue has not been resolved By either Google or the QT team. I dont see Google stepping in to separate the non-free components from the free ones and chromium has always had these issues.

If you need more detail on why this is problematic  i recommend reading the gnu.org page linked above, its mentioned else ware as well. 

# You may ask, well if that dependency is not entirely free software. What shall we use instead?

There are many different ones, but i think NeutralinoJS might be a good replacement and has no nonfree dependencies and seems to be well designed.
https://neutralino.js.org/

Also as a bonus, looking at the less important technical aspects rather than the ethical ones, It is more lightweight on resources which is what lots of people were complaining about with electron.

It also works independent from whatever frontend/backend technology you want to use. Including the web engine as it does not embed a browser, it uses existing web engines available on the os.
For GNU/Linux apparently webkit is the default, but any engine available should work as its done via a library at the OS level behind the scenes.

And its less resource intensive.

I would like to clarify the technical part is just a bonus. The thing that is of concern is the dependency which is non-free by proxy.
I have checked and its not really practical to use electron without this non-free dependency as far as i know its a hard dependency. And even if there was a way to do it, i don't see it been fixed upstream anytime soon, if at all, based on what Ive read about their comments on the matter.

# What about ungoogled chromium as the dependency instead of chromium for electron?

Firstly that would have to be a custom version of the upstream electron most likely, even then, ungoogled chromium patches does not aim to solve all the freedom issues. Only remove some of them.
I know this because of discussions on FSF mailing lists and looking at the source tree myself on the fully patched version, and looking at google chromium vanilla upstream code.

# Conclusion

I can understand this project has got complaints about electron before of a technical nature, and i sympathize with developers who constantly get requests to use something "better" and I understand the struggle. And have huge respect for free/libre software developers like everyone here as its not an easy job to compete with proprietary platforms like Spotify/Deezer.

My concern is only of a freedom/ethical nature of the default state of being a non-free package by proxy. Which restricts the 4 freedoms by proxy.

I think this is an Awesome project, and the only one which uses a free software license and is able to be a reliable/user friendly replacement for those proprietary Music platforms, and I think as far as i know this is the only issue preventing it from being entirely free software.
Thanks for reading (:

Edit: Sorry if the earlier link to NeutralinoJS was wrong, ive fixed that link now.

**Comment by nukeop** [comment]
I check alternatives to Electron regularly, because they keep popping up, but none of these projects has the same capabilities or the level of support or stability. Most are supported for a few weeks/months, then are abandoned.

I'm familiar with Neutralino but it's missing the apis that we use in Electron, such as ipc, and many other examples that are critical to implemented functionality. Replacing it would require significant effort, with no immediate payoff.
I'm open to accepting contributions that attempt to replace Electron, but as things stand, I don't think that's feasible due to the alternatives being subpar and missing features. I'll be more than happy to be proven wrong though.

I also disagree with this statement:
>Your package has some freedom issues due to its dependency on electron. This prevents it from being fully free/libre software.

Chromium is a free and open source software, due to its BSD-3 license. Electron is free and open source, due to its MIT license.

Even if they were not, that does not affect whether Nuclear is free or not, as the entirety of its codebase is licensed under AGPL. I don't think Nuclear uses any of the components you've mentioned, rendering the issue meaningless.

What practical reasons would there be to replace Chromium in this case? I don't see my freedom being violated in any way due to some optional libraries being bundled in the binaries, I don't use them anyway.

**Comment by JamesClarke7283** [comment]
> I check alternatives to Electron regularly, because they keep popping up, but none of these projects has the same capabilities or the level of support or stability. Most are supported for a few weeks/months, then are abandoned.
> 
> I'm familiar with Neutralino but it's missing the apis that we use in Electron, such as ipc, and many other examples that are critical to implemented functionality. Replacing it would require significant effort, with no immediate payoff. I'm open to accepting contributions that attempt to replace Electron, but as things stand, I don't think that's feasible due to the alternatives being subpar and missing features. I'll be more than happy to be proven wrong though.
> 
> I also disagree with this statement:
> 
> > Your package has some freedom issues due to its dependency on electron. This prevents it from being fully free/libre software.
> 
> Chromium is a free and open source software, due to its BSD-3 license. Electron is free and open source, due to its MIT license.
> 
> Even if they were not, that does not affect whether Nuclear is free or not, as the entirety of its codebase is licensed under AGPL. I don't think Nuclear uses any of the components you've mentioned, rendering the issue meaningless.
> 
> What practical reasons would there be to replace Chromium in this case? I don't see my freedom being violated in any way due to some optional libraries being bundled in the binaries, I don't use them anyway.

Thanks for your quick response, 

Its unfortunate that its not convenient to make the switch, and lacking some functionality in the replacements. However from the standpoint of it being like a web browser, i would imagine there is nothing technically stopping it. But i appreciate it would take time to do.

I dont have much background in this, and am working on other projects, like making Microsoft Access files be fully compatible with Libreoffice Base out the box, with almost functionality(Reports, Queries,Forms), except macros.

Regarding why this makes your software non-free by proxy,
I have explained why. And listed links to the relevant resources above, which explain in more detail.
The users will be running proprietary software bundled with the app.

I have also explained why Chromium is non-free. It has the Widevine DRM module preinstalled which is proprietary and that does not even come close to all the pieces of non-free/obfusticated code(unreadable) inside it, it is talked about extensibly in the resources above..

**Comment by nukeop** [comment]
Like I said, that DRM is not used in Nuclear in any capacity. So it doesn't matter freedom-wise. It's an inert piece of bits. It doesn't affect my licensing, or even the functionality in practice, so I'm not buying this definition of freedom. It hasn't been a issue for me or any of the tens of thousands of users so far.

Are there any practical problems with this I'm not seeing?

Switching to Neutralino at this point is not feasible, because it's missing critical functionality that makes Nuclear possible. It could either become a new project made by people who are interested in this, but there's no way Nuclear will switch to it.

**Comment by JamesClarke7283** [comment]
> Like I said, that DRM is not used in Nuclear in any capacity. So it doesn't matter freedom-wise. It's an inert piece of bits. It doesn't affect my licensing, or even the functionality in practice, so I'm not buying this definition of freedom. It hasn't been a issue for me or any of the tens of thousands of users so far.
> 
> Are there any practical problems with this I'm not seeing?
> 
> Switching to Neutralino at this point is not feasible, because it's missing critical functionality that makes Nuclear possible. It could either become a new project made by people who are interested in this, but there's no way Nuclear will switch to it.

DRM was one piece, its riddled with non-free parts which are active to render the page. I highly recommend looking at the links i sent firstly.

I will list one of them here:
https://labs.parabola.nu/issues/1167

I guess a practical issue to you as someone in charge of this project, is your software will be blacklisted from all FSDG complaint distros. As requires non-free dependency to run.

I am more concerned that users will be running potentially non-free code when using your program. And developers being dependent on that non-free upstream code for the program to work.

This is not a technical issue, but an ethical one, which restrictions those 4 freedoms.

**Comment by JamesClarke7283** [comment]
> Ok, but what are some practical issues stemming from that? Concrete examples? In all probability none of this code ever runs, so why would it matter? Even if you define software freedom very restrictively.
> 
> I've found so far that most people who cling to autistically defined freedom like this will never be satisfied and they are more interested in endless discussions (as evidenced in your links) than actually using my program. They are also not interested in doing anything to actually remediate those "issues" they point out, they want others to invest hundreds of hours to do it instead of them.
> 
> I looked through the distros on that list and don't see anything I've ever heard of or that would have any meaningful number of users to be honest, so I don't see any payoff from investing any time into this.

I gave you the VScode example.

Another example was [MonoDevelop](https://github.com/mono/monodevelop), they required a proprietary addon to function(the editor needed it).
Microsoft Gave up on maintaining everything with that, and most people don't know how to deal with this.
The project is now archived, but a dotdevelop fork exists with that component replaced, much like in our electron case replaced the nonfree dependency. 

https://github.com/dotdevelop/dotdevelop

Unfortunatelty dispite how it looks on gits end, its not practical for .NET development and largely is abandoned. People switched to Visual Studio or Vs Code instead. Which was what microsoft was working on as MonoDevelop "contribution" was so "Mac OS" developers could use .NET. So there was no insentive to microsoft to even maintain the non-free plugin never mind contributions to the repo.

Right now it might not be an issue, and you may think, well that wont happen.

This is not just my opinion, this is the official position about including nonfree programs in your code, from the FSF.
They do not endorse this.

There is no broad definition, just the 4 freedoms being able to be exercised in practice.

**Comment by nukeop** [comment]
In all my professional work I live by the rule of dealing with problems as they arise. So why hypothetically this scenario is possible, I don't think it's realistic to expect that it will happen. I think it's more likely that a random open source project like any of the Electron alternatives will die suddenly with no replacement, than Electron will.

Like I said I'm always open to contributions so if anyone wants to replace this dependency with something else, while keeping functionality intact, I will be more than happy to merge it. Not holding my breath though.

I don't really care what FSF has to say about the matter. All that matters to me is that my code is fully free and available under AGPL 3.

**Comment by JamesClarke7283** [comment]
Another example which is a bit different but similar in spirit of being dependent on something nonfree, is Nmap's non-free(as it currently stands) license. They are working to resolve this though, although not for a while. People thought it was the GPL but it was not its a custom license which makes it nonfree under the 4 freedoms and the OSD(Open Source Definition).

The fact that this happened is not good. I trust that nmap will resolve this one though. For now its blacklisted in all FSDG distros and distros like Gentoo, and i think Debian is waiting for the FSF to do another audit on the updated version. They will then decide if it goes in the "main" or "non-free" component, the later would mean its not available in the repos shipped with Debian.

Thats a direct licencing issue of that software, this one is more indirect and comes from upstream. But it has a tricle down effect.
I do trust Nmap to resolve the issue though, so hopefully they do that soon.

**Comment by JamesClarke7283** [comment]
Okay, that's unfortunate. Maybe i should do this,
I suppose another more difficult solution would be to go to someone further down the dependency chain Electron > Qt WebEngine > Google Chromium. And try and resolve it there.

Electron would have to use not Qt WebEngine. Replace it with one which does not rely on chromium.
Or
Qt WebEngine would have to not use Chromium, but a different web engine for QT like Webkit or Gecko(Firefoxes one)
Or dare i say
Get google to not bundle proprietary licenced code bundled in Chromium and lots of obfusticated javascript code that looks like Brain**ck.

I dont think its ideal either that googles telemetry will be included either from a user perspective, i dont like that i cant easily disable that when using your app.

**Comment by nukeop** [comment]
What google telemetry? We don't use any form of analytics in Nuclear.

**Comment by JamesClarke7283** [comment]
> That's news to me, can you show me any proof of this? As far as I tested it with Wireshark some time ago, there were no telemetry calls of any kind. Where did you get this information?

Common sense, this is why ungoogled chromium exists, removes DRM, some of the binary blobs and disabled the telementry which is usually on by default.

Its explained here:
https://github.com/ungoogled-software/ungoogled-chromium

**Comment by JamesClarke7283** [comment]
But that is for the vanilla google Chromium, not nessesarily one which was build differently with different options. as i say.

**Comment by nukeop** [comment]
I get that's the motivation behind the BROWSER called ungoogled chromium. I don't see how that applies to Electron, which is not a browser, and doesn't use the same exact code. I couldn't find anything with a google search, nor did I see anything using Wireshark. So i'm gonna assume that's a FUD lie.

**Comment by JamesClarke7283** [comment]
I am not making a lie.
I am saying if QtWebengine was built from vanilla chromium with no modification, Then it would naturally apply.

Its like if i was to embed Facebook Telementry in my library, and then someone uses it in their project. it passes on.

I was saying in that case where no modification was made. Then it would naturally pass down.

**Comment by nukeop** [comment]
Yeah, except I'm not embedding any telemetry libraries, and there's nothing to suggest that there is any. So like I said earlier, you seem to only be interested in bringing up some very made up sounding problems with no real proof, just to mess with me. You don't seem to be proposing any realistic solutions, or even proof that what you're saying is true (you just wave your hand saying "common sense"). It's common sense to me to just carry on and not care until it becomes a real, actual problem (but it never will).
