### ISSUE TITLE
Wrong link in README.md:

### ISSUE THREAD

**Issue by Flashwalker** [nukeop/nuclear#1302]
Wrong link in README.md:
`https://github.com/nukeop/nuclear/blob/master/docs/docs/electron-ru.md`

right link is:
`https://github.com/nukeop/nuclear/blob/master/docs/electron-ru.md`

**Comment by nukeop** [comment]
I'm planning to move this to a different place soon anyway. But since it's irrelevant to the program, I'm going to close this.
