### ISSUE TITLE
Add listener for media play pause

### ISSUE THREAD

**Issue by maxkraft7** [nukeop/nuclear#1306]
The key MediaPlayPause (https://www.toptal.com/developers/keycode/for/media-play-pause) could be utilized. It gets aleady used by most webbrowsers if you have streams running.

**Comment by nukeop** [comment]
I wanted to add it some time ago, but it doesn't work with https://www.npmjs.com/package/mousetrap which we use for keyboard shortcuts. I would be happy to merge this if somebody implements it.

**Comment by AnthonyMarin** [comment]
Turns out Mousetrap allows you to add keycodes. I just found the keycodes for the major media buttons added them using mousetrap.
![mtkc](https://user-images.githubusercontent.com/90010906/191602662-c7e5cfe1-08e0-4d52-a18c-617e34ee56a8.JPG)

**Comment by nukeop** [comment]
Implemented
