### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by ctsstc** [nukeop/nuclear#1307]
**Platform:**
MacOS: v11.6.7

**Nuclear version:**
v0.6.17

**Description of the issue:**
I can see the scrubber and timer going, and even the visualizer seems to be doing something, but there's no audio. I confirmed other applications could play audio just fine. I also tried restarting without any luck.  I wonder if it's choosing the wrong audio device somehow?

**Comment by nukeop** [comment]
I can't reproduce this on a Mac - provide more info

**Comment by DanMossa** [comment]
@nukeop I'm having the same issue.
M1 mac mini.
