### ISSUE TITLE
Artist Monetization

### ISSUE THREAD

**Issue by daniellivingston** [nukeop/nuclear#131]
**Issue not related to codebase stability or usage**

I think it would be brilliant to have, on artist pages, a small button that links to the artist's merch store.
This allows for the best of both worlds: free streaming, along with artist's capturing non-negligible revenue streams.

**Comment by nukeop** [comment]
Yeah, the problem is that I don't know of any source of URLs to these websites. If you know of any, then sure, it could be added.

**Comment by daniellivingston** [comment]
I think a first-pass solution might just capturing the top result of a Google search on `$(artist_name) merch`. I'll take a stab at this and submit a PR when I have the time.

**Comment by nukeop** [comment]
Awesome, really appreciated.

**Comment by trekiteasy** [comment]
I would support this. I found the following websites which could be interesting for this purpose : 
- https://bandcamp.com/developer/merch#get_merch_details
- https://www.merchbar.com

**Comment by nukeop** [comment]
Any attempt to add any such feature will likely be nipped in the bud (by me), unless done in a very subtle, tasteful way. Not saying it's impossible but I don't want my project to attract marketing and entertainment industry vultures who are interested in you only insofar as they can squeeze some spare change out of you. And I don't want to suddenly be the developer of the equivalent of a cheesy, tacky third world marketplace for peddling cheap chinese pink floyd t-shirts. I loathe any and all ads with all my soul and the last thing I will agree to is adding any to a project I run.

**Comment by jonocodes** [comment]
I love the artist tipping idea. I've been brainstorming with one outside of this app, but anyway....
Maybe a 'tip this artist' button could search the Patreon API for an artist page at least. Then nuclear could link to that page at least. Or even just link to other sites which 'likely' belong to the artist (www, bandcamp, myspace :), etc. )

**Comment by nukeop** [comment]
I think creating a service that will inform you of ways of rewarding artists you like is certainly possible, but would require a lot of manual data entering and cleaning. We'd need many users willing to help with collecting this info.

The chances of any artists, even small time, cooperating directly with us are of course slim, but if they were, they could enter their preferred way of getting paid directly into the service too. Not sure how many artists use Patreon either, I think Bandcamp is more popular. And when we do integrate with Bandcamp, we could naturally display everything artists have to offer on their pages, including vinyls, cds, and so on.

**Comment by jonocodes** [comment]
My idea was one that would not need curation.
I have been brainstorming a firefox plugin that would work on various sites (spotify, github, etc) where you could 'tip the creator'. Then the plugin would scrape various sites (patreon, bandcamp, etc) and find likely matches for the band.
It would then present these to the user and tell them these are likely artist matches. Then its on the user to decide which is which. Also there are DBs for things like this I have not looked into like https://musiciansatlas.com.

**Comment by boehs** [comment]
Keeping an eye on https://coil.com, would be monumental
