### ISSUE TITLE
Whenever I try to play anything on my playlist the application turns into a grey box

### ISSUE THREAD

**Issue by Minecraftnotlog** [nukeop/nuclear#1312]
**Platform:**
Pop!_OS
**Nuclear version:**
3f9007
**Description of the issue:**
I try to play something in my playlist the application turns into a grey box.
![Screenshot from 2022-08-23 11-10-38](https://user-images.githubusercontent.com/99844115/186195032-06ba4e21-7938-46e1-a4b4-c2e70d8ab876.png)

**Comment by nukeop** [comment]
Can you post the playlist?

**Comment by nukeop** [comment]
You can look in the config.json file (should be located in ~/.config/Electron or ~/.config/Nuclear), and post the whole file or just the playlist.

**Comment by Minecraftnotlog** [comment]
"lastFm": {},
        "settings": {
                "invidious.url": "https://invidious.snopyta.org"
        },
        "playLists": [],
        "favorites": {
                "tracks": [],
                "artists": [],
                "albums": []
        },
        "downloads": [],
        "equalizer": {
                "selected": "Default"
        },
        "last-thumb-clean-date": 1659885484753





that was what was in config.json

**Comment by mr-scripting** [comment]
Why was this closed? I'm having the same issue on windows with the latest release.

**Comment by DrachenfeuerHD** [comment]
> Why was this closed? I'm having the same issue on windows with the latest release.

Probably you are having the same problem as me. Please take a look at my issue. I am explaining there how to fix it.

#1328
