### ISSUE TITLE
For Mobile Android

### ISSUE THREAD

**Issue by MrConqueror** [nukeop/nuclear#1316]
Please do for Mobile

**Comment by MrConqueror** [comment]
@nukeop wdym completed??

**Comment by Korb** [comment]
> @nukeop wdym completed??

🤔 It seems to be a mistake.  There is no mobile application with this name on F-Droid, but on Google Play.

**Comment by ImGGAAVVIINN** [comment]
> @nukeop wdym completed??

It means it is not going to happen :(
