### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by MartyDreamy** [nukeop/nuclear#1318]
**Platform:**

Windows 10 ver 21H1 (build 19043.1889)

**Nuclear version:**
nuclear-b6e5b2

**Description of the issue:**
The player doesn't work, it doesn't stream music and it doesn't play my local music. I saw that someone else had an issue and that it was fixed but he was on Linux and I'm on Windows.

**Comment by nukeop** [comment]
Waiting for this to be fixed: https://github.com/fent/node-ytdl-core/issues/1131
