### ISSUE TITLE
Cant add local library from folder

### ISSUE THREAD

**Issue by EmirLogas** [nukeop/nuclear#1319]
**Platform:** Windows 10 build 19044.1889

**Nuclear version:** Nuclear b6e5b2

**Description of the issue:** Cant add local library from folder. When I select the location and click the refresh button, nothing happens. I downloaded 3 mp3s and tried again. Running as administrator didn't solve it either.

**Comment by nukeop** [comment]
I can't reproduce this on Mac/Linux, needs to be debugged by someone who has access to Windows.

**Comment by nukeop** [comment]
This can happen if Nuclear doesn't have read permissions to the folder you've added.

**Comment by EmirLogas** [comment]
> 

How can I authorize file access?

**Comment by nukeop** [comment]
I don't really know how it works on Windows but this could mean that you're trying to add a folder owned by an admin user (or just another user), while Nuclear is running with regular user permissions.

**Comment by EmirLogas** [comment]
I moved the folder to the desktop and it worked.

**Comment by EmirLogas** [comment]
It doesn't work when the location is like this.
![image](https://user-images.githubusercontent.com/76751818/188231318-0e6b8445-e9e9-4e74-998f-02fb314a5f24.png)
It works when the location is like this.
![image](https://user-images.githubusercontent.com/76751818/188231525-a16aa077-16c7-42cc-a555-ecd5739a810e.png)
Both folders have the same content.
