### ISSUE TITLE
Visualizer support

### ISSUE THREAD

**Issue by jberg** [nukeop/nuclear#132]
Hi, love what you are doing with this project.

I work on a port of the MilkDrop2 visualizer from Winamp to javascript: https://github.com/jberg/butterchurn

We have added support over at the Webamp project: https://webamp.org/

Would love to help add support for visualizations to Nuclear. Is this something that you would be interested in?

Thanks and awesome work on this project!

**Comment by nukeop** [comment]
Hey, if that's based on WebGL then I'm sure it can be added fairly easily. If you'd like to submit a pull request, you're more than welcome to, otherwise I'll try to add this myself at some point.

**Comment by nukeop** [comment]
If you do that maybe you could try adding a new entry in the left-hand menu, create a new view for the visualizer and render it there.

**Comment by jberg** [comment]
Sounds good! I'll give that a try

**Comment by jberg** [comment]
Had a little time to look around the source a bit. I see that you are using `react-sound` which uses `soundmanager2`.

In order to do the WebGL visualizations we need to get access to the [`AudioNode`](https://developer.mozilla.org/en-US/docs/Web/API/AudioNode) that `soundmanager2` is creating under the hood.

I'm not sure if `react-sound` is currently exposing access to `soundmanager2`.

So some small tasks we would need to do before moving forward:

- [ ] Get access to `soundmanager2` from `react-sound`
- [ ] Access `AudioNode`'s that `soundmanager2` creates

I'll try to figure these out when I have a chance, but figured I would post what I had "learned" so far, in case you knew more or had time.

Thanks!

**Comment by dhannyz** [comment]
@jberg this is awesome, is there somewhere i can have a chat with you about use of this on my own project, discord, slack, irc?

**Comment by jberg** [comment]
Thanks @dhannyz . You can reach me on this discord we use for Webamp: https://discord.gg/VP3BxQ

**Comment by jberg** [comment]
I've created an issue over at `react-sound` to determine the best way to access the underlying soundmanager2 instance: https://github.com/leoasis/react-sound/issues/75

**Comment by nukeop** [comment]
Adding something like this could be cool too: https://hackingbeauty.github.io/react-sound-display/
Either as an alternative visualizer or as a small widget somewhere (bottom bar maybe?).

**Comment by robertnealan** [comment]
@jberg Because react-sound uses SM2 under the hood you can still access the audio instance directly at `window.soundManager.sounds`, where `window.soundManager.sounds[window.soundManager.soundIDs['0']]` will automatically reference the current track playing.

**Comment by nukeop** [comment]
We don't use react-sound anymore now. It's been replaced with this: https://www.npmjs.com/package/react-sound-html5

**Comment by nukeop** [comment]
I know it took a long time, but it's finally in the newest release.

**Comment by jberg** [comment]
🥳 🥳 🥳
