### ISSUE TITLE
Play next sometimes stops current song and immediately starts selected

### ISSUE THREAD

**Issue by Efilex** [nukeop/nuclear#1321]
Platform: Manjaro 5.15.65

Nuclear version: 1662247798134:202293_9bf1a4ce1070f344d3a7a7195428aff0-2

Description of the issue: When clicking 'Play next' the currently played song sometimes is stopped and the selected song to be played next immediately starts (or sometimes any other song from the queue). This does not always happen, yet I couldn't yet figure out under which conditions this happens.
Last occurence for me was: playing a playlist -> selecting 'Play next' from artists 'Popular Tracks' selection.

Will update if I make further discoveries, maybe someone else has similar problems.

**Comment by tashilapathum** [comment]
Same issue here. I'm a new user and in my case it happened repeatedly when searching songs and using 'Play next'. The song immediately started playing but it wasn't from the beginning either. The new song started from where there previous song's timestamp was. After several times I used 'Add to queue' instead. 

Platform: Windows 11 (Build 22621.1555)
Nuclear version: 0.6.20

**Comment by nukeop** [comment]
This has been fixed now and will be available in the next release.
