### ISSUE TITLE
[Flatpak] runtime org.freedesktop.Platform branch 20.08 is end-of-life

### ISSUE THREAD

**Issue by mmahmoudian** [nukeop/nuclear#1324]
**Platform:**
> ```
> Operating System: Manjaro Linux
> KDE Plasma Version: 5.25.5
> KDE Frameworks Version: 5.97.0
> Qt Version: 5.15.5
> Kernel Version: 5.15.60-1-MANJARO (64-bit)
> Graphics Platform: X11
> ```

**Nuclear version:**
9545bf

**Description of the issue:**
According to Flatpak Nuclear uses a deprecated `org.freedesktop.Platform` runtime.

```console
❯  flatpak update 
Looking for updates…

Info: runtime org.freedesktop.Platform branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   org.js.nuclear.Nuclear

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.js.nuclear.Nuclear

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.js.nuclear.Nuclear

Nothing to do.
```

**Comment by nukeop** [comment]
Fixed by https://github.com/flathub/org.js.nuclear.Nuclear/pull/8 - thanks for reminding me

**Comment by Netherquark** [comment]
Platform:

    Operating System: Fedora/Nobara 36
    Kernel Version: Linux 6.0.7-201.fsync.fc36.x86_64 x86_64 GNU/Linux
    Graphics Platform: Wayland

Nuclear version:
8988ba

Description of the issue:
According to Flatpak Nuclear still uses a deprecated org.freedesktop.Platform runtime.

╰─ flatpak update 
Looking for updates…
Info: org.freedesktop.Sdk//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   org.js.nuclear.Nuclear
Info: org.freedesktop.Platform.GL.default//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Nothing to do.
