### ISSUE TITLE
can't play music from Musicbrainz

### ISSUE THREAD

**Issue by HeIIow2** [nukeop/nuclear#1326]
**Platform:**

 - OS: Ubuntu 22.04.1 LTS x86_64 
 - Host: B450M S2H 
 - Kernel: 5.15.0-48-generic 

**Nuclear version:**

 - 954bf (I think at least)
 - Flatpak

**Description of the issue:**

This Bug may either has something to do with nucleus, or with musicbrainz. I have searched for the artist "Crystal F" on Musicbrainz in Nucleus. The artist showed, his discography did, but once I added all Songs of "Kunst des Todes" or any other Album to the queue, all the songs dissapared one by one. But you can download the music and it works.

Maybe I just haven't set up everything correctly, the song playing of musicbrainz  is faulty or your program has a bug. Nevertheless thank you all so much for spending so much spare time in these kind of projects, so we all can enjoy and use them for free. <333

*excuse my music taste*

**Comment by nukeop** [comment]
Musicbrainz is a metadata source. The default streaming source is Youtube.
