### ISSUE TITLE
Discord Rich Presence Broken & Not Showing

### ISSUE THREAD

**Issue by JReverse** [nukeop/nuclear#1329]
**Platform:**
Windows

**Nuclear version:**
[9545bf](https://github.com/nukeop/nuclear/releases/tag/9545bf)

**Description of the issue:**
Discord Rich Presence Broken & Not Showing

**Comment by nukeop** [comment]
Somebody else was having trouble getting it to work on Windows recently, even though there were no changes in this functionality. Maybe discord changed something?

**Comment by Westsi** [comment]
I believe that Discord updated recently and that broke better discord and other client mods. I don't recall anything about rich presence though. Might be worth looking into

**Comment by Khilseith** [comment]
Hey, would just like to second that I am also experiencing this issue. I am experiencing this issue both on my Windows 11 desktop and on my gentoo linux laptop. 

I have absolutely no experience with electron or that much with js to begin with, so take anything I have to say beyond this with a grain of salt.

I managed to get it to actually display rich presence by changing the `discordClientId` to one from my own discord "application" and told it to on init set and send an activity that just said "test" or whatever. If I didn't change discordClientId it told me `error trying to connect to discord`.

And via attempts at logging I simply don't think events are being called. Particularly I was unable to verify `onSongChange` ever actually ran? 

Possibly related? An error I got when running `npm start` was 
```
ipc api Service failed to initialize 
ipc api TypeError: abs.connect is not a function
```
and
```
ipc api Service failed to initialize
ipc api Error: Could not locate the bindings file.
```

"testing" (if you can call it that) was done on the latest node LTS 18.12.1 on gentoo.

And so again, while I'd love to try and further debug this and maybe fix the issue, I have no idea what I am actually doing.

**Comment by nukeop** [comment]
More people are starting to report it. I'll look into fixing this soon. I think this could be because the person who created the app on Discord deleted his account.

**Comment by nukeop** [comment]
I merged a client ID update that fixes this.
