### ISSUE TITLE
Create a new playlist from the playlist selection dropdown

### ISSUE THREAD

**Issue by tauantcamargo** [nukeop/nuclear#1331]
the user should be able to create a new playlist without leave the current song page, just clicking in add to playlist show "add to playlist" and "create new playlist", when user click on second option, opens the modal to create playlist and that will trigger and action to save current song to new playlist created.

**Comment by nukeop** [comment]
This can be added to the existing context menu, just add a new option o create a new playlist at the bottom of the menu where you select the playlist to add a track to.

**Comment by jovanblazek** [comment]
Hi, is this available, can I work on this?

**Comment by nukeop** [comment]
Sure, I assigned you. Please check the contribution guidelines: https://nukeop.gitbook.io/nuclear/contributing/contribution-guidelines

The docs also contain instructions on how to start developing.

**Comment by jovanblazek** [comment]
What should be the name of the new playlist? Trackname, like on Spotify?

**Comment by nukeop** [comment]
The default name should be the track name, just like when you're creating a playlist from the queue, but it should be possible to change it from the input (the same exact flow).
