### ISSUE TITLE
Prioritize YouTube uploads from artist's official channels

### ISSUE THREAD

**Issue by unfa** [nukeop/nuclear#1333]
I am playing a track "Valkyrie" by Savant and it is available on the artist's own channel:
https://www.youtube.com/watch?v=akqzWMj-NpU

However Nuclear uses a 3rd party upload instead:
https://www.youtube.com/watch?v=VTxu7tEEQ1E

I guess this is because the original author's video title is confusing, as the album title is in there as well:
**Savant - Orakel - Valkyrie (artist upload)** -vs- **Savant - Valkyrie (3rd party upload)**

Maybe Nuclear could try and find official YT channels from artists and use that whenever possible?
It'd help make sure that artists get the views if they uploaded the track themselves instead of someone else who uploaded their music too.

Does this make sense?

**Comment by nukeop** [comment]
We use certain heuristics to choose the best video to source the stream from, such as certain keywords in the video title: https://github.com/nukeop/nuclear/blob/master/packages/core/src/rest/heuristics.test.ts

Unfortunately the library we use to interact with youtube does not differentiate between official and unofficial accounts. Maybe we could use the channel name though.

**Comment by nukeop** [comment]
I implemented this to fix the other issue you've raised. I'll check if it fixes this issue as well.

**Comment by unfa** [comment]
Thanks!

**Comment by nukeop** [comment]
After ranking videos from channels whose names match the artists higher, they are now ranked correctly.

**Comment by unfa** [comment]
Thank you!
