### ISSUE TITLE
Unable to install Nuclear on MacOs

### ISSUE THREAD

**Issue by alexandersuerof** [nukeop/nuclear#1337]
**Platform:**
macOs Monterey version 12.6. Device MacBook Pro(Retina, 13-inch, Early 2015)
**Nuclear version:**
[3f9007](https://github.com/nukeop/nuclear/releases/tag/3f9007)
**Description of the issue:**
When I try to install the "nuclear-3f9007.dmg" file, the system prompt to empty the app to the trash.

**Comment by nukeop** [comment]
Yeah that's a common bug of Mac OS where it fails to handle software whose developer did not pay the Apple Protection Racket fee. You can read how to install regular software on Mac OS here: https://disable-gatekeeper.github.io/

And how to disable this system-wide:
https://apple.stackexchange.com/questions/294013/how-to-allow-install-of-non-app-store-or-identified-developers-on-macos-sierra
