### ISSUE TITLE
Last.fm scrobbling not working

### ISSUE THREAD

**Issue by Korb** [nukeop/nuclear#1339]
**Platform:**
Microsoft Windows 10.0.19045.2130

**Nuclear version:**
nuclear-b2a752.exe:
Verified: Unsigned
Link date: 6:58 30.01.2018
Publisher: n/a
Company: nukeop
Description: Streaming music player that finds music sources automatically.
Product: nuclear
Prod version: 0.6.17
File version: 0.6.17
MachineType: 32-bit

**Description of the issue:**
After playing in this application several tracks found in it by search, new tracks did not appear on the page last.fm/user/%username%. Foobar2000 works fine with the same account, the tracks being played are displayed in my page on the last.fm.

![2022-10-19_12-40-11](https://user-images.githubusercontent.com/3509797/196656628-73d8a48f-324a-4725-ae54-0f9e7c60eaa7.png)

**Comment by nukeop** [comment]
Tracks are scrobbled when they finish playing. Could you please open the developer console (ctrl+shift+I), go to the network tab, and check if there's a request made to `https://ws.audioscrobbler.com/2.0/?method=track.scrobble` at the end of the track? You can skip near the end and let it play the last few seconds to do it faster.
