### ISSUE TITLE
Master Release not found

### ISSUE THREAD

**Issue by saadshahd** [nukeop/nuclear#134]
I get discogs: `master release not found` error with most of the artists

Steps:
 - Search for `Cardi B`
 - Try to play any song

**Comment by nukeop** [comment]
You sure about that? I just tried this artist and it did find an album, its tracks, and a stream to play.

**Comment by saadshahd** [comment]
@nukeop Sorry, try `Who want want the smoke?` track.

![image](https://user-images.githubusercontent.com/5410903/51280986-cb46cd00-19e9-11e9-9c5e-52d77cc98785.png)

The bug is blocker with all the Arabic artists you could try:

1. Cairokee
2. Amr Diab
3. Monir

**Comment by nukeop** [comment]
I can reproduce it now. I think this is one of the things we'll have to live with now, Discogs database has some inaccurate info and broken links to master releases. In the future I'll add more search sources and fall back on them if Discogs search fails.
