### ISSUE TITLE
Version Number has not been changed for a year

### ISSUE THREAD

**Issue by core-code** [nukeop/nuclear#1341]
is the latest stable release v0.6.17? or is it b2a752?

if the latest stable release is b2a752, why does it still have the version number 0.6.17 embedded? 

should all releases that are not 0.6.x be ignored?

**Comment by nukeop** [comment]
That's by design. I switched to using a short hash to mark releases. Easier and more accurate. The version in package.json doesn't matter.

**Comment by core-code** [comment]
it matters on macOS. the operating system determines which version is newest by looking into the CFBundleVersion.

a hash is not a valid version number as it doesn't numerically increase.

also app updaters like MacUpdater won't work if the version number doesn't increase. 

furthermore its just confusing for the user if they are still greeted by the same version number from a year ago:


<img width="424" alt="Screenshot 2022-10-20 at 12 42 32" src="https://user-images.githubusercontent.com/1261954/196927758-e1816731-b5ea-4c00-9592-c944b2748c84.png">

**Comment by nukeop** [comment]
You're right, the version number should be removed from package.json then and no longer used when building binaries.

**Comment by core-code** [comment]
no. any macOS app needs numerically increasing version numbers.

**Comment by nukeop** [comment]
That sounds like a problem with mac OS if it doesn't support different versioning schemes. Btw, I'm able to install and upgrade it from a dmg.

**Comment by core-code** [comment]
using a hash is not a "versioning scheme", as it doesn't numerically increase. 

> Btw, I'm able to install and upgrade it from a dmg.

yeah but if you have multiple versions installed, macOS won't be able to tell which one is newest because the CFBundleVersion never increased.

**Comment by BarbzYHOOL** [comment]
what about having a regular version number + the hash for easy issue debugging?
in fact, i couldn't find the hash in the app, I had to type "flatpak info xxxx.xxx.xxx" which is not easy

**Comment by core-code** [comment]
seems to be fixed now, thanks!

**Comment by nukeop** [comment]
Yep, we've switched back to semantic versioning.
