### ISSUE TITLE
Playback speed adjuster

### ISSUE THREAD

**Issue by Coloby** [nukeop/nuclear#1344]
I'm the kind of guy who like to speed things up and this [chrome extension](https://chrome.google.com/webstore/detail/spotify-playback-speed/bgehnoihoklmofgehcefiaicdcdgppck?hl=it) inspired me to make the request
![spotifyExtension](https://user-images.githubusercontent.com/71285067/197909533-78ea7daf-5d24-47ac-8cdf-2f8380f61e9a.png)

**Comment by Mish2j** [comment]
Hi there, I would like to work on this.

**Comment by nukeop** [comment]
Ok, how are you going to approach this? I'm not sure how to handle it on the web audio side and how to test it.

**Comment by Mish2j** [comment]
> Ok, how are you going to approach this? I'm not sure how to handle it on the web audio side and how to test it.

Hi @nukeop, so I went over the code and found a solution. We can add `ref` to `Sound` component and set `playbackRate attribute` to the `audio` HTML element that is a child element of `Sound` component. I tested It works fine. If you need more details or want to test it let me know. If this solution seems good to you, let me know so I keep working on it. Thanks!

**Comment by nukeop** [comment]
Nice, that sounds great. It can be tested by swapping out the Sound component with a mock.
