### ISSUE TITLE
Nuclear grabs wrong music with artist

### ISSUE THREAD

**Issue by BinaryGenius** [nukeop/nuclear#1346]
I have a problem with: (artist: RAMY track: Take Me To The Park Album: A good portion of RAMY albums)
It happens when: (Play the track)
My OS is: (Linux/Mac/Windows)
I'm using Nuclear version: Flatpak, Version: 9545bf
[config.zip](https://github.com/nukeop/nuclear/files/9894365/config.zip)

When ever I play that song or some other songs it grabs really random youtube videos. It breaks the whole vibe of the album and ruins the experience, I've heard eminem, some korean thing, hilary clinton, country, spanish music, among other things. Her songs are on youtube and sometimes they work when I press play a 100 times but other than that I can't listen to the music.

Edit: I'm under the impression that bugs like these will continue to spring up I propose a half solution. Nuclear could allow manual editing of music metadata and the user would manually point tracks to the correct youtube video then nuclear would remember that setting. Sort of like crowd sourced metadata collection. And maybe if enough users changed it that would be the default video grabbed by nuclear. *Just a thought.*

**Comment by nukeop** [comment]
I'll take a look what sources are available for this track and if the heuristics can be improved.

**Comment by nukeop** [comment]
The other solution is what I thought about some time ago but this needs servers - might be doable though.

**Comment by BinaryGenius** [comment]
I have good luck with itunesmusic that basically has everything for me just now the track played fine but then it when back to playing the wrong vid. I actually have to switch the bandcamp to find the right artist.

**Comment by BinaryGenius** [comment]
Any solution is welcome no matter how bodged it can always be refined later so shoot.

**Comment by nukeop** [comment]
Yeah that mechanism is hit or miss. I'm pretty sure it's the most accurate program for finding music on youtube given artist/title anyway. Crowdsourcing looks like the only possible way to make it accurate most of the time.

**Comment by BinaryGenius** [comment]
By program you mean Nuclear? Because I agree it's the only viable spotify replacement on flathub.

**Comment by nukeop** [comment]
Yep. There's actually an array of heuristics for matching streams to tracks, would be way worse without it. I have a plan for improving it somewhat, first I want to add a dropdown that will let you manually select the correct stream for the track, and then I'll think about implementing what you've mentioned.

**Comment by BinaryGenius** [comment]
I could download the track locally and favorite it that way would the solution take particularly long to implement because I prefer to search via the internet this would be a last resort.

**Comment by aalons01** [comment]
Hey! Thanks for your work first and foremost. Is there anything new with regard to this? I have few examples (songs) wrongly assigned

**Comment by nukeop** [comment]
Yes, you can now use the stream verification feature to manually correct these songs. These corrections are then saved on the server and can be used by everyone else too: https://nukeop.gitbook.io/nuclear/user-manual/stream-verification

I guess this issue can be fixed because verification addresses this problem.
