### ISSUE TITLE
Running "build:dist" is currently not supported under windows

### ISSUE THREAD

**Issue by L4B0MB4** [nukeop/nuclear#135]
Running "build:dist" error on windows.
**Expected**:
Runs "build:dist" without any error.
**Actual**:
Running "build:dist" on windows will run into an error due to the unknown command "cp". 
**Suggestion**:
Add:
"build:dist:win": "webpack --progress --colors --env=prod && **copy** loader.css dist" 
as another script to the package.json.

**Comment by nukeop** [comment]
I guess you'll need to get cygwin since likely this will be a problem with other npm packages too.

**Comment by L4B0MB4** [comment]
Okay by me but just fyi: everything else works fine. Just had to do this one-word-change :)
