### ISSUE TITLE
Downloading a music downloads a full mp4 video

### ISSUE THREAD

**Issue by BarbzYHOOL** [nukeop/nuclear#1350]
**Platform:** Linux ubuntu 22.4

**Nuclear version:** 9545bf

**Description of the issue:** I looked up "Wardruna" and clicked on the artist then the first result "Helvegen" (16 min long) and downloaded it, it was a mp4 video and when launched it started the video

**Comment by nukeop** [comment]
The downloaded version is selected using filters in https://www.npmjs.com/package/ytdl-core, specifically audio-only streams and highest quality available. If this results in a video then it's probably an ytdl-core bug.

**Comment by BarbzYHOOL** [comment]
or wrong config of ytdl-core maybe? dunno cant help more :P

**Comment by nukeop** [comment]
Transcoding added in https://github.com/nukeop/nuclear/commit/ac8bdac813613e02826bb58fde73a7353908e96e
