### ISSUE TITLE
Allow to hide the main window while keeping the tray icon

### ISSUE THREAD

**Issue by BarbzYHOOL** [nukeop/nuclear#1352]
I suppose it has already been suggested but I don't know the right keywords to search for

The tray icon works for me but if i close the app, it shuts down, so if you want to hide the main window and keep the tray icon only, the best way to proceed is to put nuclear in another workspace

What about a button to hide/show the main window instead?

**Comment by nukeop** [comment]
Yep this is a good suggestion. #932 is about the same thing.

**Comment by BarbzYHOOL** [comment]
ok wasn't sure it was the same thing

**Comment by Andres-Ventura** [comment]
@nukeop  Is anyone working on this?

**Comment by nukeop** [comment]
I don't think so.

**Comment by Andres-Ventura** [comment]
I can take this then. Assign me and @DHuizar to it. I want to show him how to solve an issue, make a PR, and more.

**Comment by nukeop** [comment]
Looks like @DHuizar needs to comment here before I can assign him.

**Comment by DHuizar** [comment]
hello

**Comment by nukeop** [comment]
Thanks, you're both assigned now!

**Comment by Semitalis** [comment]
Want to ping this as I see no progress on this or #932 either, but I would love for this to work ✌️
