### ISSUE TITLE
Cannot import from last.fm. Done! Imported 0/0

### ISSUE THREAD

**Issue by gaerea** [nukeop/nuclear#1361]
**Platform:** Debian based

**Nuclear version:** latest

**Description of the issue:** 
I login to last.fm
I give permission on browser
I do import in nuclear
i get 0/0 imported

![image](https://user-images.githubusercontent.com/102356922/200114844-404dad84-b37c-41c9-a4a3-974fa69b1b65.png)

I also use brave, and have a few add-ons
![image](https://user-images.githubusercontent.com/102356922/200115113-a1b19d13-3ed1-4c48-b764-a705f987faa7.png)

**Comment by nukeop** [comment]
According to you profile you don't have any favorite tracks: https://www.last.fm/user/impossible_fm/loved
