### ISSUE TITLE
Searching with Korean Language restart the application

### ISSUE THREAD

**Issue by limjiyoon** [nukeop/nuclear#137]
Hi,

I'm learning this program with Mac Mojave.
I had a problem with searching with Korean.
Could you please support multilingual searching system?

**Comment by nukeop** [comment]
Can you paste an example of search terms you used? It should be possible to use anything from unicode, if it isn't, it's a bug.

**Comment by limjiyoon** [comment]
I tried two words.
태연
악동뮤지션

**Comment by nukeop** [comment]
Actually works now.
