### ISSUE TITLE
Content on "Best New Music" not displayed correctly

### ISSUE THREAD

**Issue by DWTW321** [nukeop/nuclear#1374]
**Platform:** Windows

**Nuclear version:** 0.6.14

**Description of the issue:** Hi, I'm having a small issue with Nuclear, on the dashboard under "Best New Music" the content is not displayed properly and no images are loaded (please see the screenshot). However everything else (music streaming, album covers etc.) seems to work quite well. Any help would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/110170540/204073411-d1b93963-4b55-4161-a756-a0b128a58a72.png)

Thanks

**Comment by nukeop** [comment]
I just checked and it looks ok to me. This is probably because you're using an outdated version.

**Comment by DWTW321** [comment]
Ahh, I think you're right, the scoop version isn't up to date, sorry about that, and thanks for the reply 😄
