### ISSUE TITLE
Bug report or something like that

### ISSUE THREAD

**Issue by RichSexum** [nukeop/nuclear#1377]
**Platform:**
Windows 10 22h2
**Nuclear version:**
nuclear-e8fcb6.exe
**Description of the issue:**
Lately I have noticed that ncargan the covers in your reductor, I do not know if you have to activate an option but I hope you can help me. Pls.

![Captura de pantalla 2022-12-10 212259](https://user-images.githubusercontent.com/92557186/206884810-0aad35b5-bb51-46f9-b2c8-55b13a8ba65d.png)

**Comment by nukeop** [comment]
Huh?
