### ISSUE TITLE
Nuclear Silent Crash

### ISSUE THREAD

**Issue by Flornced** [nukeop/nuclear#1379]
**Platform:** AUR on EndeavorOS and Flatpak
**Nuclear version:** Tested only e8fcb6
**Description of the issue:** Launching Nuclear does not open any sort of window, GUI or notification. Nuclears' processes were shown in the computer's task manager but were stopped for no apparent reason after ~8 seconds. I have no idea why it fails to open. This happens on both of my AUR (both git and bin) and flatpak installs.
Here is the error message from my Flatpak nuclear install;

``[user@usercomputer]org.js.nuclear.Nuclear

[3 zypak-helper] Wait found events, but sd-event found none
      main › (node:3) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 13:16:07.503: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:16:07.503: Failed to load module "canberra-gtk-module"
      main › (node:3) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([ 'org.freedesktop.DBus.Error.ServiceUnknown' ])
    at n.emit (events.js:304:17)
    at emitError (/app/main/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:222:10)
    at /app/main/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:233:7
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
      main › (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:3) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3:1216/131618.012932:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
/app/bin/run.sh: line 2:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper /app/main/nuclear``

**Comment by nukeop** [comment]
I'm developing on Endeavor, and using the AUR version. Do you have dbus installed?

**Comment by Flornced** [comment]
dbus is installed. Nuclear still fails to launch and promptly self-terminates.

**Comment by Demizo** [comment]
I faced a similar error on Fedora 37 and was able to get the AppImage running with the launch argument "--no-sandbox". I haven't gotten the Flatpak running yet, but I was able to get a development environment running after adding "app.commandLine.appendSwitch("no-sandbox");" to main.ts.

**Comment by christophehenry** [comment]
Same problem here. Flatpak install, Fedora 37, `--no-sandbox` doesn't help.

<details>
    <summary>Stacktrace enclosed here</summary>
    <pre class="notranslate">
      <code class="notranslate">
      main › (node:3) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
      main › (node:3) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([ 'org.freedesktop.DBus.Error.ServiceUnknown' ])
    at n.emit (events.js:304:17)
    at emitError (/app/main/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:222:10)
    at /app/main/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:233:7
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
      main › (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:3) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3:0105/104432.541041:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
      </code>
    </pre>
</details>

`gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye` appearsto be a low-level chromium error as it appears [in this SO question about IntelliJ (embedded browser is in fault here)](https://stackoverflow.com/a/68548362) and searching specifically `gpu_data_manager_impl_private` gets us to [this chromium code file](https://chromium.googlesource.com/chromium/src/+/master/content/browser/gpu/gpu_data_manager_impl_private.cc).
