### ISSUE TITLE
Add list of sources to readme

### ISSUE THREAD

**Issue by timpulver** [nukeop/nuclear#138]
«Popcorn Time for music» indicates that Torrents will be used under the hood (which it seems it currently does not). It would be good to have a list of used sources in the readme, otherwise people like me might be put off thinking that nuclear uses torrents, which will surely lead to a lawsuit in some countries (like Germany). Better to make it clear what is currently uses and what is not.

**Edit:**
Found the list now:

>Searching for and playing music from youtube (including integration with playlists), bandcamp (including albums), and soundcloud

I still think that these should be easier to find (mark sources as bold text). Also making clear that no torrents are being used.

**Comment by nukeop** [comment]
There are no torrents now, but at some point there might be. At any rate, we give the users control over what sources are used, so it shouldn't be a problem either now or in the future.

**Comment by nukeop** [comment]
I made this thread to discuss changing the description: https://github.com/nukeop/nuclear/issues/140
