### ISSUE TITLE
No matter which version I install Nuclear will not run

### ISSUE THREAD

**Issue by Locutus64** [nukeop/nuclear#1380]
**Cachy a Arch based distro**

**Flatpak e8fcb6**

**No matter which version I install Nuclear will not run**

The below is from the previous version I tried to get to run including the Flatpak. I decided to try the Snap and it launches but only after I tell the dialog in the screenshot below yes or no.

```

     ~  nuclear                                                               ✔  at 02:45:51 PM   
      main › (node:18465) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
[18465:1220/144558.786005:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    18465 trace trap  nuclear
     ~  nuclear --trace-deprecation                                      TRAP ✘  at 02:45:58 PM   
      main › (node:18632) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
[18632:1220/144628.556248:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    18632 trace trap  nuclear --trace-deprecation
```

[https://i.imgur.com/EBwYI0Q.png](url)

**Comment by nukeop** [comment]
We had a workaround here: https://github.com/nukeop/nuclear/issues/1297
Can you try it?

**Comment by Demizo** [comment]
I had this same issue on Fedora 37. I was able to run the AppImage but adding the --no-sandbox launch argument like [#1297](https://github.com/nukeop/nuclear/issues/1297) . I haven't gotten the Flatpak to run, but I was able to get a development environment running after adding "app.commandLine.appendSwitch("no-sandbox");" to main.ts. Hopefully this issue solves itself as packages get updated. Hope that helps!

**Comment by SadAlexa** [comment]
Same issue, I use Arch with KDE on Nvidia driver. I tried to install the AUR version and also the Flatpak version but Nuclear return the same error message :(

**Comment by xdubx** [comment]
I get the error if i start the current version from source code. npm start ends with 
```
@nuclear/main: For help, see: https://nodejs.org/en/docs/inspector
@nuclear/main:       main › (node:19380) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
@nuclear/main: (Use `electron --trace-deprecation ...` to show where the warning was created)
@nuclear/main:       main › development Env variables loaded
@nuclear/main:       main › Initialized settings store at /home/user/.config/Electron/config.json
@nuclear/main:       main › (node:19380) ExtensionLoadWarning: Warnings loading extension at /home/user/.config/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi:
@nuclear/main:   Unrecognized manifest key 'action'.
@nuclear/main:   Unrecognized manifest key 'minimum_chrome_version'.
@nuclear/main:   Unrecognized manifest key 'update_url'.
@nuclear/main:   Permission 'scripting' is unknown or URL pattern is malformed.
@nuclear/main:   Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
@nuclear/main:       main › (node:19380) ExtensionLoadWarning: Warnings loading extension at /home/klaus/.config/Electron/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd:
@nuclear/main:   Unrecognized manifest key 'commands'.
@nuclear/main:   Unrecognized manifest key 'homepage_url'.
@nuclear/main:   Unrecognized manifest key 'page_action'.
@nuclear/main:   Unrecognized manifest key 'update_url'.
@nuclear/main:   Permission 'notifications' is unknown or URL pattern is malformed.
@nuclear/main:   Permission 'contextMenus' is unknown or URL pattern is malformed.
@nuclear/main:   Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
@nuclear/main:       main › devtools installed
@nuclear/main:       main › Local library database created at /home/klaus/.config/Electron/nuclear-local-db.sqlite
@nuclear/main:       main › Listening history database created at /home/klaus/.config/Electron/nuclear-listening-history.sqlite
@nuclear/main: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
@nuclear/main: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
@nuclear/main: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
@nuclear/main: [19380:1222/223936.492350:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
```

Have Pop OS 22. And a nvidia graphics card.

**Comment by Demizo** [comment]
Could you try adding `app.commandLine.appendSwitch('no-sandbox');` to you main.ts file? (under packages>main>src) I'm curious if this solves the bug for you. I have a similar system (Fedora 37, Nvidia Graphics)

**Comment by xdubx** [comment]
Thx. 
I added 
```
app.commandLine.appendSwitch('in-process-gpu');
```
works as well

**Comment by Locutus64** [comment]
OK I got the snap version working in CachyOS. Will try in Garuda and see if it works their as well. Now with that said I was getting a dialog box that I had to either hit yes or no on. When I finally chose no the dialog box never popped up again. All my sound got dropped down to 40 and a couple of other sound related issues. I made a report on it but don't was in the discord channel. However once I adjusted everything sound related back to what I had had it at my settings stayed on subsequent launches of the Nuclear snap.

**Comment by Locutus64** [comment]
OK I just installed snap and Nuclear and Nuclear is running. As for the sound on first attempt to run it dropped  the system sound down to 40% and reenabled the HDMI sound which I always turn off, but on subsequent launches after setting my sound back the way I have it Nuclear does not change it again.

**Comment by Lippiece** [comment]
How to use CLI flags?

I've an issue where nuclear crashes on launch.
I've installed nuclear on OpenSUSE Tumbleweed with flatpack.

**Comment by nukeop** [comment]
The runtime code is in the .asar archive, but you shouldn't be using that. You should be able to find the program in `/var/lib/flatpak/exports/share/applications` or `~/.local/share/flatpak/exports/share/applications`.

**Comment by Lippiece** [comment]
> The runtime code is in the .asar archive, but you shouldn't be using that. You should be able to find the program in `/var/lib/flatpak/exports/share/applications` or `~/.local/share/flatpak/exports/share/applications`.

Thank you. But I've tried these edits to `org.js.nuclear.Nuclear.desktop` with no success:

- `Exec=/usr/bin/flatpak run --no-sandbox --branch=stable --arch=x86_64 --command=/app/bin/run.sh org.js.nuclear.Nuclear`
- `Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/run.sh org.js.nuclear.Nuclear --no-sandbox`

Currently, only downloading the tar and launching the executable with the flag works. I've made a simple script but that's a sad solution.

**Comment by nukeop** [comment]
You can try this tool: https://flathub.org/apps/details/com.github.tchx84.Flatseal

It should let you add arguments to the installed programs.
