### ISSUE TITLE
waiting for download tracks on Mac

### ISSUE THREAD

**Issue by VURDO** [nukeop/nuclear#1383]
**Platform:**
macOS Monterey 12.6.2
**Nuclear version:**
 nuclear-e8fcb6 0.6.17 
**Description of the issue:**
download stuck pending (only 10 tracks),
while playing same tracks (one album) works fine.
November pre-release was returning same issue.
No VPN or net filters of any kind are enabled on iMac.
![Schermata 2023-01-03 alle 13 50 09](https://user-images.githubusercontent.com/81679880/210321136-09ec8d64-33f2-4911-8621-eb17931edb96.png)

**Comment by nukeop** [comment]
Should be fixed in the new release.
