### ISSUE TITLE
Export playlists as PNG

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#1385]
Currently, the only options for saving and sharing playlists are through JSON.

I propose that we allow users to export their playlists as PNG images, which would include the playlist title and some of the tracks in the playlist, plus Nuclear's logo. This would allow users to easily share their playlists on social media (Discord, Matrix) or other platforms where they can't easily share a json file.

To make this feature even more useful, we could also allow users to import playlists from PNG images. By embedding the playlist data in the PNG as a JSON object, we can allow users to simply drag and drop a PNG image into the app to import the playlist.

**Comment by dank-foss** [comment]
that is actually wonderful

**Comment by ColinPanarra** [comment]
Hi, I'm pretty new to the open source theme and would like to try to take this task on. I'll pull it right now and see what I can do!

**Comment by nukeop** [comment]
Ok, let me know if you start. And it's best to do it in small steps. Please also check out the contribution guidelines: https://nukeop.gitbook.io/nuclear/contributing/contribution-guidelines

**Comment by ColinPanarra** [comment]
Hey, I got it running and exporting the json for a playlist locally. Poked around a bit and wanted to make sure this is the right location to make changes 

_packages\core\src\helpers\playlist\index.ts_

If so I'll try to get started sometime this week

**Comment by nukeop** [comment]
Yep, that's one of the places that will need to be changed.

**Comment by ColinPanarra** [comment]
Hey I think I'm going to look for another issue somewhere else- I was looking into some libraries like 
https://github.com/Nishisonic/ts-steganography but ultimately I have 0 typescript experience and am struggling to get anything going. Sorry about that!

**Comment by Vivy24** [comment]
Hi , could I try to take this take ? Thank you and have a great day

**Comment by yatish-a** [comment]
I want to start with open source so is it fine if i take this as my first issue? i think we can use canvas and download it as an image.

**Comment by nukeop** [comment]
You're free to try, but please start small.

**Comment by yatish-a** [comment]
https://github.com/nukeop/nuclear/pull/1403 hey please check this out.

**Comment by nukeop** [comment]
Ok, can you post an example generated image? How is the playlist data encoded in it?

**Comment by yatish-a** [comment]
![playlist1](https://user-images.githubusercontent.com/109519133/221277768-5d7795b3-78b1-4521-bb0a-6dacfd5a898d.png)
the playlist data isn't encoded in it. this is for the first requirement of the issue where the playlist is shareable to social media. i looked into how to possibly encode the data in it and the best way seems to be as a xml string in the metadata of the image but that is currently beyond my abilities as it will take a lot of time.
