### ISSUE TITLE
Spotify import playlist progress stuck at 0%

### ISSUE THREAD

**Issue by jeffmprod** [nukeop/nuclear#1386]
**Platform: Windows**

**Nuclear version: 95cfe0**

**Description of the issue: When trying to import a Spotify playlist using the "Import from url (Spotify)" button, the progress bar just gets stuck at 0% and i can't tell if it's actually being imported and just takes a long time or if the functionality is broken**

**Comment by nukeop** [comment]
Have you tried restarting the import and trying again? It should at most take a couple of seconds.

**Comment by jeffmprod** [comment]
Yes, i've tried canceling and trying to import again multiple times.
Here is the playlist link: https://open.spotify.com/playlist/1ctQfQ513CcSUNOzlpS48G

**Comment by Demizo** [comment]
Jumping in just to say that this playlist does import properly on Linux, Nuclear version 95cfe0. Also I like your playlist @jeffmprod :)

**Comment by Rednas83** [comment]
I have the same issue. If it works on linux then it's probably related to windows. Is it also tested for windows?

**Comment by thisprojects** [comment]
I have this same problem on mac version 0.6.17 (as downloaded via nuclear app website). When I run the development environment locally, however, I am able to import playlists from spotify, package JSON shows that dev version is also 0.6.17 - I'll pick up on this issue and take a look.

**Comment by NicTanghe** [comment]
I`m having the same issue with my playlist
https://open.spotify.com/playlist/6aZDgWrzzIxrnsWMlaZfnb?si=29b062e5a8ff4f68

**Comment by nukeop** [comment]
Fixed in 9ee0cd58d648aec6d0167fd28715cd0d96d13526
