### ISSUE TITLE
Please add a way to import youtube playlist into nuclear

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [nukeop/nuclear#1389]

**Comment by nukeop** [comment]
Try pasting the playlist url into the search box

**Comment by Kreijstal** [comment]
didn't work?
![image](https://user-images.githubusercontent.com/2415206/232119993-8294adf3-66cb-4f8b-8f17-9248fff0176f.png)

**Comment by nukeop** [comment]
This is a link to a video. You need a playlist link (with /playlist).

**Comment by Kreijstal** [comment]
> This is a link to a video. You need a playlist link (with /playlist).

huh, everytime I find a playlist on youtube format is watch?v=something&list=playlistid I've never seen /playlist, what is the format?

**Comment by nukeop** [comment]
Example: https://www.youtube.com/playlist?list=PLNxOe-buLm6cz8UQ-hyG1nm3RTNBUBv3K

**Comment by Kreijstal** [comment]
am I dumb?
![image](https://user-images.githubusercontent.com/2415206/232169273-9998ecdf-910b-4d9a-b4a0-cd9678b11086.png)
is this doing it wrong?

**Comment by nukeop** [comment]
Just pasted the above link to check:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/12746779/232169730-1dc8fbb8-474a-48ce-8d11-24ef1c62093c.png">

**Comment by nukeop** [comment]
Oh right - you're using an ancient version. Get the newest one.

**Comment by ImGGAAVVIINN** [comment]
It does not work with discogs on the latest version, I am so confused
