### ISSUE TITLE
Nuclear Stops Working after Playing a few songs in playlist

### ISSUE THREAD

**Issue by rchaklashiya** [nukeop/nuclear#1394]
**Platform:**
Microsoft Windows 11 Home (Version 10.0.22621)
**Nuclear version:**
95cfe0 (the Windows nuclear.Setup.95cfe0.exe download from this page: https://github.com/nukeop/nuclear/releases/tag/95cfe0 )
**Description of the issue:**
Nuclear stops working and shows the following blank screen after playing a few songs:
![image](https://user-images.githubusercontent.com/18043279/216792268-38b9cf6c-c03f-4a4e-8c82-3586b23026ae.png)
This has consistently happened 3 times now. After putting my playlist in queue (26 songs), it plays a few songs (maybe 3-4 songs) then stops playing and the screen becomes like above. I have not successfully gotten it to play any more songs in a row than that. Does anyone know any workarounds to this issue or if a different version may solve the issue? Thanks!
**More Information**
The playlist was this one, I created it by pulling songs from various artists found on Nuclear's Youtube search.: 
![image](https://user-images.githubusercontent.com/18043279/220202960-aa5e3c12-d428-43b9-a01b-57135d7d3590.png)
![image](https://user-images.githubusercontent.com/18043279/220203123-0b646b50-be1d-4bb1-831a-bf6066370dfe.png)
![image](https://user-images.githubusercontent.com/18043279/220203142-730a2196-f069-4d90-a7a1-498881e98c32.png)
Json of playlist is attached here in this zip file: 
[Mix.zip](https://github.com/nukeop/nuclear/files/10787987/Mix.zip)

**Comment by nukeop** [comment]
[Mix.json.zip](https://github.com/nukeop/nuclear/files/10788453/Mix.json.zip)

Try this file instead.
