### ISSUE TITLE
Not all Miniplayer PlayOptions clickable

### ISSUE THREAD

**Issue by a0kami** [nukeop/nuclear#1396]
**Platform:**
Linux `Linux 6.0.19-3-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Jan 18 07:57:11 UTC 2023 x86_64 GNU/Linux`

**Nuclear version:**
0.6.17 (latest AUR `nuclear-player-bin` "95cfe0")

**Description of the issue:**
When enabling the miniplayer, the bottom lower part is not clickable as shown in the screenshot.
![Screenshot_20230207_235051](https://user-images.githubusercontent.com/8460863/217385995-62c9351b-9dd3-4b62-8c63-e06bff264274.png)

I've managed to make it work locally by setting an arbitrarily high `z-index` value (100) on the scss properties of the `mini_play_options` object in file `packages/ui/lib/components/MiniPlayer/MiniPlayOptions/styles.scss`. eg:
```css
.mini_play_options {
  ...

  z-index: 100;
  
  ...
}

```

Not sure if there's a proper convention or a project specific way to set the z-index.

Also, I might look into adding a test for it.

**Comment by nukeop** [comment]
Feel free to just put that value directly in the css. No need to write tests in this case.

**Comment by maboroshin** [comment]
Title bar cannot be dragged in Windows 10. I cannot move the mini-player window. I don't know about other operating systems.

**Comment by nukeop** [comment]
Fixed by #1592
