### ISSUE TITLE
Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [nukeop/nuclear#14]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional(!) desktop integration with `appimaged`
- Binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can GPG2-sign your AppImages (inside the file)

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

__electron-builder__ has support for AppImage built in, in fact it is the default for Linux.

**Comment by nukeop** [comment]
AppImage added to the newest release:
https://github.com/nukeop/nuclear/releases/download/ddoyle/nuclear-ddoyle-linux-x64.AppImage

All future releases will also include the AppImage build.

Leaving this issue open for a couple of days for reference.

**Comment by probonopd** [comment]
Thanks, added to https://github.com/probonopd/AppImageKit/wiki/AppImages

**Comment by hideout** [comment]
nice!

**Comment by Calinou** [comment]
It runs in Fedora 25 KDE (fresh install with updates), with a few caveats:

- application icon is not displayed in the window top bar,
- icons don't show properly in the, including the application logo.

See screenshot below.

![screenshot_20170212_150755](https://cloud.githubusercontent.com/assets/180032/22862783/8dbd31d8-f135-11e6-8b16-5e704d76287a.png)

Desktop integration seems to work, but the application doesn't display an icon in the start menu either. Maybe no icon was added?

**Comment by nukeop** [comment]
I will test this once I set up a VM with Fedora. I know there were issues with fonts and logo on Windows too, but they were fixed. I might have to take a look at fontawesome files.

Also, the blur is kinda ugly in the lower left corner on your screenshot, likely platform-dependent. I'll make a mental note to replace it with a static image.

**Comment by nukeop** [comment]
Try this release:
https://github.com/nukeop/nuclear/releases/tag/eddin

I shuffled some paths around and updated font-awesome, the program should be able to find the fonts now.

Testing on my VM, appimage adds an icon to the app menu (at least on XFCE).

**Comment by probonopd** [comment]
Thanks, fonts and icons are now showing up correctly.
