### ISSUE TITLE
New tagline

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#140]
Current one is a tongue in cheek comparison that apparently causes some confusion.
Suggestions welcome.

**Comment by timpulver** [comment]
- «Nuclear – search and stream Youtube, Soundcloud & Co. in one app»
- «Nuclear – your player for Youtube, Soundcloud & Co. in one app»
- «Nuclear – Youtube, Soundcloud & Co. in one app»
- «Nuclear – stream music from free sources like Youtube or Soundcloud»

**Comment by adamlaz** [comment]
Just gonna dump this here as I'm thinking about it.. But, I bet we can come up with a short 'n sweet tagline/description! 

> An open-source and cross-platform application to listen to music. Search, stream, save, and organize music from your own collection and tons of online sources.

**Comment by mkg20001** [comment]
- All of the music, none of the costs
 - Imagine one app for all free music. That's nuclear.

**Comment by akaleeroy** [comment]
> - Unified music player
> - Universal music player

I also have a name suggestion but it's kinda late for that:
> ### [**Songlines**](https://en.wikipedia.org/wiki/Songline) :musical_note::dove:

**Comment by nukeop** [comment]
This is a good suggestion for the future, when we can truthfully claim it's a universal music player.
