### ISSUE TITLE
An error has occurred when searching for streams with Youtube for

### ISSUE THREAD

**Issue by cosheimil** [nukeop/nuclear#1401]
**Platform:**
EndeavourOS Linux x86_64
**Nuclear version:**
202313_73fec2bea34d74fc7908a752d7b8f884-2
**Description of the issue:**
```
Error: Cannot find module '/opt/nuclear/resources/app.asar/package.json'
    at t (file:///opt/nuclear/resources/app.asar/dist/main.e2172b51a67a4da5a541.js:1:1246357)
    at c (file:///opt/nuclear/resources/app.asar/dist/467.ef6c69d4fe4adfb2ea9b.js:4:11099428)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/467.ef6c69d4fe4adfb2ea9b.js:4:11099923)
    at file:///opt/nuclear/resources/app.asar/dist/467.ef6c69d4fe4adfb2ea9b.js:4:11095893
    at Array.map (<anonymous>)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/467.ef6c69d4fe4adfb2ea9b.js:4:11095885)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async p (file:///opt/nuclear/resources/app.asar/dist/467.ef6c69d4fe4adfb2ea9b.js:4:6588624)
    at async file:///opt/nuclear/resources/app.asar/dist/main.e2172b51a67a4da5a541.js:1:402536
```

**Comment by nukeop** [comment]
How did you install it? AUR?

**Comment by cosheimil** [comment]
AUR

**Comment by nukeop** [comment]
I just tested this on Endeavor, and installed `nuclear-player-bin` from scratch, and couldn't reproduce it.

**Comment by cosheimil** [comment]
And what i need to do?) 
Because this error can be and can not be. For example im opening nuclear, listening 3-4 songs and after that i have this problem.

**Comment by LegendTheo** [comment]
I believe I'm having the same issue on windows 10. I don't know where the logs are store and the error on the song box is too small to verify. Latest release version 95cfe0

**Comment by elmaester** [comment]
Also happens to me. And it depends on which track I try to play. Some work, some don't. AUR

**Comment by elmaester** [comment]
Could some YouTube API have changed very recently? Or something like that

**Comment by elmaester** [comment]
Just tried installing from snap and it's no different :(

**Comment by nukeop** [comment]
We don't use the Youtube API, it's based on scraping, so it's prone to breaking :( You're right that something's broken though, I was able to reproduce it just now.

**Comment by elmaester** [comment]
Godspeed solving :) And thanks!

**Comment by nukeop** [comment]
Try the newest release - it should work

**Comment by elmaester** [comment]
Wonderful! Thank you :)
