### ISSUE TITLE
Searching is getting stuck quite often

### ISSUE THREAD

**Issue by kha84** [nukeop/nuclear#1404]
**Platform:**

Linux Ubuntu 22.10 x86_64

**Nuclear version:**

Tried both the one from snap:
```
nuclear                               0.6.17                      52     latest/stable    nukeop      -
```
and two AppImage versions:

nuclear-58dfc7.AppImage
nuclear-95cfe0.AppImage

**Description of the issue:**

##

I found that Nuclear quite often fails to perform search successfully. Like if you type a name of artist or song, it shows the spinning wheel indicator, without anything being returned. And if you just retry the very same search once again, like by hitting enter in a search input field, there's 99% chance this next attempt will be successful. 

I'm able to reproduce this all the time, following the below scenario:

1. run Nuclear and let it load completely
3. type "mozart" in search input field on a top, as fast as you can, without making any pauses while typing. Do not press any other keys in there, neither enter nor spacebar. Literally, what you should have typed is [m][o][z][a][r][t]. Or just paste that "mozart" string from the clipboard
4. the animated spinning wheel indicator is being shown, without any search results being displayed at all. 
5. switching the ~ search engine here, while this spinning wheel indicator is being shown, doesn't give any effect
6. BUT, if you hit enter, space bar or just append anything to your existing search string (I assume, this initiates another call to the selected search engine), results are being displayed and the below lines are printed to console:

```
  renderer › Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1544:19)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
  renderer › Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
```

It might be some kind of bug in the Nuclear code, or it might be not the Nuclear fault, but all those 3rd party services, Nuclear is using as indexers for searching, are timing out. If latter is the case, I guess Nuclear should implement some retry option after a timeout (e.g. if nothing is returned within say 5-10 seconds), so user won't have to do that himself. 

As a side note, I also think it makes sense to trigger another search call if user changes the search engine, to minimize the number of actions needed.

**Comment by nukeop** [comment]
That sounds like an issue with your connection. Try opening the dev tools (ctrl+shift+I) and see if the request to your chosen search provider is getting through.

**Comment by kha84** [comment]
Hey @nukeop, thanks for coming. 

It's some kind of bad joke happening to me right now. As soon as I open that developer console (or soon right after) the whole damn operating system becomes completely unresponsive / freezes. It is no coincidence - I tried that several times, both in X11 and in Wayland Gnome sessions with the same outcome. I tried to tail journal messages together with kernel messages and have my  btop opened to see what might be happening - but none of that gives any clues why the whole system freezes just because of (presumably) single app - up until the moment system freezes everything looks normal. It might be some issue with the most recent kernel update I got couple of days back. I'll try to sort it out myself. 

But jokes aside, speaking of this ticket I'll re-check if this Nuclear behavior is the same on my other machine which is running Fedora 37 but in the same home wifi network.

**Comment by nukeop** [comment]
Ok, guess I'll chalk it up to local setup issues then. Let me know if anything changes.

**Comment by kha84** [comment]
I tested it on a different laptop as I was planning - and I can confirm this behavior exactly as in the scenario I provided above.

**Comment by nukeop** [comment]
What search provider are you using?

**Comment by kha84** [comment]
With Discogs the bug is reproduced all the time, right after startup. With iTunes music it is reproduced every once in a while. 

I think, if we talk in general, there's definitely need some kind of hangup and redial mechanism, if the request wasn't repsonded after a timeout

**Comment by nukeop** [comment]
I don't see how that's going to help. If a request fails for an unknown reason, we have no reason to believe it will succeed if tried a second time. It's better to remove the underlying cause, instead of just spamming in hopes one request out of several will go through.

**Comment by kha84** [comment]
For that we can have some small number of retries to avoid constant spamming. I finally installed the proper key capture tool so I can show you how it looks like from user persective - will record a video and put it here

**Comment by kha84** [comment]
[Screencast from 2023-03-01 01-47-40.webm](https://user-images.githubusercontent.com/110789576/221999987-bf6f71b0-725a-47c0-8ac0-cedf27177224.webm)

**Comment by kha84** [comment]
Mind those moments, when nothing is returned by search and I press "Enter" to repeat it - and results are returned immediately on my 2nd attempt.

**Comment by nukeop** [comment]
Can you try this with developer tools?

**Comment by kha84** [comment]
For some reason it doesn't get open on Ctrl+Alt+I. I tried to enable developer mode in settings - but it doesn't help. Could be something with flatpak. Will give it a try with AppImages you distribute today

**Comment by kha84** [comment]
So I gave a try to run different appImages on my Fedora 37 laptop: 
* nuclear-58dfc7.AppImage 
* nuclear-95cfe0.AppImage

The Ctrl+Shift+I shortcut doesn't seem to work for me in both of them, but the same shortcut works just fine Firefox - it shows the developer panel.

**Comment by kha84** [comment]
[Screencast from 2023-03-03 00-21-26.webm](https://user-images.githubusercontent.com/110789576/222561040-c77341f3-81c7-43f0-81f0-14a85c6cfb41.webm)
