### ISSUE TITLE
"Play now" for a track is getting stuck quite often with YouTube Plugin

### ISSUE THREAD

**Issue by kha84** [nukeop/nuclear#1405]
**Platform:**

Linux Ubuntu 22.10 x86_64

**Nuclear version:**

Tried both the one from snap:
```
nuclear                               0.6.17                      52     latest/stable    nukeop      -
```

and two AppImage versions:

```
nuclear-58dfc7.AppImage
nuclear-95cfe0.AppImage
```

.. all are having the same issue

**Description of the issue:**

Similar to the previous ticket I raise #1404, probably the same nature, but happens to tracks. Here is how to reproduce:

1. open Nuclear and let it load completely
2. enter "Nessun dorma" in the search field, wait for a while if nothing gets returned , then hit enter 
3. scroll down to "Tracks" and left click on "Luciano Pavarotti Nessum Dorma", in the menu select "Play now"
4. see the track appeared on the right hand side ~play queue panel with a spinning wheel indicator **but it is not being played**. In this state it could be any long time without any effect.
5. repeat point 3 few times, until the track is started to play. During these retries you might see the below messages being printed to stdout (if you ran Nuclear from terminal):
```
  renderer › An error has occurred when searching for streams with Youtube for "Luciano Pavarotti - Nessun Dorma."
  renderer › Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1544:19)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
      main › Main process failed to react to IPC clear queue event
  renderer › An error has occurred when searching for streams with Youtube for "Luciano Pavarotti - Nessun Dorma."
  renderer › Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1544:19)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I totally realize it could be something on the youtube side, like they have introduced some throttling and randomly rejecting requests. Guessing the same as with #1404 some kind of retry & fallback mechanism should be introduced here. 

I tried to use all other streaming plugins, but for me they just don't work - looks like it's some kind of tag game all these media streaming services are playing, while trying to resist such a nice application from operating properly :)

**Comment by nukeop** [comment]
This seems to be the same as #1404
