### ISSUE TITLE
UX bug: Doubleclicking on the track in the play queue doesn't start playing it, if pause was pressed before

### ISSUE THREAD

**Issue by kha84** [nukeop/nuclear#1407]
**Platform:**

Linux Ubuntu 22.10 on x86_64

**Nuclear version:**

nuclear-58dfc7.AppImage
nuclear-95cfe0.AppImage
nuclear 0.6.17 (from snaps)

**Description of the issue:**

(This ticket assumes all the tracks you have in a play queue were already downloaded, to not be confused with #1406) 

1. Have some number of tracks in your play queue
2. Play some track
3. Press a pause button, while Nuclear is playing
4. Double click on **some other** track name in a right hand side "play queue" panel. The track is not started to play until you hit the play button again. I think this is UX bug. When user doubleclicks the track name, that is quite a clear intention for that track to play. At least, this is what all other players are doing and what user expects from all other players.

**Comment by nukeop** [comment]
Double clicking only moves the current track pointer to the track you click. This is working as intended.
