### ISSUE TITLE
Suggestion: make the "Toggle discord rich presence" setting to be turned off by default (at least for snap package)

### ISSUE THREAD

**Issue by kha84** [nukeop/nuclear#1408]
If Nuclear is installed on Ubuntu as snap, it looks like it comes with "Toggle discord rich presence" setting turned on. Which means upon the startup it attempts to change something and Ubuntu' Gnome handles that to raise the below modal confirmation dialog which scares people: 

```
Allow settings change?

Allow snap "nuclear" to change "default-url-scheme-handler" subproperty "discord-1038970224050962582" to "nuclear_nuclear.desktop" ?

This dialog will close automatically after 5 minutes of inactivity.
```

A simple solution for the ones, who don't need that Discord integration, would be to turn "Toggle discord rich presence" setting off and restart Nuclear, so they will never see that dialog again. 

But the proper solution I think would be to ship Nuclear with this setting turned off, at least for the snap distribution: so it could be turned on only by users who need that and it won't be frightening people who don't have any idea about what is happening.

(Running Nuclear from AppImage does't freak Ubuntu' Gnome out, regardless if that setting is on or off)

**Comment by nukeop** [comment]
If you don't use Discord that setting won't do anything, it's just one click at the start (and 0 if you don't use Snap store)
