### ISSUE TITLE
Small UI/UX bug: unrelated "Add selected to downloads" action is being shown for "Local Library" tracks

### ISSUE THREAD

**Issue by kha84** [nukeop/nuclear#1409]
**Platform:**

Linux Ubuntu 22.10 x86_64

**Nuclear version:**

nuclear-58dfc7.AppImage

**Description of the issue:**

1. Make sure to have some tracks in your local library first
2. Open "Collection" -> "Local Library" page. Open inline (..) menu for any of your local tracks. You'll see "Download" item in there, which doesn't make sense, as the track is already there in your local library

![image](https://user-images.githubusercontent.com/110789576/221414201-81b6fc96-02f8-4ac9-a1a9-af5128fbfa22.png)

4. Now select few tracks and click on the similar (...) button in the table header - you'll see the similar item in there:

![image](https://user-images.githubusercontent.com/110789576/221414277-7c5aae0f-dd7e-458d-921f-5510d2e75843.png)

I can imagine, there're tricky use cases related to other pages, like "Favorite Tracks", where user can have a mixture of tracks from internet and his local ones. But at least here, on a "Local library" page, it doesn't make sense to show it.

**Comment by nukeop** [comment]
This should be solved with a flag on the popup component
