### ISSUE TITLE
LINUX - Nuclear configuration file path

### ISSUE THREAD

**Issue by abacao** [nukeop/nuclear#141]
Please consider looking the configuration file not only in ~ but also in ~/.config/nuclear/... (or even change it to this path)

specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

unix.stackexchange.com/questions/312988/understanding-home-configuration-file-locations-config-and-local-sha

**Comment by nukeop** [comment]
In the development version persistence is handled by this package: https://www.npmjs.com/package/electron-store
Which uses `app.getPath('userData')`, which in turn points to ~/.config according to this: https://electronjs.org/docs/api/app#appgetpathname

**Comment by abacao** [comment]
I have found this and it was the reason why I have opened this issue.

```
cat ~/nuclear.json 
{
  "lastFm": {},
  "settings": {}
}
```

**Comment by nukeop** [comment]
Ok, I'll try to find what uses that file.

**Comment by nukeop** [comment]
Should no longer be a problem.
