### ISSUE TITLE
Downloading Songs makes copies of the song

### ISSUE THREAD

**Issue by ghost** [nukeop/nuclear#1411]
**Platform:**
Windows 10
**Nuclear version:**
0.06.17
**Description of the issue:**
Downloading music makes a copy of the song, for example:
Artist Name - Song Name (1).webm
Artist Name - Song Name (2).webm
Artist Name - Song Name (3).webm

Sometimes they stay, sometimes they disapear when the song has finished download, other cases are always stay

**Comment by nukeop** [comment]
If you download the same song multiple times this can happen. What would you like to happen instead?

**Comment by BananaCurry** [comment]
> If you download the same song multiple times this can happen. What would you like to happen instead?

Oh, sorry, didn't really understand it at first, when I download an abulm it works fine for the first couple songs, then the download will start to buffer, the percentage will won't move and it will make copies of the song over and over till the app crashes

**Comment by nukeop** [comment]
Can you post an example and steps I can follow to reproduce this?
