### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by kha84** [nukeop/nuclear#1413]
**Platform:**

Fedora 37 x86_64
Intel Atom x5 Z8350

**Nuclear version:**

nuclear-95cfe0.AppImage
nuclear-58dfc7.AppImage
RPMs from the above release tags
The most recent Flatpak version
(basically whatever I tried is having the same issue)

**Description of the issue:**

The sound is very "distorted" during playback. It looks like there're some sort of micro pauses are happening all the time. It's hard to describe that  properly, but imagine that your sound is being interrupted like 10 times per second with some 50 ms pauses. I'm not sure if there's something wrong with the Nuclear or it might be a wider issue with all Electron apps in my case. 

As a word of self-defence, the sound (and video) playback works perfectly fine on youtube using Firefox web browser. Also whatever audio files I downloaded with using Nuclear can be played without any issues with using VLC or default Gnome "Videos" app ("totem", I believe).

I'm happy to troubleshoot and dig it deeper myself, so this my experience will be of some use to whoever is  having  same issues with sound, if only you can give me some guidance what to look at?

**Comment by nukeop** [comment]
We use the standard audio stack provided by chromium, and Web Audio API: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

Since I haven't gotten any other reports like that, I'm gonna assume it's your setup

**Comment by kha84** [comment]
Thanks for letting me know. I'll install Chromium to see how it behaves while playing youtube and same files I tried to play with Nuclear
