### ISSUE TITLE
UI/UX bug: Add track to favorites in Favorite Tracks

### ISSUE THREAD

**Issue by Alzamer** [nukeop/nuclear#1421]
**Platform:**
Linux Ubuntu 22.10 x86_64
**Nuclear version:**
nuclear-fd06a3.AppImage
**Description of the issue:**
In Favorite Tracks bookmark you can add a track back to the Favorite Tracks list. The track disappears and is added to the end of the list. It is not possible to delete a track from favorites.
![Screenshot from 2023-03-12 21-19-08](https://user-images.githubusercontent.com/91850532/224571546-8292978d-3dab-4046-9d7b-def1afe4a7b3.png)

**Comment by Alzamer** [comment]
I'd like to work on it, so I would be happy if someone would assign me to it

**Comment by nukeop** [comment]
Ok, this should be covered by a test and should be a relatively easy fix
