### ISSUE TITLE
Cannot drag mini-player

### ISSUE THREAD

**Issue by maboroshin** [nukeop/nuclear#1423]
**Platform:**

nuclear-fd06a3, Windows 10

**Description of the issue:**

Title bar cannot be dragged in Windows 10. I cannot move the mini-player window. I don't know about other operating systems.

At 800 pixels wide, you can drag the upper right corner of the window. (orange in the image below) At 300 pixels wide, there is no draggable area.

![image](https://user-images.githubusercontent.com/41102508/224600961-0effc586-a7f6-4cc9-8de6-0728f55f12c9.png)

**Comment by nukeop** [comment]
Likely a CSS issue, thanks for reporting.

**Comment by nukeop** [comment]
It can, except for the buttons (otherwise you won't be able to click them). You can take a look at how it's handled in the regular view.

**Comment by iamnexxed** [comment]
Yeah, in that case, the buttons could be made not draggable. Would that be a correct way? Sorry, I didn't get what you meant by regular view.

**Comment by nukeop** [comment]
Yeah, there should be a handle at the top: https://www.electronjs.org/docs/latest/tutorial/window-customization#set-custom-draggable-region

**Comment by Mintmu01** [comment]
1423
