### ISSUE TITLE
Tray icon menu is still in English

### ISSUE THREAD

**Issue by maboroshin** [nukeop/nuclear#1424]
**Platform:**

nuclear-fd06a3, Windows 10

**Description of the issue:**

Tray icon menu is still in English.

* New translation string : "Playing" + "by"
* Already registered for translation in other parts. : Pause/Next/Previous/Quit

**Comment by nukeop** [comment]
Definitely a bug, might be tricky because it's in the `main` package.

**Comment by moritzrose** [comment]
Is still bug still an issue? 
I am completely new to OpenSource and would like to try my best to at least understand and maybe even fix something:)

**Comment by nukeop** [comment]
Yes it is, you can check the `i18n` package to get an idea of how internationalization works in Nuclear.

**Comment by moritzrose** [comment]
Can I get a picture maybe? Just downloaded nuclear to get a good impression, but what is meant by tray icon?

**Comment by moritzrose** [comment]
Ok pls correct me if I am wrong, but from what I have understood so far is, that the buttons have an english tooltip, correct? In my case, there is actually no tooltip shown at all. I will see what causes that.

So are those suggestions or advice?: - New translation string : "Playing" + "by"
                                                                - Already registered for translation in other parts. : Pause/Next/Previous/Quit

**Comment by maboroshin** [comment]
@moritzrose What you are talking about is a tooltip.

* Tooltip : What you see when you hover the mouse cursor over it
* Menu : It appears when clicked with the mouse cursor on it.

Tooltips and menus are displayed in Windows. I don't know why it's not show, What OS are you using?

----

Tooltip (Playing):

![image](https://github.com/nukeop/nuclear/assets/41102508/5bf562c0-2b0d-4983-babc-1becef131163)

Tooltip (Pause):
![image](https://github.com/nukeop/nuclear/assets/41102508/7e66b383-3596-498d-86f3-ae93c6f311ec)

----

Menu (Playing):
![image](https://github.com/nukeop/nuclear/assets/41102508/f9b4aceb-6181-4505-935b-a4675269a303)

Menu (Pause):
![image](https://github.com/nukeop/nuclear/assets/41102508/c2a444dc-2b9b-495c-8ce1-beeb49ef1b4e)

Menu (Immediately after start : Nothing has yet played):
![image](https://github.com/nukeop/nuclear/assets/41102508/e2d12311-5032-4508-ae01-d5e43e9e011e)

**Comment by moritzrose** [comment]
Ah thanks! That helped a ton! Does it make sense for me to work on that problem when I am on macOS? Maybe it's not the best problem to start with, since the problem occurred on windows? But shouldn't it occur on whatever OS then?

**Comment by nukeop** [comment]
This has been fixed in the new release!
