### ISSUE TITLE
Skip back button greys out when nothing precedes song in queue despite being the easiest way to rewind a track

### ISSUE THREAD

**Issue by phynxinferno** [nukeop/nuclear#1426]
The skip back button is the best way to restart a song, but it's disabled when the song is the first in queue.

**Comment by nukeop** [comment]
Ok, in this case it should be active and simply rewind the track.

**Comment by HiroakiYo** [comment]
Hi, I am new to the open-source development community and I would like to try out this task. Is there anything I should be aware of besides the https://nukeop.gitbook.io/nuclear/contributing/contribution-guidelines?

**Comment by nukeop** [comment]
This should be all, I'll assign this issue to you.

**Comment by HiroakiYo** [comment]
Hi, I think I have added the functionality and made a pull request. It can pass all the npm tests. Is the code ready to be merged or should I add something else?

**Comment by sameer-haider** [comment]
Has this issue been resolved as per the pull request mentioned above?

**Comment by nukeop** [comment]
Yep, the issue wasn't mentioned in the PR, but it's been merged.
