### ISSUE TITLE
Display of empty artists in Discogs

### ISSUE THREAD

**Issue by maboroshin** [nukeop/nuclear#1427]
**Platform:**

nuclear-fd06a3, Windows 10

**Description of the issue:**

Display of empty artists in Discogs.

1. Select Discogs and enter the following search terms : "Delta 9kid" or "Gplants" or "舐達麻"
2. Select an artist and a blank screen will appear.

I have searched for artists that contain Kanji characters. But, This cannot be reproduced with other search terms.

**Expected correct behavior**:
Displaying Information : Unable to retrieve artist information.

**Comment by nukeop** [comment]
Artist pages for reference:
https://www.discogs.com/artist/7673282-Delta9kid
https://www.discogs.com/artist/7673280-Gplants
https://www.discogs.com/artist/7347076-%E8%88%90%E9%81%94%E9%BA%BB

While the first two only have a single record each, the third one has more, but there must be something on the artist page that's missing data we expect to be there normally.

**Comment by sferra** [comment]
I could fix this and create a PR if anyone is interested.

**Comment by nukeop** [comment]
Okay, what's the plan?

**Comment by sferra** [comment]
I checked, and the issue is caused because of missing artist information from Lastfm. The code accesses the data nevertheless. I'll commit a quick fix so we have something concrete to look at, then improve and add test later.

**Comment by sferra** [comment]
This issue is fixed.
