### ISSUE TITLE
Empty artists added to favorite

### ISSUE THREAD

**Issue by maboroshin** [nukeop/nuclear#1428]
**Platform:**

nuclear-fd06a3, Windows 10

**Description of the issue:**

1. Press the favorite button of an empty artist. Related: https://github.com/nukeop/nuclear/issues/1427
2. An empty artist will appear in the Favorite Artists tab.
3. Selecting Remove will not remove this artist.
4. An empty array is registered in```config.json``` : 
```
		"artists": [
			{}
		],
```

**Expected correct behavior**:
* Prevent empty artists from registering.
* Automatically delete empty artists.

**Comment by aditdesai** [comment]
@nukeop I would like to work on this

**Comment by sferra** [comment]
This issue should be fixed, since #1427 is fixed.
