### ISSUE TITLE
Add TypeScript gradually

### ISSUE THREAD

**Issue by vilanz** [nukeop/nuclear#143]
Facebook has been ditching Flow and favoring TS lately, so support for React and RN is much better than a year ago.

I know this is just the beginning of the project, but that's exactly the point; IMO typing is not only about bug prevention, but a sort of documentation when walking through the code. It's another compilation step for sure, but the conversion to TS could be gradual (only a few .ts files at the beginning).

What do you think?

**Comment by nukeop** [comment]
I'm gonna have to say no on this one, first of all I'm not that experienced with TS, and the second reason is that I'd rather not trap myself by using something developed by MS.
