### ISSUE TITLE
"Can not find youtube track with…" issue

### ISSUE THREAD

**Issue by Saltane** [nukeop/nuclear#1438]
I have a problem with: YouTube stream provider.
It happens when: song added to queue.
My OS is: Linux.
I'm using Nuclear version: AppImage, ver. fd06a3

Nuclear can not find any song in queue, throwing "Can not find youtube track with…" error.
![image](https://user-images.githubusercontent.com/101461606/230177871-e324b707-0dc2-4775-a938-0d62f34f3264.png)

Tried adding different songs, searching stuff while it's loading, adding from startpage reccomended playlists -- none worked. Issue is persistent and replicated in 100% of attempts.

**Comment by nukeop** [comment]
Upstream bug: https://github.com/fent/node-ytdl-core/issues/1197

**Comment by nukeop** [comment]
Works in the new release.
