### ISSUE TITLE
Unexpected token { - npm run watch fails

### ISSUE THREAD

**Issue by nryberg** [nukeop/nuclear#144]
I'm getting the following when launching run watch: (log attached)

> nuclear@0.4.4 watch /Users/Nick/Develop/nuclear/nuclear
> webpack-dev-server --inline --progress --env=dev

/Users/Nick/Develop/nuclear/nuclear/node_modules/webpack-dev-server/bin/webpack-dev-server.js:30
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

npm ERR! Darwin 18.2.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! nuclear@0.4.4 watch: `webpack-dev-server --inline --progress --env=dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuclear@0.4.4 watch script 'webpack-dev-server --inline --progress --env=dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nuclear package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
[npm-debug.log](https://github.com/nukeop/nuclear/files/2773367/npm-debug.log)

**Comment by nukeop** [comment]
Try installing node 8 or 10, this log says you're at version 5. Also, upgrade npm.

**Comment by nryberg** [comment]
brew upgrade npm and npm rebuild did the trick.
