### ISSUE TITLE
README has an entire section on personal insults.

### ISSUE THREAD

**Issue by will-ca** [nukeop/nuclear#1441]
I'm sorry. Electron is fine. But as an outsider:

- "people who lack real-world programming experience".
- "vaguely mumbled".
- Mock-stuttering: "b-but it's an entire browser".
- "because they think whining makes them seem smart".
- Linking to "mps-youtube" which is clearly *not* "a similar program", being a console application, and which I can thus only conclude was only chosen to appear antiquated (or "seem smart") in comparison.

…Does not [read](https://github.com/nukeop/nuclear/blob/bfada5d87e6d7ec6f3da7f64a8b3cd493507e2be/docs/electron.md) to me as defending Electron, so much as preemptively lashing out insulting potential users and potential developers who otherwise may be interested in collaborating.

<br>

I may also dispute the factuality of some of some of the insinuations, upon "critically examining whether it makes sense or not". On my computer, Nuclear is currently using something like 5 separate processes (not counting Flatpak sandbox) totalling over 800MB of memory at idle, to still struggle to display a local music library. By comparison, VVave, displaying the same music library without any performance issues, comprises just 1 process with 50MB-250MB of memory. And while I don't know much about QT Designer (I also decided to stay far away from it after trying it), I've personally found QML+Javascript to be quite pleasant to use.

*But that's not the point*, because you may well be right in that Electron is "certainly good enough", and brings multiple worthwhile benefits with "no good alternative that would provide all these benefits". 800MB of memory across many processes is an extreme example, and even that is still acceptable on modern systems that have over a dozen gigabytes of RAM and pagefiles backed by SSDs. Drawbacks are not actually necessarily problems in practical usage; Clearly the choice of Electron as a platform has also enabled certain advantages in feature set seeing as I still have Nuclear installed and find it worth digging into. And you are certainly right in that there are "tradeoffs you take when building software", no matter how you do it.

<br>

**Electron is** ***fine***. QT is *fine*. Motif or NCURSES, if it gets the job done, is *fine*. Nuclear is a solid application, that has a specific focus, and does it well.

Using the first section after the introduction in your README as a popular open-source project in order to mock other people, people you haven't met, with the sole intention of degrading and hurting them— Because, let's be real, that's the only reason for an entire paragraph phrased such as the intro to `electron.md`— Is, in my opinion, kind of *not* fine.

<br>

I know that this world is full of cruel humans "who read angry rants" and latch onto anything as an excuse to hate, for the pettiest of reasons. And sharing something for free that you've spent time from your own life making, and being treated with that vitriol as your reward, is a *terrifying* prospect. I'm sorry for that, and I am thankful that this application exists and is made freely available.

I suggest that this project not be part of the problem. Mud is bad for code.

**Comment by nukeop** [comment]
But I like mocking people who have retarded opinions.

**Comment by will-ca** [comment]
Oh. I see. You're just a petulant hypocrite.

**Comment by nukeop** [comment]
What's hypocritical about that?

**Comment by will-ca** [comment]
There are certain people who would see "I like bullying" as a flaw, not a virtue.

And it's hypocritical because your opinions are frankly just as "retarded", and worthy of mockery. But apparently, and unsurprisingly, that went over your head.

**Comment by nukeop** [comment]
Go ahead then I'd like to see that

**Comment by will-ca** [comment]
> Go ahead then I'd like to see that

I'm not here to trade insults with you.

It is disgusting and concerning that you respond to having your abusive behaviour pointed out by taunting and inviting such.

The entire *point* is to *not do that*.

<br>

That said, I did point out in my original comment that some of the most basic technical assertions you made in `electron.md` are both factually untrue and very easily disproved.

Again, it is disappointing, but unsurprising, that that apparently went over your head.

<br>

At the end of the day:

- You enjoy bullying people. You openly admit this. You lucked into being in charge of an open-source project with a significant following, and you have placed your soapbox there to punch down at imagined inferiors.
- I made the mistake of thinking that you did so in misjudgement, or defensively, rather than out of malice or pettiness. It is clear now that that is not the case.
- You continue to miss the point. Mocking people is *bad*. Bullying is *unproductive*. Opinions, by definition, are *subjective*, and in most civilized circles, "retarded" is considered to be an ableist slur. Only a malignant narcissist truly believes that their "opinion" is the only objectively valid one, and everyone else is undeserving of basic respect. Being *proud* of that is disgusting.
- I don't care what you think you would "like to see". *I* would not enjoy doing it.

I would much rather focus on finding solutions to technical issues that benefit both of us, such as my comment in https://github.com/nukeop/nuclear/issues/1435#issuecomment-1500664499, rather than try to address this bad taste left in my mouth by a software package I thought I liked.

I have no interesting stooping to your level, and it is clear that you have no desire to do any better.

There is nothing left for me to say or do here.

**Comment by nukeop** [comment]
How new are you to the internet?

**Comment by nukeop** [comment]
BTW this is what QT shows as an example of its music player components:
https://doc.qt.io/qt-5/qtwinextras-musicplayer-example.html

It looks like a pile of crap.

**Comment by will-ca** [comment]
> BTW this is what QT shows as an example of its music player components: https://doc.qt.io/qt-5/qtwinextras-musicplayer-example.html
> 
> It looks like a pile of crap.

IDGAF about QT or Electron or whatever you want to pretend this is about. I'm just saying you're being an asshole; You're the one turning it into a "retarded" flame war about software components that nobody cares about.

But since you made it so easy, frankly, you are an idiot:
https://doc.qt.io/qt-5/qml-qtmultimedia-audio.html#details
