### ISSUE TITLE
Play now song problem

### ISSUE THREAD

**Issue by DanSeraf** [nukeop/nuclear#145]
If you click play now when a song is playing the application show the logo and no actions can be performed.

**Comment by jcheype** [comment]
mps-youtube fix, it also fix nuclear

pip install --upgrade https://github.com/Khang-NT/youtube-dl/archive/master.zip

see https://github.com/rg3/youtube-dl/issues/18873 for more infos

**Comment by nukeop** [comment]
I don'tthink so,wedon't use python in this project, we use ytdl-core, which is already fully updated.

**Comment by sumitbhanushali** [comment]
facing same issue on mac too

**Comment by trekiteasy** [comment]
This issue is now fixed
