### ISSUE TITLE
Bandwith Hog - Bandwith demand

### ISSUE THREAD

**Issue by oddsito** [nukeop/nuclear#1456]
Well... the modern society, the world has evolved into a very complex world with many unattended or ignored characteristics for human beings in it.
To listen to 1 song, well i have to spend like 15-20mb, which is quite expensive with mobile data.

I've downloaded this app twice in the past 8-14 months and  i always find the same problem.
I can't give it a 3rd try, because that means another 100mb...

I suggest an option to reduce bitrate, audio quality, Bandwidth friendly option

We live in a world with special characteristics and structures such as the people in it, a world where people live with personal situations/circumstances, such as poverty for example.

**Comment by nukeop** [comment]
Can you give an example of a song that you tried to listen to?

**Comment by oddsito** [comment]
Excessive Bandwidth Hog /Bandwidth demand *
Well... the modern society, the world has evolved in a very disproportional, inflexible way, and into a very complex world with many unattended or ignored characteristics for human beings in it*

Well people in some countries like mine can only download at 100kbps , have 1-2mbps capped, there is no optic fiber. Only wifi from antennas, high ping , latency. So its very disproportional in that sense to ask the user to download sometimes 10-20mb in the process of trying to listen to 1 song. or 50GB' games, etc, Nowdays the human ways of living life became disproportional between the societies/groups of people.

You ask what song? It happens with any song. Villa-lobos, Altai Kai, anything. In the process of loading the album, hitting play, i get a constant consumption of 120-220kbps sometimes constant 400-800kbps, even other users in my house complain. immedietly 5-10mb's are consumed in 1 song, Im there thinking " wow im not visualizing a single video yet, im downloading this much per sec , the audio quality must be very high 320 bitrate + , 13k channel audio who knows "  I think the question is what speed do i have? And what bandwidth-speed do you have? I use other services/softwares like youtube music,  spotify, while using spotify i have 2kb - 40kbps of constant consumption , each song is 4-6 mb , Spotify and youtube music both offer options to use " Low quality Audio " ... Just implement that into your app. Pros of your APP ,it has an ad-blocker , ads are annoying when using official spotify app/website. BUT CONS, the songs can sometimes hog the bandwidth constantly. 

Its not that the songs are downloaded all at once, it actually downloads too much as it tries to stream them.

**Comment by oddsito** [comment]
Just ignore me if you wish, people usually stay silent, it makes sense, Poor people cannot comment, or say anything, life advances in other countries, you people will never notice the poverty, the struggles here, so its indifferent for free or paid services, it is indifferent what kind of consumer they get, The consumer can only be a consumer, if he has enough to consume. So its indifferent for everyone, so us poor people usually stay silent , or we're never heard, but this time i took my time to expose a reality, where in other countries Bandwidth speed evolved, while in mine Venezuela or African countries, bandwidth speed has remained the same and in fact worsen itself the past 20 years. In the past 20 years, my country will not offer a service higher than 2mbps (Excuses such as our infrastructure cannot provide such speeds, unless you pay incredible amounts of money) which is impossible for any Venezuelian.

**Comment by nukeop** [comment]
Speedtest says Venezuela enjoys a median mobile download speed of 6.59Mbps, and 22.04 for broadband:

https://www.speedtest.net/global-index/venezuela
