### ISSUE TITLE
import youtube playlist from url

### ISSUE THREAD

**Issue by RiedleroD** [nukeop/nuclear#1463]
you can already import spotify playlists, I'd like to be able to import youtube playlists.

**Comment by nukeop** [comment]
You'll be happy to learn that this is already possible: https://nukeop.gitbook.io/nuclear/user-manual/importing-playlists#to-import-from-youtube

**Comment by RiedleroD** [comment]
yes, I found that after some tinkering. two notes:

- why doesn't the spotify import work like that too?
- why not add the extra button anyway?

The current UX suggests you can't import YouTube playlists and having to paste the url into the search bar is kinda counterintuitive. Putting two (to the user) identical features into different places is a bad idea.

Also, I've since uninstalled your program and didn't test it further, but when I went to search for my 1000+ tracks playlist, only a fraction of the songs showed up in the result. idk if they were hidden or something, but that's maybe something to look out for.
