### ISSUE TITLE
Top Artists images fail to load

### ISSUE THREAD

**Issue by benjaminwgordon** [nukeop/nuclear#1466]
**Platform:**
MacOS Big Sur 11.7.6
**Nuclear version:**
v0.6.21
**Description of the issue:**
When viewing the Genres tab (navigated from (Dashboard -> Genres), the Top Artists panel always fails to load artist images.  

<img width="929" alt="Screen Shot 2023-05-16 at 9 07 24 PM" src="https://github.com/nukeop/nuclear/assets/17805669/d8a4a08a-d60a-40df-82ca-db5384bec888">

When viewing the Network tab in dev tools, I can see that the request for top artists results in valid image URLs, but all the lastFM image result urls point me to just a blank star image.  Is this data source still expected to return valid results, or is it no longer being maintained?

**Comment by benjaminwgordon** [comment]
I tried subbing out a new API key and a few other ideas with no improvements.

Then I did some reading and found an article stating that this api no longer supports artist image results.  Has any thought gone into finding an alternative API for artist images?

**Comment by benjaminwgordon** [comment]
Yup, totally makes sense.  I spent a bit of time searching for other metadata APIs and didn't see anything.  I'm happy to let this close if you don't intend to make any changes.

Thanks for making a cool product!

**Comment by nukeop** [comment]
Thanks! It might be possible to replace some of these with Deezer APIs, but it's not really feasible to search for images one by one somewhere else,
