### ISSUE TITLE
Songs don't play 

### ISSUE THREAD

**Issue by Kyr4l** [nukeop/nuclear#1467]
**Platform:**
OpenSUSE Tumbleweed

**Nuclear version:**
0.6.21 (RPM and AppImage)

**Description of the issue:**
Every time i click "Play Now", nothing happens and the song load indefinitely
![image](https://github.com/nukeop/nuclear/assets/24955106/53b302c4-091f-4cf1-879a-0f66718a3f57)

**Comment by nukeop** [comment]
This particular song doesn't work for me either. I can see no reason why it wouldn't load, because it's not age-locked.

**Comment by nukeop** [comment]
I found out how to fix it! Wait for the next release.
