### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by glitchmunnky** [nukeop/nuclear#1470]
**Platform:**

**Nuclear version:**
Ubuntu 22.04.2 LTS aarch64 
**Description of the issue:**
Nuclear seems to not be on anything. I've tried searching Flatpak, Snap and Apt on terminal and....nothing!! I've also gone to the nuclear website and Flathub....still nothing!! The packages are there to install on the websites, but are not there in the AppStore.

**Comment by nukeop** [comment]
https://snapcraft.io/nuclear are you high?
