### ISSUE TITLE
Binaries seem to disappear from release tags on GH

### ISSUE THREAD

**Issue by ivanbartsov** [nukeop/nuclear#1473]
**Platform:** All of them

**Nuclear version:** --

**Description of the issue:** Currently, version [v0.6.24](https://github.com/nukeop/nuclear/releases/tag/v0.6.24) is out and Homebrew hasn't picked it up yet. It's attempting to install [v0.6.23](https://github.com/nukeop/nuclear/releases/tag/v0.6.23) and fails because binaries are missing from that one, as well as from all earlier releases.

Is this the intended behavior?

**Comment by ivanbartsov** [comment]
From what I gather, it's because of the usage of `upload-artifact` action which will overwrite the artifact entirely on succeeding uploads with the same name (i.e. doesn't matter what the file names are, everything is wiped clean every time)
The manual suggests using versioned artifact names to avoid that.
https://github.com/actions/upload-artifact#uploading-to-the-same-artifact

On a side note, what's the purpose of a separate `updload-artifact` step? `action-gh-release` seems to handle file upload as well 🤔
https://github.com/nukeop/nuclear/actions/runs/5361737779/workflow#L78-L82

**Comment by nukeop** [comment]
They don't disappear, I deleted them, because they weren't working, and then relased new, working binaries.

**Comment by ivanbartsov** [comment]
Oh, I see, sorry for the false alarm then, closing :)
