### ISSUE TITLE
Importing Youtube Playlist to Nuclear

### ISSUE THREAD

**Issue by EmMogwai** [nukeop/nuclear#1477]
**Platform:** YouTube 

**Nuclear version:**The most recent one, for PC

**Description of the issue:**
Since making the switch from Spotify to Youtube music I have been blessed with more content and less controll of playlist management xxx this is driving my poor ADHD brain crazy. I have tried so many different music apps now and nothing works xx I have invested hours and hours and days of time xxx and even more time in between in frustration because Youtube does not allow for any usual playlist functions such as "order alphabetically" or "search within playlist" . Nuclear seems like a brilliant fresh breeze and I have only just installed it today (after devoting half my day to learning AIMP that later would crash every time I tried to play any song) However, it will not find the playlists that I am trying to search for using the correct URLs x Please help this is seriously affecting my flow and music is the cure you know xx Here is one URL from my Youtube account, does it work for you? Is it just me?? 
https://www.youtube.com/playlist?list=PLq70SGI62sOtwL1JiLzlHaw3zyGdl2tzk 

kind regards
Em

**Comment by EmMogwai** [comment]
Ok the Playlist has to be "Public", in playlist settings in Youtube, "unlisted" is not enough. and it took a little while for it to load. Long enough for me to register with GitHub and type this letter. It works! Never mind my issue. 
Thank you for being here!

**Comment by nukeop** [comment]
Alright, have a good one!
