### ISSUE TITLE
Suggestion: properly capitalize application name in taskbar of Windows (non-issue?)

### ISSUE THREAD

**Issue by mknepper** [nukeop/nuclear#148]
![image](https://user-images.githubusercontent.com/12740958/51409175-a2782200-1b26-11e9-9d37-513db823b493.png)

Not sure how big of a deal this is, but I noticed it's not capitalized, and could probably use a sliver more space between the icon and application name.

**Comment by vilanz** [comment]
Fixed by #163 it seems

**Comment by nukeop** [comment]
Yes, thanks for pointing it out. Although I initially stylized it this way because the logo is all lowercase too. Doesn't make any difference to me though.
