### ISSUE TITLE
Silence "A is not iterable"

### ISSUE THREAD

**Issue by thewindsofwinter** [nukeop/nuclear#1481]
**Platform: Windows 10**

**Nuclear version: 0.6.24**

**Description of the issue:** When I'm playing a playlist, most of the songs have this annoying "A is not iterable" error. This error is not actionable by the user and seems to have begun occurring fairly recently. Preference is to figure out the root cause of this issue, but tbh just silencing it should also work, given that it doesn't seem to change core functionality and the user can't do anything about it.

<img width="213" alt="A is not iterable" src="https://github.com/nukeop/nuclear/assets/46852717/b0253105-a304-4a30-94d0-d81fdddee9b2">

**Comment by nukeop** [comment]
Might need a ytdl-core update

**Comment by computergnome99** [comment]
I am also getting this issue (and seeing very long download times for YouTube-sourced tracks, although I only started using Nuclear this evening, so this may be normal).

I'm on the latest version (0.6.24) on Linux Mint. I installed via the `.deb` file.

**Comment by FacuGOLAZO** [comment]
beside this, none of the other plugins work for me.
