### ISSUE TITLE
Max retries exceeded

### ISSUE THREAD

**Issue by robinhood2014** [nukeop/nuclear#1488]
**Fill in the form to describe your problem**
I have a problem with: YouTube
It happens when: I play any song at all
My OS is: Windows 11
I'm using Nuclear version: 0.6.28

**Additional context**
"An error has occurred when searching for streams with Youtube. Max retries exceeded"

**Comment by nukeop** [comment]
This is related to this issue: https://github.com/TimeForANinja/node-ytsr/issues/206

If it's not fixed soon I will try to patch it myself.

**Comment by nukeop** [comment]
Should be fixed now
