### ISSUE TITLE
Max retries when loading any song.

### ISSUE THREAD

**Issue by l3dlinux** [nukeop/nuclear#1489]
**Platform:**
Garuda Linux dragonized
**Nuclear version:**
v0.6.28
**Description of the issue:**
max retries exceeded with trying to play any song and yes it doesn't matter what  I search all the same thing.

![Screenshot_4](https://github.com/nukeop/nuclear/assets/17328683/bfa153ff-edba-417c-9cf2-8c785bbf35fe)

**Comment by nukeop** [comment]
Duplicate of #1488
