### ISSUE TITLE
YouTube search not finding results; missing results

### ISSUE THREAD

**Issue by mknepper** [nukeop/nuclear#149]
So, if you try search for some artists, they don't show up. For example, my music (M. Knepper) doesn't show up under artists, and neither do my EPs. If you actually go YouTube.com and search for my EPs (Uncomfortable Junctions & Uncomfortable Junctions II), they show up fine. I just thought I'd point out that the search seems to be hit or miss. On Windows 10 Pro, everything up to date.

**Comment by nukeop** [comment]
The search provider is Discogs. If you're on there, you'll show up. The alternative is Musicbrainz, unless there's another good source of indie artist data. The problem is that we also need information about tracks and albums, not just streams/videos.

**Comment by mknepper** [comment]
Well, I guess my stuff was taken off Discogs. Fascinating. Thanks for pointing that out. I'd close this issue as solved.
