### ISSUE TITLE
Invidious plugin fails to play most songs

### ISSUE THREAD

**Issue by TheFastBadger** [nukeop/nuclear#1490]
I have a problem with: Invidious Plugin
It happens when: playing music
My OS is: Windows 10
I'm using Nuclear version: 0.6.29

**Nuclear skips many songs:** 
- Potentially caused by getTrackInfo in nuclear/packages/core/src/rest/invidious.ts - it doesnt have a value for videoId and attemps to fetch https://inv.in.projectsegfau.lt/api/v1/videos/undefined
- Affects most songs

**Errors:**
- "Error: invidious track info failed"index.js:118 
- "The audio playback can not be loaded, either because the server or network failed or because the format is not supported."
- "Error while searching  for The Beatles Here Comes The Sun on Invidious"

**Comment by nukeop** [comment]
Something is majorly fucked up with Invidious in general: https://github.com/iv-org/invidious/issues/3822

This is the issue I get linked to when I try using the api to get pretty much any song, like this: https://invidious.snopyta.org/api/v1/videos/dD0z2GWo5DM

I'm going to close this for now and reopen when they sort it out.
