### ISSUE TITLE
SyntaxError when playing music

### ISSUE THREAD

**Issue by hl2guide** [nukeop/nuclear#1492]
**Platform:**

Windows 10 22H2

**Nuclear version:**

[v0.6.29](https://github.com/nukeop/nuclear/releases/tag/v0.6.29)

**Description of the issue:**

![1](https://github.com/nukeop/nuclear/assets/17044982/118d6931-4668-4296-9da9-328979b7820d)

**Comment by nukeop** [comment]
I thought this happens when there are 0 search results, but I can't reproduce this using the album shown in the screenshot, so I'll close this. If you have a song that reliably reproduces this issue, feel free to reopen.
