### ISSUE TITLE
Remote mounts not read by Local Library

### ISSUE THREAD

**Issue by rkben** [nukeop/nuclear#1493]
**Platform:** Windows 10

**Nuclear version:** v0.6.29

**Description of the issue:** Library folder *added* but not imported.

This specifically effects [sshfs on Windows](https://github.com/winfsp/sshfs-win), but would most likely effect NFS mounts and potentially SMB.

Example path: `\\sshfs.kr\user@remote.host\media`

**Comment by nukeop** [comment]
Is anything printed to the console or the logs?

**Comment by nukeop** [comment]
Also: related to #1458

**Comment by nukeop** [comment]
There's a new scanner, let me know if it still occurs.
