### ISSUE TITLE
random song auto adding to the playlist

### ISSUE THREAD

**Issue by Zawajiro** [nukeop/nuclear#1494]
every time i rewind the song i'm listening to, some random song pops up in my playlist and i have to remove them manually. mostly songs from similar artist

**Comment by Zawajiro** [comment]
also this is bug label btw i fogor

**Comment by nukeop** [comment]
This is not a bug, it' an existing feature. You can disable it by clicking the magic wand icon on the bottom right.

**Comment by Zawajiro** [comment]
zamn okay

**Comment by 0x41DEAD41** [comment]
I think he means to disable this feature by default.
