### ISSUE TITLE
Nuclear window contents zooming out automatically

### ISSUE THREAD

**Issue by dhananjey** [nukeop/nuclear#1497]
**Platform:**
Windows 11
**Nuclear version:**
0.6.30
**Description of the issue:**
When I minimize the Nuclear window or switch to another Windows application and return back to Nuclear Window, all the elements in Nuclear get zoomed out to very tiny level. This happens almost every time, when I switch between other Windows apps, and Nuclear. For example, when I minimize the Nuclear window, and start to use Notepad, while listening to a song, the playback never gets interrupted, but when I switch back to Nuclear window again, all the elements get zoomed out to the tiniest level, which makes it impossible to use the software without closing and reopening again, or I need to press Ctrl + 0 to restore to normal view. Could you please fix this?

**Comment by nukeop** [comment]
I can't reproduce this. This sounds like it's cause by something specific to your computer, if it was common I'd assume more people would have reported that.
