### ISSUE TITLE
Downloads feature

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#150]
Right now we can stream songs from some sources, but we can't download yet. Downloading is essentially it's the same process, so adding this feature shouldn't be that hard. The view where the download manager should go is currently a stub in the left hand menu bar.

Please post your suggestions and requests related to this feature here.

**Comment by vilanz** [comment]
Agree with what @sepiropht said, but I haven't found a way to show only downloaded songs or playlists in Spotify's app. Perhaps something like that should be shown in the Downloads view?

**Comment by C-Kenny** [comment]
@vilanz the mobile Spotify app displays a green download icon when a playlist is downloaded/available locally.

**Comment by nukeop** [comment]
I'm planning to add a download button everywhere you can add something to a queue, as well as to the queue item context popup.
Then, the download section will contain a list of files and download progress for each of them. Download location will be of course configurable. Maybe I'll also add something to tag the resulting files automatically.

**Comment by akaleeroy** [comment]
If I may delve into politics a little here... I've read LEGAL.md but this feature isn't a good idea right now. It's technically within reach but out of scope and bad press waiting to happen.

I would focus development efforts on nailing the glue, the aggregation of multiple sources under one familiar un-fragmented UX. More and more people suffer from "silo fatigue" and a unified experience is an irresistible breath of fresh air.

Cheers!

**Comment by nukeop** [comment]
I disagree, adding downloads is a low hanging fruit that brings a useful feature for many people. If I cared about bad press I wouldn't have started this in the first place.

**Comment by akaleeroy** [comment]
It may be my overreaction to the scores of similar projects that shut down. Even if the app dies we should aim to design so that the metadata scraping, normalization and aggregation live on. One of the edges of paid services is clean metadata, and one of their vulnerabilities is incomplete catalogs. _We must not allow a mine-shaft gap!_

**Comment by nukeop** [comment]
Downloads added.
