### ISSUE TITLE
update flatpak to use wayland, x11-fallback

### ISSUE THREAD

**Issue by SnuggleCovenant** [nukeop/nuclear#1501]
flathub shows nuclear  is unsafe because it uses the x11 socket which allows others apps to tamper with the data in memory among other things

change the socket to wayland, x11-fallback

it can be fixed on a case-by-case by the user with the third party app flatseal

this fix would improve the trust for new users and also adhere to the highest standards

**Comment by waldo121** [comment]
duplicate #1464
