### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [nukeop/nuclear#1504]
**Platform:**

**Nuclear version:**

**Description of the issue:**
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

Steps To Reproduce
In Header section see twitter old logo

Expected behavior
Twitter logo should be changed to X

Screenshot
<img width="960" alt="Screenshot 2023-09-10 090050" src="https://github.com/nukeop/nuclear/assets/91591901/acddbc95-3482-42d9-8bbc-29885163c9a9">

@kant 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by nukeop** [comment]
If you put a large "X" in the upper right corner of a website people will think it's a close button. I still refer to it as twitter, and they still use that bird in many places. It would be a mistake to respect that logo change.
