### ISSUE TITLE
Volume suddenly increasing

### ISSUE THREAD

**Issue by BarbzYHOOL** [nukeop/nuclear#1505]
**Platform:** POP OS 22.04

**Nuclear version:** sry I don't find where it is and forgot where to check, but it's a recent one like 2 months old max

**Description of the issue:**
I'm listening to my fav tracks, it's pretty low volume, then after a while, it suddenly increases and stays like that. During a song, not when skipping a song or after pressing any button

**Comment by nukeop** [comment]
This is probably unrelated to the player and is caused by the original streams having volume differences. You can enable audio normalization in the settings.

**Comment by BarbzYHOOL** [comment]
@nukeop I have enabled it already and it happened on several musics, while it never happens when browsing youtube. So no...

**Comment by BarbzYHOOL** [comment]
it just happened again rofl
