### ISSUE TITLE
 an error has occured when searching for streams with youtube A is not iterable

### ISSUE THREAD

**Issue by jakemcc22** [nukeop/nuclear#1506]
no music is playing  in nuclear Music player,,   i keep  getting  the  error 

an error has occured when searching for streams with youtube A is not iterable       please help im using the latest version,,   it loads  but no  music streams

**Comment by nukeop** [comment]
I can't reproduce this. Make sure it's actually the latest version. This sounds like an issue with an outdated version of a library that was included 1 or 2 versions ago.

**Comment by jakemcc22** [comment]
can you please direct me  too the windows install,,   i thought i had the latest version installed    thank  you

**Comment by jakemcc22** [comment]
> I can't reproduce this. Make sure it's actually the latest version. This sounds like an issue with an outdated version of a library that was included 1 or 2 versions ago.

could you please help me install the correct version?    ive ran everything from powershell     i uninstalled everything cause i couldn't find  no solution,,  sorry for spamming,    just wanted  too try this software  out     thank you n advance
