### ISSUE TITLE
problem unsolved :( 

### ISSUE THREAD

**Issue by jakemcc22** [nukeop/nuclear#1507]
nuclear music player   not  streaming    
an error has occured when searching for streams with youtube A is not iterable     this was not resolved,,   can someone please point me in the right direction  too reinstall this  for  windows...   n how  to  remove it  for  a cleaner install         thank you for your help..  im running 6.30   always i get n a error  where  i start   it will not stream nothing

**Comment by jakemcc22** [comment]
why did you close my issue    thats rude    you didnt even bother too help

**Comment by nukeop** [comment]
It's because you spam copypasting the same exact post with an irreproducible issue caused by using an old version.
