### ISSUE TITLE
windows npm install error

### ISSUE THREAD

**Issue by ayanb07** [nukeop/nuclear#151]
The package did not install in windows. giving the log file for investigation.

c:\Users\sayan\Documents\GitHub\nuclear\npm-debug.log
[npm-debug.log](https://github.com/nukeop/nuclear/files/2775182/npm-debug.log)

**Comment by nukeop** [comment]
Update node and npm, you're running years-old versions.

**Comment by ayanb07** [comment]
Updated my node and npm to latest versions. But still "npm install" failed. Attaching log below.
[2019-02-01T15_34_55_612Z-debug.log](https://github.com/nukeop/nuclear/files/2822268/2019-02-01T15_34_55_612Z-debug.log)
