### ISSUE TITLE
Music does not start automatically or after 5 minutes

### ISSUE THREAD

**Issue by BarbzYHOOL** [nukeop/nuclear#1510]
**Platform:** popos 22

**Nuclear version:** aout or july 2023

**Description of the issue:** often you start playing a song and it doesn't start, so you give up and do something else and it starts 5 min later.
If you pause and play it may start immediately

**Comment by nukeop** [comment]
This needs reproduction steps. Sounds like a network issue.

**Comment by BarbzYHOOL** [comment]
bru every issue i give you it's my fault yet i have no issue with all other apps
there is no step, it's like that for every song

i think i'm gonna just uninstall nuclear since it's obviously never gonna work properly

**Comment by nukeop** [comment]
Ok
