### ISSUE TITLE
Does not display Japanese characters.

### ISSUE THREAD

**Issue by 0x41DEAD41** [nukeop/nuclear#1519]
**Platform:** Void Linux

**Nuclear version:** v0.6.30 (AppImage)

**Description of the issue:**
The program does not display Japanese characters. I have all the necessary fonts installed in my system, but the program still does not display them. Is it because the program is forced to use a certain font or is it my system? 
![Screenshot_20231025_002512](https://github.com/nukeop/nuclear/assets/128151664/f8a6fa5a-498b-4009-a173-8c063d03fcec)

**Comment by nukeop** [comment]
Nuclear uses Lato, which is bundled with it, and as far as I know, it can display Japanese, Korean, Chinese, and many other alphabets (it has a fallback in case of missing characters). I found the album you're showing here and was able to display it correctly:

<img width="1092" alt="image" src="https://github.com/nukeop/nuclear/assets/12746779/3e34bd6c-f66b-4d1c-9bf7-21a07ddcfebe">

It comes from this Discogs album: https://www.discogs.com/master/1626772-Livetune-feat-%E5%88%9D%E9%9F%B3%E3%83%9F%E3%82%AF-ReDial
