### ISSUE TITLE
White screen on startup

### ISSUE THREAD

**Issue by anoadragon453** [nukeop/nuclear#152]
Saw this was already reported in the comments [here](https://github.com/nukeop/nuclear/issues/60) but still getting it on latest master (754a0acdce3ddc9c1c4cdde3442ed6c4587c8b35) so wanted to make an issue for it.

I am running Debian testing. I did:

* `npm i` to install deps
* `npm run build:linux` to build a `deb` package
* Installed the package
* Ran `nuclear` in a terminal

What results is a window that opens up that's completely blank.

I'm not sure where log files are stored (couldn't find them in current dir, `/var/logs` or `~/.config/nuclear`. Any way I can be of more help?

**Comment by anoadragon453** [comment]
`npm start` does produce a working window however.

**Comment by nukeop** [comment]
You only started the empty electron window, you also need a server with the react app, started with a separate command.

**Comment by anoadragon453** [comment]
Ah, is there another command that comes with the `deb` package?

**Comment by nukeop** [comment]
No, but before building that, you have to build the react app so it can be packaged together with the server.

**Comment by anoadragon453** [comment]
Ah I see. Following the build instructions on the README:

```
$ npm run build:dist
$ npm run build:electron
$ npm run build:linux
```

worked perfectly. Thanks, and sorry for the trouble!

**Comment by nukeop** [comment]
No problem, glad that it worked.
