### ISSUE TITLE
App Down, Error Message

### ISSUE THREAD

**Issue by moderncoderzz** [nukeop/nuclear#1522]
**Platform:**
MacOS

**Nuclear version:**
0.6.30

**Description of the issue 1:**

When starting Nuclear application, it shows this error message.
<img width="272" alt="Screenshot 2023-11-02 at 3 01 32 PM" src="https://github.com/nukeop/nuclear/assets/143584383/334c519a-2fcb-4511-b4f0-cfc0b147319f">

**Description of the expected behavior 1:**

No error message

**Description of the issue 2:**

When playing any song, it loads in this green state, and then just skips and goes onto the next song. This continues until skipping every song. The app is unable to play any music. 

<img width="287" alt="Screenshot 2023-11-02 at 3 12 27 PM" src="https://github.com/nukeop/nuclear/assets/143584383/22d69616-89af-4cfa-88a6-04424ddd0b7d">

**Description of the expected behavior 2:**

Songs play without skipping

**Comment by nukeop** [comment]
1. likely means that Nuclear can't access the config folder, and can't initialize its config files. Does it have access to `/Users/<name>/Library/Application Support/nuclear`?
2. I can't reproduce this issue. Have you changed the default streaming settings? You might be blocked from accessing Youtube altogether.

**Comment by moderncoderzz** [comment]
Thank you! 

2. Making a folder called "/Users/<name>/Library/Application Support/nuclear" helped with the second issue. Songs now play for some reason. The folder in Application Support did not exist. It must have been a problem from updating the application.

1. The first problem still is there. How do I check if Youtube is blocked? As the songs now play, it might be a different issue.

**Comment by moderncoderzz** [comment]
As an update, I did chown to make sure there is read and write access for the nuclear folder in application support. Even then, it still gives the same error message.

```
User/Application Support % ls -ld nuclear

drwxrw-rw-@ 21 username staff  672 Nov  3 20:17 nuclear
```

<img width="256" alt="Screenshot 2023-11-03 at 8 19 21 PM" src="https://github.com/nukeop/nuclear/assets/143584383/c7393d1e-003b-4250-a3ff-2773c0700f2f">

**Comment by nukeop** [comment]
I'll be releasing a new version soon, let's see if it's fixed then.

**Comment by nukeop** [comment]
The new version is out, let me know if it still occurs.
