### ISSUE TITLE
CI/CD fails due to node-gyp error on macos-latest

### ISSUE THREAD

**Issue by jeremy-code** [nukeop/nuclear#1529]
**Platform:**
GitHub Actions/macos-latest

**Nuclear version:**
0.6.30

**Description of the issue:**
* CI/CD fails due to node-gyp error on macos-latest
* `diskutil` removed on Python 3.12 resulting in node-gyp erroring out on CI/CD tests, and does not proceed to build
* Steps to reproduce: Run CI

**Comment by nukeop** [comment]
Thanks. yeah I noticed it. You think this is because of an update to the image? Last good build was on 27th Oct.
