### ISSUE TITLE
Queue error on some local music.

### ISSUE THREAD

**Issue by mateusfn98** [nukeop/nuclear#1531]
**Platform: Windows**

**Nuclear version: [v0.6.30](https://github.com/nukeop/nuclear/releases/tag/v0.6.30)**

**Description of the issue:**

Music player don't play some music from my local playlist.
![image](https://github.com/nukeop/nuclear/assets/74764525/91464b4f-a9f7-42fe-a5df-d0cf758c1c74)
This error appears in the queue on the right side.

Also, at the bottom of the queue, this is happening in a loop (blinking):
![image](https://github.com/nukeop/nuclear/assets/74764525/192be970-784f-43f2-a0d3-749c2fb61202)
![image](https://github.com/nukeop/nuclear/assets/74764525/946deb7a-a692-48b2-acfe-e80c9ca9e44c)

**Comment by nukeop** [comment]
Should be fixed in the next release.
