### ISSUE TITLE
import spotify dont work 

### ISSUE THREAD

**Issue by kazundo** [nukeop/nuclear#1532]
**Platform: mac os sonoma 14.2

**Nuclear version:0.6.30

**Description of the issue:**
I tried several times to import my Spotify playlist but it doesn't work!!

**Comment by nukeop** [comment]
Can you link the playlist here? Note that it has to be public.

**Comment by kazundo** [comment]
https://open.spotify.com/playlist/5rYb2HiIgzweiEWC7COeJa?si=c360c0648be74d0b

**Comment by B1ack3ye** [comment]
The same for me, the import worked, but when I try to select the playlist, I get a "null" error.
The Playlist: https://open.spotify.com/playlist/3tQgOLUgvtVWWaFAs0QN8O?si=0c5fc709a04640eb
![image](https://github.com/nukeop/nuclear/assets/63259739/b0ecf37f-fe4c-4894-903f-9ee905c0ec2d)

**Comment by nukeop** [comment]
Thanks, this is actually the key clue here, since I already saw another person reporting a `null` in the imported playlist. This means the scraper needs to be updated.

**Comment by UnoNYC** [comment]
Hi, I am using the latest version and the spotify import does not work.. it just hangs at 0%.. is there another version of this app where this feature does work? I am using Windows 10 22H2 x64

Here is the playlist url..

https://open.spotify.com/playlist/0dtfQoGtQBqzuhFGBAJ4fH

**Comment by nukeop** [comment]
I can confirm that I can't improt taht playlist either. I'll be able to fix that in the next release.

**Comment by nukeop** [comment]
In the new release I was able to download that. Try again, and if it doesn't work for you, let me know. Reopen this issue, or make a new one.
