### ISSUE TITLE
IMPORTATION SPOTIFY PLAY LISTES

### ISSUE THREAD

**Issue by HaroldLEBRUN** [nukeop/nuclear#1533]
**Platform:**

**Nuclear version:** Bonjour je n arrive pas a importer mes plailistes depuis Spotify 
comment je dois m y prendre 
merci pour votre réponse 
Harold lebrun

**Description of the issue:**

**Comment by Tweniee** [comment]
Translation:
`Nuclear version: Hello, I can't import my playlists from Spotify,
how should I take them,
thank you for your response
Harold Lebrun`

**Comment by HaroldLEBRUN** [comment]
https://open.spotify.com/playlist/10tCbbagYskTsCcjwKopHe
Bonjour voici le lien 
Merci pour votre aide


 Hello here is the link
Thank you for your help

**Comment by HaroldLEBRUN** [comment]
https://open.spotify.com/playlist/37i9dQZF1DXd0Y4aXXQXWv

Bonjour celui la en exemple
Hello this one in example

**Comment by nukeop** [comment]
I was able to download both of these playlists in unmodified Nuclear.
