### ISSUE TITLE
téléchargement bloqué

### ISSUE THREAD

**Issue by masderoulan** [nukeop/nuclear#1535]
windows 10 - 32 bits

**Nuclear version:**3
Les téléchargements sont bloqués, la liste s'affiche mais impossible de les relancer en faisant "pause"
![nuclear download page](https://github.com/nukeop/nuclear/assets/153221630/7caf0b6d-138f-47c2-9636-784bb6d222f7)

**Comment by nukeop** [comment]
Use english
