### ISSUE TITLE
Full screen on mac

### ISSUE THREAD

**Issue by nobodyme** [nukeop/nuclear#154]
Yes, this is not a huge issue but the app fails to open in full screen on mac. The dock at the bottom still appears. Would like to learn and contribute if any help is needed with little guidance. Thanks.

**Comment by nukeop** [comment]
To be honest I have no way to test it so any help would be appreciated.

**Comment by trekiteasy** [comment]
@nobodyme, could you give more details on what's happening and what should happen. On my side, when I click on the maximize button, everything seems to work properly.
(What versions of macOS do you have ?)

**Comment by nobodyme** [comment]
@trekiteasy, I downloaded the latest mac zip file from the release page and the app on maximize looks like this,

![image](https://user-images.githubusercontent.com/22789194/51438157-36382280-1cce-11e9-923f-e26d01d08241.png)

But dock should be hidden on full screen right?
And I use High Sierra btw.

**Comment by trekiteasy** [comment]
The latest commit will solve this. It should be included when the next release is out.

**Comment by nobodyme** [comment]
Great and sorry about this noob question not sure if this is the place as well but if you could just tell me if this is the right behaviour. So I completely didn't have any idea about electron and learnt about it a little bit in order to contribute to this issue myself. Yes, I did find that setFullScreen method but when I edited the code and tried to run it, as described in the readme like,

```
npm install
npm run watch
npm run electron:dev
```

I get the application running with the dev-tools open like in the below image,

![image](https://user-images.githubusercontent.com/22789194/51492217-13ddfc00-1dd7-11e9-8737-1446c28200c0.png)

This is how it's intended to be?
Thanks!
