### ISSUE TITLE
Nuclear cannot download songs when a song is paused halfway thorugh the download.

### ISSUE THREAD

**Issue by LibTheBirdLover** [nukeop/nuclear#1540]
For a few days, I've been having this bug wherein if you pause a download halfway and close the app, and then reopen it, nuclear cannot resume the download or download any other songs unless all song downloads are paused and the song which is halfway downloaded is removed and added again.

Is anyone else having this bug?

**Comment by nukeop** [comment]
Nothing's changed on our end. Does playback work for you?

**Comment by LibTheBirdLover** [comment]
The bug doesn't happen anymore. Aquick restart of my computer fixed it. Wonder what caused it in the first place.

**Comment by nukeop** [comment]
Glad it helped. If it reoccurs, feel free to reopen the issue, or make a new one.
