### ISSUE TITLE
Suggestions for Nuclear New Features

### ISSUE THREAD

**Issue by phxchristian** [nukeop/nuclear#1541]
**Platform:**
PC

**Nuclear version:**

**Description of the issue:**

Som ideas I have are maybe themes, or more settings for visualizer (shuffle visualizations / randomizer), also maybe room settings for EQ / reverb / compression.

And under downloads, support for other codecs like MP3 / M4A.

Also tried to remove the bug label, but couldn't under Github.

**Comment by nukeop** [comment]
Downloads can now be transcoded to mp3. As for the other features, there are already other issues for them.
