### ISSUE TITLE
Play/Pause button not centred

### ISSUE THREAD

**Issue by ghost** [nukeop/nuclear#1544]
**Platform:** Linux

**Nuclear version:** v0.6.30

**Description of the issue:**
The Play/Pause button at the bottom of the window isn't centred between the Previous and Next buttons - it's closer to the Next button (i.e. to the right). Hard to see for the Play button, but easier with the Pause button:

![button_alignment_play](https://github.com/nukeop/nuclear/assets/2385329/46b676f9-cd4f-4fbf-b287-c32a796c470e)

![button_alignment_pause](https://github.com/nukeop/nuclear/assets/2385329/62cb4470-0618-42c4-8209-0bda082195c4)

**Comment by nukeop** [comment]
Hey, this is a tricky one - it needs some extra alignment to be perfectly centered beyond what flexbox does automatically. Did you happen to measure the pixels?

**Comment by BWPanda** [comment]
Yep:

![image](https://github.com/nukeop/nuclear/assets/2385329/e97ed9b1-722a-40f9-9df2-1d38d403f0b8)

Left: 23px
Right: 19px

![image](https://github.com/nukeop/nuclear/assets/2385329/421a14a1-c212-4958-9940-39857bef0623)

Left: 26px
Right: 19px

![image](https://github.com/nukeop/nuclear/assets/2385329/63208b5d-af31-4bf4-92b5-410bcd81e8c5)

Left: 26px
Right: 20px

**Comment by nukeop** [comment]
You're right! This must be because we center the bounding box of the icon, not the actual icon (visually). This can be solved with adding a small margin to one side of the icon, different for each type of icon.

**Comment by sqallFF** [comment]
Hello there i was wondering if anyone fixed this issue yet? I would like to work on this

**Comment by nukeop** [comment]
@sqallFF thanks, go ahead!
