### ISSUE TITLE
Downloads only .mp4 format track

### ISSUE THREAD

**Issue by Leezan-1** [nukeop/nuclear#1550]
Fedora 39

v0.6.30

When i download a track it downloads in mp4 format not in audio format

**Comment by nukeop** [comment]
MP4 is a container format which may contain audio or video, or both. The downloaded format depends on what format the original stream source is in. Nuclear doesn't do any conversions (yet).

**Comment by nukeop** [comment]
Transcoding added in https://github.com/nukeop/nuclear/commit/ac8bdac813613e02826bb58fde73a7353908e96e
