### ISSUE TITLE
Shuffle visualization presets with an interval

### ISSUE THREAD

**Issue by elmaester** [nukeop/nuclear#1555]
Manually changing presets is no fun. Currently there's a default visualization preset, and it never changes.

I propose doing a setInterval where the callback increments the index of the active preset in the array of presets.

Or achieving a similar effect in a different way.

Or perhaps playing a new track could be the trigger.

And actually, instead of incrementing and moving to the next preset, it should be chosen randomly from the available options.

**Comment by nukeop** [comment]
I agree switching to a random preset whenever you start playing a new track sounds like a good idea.

**Comment by elmaester** [comment]
Bumping up because I still want this ☺️

**Comment by gurvanhenry** [comment]
A `shuffle button` next to preset list could also be interested for the user to discover other visualizations randomly.

Something like this:

![image](https://github.com/nukeop/nuclear/assets/2821522/573e024b-87bb-407a-9c33-f2c90e771b4d)

**Comment by nukeop** [comment]
I'd rather see it to the left of the existing fullscreen button, and in the same style, but it's the right idea.

**Comment by CarlosBor** [comment]
Silly as it might be, the visualizer is the kind of feature that brings a smile to my face.
I'll start working on this feature.

**Comment by nukeop** [comment]
Great, additionally people have been asking about adding this on Discord.

**Comment by nukeop** [comment]
Implemented!

**Comment by elmaester** [comment]
Badass! Thank you! I'll update and check it out soon 🎉
