### ISSUE TITLE
can't use

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [nukeop/nuclear#156]
![image](https://user-images.githubusercontent.com/29156241/51444667-8784e980-1caf-11e9-8a1a-88d5ee2832ca.png)
just stays like that changing colors

**Comment by C-Kenny** [comment]
I've managed to browse around the dashboard/genres and get a song playing. However when click on a search result, I get the same error as OP. Although this might just be the general exception error, as it just hangs there.

Does Nuclear output log files, if just running as a .exe which we can use to debug?

**Comment by nukeop** [comment]
There is a debug log if you run in a terminal. There are other threads related to this and likely it's already solved in development version, I'll close this since this thread doesn't give us anything to work with.
