### ISSUE TITLE
Playback hangs indefinitely when no streams are available for tracks

### ISSUE THREAD

**Issue by sferra** [nukeop/nuclear#1560]
**Platform:**
Linux

**Nuclear version:**
0.6.30, 1ec000acaa3926a52119b35bfaf0e1b091dfe5c4

**Description of the issue:**
The playback hangs indefinitely when no streams are available for a track.

To replicate:
1. Select 'Bandcamp' as stream provider
2. Search for "Monkey3", select the album "[Welcome to the Machine](https://monkey-3.bandcamp.com/album/welcome-to-the-machine)". The album has 5 tracks, of which only 2 (tracks 2, 4) can be streamed.
3. Select "Play" for the album. Playback hangs indefinitely because no stream can be resolved for the first track. Attempting to skip the  track also results in an uncaught runtime error: "The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22"

The above can occur for any stream provider, not just Bandcamp, if no stream is available.

**Comment by nukeop** [comment]
This should instead remove the affected track from the queue, and I'm pretty sure that in does, when the request to the streaming service results in a 404

**Comment by sferra** [comment]
Yet the track isn't removed. It can be easily reproduced with the steps above.
There is no 404, since the stream itself is `undefined`.

IMO the unavailable stream should be removed and if it's the last one then the track should be probably removed, at least as a first fix.  It would be nicer IMO to mark the track as unavailable and skip to the next one, instead of letting it magically disappear.

I have a local fix for removing the unavailable stream, if you are willing to reproduce & review.

**Comment by nukeop** [comment]
Fixed by #1562
