### ISSUE TITLE
Sync Playlists and Favorites

### ISSUE THREAD

**Issue by heliophane** [nukeop/nuclear#1564]
Hello,

I use Nuclear on two computers, a desktop and a laptop. I would like the ability to sync my Playlists, Favorite Tracks, and Favorite artists between my computers. If this would not be feasible to add, is there a some kind of datastore or set of dotfiles I could sync using something like syncthing?

Apologies if that has already been requested to death, I did a quick search and didn't see anything specific

**Comment by nukeop** [comment]
Depending on the system, you can just copy the config files. They should be in `~/.config/nuclear` on Linux, `%APPDATA%/nuclear` on Windows, and `Application Support/nuclear` on Mac OS.

**Comment by heliophane** [comment]
Awesome! This worked out quite well! Thank you! 🙂

Hope to be able to listen on mobile some day. Keep up the good work!
