### ISSUE TITLE
Local library: unable to map a directory to a network share

### ISSUE THREAD

**Issue by OrdoConcept** [nukeop/nuclear#1569]
**Platform:** Windows 10

**Nuclear version:** 0.6.30.0

**Description of the issue:**
Impossible to map a directory to a network share (a NAS for example). Why?

**Comment by OrdoConcept** [comment]
Thank you for this quick response.
If I put my library on a physical disk on my machine everything works. If I put it on my NAS, even if I mount the directory in the file system, no file is detected...

**Comment by CarlosBor** [comment]
I looked into this and there might be a chance the base issue was accidentally fixed? These were not exactly done with a NAS but another computer in my network which has a shared folder instead, I presume them to be analogous.

In the latest release of nuclear (0.6.30 at the time of writing) it certainly doesn't seem to detect the files. It grabs the folder fine and all, but just seems to find nothing:
![image](https://github.com/nukeop/nuclear/assets/48533334/bd01bbe7-7885-4152-9eb9-09827e3d2ace)

But if I clone the repo as it is right now and build it, then do the same thing it finds the files just fine:
![image](https://github.com/nukeop/nuclear/assets/48533334/fd57cd8c-37bc-4588-94ae-f04a0fd7a61d)

Trying to play them right then and there yields a "local.tracks.find is not a function" error, but after restarting the app the files can be played. I'll take a look at that next but if someone that actually has a NAS available could verify if the behavior above replicates that'd be nice.

**Comment by nukeop** [comment]
On the master branch you would be using the new scanner, which wasn't written with network shares in mind, but behaves differently, so it is very possible that it was fixed accidentally. Thanks for verifying this!

**Comment by nukeop** [comment]
The new release includes the new scanner. Try it, and if it doesn't work let me know.
