### ISSUE TITLE
Playing songs is counter intuitive

### ISSUE THREAD

**Issue by paperbenni** [nukeop/nuclear#157]
When you click on a song in an album, you expect it to play, that's how it works everywhere else and there's no reason to use something else. I would suggest to move the context menu that pops up instead to the right mouse button which does nothing at the moment. Also I am able to stack multiple context menus by clicking on multiple songs, that shouldn't happen either. 
https://imgur.com/a/DhOcJUp
I'm using the version from the latest master commit on archlinux. 

By the way I think this app has incredible potential, keep up the amazing work :)

**Comment by nukeop** [comment]
If I remember correctly the track number becomes a play button when you hover over the track, and clicking it does what you want.

**Comment by paperbenni** [comment]
No it doesn't. And remapping the menu would still be nice.

**Comment by nukeop** [comment]
If it doesn't then it's a good idea to make it do so then, maybe I implemented this before I rewrote it from scratch and forgot. I planned replacing right clicks with a custom context menu at some point too.

**Comment by trekiteasy** [comment]
I do agree I would suggest : 
- to harmonize all track interactions (in dashboard / artist view / playlist view / album view / tag view)
- to replace the number button (or the track icon) by a play button on hover
- a click on the play button would : add the track to the current queue just after the current song & play this new song right over
- move the context menu to the right click action on a track
- add a shortcut : double-click to add the track at the end of the queue
What do you think about it ?

**Comment by nukeop** [comment]
The previous version had two extra buttons on hover, one "play now" which clears the queue, adds the selected song, and starts playing it, and a plus sign button which pushes the song to the end of the queue, similar to how "play now" and "add to queue" work elsewhere. I agree that the popup for tracks should be unified and given its own component (maybe make it accept a list of additional buttons in case we want to add some extra actions in some places in the future).

I remember trying to use right clicks for the context menu but I think React handled that poorly.

**Comment by charjac** [comment]
it is actually possible to handle the right click with react
```jsx
<p>onContextMenu={console.log}>right click me</p>
```
and the popup from react-semantic-ui can have a controlled state:
https://react.semantic-ui.com/modules/popup/#usage-controlled

**Comment by swrenst** [comment]
Is there still interest in making the track number a play button on hover? I have it running and currently, nothing happens when I hover over "A#", but I think this would improve the user experience. Would this be something I could try implementing?

**Comment by nukeop** [comment]
Definitely, if you want to do it I would appreciate it.
