### ISSUE TITLE
Navigation issues after deleting a playlist

### ISSUE THREAD

**Issue by sferra** [nukeop/nuclear#1570]
**Platform:**
Linux

**Nuclear version:**
0.6.30 80a7b1c97b9380c7b58b67a4b14c907f9739ca67 

**Description of the issue:**
Back navigation triggers an error and behaves incorrectly after deleting a playlist.

After deleting a playlist and navigating back (using the navigation buttons, for example), an error is displayed. Also, the playlists overview is displayed instead of actually navigating back to the previous view.

To replicate:
1. Create a new playlist (name and contents are irrelevant)
2. Select the playlist. The playlist is displayed.
3. Delete the playlist using the option in the '...' menu.
4. The playlists overview is displayed
5. Attempt to navigate back using the navigation buttons in the UI. An error is displayed, the playlists overview is displayed instead of navigating back to the previous view.
6. At this point we can also attempt to navigate forward, which will trigger the same error once more

The issue is caused by the fact that after deleting a playlist, the current implementations actually navigates forward to the playlists overview instead of going back to the previous view. Therefore navigating back attempts to display the playlist we just deleted.

`PlaylistView.onDeletePlaylist`:
```ts
deletePlaylist(playlist.id);
history.push('/playlists');
```
should rather be:
```ts
deletePlaylist(playlist.id);
if (history.length > 1) {
  // The current playlist is the top of the navigation stack, go back to the previous view
  history.goBack();
} else {
  // Fallback in case we can't navigate back to a previous view
  history.push('/playlists');  
}
```

This works nicely, without having to touch existing component tests, nevertheless, the new (and relevant) execution path wouldn't be tested.

**Comment by nukeop** [comment]
This looks to be an oversight, can probably be reproduced and tested.

**Comment by sferra** [comment]
How can we test this without adding an additional, expensive component test?

**Comment by nukeop** [comment]
There's no cost that I can think of to having an additional test. The tricky part might be setting up the history to work correctly. The current setup should be able to handle that.
