### ISSUE TITLE
Hijacked testimonials

### ISSUE THREAD

**Issue by Anonymous941** [nukeop/nuclear#1572]
It seems the testimonials section has been hijacked, because it's a series of insults and legal threats about the project along with cussing, attributed to "redditor".  It's not like this project is even illegal anyway as it just pulls from free sources...

![Screenshot](https://github.com/nukeop/nuclear/assets/36797492/97e00158-0424-4294-8c0f-dc32d1366570)

**Comment by nukeop** [comment]
I hijacked it myself to be one step ahead of the hackers.

**Comment by Anonymous941** [comment]
I'm confused...

**Comment by nukeop** [comment]
I made the entire website. There's no way for anyone to hijack anything.

**Comment by Anonymous941** [comment]
@nukeop I see now that it was added 3 years ago in nukeop/nuclear@f29d68d01adee4d8c96ae60eef04e5a3c1c30c02, but I'm still confused...
