### ISSUE TITLE
Téléghargement

### ISSUE THREAD

**Issue by Patxi56** [nukeop/nuclear#1573]
**Platform:**

**Nuclear version:**

**Description of the issue:**
Bonjour
J'ai souhaité téléchargé une dizaine de morceaux mais ça ne bouge pas????

**Comment by nukeop** [comment]
What doesn't work?

**Comment by Patxi56** [comment]
Merci
Dès que je sélectionne le morceau il s'affiche avec les autres et il y écrit "waiting" et rien ne se déclenche?????
________________________________
De : nukeop ***@***.***>
Envoyé : mercredi 27 mars 2024 16:27
À : nukeop/nuclear ***@***.***>
Cc : Patxi56 ***@***.***>; Author ***@***.***>
Objet : Re: [nukeop/nuclear] Téléghargement (Issue #1573)


What doesn't work?
