### ISSUE TITLE
Player options popup menu has a broken layout

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#1574]
When the window is narrow, the options in the player bar (volume, shuffle, loop, etc) are hidden in a popup that appears when you hover over the ellipsis button. At some point it got broken and now looks like this:

<img width="349" alt="image" src="https://github.com/nukeop/nuclear/assets/12746779/21bdc6ca-95bd-449f-9400-05240e7d0dfe">

Needs to have the layout fixed.

**Comment by sicin** [comment]
I'll see it in the near future, maybe at the same time it would be worth it to add volume control to the miniplayer.

**Comment by sossost** [comment]
hello. I am sossost, a new contributor. I would like to solve this problem together. Is it possible??

**Comment by sicin** [comment]
> hello. I am sossost, a new contributor. I would like to solve this problem together. Is it possible??

You can take over this issue if you want, it's too small to have 2 people working on it imo. As for the miniplayer, I think a new issue should be opened.

**Comment by nukeop** [comment]
Sure, I agree.

**Comment by sossost** [comment]
@sicin First of all, thank you for your consideration :)
However, I would like to proceed with another issue.

**Comment by nukeop** [comment]
Alright, feel free to take whichever you want.

**Comment by camicacace** [comment]
Hi, can I work on this issue?

**Comment by nukeop** [comment]
Sorry I already fixed this, forgot to close this issue.
