### ISSUE TITLE
Empty Playlists

### ISSUE THREAD

**Issue by Lazontez** [nukeop/nuclear#1575]
Description: When a user empties all songs from a playlist, the playlist itself should also be deleted as there are no songs attributed to it, and takes up unnecessary space.

Resolution: Automatically (or with a pop-up to confirm with the user) delete the playlist with NO songs.

![image](https://github.com/nukeop/nuclear/assets/48937296/2b8f4aa3-c9de-493e-bd3d-34f527540a63)

**Comment by nukeop** [comment]
An empty playlist takes almost no space. It's possible (and needed) to delete all tracks from a playlist, and then add new tracks to it, so I decided not to go ahead with this feature.
