### ISSUE TITLE
Add all tracks in the queue to an existing playlist 

### ISSUE THREAD

**Issue by rohanrider** [nukeop/nuclear#1577]
It would be awesome to add all tracks in the queue to an existing playlist (like you can already do to create a new playlist). Love the software. Thanks for it!

**Comment by nukeop** [comment]
Thanks! That's a pretty natural option to have.

For now, advanced users can merge playlists manually in the config json, but there should be a button added for this.

**Comment by sossost** [comment]
Hi ! @nukeop I am sossost, a new contributor. I'd like to contribute to this issue! Can I proceed??

**Comment by nukeop** [comment]
> Hi ! @nukeop I am sossost, a new contributor. I'd like to contribute to this issue! Can I proceed??

Sure, would you like to take both of those issues?

**Comment by sossost** [comment]
@nukeop oh! No, I will choose this issue. thank you!

**Comment by sossost** [comment]
Thank you! I'm glad to hear that. Your feedback motivates me to maintain high standards in my work. I'll keep up the good work!"

**Comment by nukeop** [comment]
Thank you, that was really quite awesome. You did everything - set up the project for yourself, implemented the feature very well, created a test for it, and updated existing tests, committing only the necessary changes. Very nice!
