### ISSUE TITLE
Playlist dialog title not translated (english only)

### ISSUE THREAD

**Issue by gurvanhenry** [nukeop/nuclear#1579]
**Platform:**
macOS

**Nuclear version:**
Version 0.6.30 (0.6.30)

**Description of the issue:**
I found a dialog title that is not translated: `header={<h4>Input new playlist name:</h4>`

![image](https://github.com/nukeop/nuclear/assets/2821522/7b18b250-a084-49df-ba15-89c5eb108d9d)
![image](https://github.com/nukeop/nuclear/assets/2821522/70251b7f-8ebf-4814-a37f-cede63fff0be)

Lines of code with text to translate:
![image](https://github.com/nukeop/nuclear/assets/2821522/47e38345-3178-4ee1-bb4c-fa475264f739)

**Comment by nukeop** [comment]
Thanks, this should be placed in en.json

**Comment by Just-A-Pixel** [comment]
Resolved issue
PR: https://github.com/nukeop/nuclear/pull/1581
