### ISSUE TITLE
Better right panel UX

### ISSUE THREAD

**Issue by vilanz** [nukeop/nuclear#158]
Currently you can use the right panel to create playlist, but it's too non-intuitive.

From what I can understand the -very small- save icon saves the queue as a playlist and the trash bin button removes it. But these buttons are too small and their intention hidden behind icons. Such an important feature deserves its own large, shiny buttons, with explicit text (i.e. "+ Add to Playlist...").

**Comment by Zannisdf** [comment]
Can I work on this?

**Comment by nukeop** [comment]
Not yet, I don't think we'll want any major changes to the UI right now.

**Comment by nukeop** [comment]
Sure, I remember experimenting with button placement when I developed this feature and I think it looked a bit out of place at the bottom, leaving an almost empty row. Be sure to include a screenshot if you feel like changing it.

I know these queue buttons are pretty small but it's hard to manage the limited horizontal space in a different manner without making it look like a parade of random unrelated options. We don't want something like this: http://www.ssw.com.au/ssw/Standards/Rules/Images/bad-functionaloverload1.jpg

**Comment by vilanz** [comment]
@trekiteasy Playlist management deserves its own separate issue, this one was just for creating playlists in the right panel.

@nukeop We'd only need like, a "Add to Playlist" and a "Clear all" button, just like right now...
Also, the right panel could have a "Queues" title. What do ya think?

**Comment by nukeop** [comment]
I revamped the queue panel buttons and created a menu with clearly named buttons, I think most of these can be hidden away behind 1 extra click without it being too much of a hassle.
