### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by sicin** [nukeop/nuclear#1585]
**Platform: ubuntu 22.04**

**Nuclear version: 0.6.30**

**Description of the issue: "Popular Tracks" is not translatable/translated**
![Screenshot from 2024-04-12 14-03-27](https://github.com/nukeop/nuclear/assets/60555965/cb7a1113-cf51-4c65-b522-398bb55478dd)

**Comment by ajkapala21** [comment]
Created fix with PR: #1586

**Comment by sicin** [comment]
Found more untranslated strings, should I create a new issue for that?
