### ISSUE TITLE
More untranslated strings

### ISSUE THREAD

**Issue by sicin** [nukeop/nuclear#1587]
**Platform: ubuntu 22.04**

**Nuclear version: 0.6.30**

**Description of the issue: Untranslated strings in several places**
![Screenshot from 2024-04-13 03-24-49](https://github.com/nukeop/nuclear/assets/60555965/8f4c6bd1-0b2c-43d1-9645-60dc7126b368)
![Screenshot from 2024-04-13 03-24-58](https://github.com/nukeop/nuclear/assets/60555965/b8739e98-5832-4ff7-a904-c167ead27657)
![Screenshot from 2024-04-13 03-25-14](https://github.com/nukeop/nuclear/assets/60555965/67c38023-efb2-457b-9438-b6fc932b0f8e)
![Screenshot from 2024-04-13 03-25-34](https://github.com/nukeop/nuclear/assets/60555965/b9580440-16fe-4d89-af5c-a0fb2c066d3e)
![Screenshot from 2024-04-13 03-25-45](https://github.com/nukeop/nuclear/assets/60555965/acf2589e-c31c-442d-842c-2932e092b0dc)

**Comment by nukeop** [comment]
Thanks, I was pretty sure we got all of this down
