### ISSUE TITLE
Dragging things around freezes them, might crash the app

### ISSUE THREAD

**Issue by vilanz** [nukeop/nuclear#159]
As the title says, whenever I - for example - accidentally drag a song or a sidebar item somewhere, it gets frozen in place. In some situations - sidebar items for instance - it will inevitably make the app crash.

I'm running `electron:prod` on Ubuntu 18.10.

**Comment by nukeop** [comment]
Dragging is handle by an external  package, I'll take a look if we can fix this.

**Comment by qualitymanifest** [comment]
Looks like it might be related to https://github.com/electron/electron/issues/14430 and https://github.com/electron/electron/issues/14073

In those issues the user reported the problem just from dragging around text. If I type something in the search bar and then select and attempt to drag it, I get the same problem - the app freezes.
