### ISSUE TITLE
Change search model

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#16]
Search model could be improved. Here's the plan:

1. Nobody cares where the music comes from. The search source should not be selected by the user, because they want to listen to music, not to decide where to look for it.
2. The user should be able to search for three things: artists, albums, and individual tracks. The artist's page should have a list of albums (like Spotify or Deezer, shown as album covers and expandable to lists of tracks), and a short list of the most popular tracks. The album page should show the cover and a list of tracks. Individual tracks can be played, added to the queue, or added to downloads.
3. The program decides behind the scenes where to look for the music, trying to match definitions from musicbrainz. We either only look for the first 100% match (title/track length) or try to find best quality.
4. Fine grained settings like excluding some sources could be contained in the settings panel where nobody will ever look.

**Comment by g5codyswartz** [comment]
Maybe a post-search filter could be used for picky users, or it could be added to settings for a more permanent result.

**Comment by nukeop** [comment]
Album search is already implemented.

Artist search & pages coming up next:

![screenshot](http://i.imgur.com/H4Vvw7K.png)

**Comment by nukeop** [comment]
a little bit nicer now:

![screnshot](http://i.imgur.com/wgwJUwd.png)

soon it will be ready for a new release

**Comment by nukeop** [comment]
The images for artist pages could be stolen from Spotify via their api:

https://developer.spotify.com/web-api/get-artist/
