### ISSUE TITLE
Inaccurate tracks

### ISSUE THREAD

**Issue by Te9chira** [nukeop/nuclear#1605]
**Platform:**
Windows 10 64x
**Nuclear version:**
Latest
**Description of the issue:**
Sometimes when I look up a specific track and play it just gives me some other random song for some reason, tried changing the source and metadata provider, still the problem is present.

**Comment by nukeop** [comment]
This is expected and inevitable, because Nuclear uses heuristics to match streams to metadata. To mitigate this, you can verify tracks for which Nuclear found wrong streams: https://nukeop.gitbook.io/nuclear/user-manual/stream-verification
