### ISSUE TITLE
Lyrics scroll back to the top on new song

### ISSUE THREAD

**Issue by KingCalad** [nukeop/nuclear#1606]
if you scroll to the bottom of the lyrics, it will stay at the bottom when a new song plays. it seems more intuitive for the lyrics to always start at the top for each new song

**Comment by nukeop** [comment]
Great idea - I'll be very happy to work on this with someone

**Comment by nukeop** [comment]
Fixed by a djinn in #1607

**Comment by KingCalad** [comment]
that was quick, thanks!

**Comment by nukeop** [comment]
It was also a great way to test a new Github feature where the AI codes everything
