### ISSUE TITLE
App crash after click Downloads

### ISSUE THREAD

**Issue by DanSeraf** [nukeop/nuclear#161]
After you open an artist page, if you click on Downloads in the menu bar the app crash

**Comment by nukeop** [comment]
The downloads section only renders a line of text as a placeholder, I doubt this is something on our end unless you give me more details.

**Comment by DanSeraf** [comment]
It's strange because the app render the line correctly unless you open an artist/album page, the application goes in a logo loop like #145

**Comment by trekiteasy** [comment]
Same here on my own build... no error is shown in dev mode, and the download page is displayed correctly in dev mode.

**Comment by nukeop** [comment]
Can't reproduce. Whatever it was, it's likely already been fixed.
