### ISSUE TITLE
I need the Nuclear Music Android app Please.

### ISSUE THREAD

**Issue by MagdyElshafey** [nukeop/nuclear#1614]
**Platform:**

**Nuclear version:**

**Description of the issue:**
I need the Nuclear Music Android app Please.

**Comment by nukeop** [comment]
There is no android app. Anyone saying otherwise is trying to scam you.

**Comment by MagdyElshafey** [comment]
I know that very well, But I advise you and ask you to create an Android mobile app for Nuclear Music app, Please.
   On Monday, June 3, 2024 at 09:47:38 AM GMT+3, nukeop ***@***.***> wrote:  
 
 


There is no android app. Anyone saying otherwise is trying to scam you.

**Comment by rockrevenchy** [comment]
> I know that very well, But I advise you and ask you to create an Android mobile app for Nuclear Music app, Please. On Monday, June 3, 2024 at 09:47:38 AM GMT+3, nukeop ***@***.***> wrote: There is no android app. Anyone saying otherwise is trying to scam you. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

"advice you"
I mean i'd love to see an android version too but this just sounds ominous for no reasons lmao

**Comment by nukeop** [comment]
Don't worry, I understand that English is not everybody's first language 😄

**Comment by MagdyElshafey** [comment]
I can understand clearly, I'm Like you too, I'm Egyptian and English is not my first language but I Love practicing the language with everyone when I have the opportunity for that. 
    On Wednesday, June 19, 2024 at 07:46:05 PM GMT+3, nukeop ***@***.***> wrote:  
 
 


Don't worry, I understand that English is not everybody's first language 😄

**Comment by MagdyElshafey** [comment]
What is that?

    On Sunday, July 14, 2024 at 10:29:59 PM GMT+3, nukeop ***@***.***> wrote:  
 
 


Closed #1614 as completed.

**Comment by nukeop** [comment]
I closed that as not planned.
