### ISSUE TITLE
Uncontrolled middle click behavior.

### ISSUE THREAD

**Issue by CarlosBor** [nukeop/nuclear#1619]
**Platform:** Windows

**Nuclear version:** 0.6.30

**Description of the issue:**
When using the middle mouse button to click on left sidebar elements a blank window is opened:
![image](https://github.com/nukeop/nuclear/assets/48533334/e3a1338e-b2aa-406e-9972-058ec4e4dd20)
When clicking history buttons, it actually opens a new instance of nuclear, which window controls (close, maximize, minimize) actually take effect on the original window

I'm not aware of any present functionality pressing the middle mouse button has on the app, perhaps capturing every instance of that action and ignoring it or treating it as a left-click would be an easy fix?

**Comment by nukeop** [comment]
Also reproduces on Mac. I guess this is because it's trying to open the URL in a new tab by default or something. It should be pretty easy to just disable this altogether.

**Comment by sean-mongey** [comment]
Hi Carlos. I was wondering if I could take a look at solving this

**Comment by CarlosBor** [comment]
As far as I am concerned, sure thing, I'm not currently working on it or anything.

I don't get to assign contributors but I'm sure you'll have no problem.

**Comment by nukeop** [comment]
This can likely be easily solved by using the `auxclick` event. You can assign a click handler with `preventDefault` to it: https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event
