### ISSUE TITLE
arm64 version

### ISSUE THREAD

**Issue by svitakj** [nukeop/nuclear#1621]
It is curious, why you have not native arm64 version. It is possible to make one in 2024?

**Comment by nukeop** [comment]
I'd rather make a universal binary instead. I already tried doing it on a branch, I think it could be available for the next release.

**Comment by svitakj** [comment]
It's a handy tool, it's just a pity that it's still under Rosetta. I look forward to it. Thank you for your efforts.

**Comment by nukeop** [comment]
I found that it'll be easier to make an arm64 and x64 versions instead, so that's how it's gonna be. The next build will contain both, so I guess this can be closed now.
