### ISSUE TITLE
all song don't want load

### ISSUE THREAD

**Issue by lofag892** [nukeop/nuclear#1627]
**pc**

**Nuclear version:last**

i want listen a song but this thing comming i don't undersand why

![Capture d’écran 2024-07-09 181622](https://github.com/nukeop/nuclear/assets/175142824/d08a76c0-14aa-4bbe-b3a7-50e4148b9a40)

**Comment by nukeop** [comment]
Hi, this looks like a problem with oyur network. Make sure you're not using any VPNs, proxies, etc.
