### ISSUE TITLE
Nuclear music no me reproduce ninguna cancion

### ISSUE THREAD

**Issue by saminnie92** [nukeop/nuclear#1630]
**Platform:** Nuclear Music 

**Nuclear version:**
Nuclear Music 0.6.30

**Description of the issue:**
Buenas tardes Nuclear Music no me reproduce ninguna cancion no se si tengo que configurar algo previamente.

**Comment by nukeop** [comment]
Hi, please use English when opening issues.

**Comment by saminnie92** [comment]
Platform: Nuclear Music

Nuclear version:
Nuclear Music 0.6.30

Description of the issue:
Good afternoon Nuclear Music does not play any songs for me, I don't know if I have to configure something beforehand.

**Comment by nukeop** [comment]
See #1629
