### ISSUE TITLE
No se reproduce ningún audio

### ISSUE THREAD

**Issue by Chumi97** [nukeop/nuclear#1634]
Hola
Me acabo de descargar NUCLEAR 0.6.30 y no se reproduce ningún audio.
He importado alguna lista de reproducción desde SPOTIFY y tampoco se oye nada.
Ayuda, por favor
**Platform:**

**Nuclear version:**

**Description of the issue:**

**Comment by nukeop** [comment]
Please use English

**Comment by Chumi97** [comment]
Hello
I just downloaded NUCLEAR 0.6.30 and no audio plays.
I have imported a playlist from SPOTIFY and I can't hear anything either.
Please help

**Comment by nukeop** [comment]
This is a duplicate of #1629. Next time when reporting bugs, don't ignore the fields in the template. They're there for a reason.
