### ISSUE TITLE
Allow snap "nuclear" to change "default-url-scheme-handler" subproperty "discord-1038970224050962582" to "nuclear_nuclear.desktop" ?

### ISSUE THREAD

**Issue by angelnolys** [nukeop/nuclear#1638]
**Platform:**

**Nuclear version:**

**Description of the issue:**

**Comment by angelnolys** [comment]
What this mean? My app stop working.

**Comment by nukeop** [comment]
Can you fill the fields in the template?

**Comment by angelnolys** [comment]
Yes, but went I try to play anything the app tries to verify and stop working.

**Comment by nukeop** [comment]
Yep we're tracking this in #1629
