### ISSUE TITLE
Installation via arm64 DMG fails on MacOS

### ISSUE THREAD

**Issue by rkben** [nukeop/nuclear#1643]
**Platform:**
macOS Sonoma 14.5, arm64

**Nuclear version:**
`v0.6.31-arm64`

**Description of the issue:**
Post install, attempting to run,
```
"nuclear.app" is damaged and can't be opened
 ...
```

**Comment by nukeop** [comment]
This is a bug on MacOS. Run `sudo xattr -r -d com.apple.quarantine /Applications/Nuclear.app` (or wherever the binary is) and it will be gone.

**Comment by LinuxForEveryone** [comment]
@nukeop 
I'm glad I stumbled across this, but most users won't. Is this bug going to be fixed?

**Comment by nukeop** [comment]
It's a bug on Apple's side, so I don't know. The instructions how to work around this can also be found here: https://nuclearplayer.com/downloads

**Comment by LinuxForEveryone** [comment]
Thanks for the reply and the link, much appreciated.
