### ISSUE TITLE
Error at the end of downloads

### ISSUE THREAD

**Issue by PiliJ** [nukeop/nuclear#1648]
Win 11 23H2

**Nuclear version:** 0.6.31.0

**Description of the issue:**
At the end of downloads, I receive an error popup like this: :

![2024-07-19 19 45 27](https://github.com/user-attachments/assets/7ce0a809-118b-4145-9314-bde837463abc)

Thank you !

**Comment by nukeop** [comment]
Is it happening after every download, or just some of them? If so, which ones?

**Comment by PiliJ** [comment]
Hi,

After each download !

**Comment by nukeop** [comment]
This version introduces transcoding to mp3 at the end of the downloads, and it looks like it can't find ffmpeg.

**Comment by PiliJ** [comment]
OK !... ffmpeg is located in various places on the PC (included in other programs obviously).
Should I do anything special?

**Comment by nukeop** [comment]
No, ffmpeg is bundled with Nuclear, it's inside the .asar archive. If it doesn't work, then it's bundled wrong and needs to be fixed on our side.

**Comment by nukeop** [comment]
Ok, I fixed this, try release 0.6.36.
