### ISSUE TITLE
Error Javascript

### ISSUE THREAD

**Issue by patchunk** [nukeop/nuclear#1651]
**Platform:** windows 11

**Nuclear version:** 06,31

**Description of the issue:** each time i open Nuclear, I have the following screen on my desk : "a javascript error occured in the main process" - Uncaught exception. Error : Einval, invalid argument, mkdir. 
Then Nuclear opens, but when I listen songs,, it works, but I have a message in red colour : "failed to parse contents with data"
. Thanks for your answer.

**Comment by nukeop** [comment]
You and some other users have noticed this problem. Looks like Youtube is rolling out an experiment to some users, which is interfering with stream retrieval.

**Comment by rafabadger** [comment]
i Got this message too First time I install in this PC ..
windows 10

**Comment by nukeop** [comment]
I rolled out an upgrade to the youtube streaming module which should solve this.

**Comment by conrad79** [comment]
Hello, I also have this problem: when I play a song, it says "failde to parse contents whit data. An error has occoured when searching stram with Youtube; cannot read property 'stream' of..."
How can I fix it?
Thanks
