### ISSUE TITLE
Can`t download andl isten

### ISSUE THREAD

**Issue by Frosefrog** [nukeop/nuclear#1653]
**Platform:**

**Nuclear version:**

**Description of the issue:**
![image](https://github.com/user-attachments/assets/91e7c46a-7d8c-4edb-98f8-149ae14ab061)
can`t use and download

**Comment by x1nel** [comment]
Try disabling VPN. This solved the problem for me.

**Comment by nukeop** [comment]
A couple of people on Discord also had success with this method.

**Comment by MrWTSN** [comment]
j'ai exactement le même problème et je n'est pas de vpn actif . que faire ???

**Comment by devcomputer** [comment]
Cant listen or download to anything in nuclear anymore. I think alphabet needs more money.

**Comment by nukeop** [comment]
Are you using the newest version?

**Comment by devcomputer** [comment]
i used these two:
nuclear-v0.6.30.AppImage
nuclear-v0.6.31-x86_64.AppImage

to my suprise the deb package still works. ¯\_(ツ)_/¯

**Comment by nukeop** [comment]
These two are outdated. Get the newest one, where this issue is fixed.

**Comment by devcomputer** [comment]
thanks!

**Comment by Frosefrog** [comment]
Thanks
