### ISSUE TITLE
Mac binary is not signed

### ISSUE THREAD

**Issue by fulldecent** [nukeop/nuclear#1654]
**Platform:**

macOS with M1.

**Nuclear version:**

nuclear 0.6.31-arm64

**Description of the issue:**

On terminal you can see the app is not signed: **SEE `TeamIdentifier=not set`**

```sh
codesign -dv --verbose=4 nuclear.app 
Executable=/Users/williamentriken/Desktop/nuclear.app/Contents/MacOS/nuclear
Identifier=Electron
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=1953 flags=0x20002(adhoc,linker-signed) hashes=58+0 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=720896
Hash type=sha256 size=32
CandidateCDHash sha256=c757eadcbce1106f33e3c7f8c12b463f25d53c1f
CandidateCDHashFull sha256=c757eadcbce1106f33e3c7f8c12b463f25d53c1f1a45e9add3c43891ed81a5ad
Hash choices=sha256
CMSDigest=c757eadcbce1106f33e3c7f8c12b463f25d53c1f1a45e9add3c43891ed81a5ad
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=196608
Executable Segment flags=0x1
Page size=4096
CDHash=c757eadcbce1106f33e3c7f8c12b463f25d53c1f
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none

```

When opening the app you see

![Screenshot 2024-07-23 at 10 54 03](https://github.com/user-attachments/assets/a35cb9dc-3763-4c61-87fd-052bcd37a36e)

**Discussion**

This indicates the binary was not properly signed.

Here is documentation on how to fix this https://www.electron.build/code-signing.html

**Comment by nukeop** [comment]
Hey, I described how to override that restriction here: https://nuclear.js.org/downloads (click "If you have trouble running Nuclear")

I will close this as not planned, because signing requires paying the Apple Extortion Fee.
