### ISSUE TITLE
Proxy Options for Bypassing Censorship

### ISSUE THREAD

**Issue by mmm-eskandari** [nukeop/nuclear#1663]
**Description:**

In some regions, access to music streaming services and other online content may be restricted due to censorship. To improve accessibility and user experience, it would be beneficial to include proxy settings within the Nuclear music player. This would allow users to configure proxies directly in the app, enabling them to bypass regional restrictions and access content freely.

**Proposed Solution:**

- Add an option in the settings menu for users to enter proxy server details (e.g., IP address, port, username, password).
- Support for different types of proxies (HTTP, HTTPS, SOCKS5).
- An option to toggle the use of the system-wide proxy or a custom proxy.

**Use Cases:**

- Users in countries with strict internet censorship can access music services blocked in their region.
- Users concerned about privacy can route their connections through a secure proxy.

**Additional Context:**

- This feature would greatly benefit users in regions like Iran, China, etc., where internet censorship is prevalent.

There are older requests related to proxy support and censorship bypass that remain unresolved. Revisiting these could help provide a more comprehensive solution for users facing these issues.
Thank you for considering this feature request!

**Comment by nukeop** [comment]
As ChatGPT who generated this text noticed, there were earlier feature requests regarding proxying requests. In general, this is not within the scope of functionality that a music player should have, routing requests should be done on the level of the operating system, and as such this is not planned.
