### ISSUE TITLE
MPRIS does not work on Fedora with GNOME

### ISSUE THREAD

**Issue by yang-musa** [nukeop/nuclear#1666]
**Platform:**
Fedora 40, fully updated

**Nuclear version:**
0.6.36 installed from Flatpak

**Description of the issue:**
According to this feature request, Nuclear already has MPRIS support as of 2023: https://nuclear.featureupvote.com/suggestions/507538/mpris-support  However, music control keys do not work on Fedora with Gnome (but yes, they do work with all other audio apps).

**Comment by nukeop** [comment]
Nuclear registers itself as `org.mpris.MediaPlayer2.nuclear`, and I just found out that flatpak wants `org.mpris.MediaPlayer2.$FLATPAK_ID `, so I guess it'd be `org.mpris.MediaPlayer2.org.js.nuclear.Nuclear`.

For future reference: https://docs.flatpak.org/en/latest/sandbox-permissions.html#d-bus-access

Flatpak likes making things arbitrarily difficult

**Comment by nukeop** [comment]
Will be fixed in the next release.

**Comment by yang-musa** [comment]
Thanks for the fix, and a great app!
