### ISSUE TITLE
Uncaught error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Lucki** [nukeop/nuclear#1667]
**Platform:** Flatpak

**Nuclear version:** 0.6.36

**Description of the issue:** 
I found one album ~~only~~ with the iTunesMusic provider and added that album to my favorites.
I searched for another album and could only find that one on a different metadata provider.
Now I get `Uncaught error: Cannot read property 'length' of undefined` when I click on the first album in the favorite list.
The UI reloads itself, any playing music gets a short outage. The application doesn't crash completely though.

I think the important steps are:
1. Favorite an album using the iTunesMusic search, ~~maybe it's required that it isn't available on a different search provider~~
1. Switch the metadata provider
1. Try to access the favorite album by clicking the album icon in the favorite album list
1. Crash
1. Switch the search provider back to iTunesMusic
1. Try to access the same album again from the favorite album list
1. No crash
1. Repeat

In case you want to reproduce:
The album is "Welcome to War" by "Dex Arson".
~~Only~~ iTunesMusic finds it by "Welcome to War - EP"

**Comment by nukeop** [comment]
Thanks for reporting this. Are you able to attach your config? It should be in `~/.var/app/org.js.nuclear.Nuclear/config/nuclear/config.json` if you're using Flatpak.

Failing that, try `~/.config/nuclear/config.json`.

**Comment by Lucki** [comment]
[config.json](https://github.com/user-attachments/files/16617931/config.json)

**Comment by nukeop** [comment]
Thanks, this happens because Nuclear looks up the album data using the selected metadata provider. The album has a diferent ID in iTunes and Musicbrainz, so it can't look it up. But it's possible to simply use whatever is saved in the config withou making any extra requests, so I'm going to fix it this way.

**Comment by nukeop** [comment]
After a few more minutes, I realized that I already implemented what I said above years ago. The problem was that iTunes uses numbers as ids, and they weren't correctly compared to the albums saved in favorites, so I fixed that. In the next release this issue will be gone.

**Comment by Lucki** [comment]
Confirmed working now with 0.6.37
