### ISSUE TITLE
Lower part of characters are cut off in album titles

### ISSUE THREAD

**Issue by Lucki** [nukeop/nuclear#1670]
**Platform:** Flatpak

**Nuclear version:** 0.6.37

**Description of the issue:**

The letters g and p are cut off on the lower part in the album title seen in the screenshot:

![Bildschirmfoto vom 2024-08-15 20-17-45](https://github.com/user-attachments/assets/f9f26aee-26f7-4963-a7bc-84bc6e30be8f)

**Comment by nukeop** [comment]
I adjusted the CSS to fix this.

**Comment by nukeop** [comment]
Looks like I didn't understand you, and there was a similar bug affecting the player bar (showing what's playing now) - that was the one I fixed.

**Comment by u7630748** [comment]
I would like to fix this issue, thanks!

**Comment by nukeop** [comment]
Fixed by #1721
