### ISSUE TITLE
Spotify token expires while using the program

### ISSUE THREAD

**Issue by Lucki** [nukeop/nuclear#1674]
**Platform:** Flatpak

**Nuclear version:** 0.6.37

**Description of the issue:**

Keeping the program open for a longish time let the Spotify token expire.
As a result the metadata search isn't working anymore using this particular search provider.
A restart of the program is refreshing the token as a workaround.

In the console I can see a 401 returned:

<details>
<summary>Screenshot</summary>

![grafik](https://github.com/user-attachments/assets/ceb0b6b2-0eda-4b04-be2a-575108ca68f5)

</details>

The network tab shows the reason:
~~~ json
{
    "status": 401,
    "message": "The access token expired"
}
~~~

Bonus bug:

The failure state isn't handled and the spinner is spinning forever in the search entry.

<details>
<summary>Details</summary>

![grafik](https://github.com/user-attachments/assets/e85193e0-89ca-4a67-a5d3-bbca03b610c7)

</details>

**Comment by nukeop** [comment]
Fixed with https://github.com/nukeop/nuclear/commit/50248eb4a3578fb452a024d1a6829cb5e68444af

Thanks for reporting.
