### ISSUE TITLE
Move the "remove" button further away from the "play" button

### ISSUE THREAD

**Issue by Lucki** [nukeop/nuclear#1675]
Context: 
Lists containing tracks by the user can remove a list item with the (X) button.

![grafik](https://github.com/user-attachments/assets/9bfb95d8-a8d5-4ecd-be85-87e3eab38b77)

The remove button (X) seems a bit too close to the play button for my(!) liking. A small overshoot with the mouse or a fat finger on a touchscreen can easily trigger an unwanted action, particular because the is no "are you sure"-dialog.

Possible improvements:
* Interchange the "select"-column with the "delete"-column in lists, so that the remove action is nowhere near any different possible action anymore
* Move the remove action into the context menu

**Comment by Anonymous-hss** [comment]
Hey @Lucki I have understood the issue and can you assign me this issue ?

**Comment by nukeop** [comment]
We don't assign issues.

**Comment by Anonymous-hss** [comment]
Okay I will make the necessary changes and once it is done I will let you know

**Comment by angelbaezsa** [comment]
Has the issue been resolved?

**Comment by nukeop** [comment]
I think it's still up for grabs.

**Comment by u7630748** [comment]
Hello! I'm a computer science student and interested in contributing to this project. This issue looks like a good starting point for me. I'll create a pull request soon.

**Comment by nukeop** [comment]
Fixed by #1717
