### ISSUE TITLE
New Spotify playlist import fails (Cannot read property 'name' of null)

### ISSUE THREAD

**Issue by Lucki** [nukeop/nuclear#1679]
**Platform:** Flatpak

**Nuclear version:** 0.6.38

**Description of the issue:**

I tested the new Spotify playlist importer and it fails for a playlist which worked before the new importer was released.
In the network tab I can see that all request are made correctly to API and all tracks info is properly fetched.
I see an album image being fetched as the last request.
However, the rotating thing stops and I'm back at the initial playlist overview page.
In the lower right a red warning appears with "Cannot read property 'name' of null".

Playlist to reproduce: https://open.spotify.com/playlist/0h3RKHIfeXmXa0FsT1PZ1g

Console output:
![grafik](https://github.com/user-attachments/assets/f3dc46f2-e7a2-4821-b6ab-6fb50203c6b7)

<details>
<summary>Screencap</summary>

[Bildschirmaufzeichnung vom 2024-08-19 18-40-11.webm](https://github.com/user-attachments/assets/85acfafa-8777-495b-a618-13db31082c04)

</details>

**Comment by nukeop** [comment]
This playlist has over 3600 tracks. Try dividing it into smaller pieces.

**Comment by Lucki** [comment]
This isn't mine - I can't divide it.
It worked with the previous version of the Spotify importer and the fact that the fetching happens correctly lets me believe the count of tracks itself is not the issue with the new importer version.

**Comment by nukeop** [comment]
Even if you manage to import it, the playlist view is not going to be able to handle it fluidly.

**Comment by nukeop** [comment]
The playlist contains a podcast: https://open.spotify.com/episode/6kr6DwNhUZahu5DWNEUuH4 which does not have an artist, so it results in an invalid track.
