### ISSUE TITLE
Songs from albums without a picture show broken image icon

### ISSUE THREAD

**Issue by Lucki** [nukeop/nuclear#1684]
**Platform:** Flatpak

**Nuclear version:** 0.6.38

**Description of the issue:**

Songs from an album without an image display a broken image icon on various places.
I would expect the same fallback image from the album being used as the song image.

<details>
<summary>Steps to reproduce</summary>

1. Album example without an image: "Midnight Club II" from MusicBrainz
  ![image](https://github.com/user-attachments/assets/a593a23f-9703-470f-92fd-c1ba6fb5ce00)
1. Add a song from the list as favorite and/or add it to the queue
  ![image](https://github.com/user-attachments/assets/b23bc5ed-4c9a-4de4-bb2a-9653d2966c89)
    * See the broken image in your list of favorite songs
      ![image](https://github.com/user-attachments/assets/dde3219a-08c5-4f2e-b2e3-59fde4a473b9)
    * See the broken image in your queue
      ![image](https://github.com/user-attachments/assets/3eaa871d-765b-4e43-aee2-2a78193cce1d)
    * As well as the currently playing song
      ![image](https://github.com/user-attachments/assets/21ccafcd-77f6-491c-a09c-630ebd5c859a)
    * And the miniplayer
      ![image](https://github.com/user-attachments/assets/3d886bc5-30fd-4a25-ba33-95bd061d29f2)

</details>

**Comment by KartikChinda** [comment]
Hi @Lucki I'd love to work on this. However, I've not worked with electron before so it might take me a while to get through this. 
If that's okay, please assign this issue to me.

**Comment by nukeop** [comment]
We don't assign issues, you're welcome to start working and submit a PR any time.
