### ISSUE TITLE
Problème de connection

### ISSUE THREAD

**Issue by Lebaron2** [nukeop/nuclear#1690]
Windows11

Version Nuclear : 0.6.38 x64

Le lecteur ne joue pas. La flèche tourne et es morceaux commencent à charger une fraction de seconde, puis plus rien. Y a t-il un paramètre à changer ? Je comprend d'autant moins bien que tout fonctionnait très bien avant. Merci de votre réponse.

**Comment by nukeop** [comment]
Hi, please use english when communicating anywhere in the repo
