### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by Lebaron2** [nukeop/nuclear#1691]
Win11

0.6.38 x65

Hello,
Unable to play a piece of music. The arrow rotates and the music seems to play for a split second, then nothing more. 
Is there a setting to be made, or is there a problem? Thank you for your answer.

**Comment by Lebaron2** [comment]
Win11

0.6.38 ext. 65

Hello,
Unable to play a piece of music. The arrow spins and the music seems to play for a split second, then nothing.
Is there an adjustment to be made, or is there a problem? Thank you for your answer

**Comment by nukeop** [comment]
Try the new version.
