### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Lebaron2** [nukeop/nuclear#1695]
Win11

0.60.38 x64

No download of music. When i click on a track, Nuclear is searching, the arrow is turning a few seconds, stop, and nothing happens.
I don't understand, because this problem happens suddenly, I reinstall the program, but nothing change.

**Comment by Lebaron2** [comment]
Text is transated automatically in french. Why ?

**Comment by nukeop** [comment]
Hi, there are currently no known persistent issues regarding playback. When troubleshooting make sure that:

- You have a stable internet connection
- Any VPN or proxy is turned off
- Nuclear has access to the internet
- Sound is not muted at the system level
- If you're using a firewall or antivirus software, ensure it's not blocking Nuclear from accessing the internet

**Comment by Lebaron2** [comment]
Thanks😉Le 8 sept. 2024 à 21:37, nukeop ***@***.***> a écrit :﻿
Hi, there are currently no known persistent issues regarding playback. When troubleshooting make sure that:

You have a stable internet connection
Any VPN or proxy is turned off
Nuclear has access to the internet
Sound is not muted at the system level
If you're using a firewall or antivirus software, ensure it's not blocking Nuclear from accessing the internet
