### ISSUE TITLE
Difficulty using volume slider

### ISSUE THREAD

**Issue by vilanz** [nukeop/nuclear#170]
The clickable zone's way too small, which makes changing the volume almost irritating.

**Comment by nukeop** [comment]
https://codesandbox.io/s/JqRpW8Mw2

Would something like this be better?
I swear, npm is making me lazier and lazier, there's a package for everything.

**Comment by vilanz** [comment]
Looks great! It ain't no cargo cult, just a control that fits the specific use case.

**Comment by nukeop** [comment]
Ok, I can try to replace the current slider with this then.

**Comment by Chandankkrr** [comment]
Hi @nukeop, I would be interested and can help out with the slider enhancement.

**Comment by nukeop** [comment]
Nice, you can try integrating this: https://www.npmjs.com/package/react-range-progress

Try to stay as close to existing css as possible.

**Comment by Chandankkrr** [comment]
Hi @nukeop, I have implemented `react-range-progress` component for the `volume_slider` (see the screenshot below). I have kept the original height for the slider and used the `pink` colour (similar to the progress bar) for the thumb.

<img width="213" alt="volume_slider_improvement" src="https://user-images.githubusercontent.com/5574015/51835337-3e890100-2351-11e9-9213-e43ea42da441.png">

How does it look?

**Comment by nukeop** [comment]
Looks pretty great, is that the pink from the palette? I think it would look better white anyway. Good work, start a pull request when you're ready.

**Comment by Chandankkrr** [comment]
Hey @nukeop, I'm ready to do a PR but I'm getting a 403 permission denied. Could you please check? Thanks

**Comment by nukeop** [comment]
What's giving you that error?

**Comment by Chandankkrr** [comment]
@nukeop All good, I had some issues with my Git Credentials. Here is the link to my PR (https://github.com/nukeop/nuclear/pull/218)
