### ISSUE TITLE
NUCLEAR CANT PLAY MUSIC ANYMORE

### ISSUE THREAD

**Issue by txrez98** [nukeop/nuclear#1700]
**Platform:**
WINDOWS

**Nuclear version:**
v0.6.30

**Description of the issue:**
IT CANT MUSIC ANYMORE.. THE SEARCH RESULT IS FINE, ITS FINDING ALL THE MUSIC I SEARCH, BUT I CANT PLAY IT, CANT DOWNLOAD IT

**Comment by waldo121** [comment]
I experienced this using the nixos packaged app too. Both versions 0.6.30 and 0.6.31 did stop working.

**Comment by nukeop** [comment]
That's because version 0.6.30 is severely outdated. Get the newest one.
