### ISSUE TITLE
Service for sharing playlists

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#172]
Playlists are currently 100% local, but maybe something like Spotify's playlists service could be popular. In addition it could provide a way to export the playlists and convert them to a number of formats. Services like Spotify are designed to trap you forever, so they intentionally do not provide any way of exporting your data.

This could be a separate project, which would run as its own microservice on some provider's servers (preferably stateless in Docker). Proposed features:

* Thin user accounts (to allow for persistent playlist storage, following, searching, etc)
* Account needed for saving playlists on the server (to prevent spam, etc)
* Default playlist format: JSON
* Allow exporting to other popular formats
* Integration with Nuclear in a way that allows read access without an account, and local storing of downloaded playlists

Suggestions?

**Comment by 1yzo** [comment]
I'm down to help out with this.

**Comment by yourWaifu** [comment]
This is great but I don't wan to make a new account, can I store this info on my own file server or cloud service like google drive or one drive and have the app integrate with these and allow me to be the one handling this.

**Comment by nukeop** [comment]
I intend for this to integrate with Github accounts (and maybe others)
