### ISSUE TITLE
docker version?

### ISSUE THREAD

**Issue by stkac** [nukeop/nuclear#173]
# someone know how make nuclear run using docker?
## I mean using PM2 Entrypoint

thanks in advance,

**Comment by nukeop** [comment]
I'll add this to the backlog, build&run process is well documented and pretty simple so this shouldn't be too much of a problem.

**Comment by gabriel376** [comment]
Hi,

I would like to take this one.
This is a simple testing I created to allow build and run Nuclear inside a Docker container:

Dockerfile:
```
FROM node

RUN apt-get update && apt-get install -y libnss3 libgtk-3-0 libx11-xcb1 libxss1 libasound2

WORKDIR /opt
RUN git clone https://github.com/nukeop/nuclear

WORKDIR /opt/nuclear
RUN npm install && npm run build:dist

CMD ["npm", "run", "electron:prod"]
```

To build the image:
`docker build -t nuclear .`

To run the image:
`docker run --rm --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --device /dev/snd nuclear`

(I am running Ubuntu 18.04 bionic)

Would be great if we can have dockerfiles for building and running Nuclear, for DEV and PROD. We can publish it to https://hub.docker.com too. The dockerfile is cloning the repository but another option is to share the source directory from host to container using volumes.

Any suggestions or tips ?

**Comment by nukeop** [comment]
hm, since we'll likely host this dockerfile inside this repo (preferably at the root level), the git clone step can be omitted.

If you'd like, feel free to make a pull request with production/development images, and if you want you can host the images yourself on Docker hub, then add yourself to th readme in the third party packages table.

**Comment by nukeop** [comment]
Btw, after `npm install`, `npm run build:dist` and `npm run build:electron` we can delete everything on the dev dependencies list to reduce the size of the image. Actually I'd try to approach this from another angle, build the scripts locally first and then the dockerfile can just copy the built binaries. Then, there's no need to even install the dev dependencies in the first place.

**Comment by gabriel376** [comment]
I will do that, thanks!
