### ISSUE TITLE
v0.6.40 - VirusTotal gives 1 malware as result - Bkav Pro > W32.AIDetectMalware

### ISSUE THREAD

**Issue by boly38** [nukeop/nuclear#1742]
**Platform:**
W32 Windows 10Entreprise

**Nuclear version:**
v0.6.40 - download from github release assets

**Description of the issue:**
HowTo reproduce
- download `nuclear-v0.6.40-x64.exe` (from [0.6.40 release assets](https://github.com/nukeop/nuclear/releases/tag/v0.6.40))
- put it on https://www.virustotal.com/
- it gives 1 malware as result :(
>Bkav Pro - W32.AIDetectMalware

![image](https://github.com/user-attachments/assets/a92734b4-45de-4b4e-9856-38e7d2c27564)

I really want to test this app so please make him passing all virus-related test green.
(probably `Bkav Pro` is too much sensitive (seen on [reddit](https://www.reddit.com/r/antivirus/comments/16uuun2/questions_about_w32aidetectmalware64/?tl=fr)) and this may be a false positive, but we need to be sure and clearly document this in that case)
Regard 🙏

**Comment by nukeop** [comment]
It's wrong. Nuclear is open source, there's nowhere to hide any malware in it. Your antivirus is a black box and there's no way to tell why it's doing that.

**Comment by boly38** [comment]
(same ticket here : https://github.com/Cubitect/cubiomes-viewer/issues/262)
