### ISSUE TITLE
Discord Server and Channel for help

### ISSUE THREAD

**Issue by syedalisait** [nukeop/nuclear#181]
Hey guys - I recently downloaded nuclear and wasn't able to play anything. When I searched, all I found was "nothing". Also wasn't able to play anything from the dashboard.

So i thought a Discord Server/Channel would be of help for people who are downloading and using the pre-release version

**Comment by nukeop** [comment]
I'd prefer a matrix.org group for this, since I don't use Discord and it's a proprietary system with many non-free components required to use it.

**Comment by mknepper** [comment]
+1 for matrix.

**Comment by nukeop** [comment]
Ok, I was able to use the address `#nuclear:matrix.org `.

**Comment by syedalisait** [comment]
Just checked the Overview page of Matrix. Looks cool. I said discord because the only means of communication I have seen people using is Slack or Discord. Matrix is new to me and I'm absolutely fine with Matrix too.

There needs to be some sort of Help Channel for people who are trying to use/code nuclear. That's the intention for creating this issue.

**Comment by nukeop** [comment]
Ok, I changed the settings to allow anyone in (except guests to limit spam).

**Comment by mknepper** [comment]
I'd also recommend IRC. I think you can use IRC in conjunction with Matrix, though I could be wrong.

**Comment by mknepper** [comment]
There's also Tox, which seems more active. Still free and open-source, GPL v3. There are more desktop clients for it, as well. Just a suggestion.

**Comment by syedalisait** [comment]
Since #nuclear:matrix.org was created, i'm closing this out.

**Comment by Korb** [comment]
https://discord.gg/JqPjKxE at https://nuclear.js.org:

> Whoops...
> Unable to accept invitation
> 148 online
> 1,083 members

Link not available. Mozilla Firefox 105.0b2 (64-bit), Discord PTB 1.0.1017 x86, Microsoft Windows 10.0.19043.1889.

**Comment by nukeop** [comment]
You sure about that? That link is still active and being used everyday as far as I can tell

**Comment by Korb** [comment]
> You sure about that? That link is still active and being used everyday as far as I can tell

![2022-08-24_15-10-38](https://user-images.githubusercontent.com/3509797/186414975-c437a8ff-0c2e-46bf-9707-aa26408e1c9f.png)

**Comment by Korb** [comment]
> This could mean you were banned

However, I was able to join the community through the link provided in the README.md.
