### ISSUE TITLE
Command palette a la Emacs, Atom or VS Code

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#185]
Step 1: Define all possible user actions as commands. Rewrite the interface so that clicking elements invokes those commands. Each command needs an identifier, a name, and a description.
Step 2: Allow opening a command palette, that lets users search for commands, like M-x in Emacs. Picking a command from there is an alternative to choosing it via clicking.

Result: A great interface for programmers and non-programmers alike.

Optional step 3: Allow users to define their own keyboard shortcuts by using a text config file that binds commands to key combos or sequences.

**Comment by vilanz** [comment]
This woukd be great! Any progress?

**Comment by nukeop** [comment]
Not yet, working on the downloads feature now. For now this is in the proposal stage, to gather feedback and as a reminder to myself.

**Comment by heckeop** [comment]
Consider looking at [Reaper](https://www.reaper.fm/). It has a UI system similar in spirit to what you describe (programmable actions). Details are in the user guide.
