### ISSUE TITLE
UX is very inconsistent

### ISSUE THREAD

**Issue by vilanz** [nukeop/nuclear#187]
I'll begin with a Hacker News comment from https://news.ycombinator.com/item?id=18921296. I know the community on that site isn't exactly the most welcoming, especially for Electron projects, but this post rings true with me.

> This looks great conceptually but the UX on my first run through was awful.
The prominent "Best new music" part had an Earl Sweatshirt album review, so I wanted to listen to it, but you can't click the album title... only the artist name. Then I had to sift through 30+ album covers (no titles... not ordered by release date) to find the one that looked like the one I saw on the previous page (it had a slightly different cover).
You'd think a "new" album would be at the top.
Then I double clicked the first song twice, then realize there is a popup that has a "Play Now" button on a SINGLE click (unlike Spotify or Google Music). I clicked that and it only added it to my "queue", I thought it was downloading for a couple min, but nope I had to click "Play" at the bottom to actually start it.
I went to another album, clicked "Play Now" on a song and it froze with the logo pulsing fullscreen, and I had to restart the app.
This is basic stuff. 

It's just like my first experiences with the app. I'll list a few of my pet peeves here:

* clicking the Play button doesn't do anything at times, you'll have to click and click and click to get it working
* the Playlist flow is very inconsistent IMO. Might be just me, though. I think this needs its own issue, because I haven't even quite figured out how to properly edit playlists for example
* the search results' view is.. weird. I don't know how to put it into words, but it should display more stuff
* I feel like I have to *guess* what stuff does

These are personal opinions (as all UX is) for a **pre-alpha** project, but with the sudden burst of popularity many users' (and potential contributors') opinions may be similar. I don't know if you even expected this to blow up @nukeop, so the more future helping hands the merrier I guess!

**Comment by mknepper** [comment]
Once I get the presskit done for you, I might be able to assist. UI is mainly CSS/HTML stuff, right?

**Comment by nukeop** [comment]
It's React, so there's more to it than that, but the code is easy to understand and very modular, so the bar to entry is low.

**Comment by trekiteasy** [comment]
Just to break up @vilanz points in separates issues : 
- Best New Albums : "you can't click the album title" => #192 
- Standard behavior for playing tracks / adding tracks => #157 
- Freezing on "Play" => #145 
- Playlist management => #158 
- Search result view => is mentioned in #171 

I think everything is already mentioned in other issues, so I think we should close this one.

**Comment by nukeop** [comment]
Great, thanks for settling this.

**Comment by paperbenni** [comment]
I agree that a lot of people have too high expectations. But I don't think that the reason is the UI. In the readme it says that it's "Spotify but with a bigger library", suggesting that it is a music player that unites the libraries of multiple free and legal services, freeing you from having to choose between different incomplete collections of songs or hop between different services. Freeing you from manipulative algorithms. I think that's what drove most people's attention and it certainly doesn't hold up to that standard at all. It shouldn't have to, but it also shouldn't have such a readme.

**Comment by nukeop** [comment]
It's a sales tactic, advertise and sell features you don't have yet but plan to.
