### ISSUE TITLE
Tag view page - click on album not working

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#191]
In the Tag View page (ex : #rock), when I click on an album, nothing happens. I'm expecting to have an album view page opening here.

**Comment by PaliwalSparsh** [comment]
@trekiteasy Can I pick this up?

**Comment by PaliwalSparsh** [comment]
Got it. I am working on the PR will share it soon :)

**Comment by PaliwalSparsh** [comment]
Hi, I have created the PR. Please, can you review [#204](https://github.com/nukeop/nuclear/pull/204).
