### ISSUE TITLE
Dashboard > Best new Music > Best new albums - Not to possible click on the album

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#192]
I would expect to be able to open an album view from the dashboard when I click on a new album

**Comment by nukeop** [comment]
For many new albums Discogs won't have their data yet. Same goes for #193

**Comment by trekiteasy** [comment]
Ok... I understand. 
Maybe it is something we can at least try to fetch, give the possibility to open the album / track if found ?
Otherwise, I strongly believe this "Best new album" / "Best new tracks" sections are worse than having nothing ; it generates frustration for me.
If no solution is found, I'd advise to put some lastfm charts of some other charts as a first tab.

**Comment by nukeop** [comment]
Best we can do is open the search page with the album/track filled in. Anyway the best new music page needs to be reworked slightly in terms of alignment, i never liked how it scales when there's a lot of text and could be more useful.

**Comment by trekiteasy** [comment]
We lost this in the dashboard revamp...

**Comment by nukeop** [comment]
Yeah, I'm aware. I'll be restoring this soon.
