### ISSUE TITLE
Dashboard > Best new Music > Best new tracks - No possibility to play or add the track

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#193]
I would expect to be able to easily play / add the track to the queue

**Comment by trekiteasy** [comment]
This is now possible in dev version.

**Comment by trekiteasy** [comment]
We lost this in the revamp of the dashboard...

**Comment by sgraczyk** [comment]
Hi, I decided to dig into this issue as my first one. I managed to implement it although I'm a little bit worried about the UI/UX aspect of my solution. I've found that currently the possibility to play a track or add it to the queue is performed using a popup/tooltip. I used the same mechanism but I believe it looks a little bit odd. I've attached a screenshot as an example.

![image](https://user-images.githubusercontent.com/8076673/58103073-a1ddbe00-7be2-11e9-9006-4d47124bf3f7.png)

I'm open to different ideas regarding this issue, maybe I've missed a different way to add track (in UI/UX manner).

**Comment by nukeop** [comment]
I think a better way to do this would be to add an empty star icon next to the track title, clicking it adds it to favorites. If it's already there, the button is replaced by a filled star and clicking it lets you remove it.
Maybe instead of using a popup you could add the same buttons under the review header? This way they're easy to find and obvious.

**Comment by sgraczyk** [comment]
Ok, I just wanted to make sure if that popup was some kind of standard in the application. I'll add the buttons under the review header then. Will consider the star idea also.

**Comment by sgraczyk** [comment]
Hi, I'm back with some spare time so I can finish this task. I've just managed to resolve conflicts so it shouldn't take me long to provide a version to review.

Hope that's fine and no other similar work is in progress ;)

**Comment by nukeop** [comment]
Hey, very nice. Nobody else picked up this one so your work is still very much appreciated.

**Comment by DRob1260** [comment]
I'd like to take a crack at this. I thought a good solution might be to update the `Dashboard/BestNewMusicTab/BestNewMusicContent` component to have a similar design to the top portion (see screenshot) of the `AlbumView` component. Thoughts?

<img width="1067" alt="Screen Shot 2020-08-02 at 8 39 26 AM" src="https://user-images.githubusercontent.com/19953794/89124559-a156dd80-d49d-11ea-95ea-226f083f2ed5.png">

**Comment by nukeop** [comment]
Sounds nice, how would you switch between the different albums and tracks?

**Comment by DRob1260** [comment]
I think `BestNewMusicMenu` could stay the same, so switching between the albums or tracks would still be handled through that.  The main goal here would be to have the buttons below included in the `BestNewMusicContent` component, to allow for playing an album or a track. 

<img width="214" alt="Screen Shot 2020-08-02 at 11 50 11 AM" src="https://user-images.githubusercontent.com/19953794/89127814-572e2600-d4b6-11ea-9a65-95256a29d392.png">

**Comment by nukeop** [comment]
That sounds nice but involves a few more steps. We don't have the track lists available on this screen yet, we'd have to download them in the background from somewhere.
