### ISSUE TITLE
Add ability to click on artist name in the down-left corner

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#194]
It would be nice to be able to click on the artist name on the low left corner to open the artist page (especially with the "flow / autoradio" feature, it is a nice way to discover new artists)

**Comment by aayushchhabra** [comment]
@trekiteasy I'd like to pick this up ...

**Comment by aayushchhabra** [comment]
@nukeop cool, I'll check it out ...

**Comment by trekiteasy** [comment]
I seems this one can be closed now.
