### ISSUE TITLE
Dashboard > Search > Artist > Album > Play doesn't start playing music until you double click play

### ISSUE THREAD

**Issue by ivyjsgit** [nukeop/nuclear#195]
Whenever you try to play an album via an artist's page, you must first click the pause button twice in order to begin playing music. 

Steps to reproduce:
1. Search for an artist
2. Select an album from the artist's page
3. Click "Play"
Expected result:
Album artwork and song info appears in the bottom left and the album starts playing.
Actual result: 
Album artwork and song info appears, but there is a pause button when there is no music playing. In order to start to playback of music, you have to click the play button in the controls twice.

**Comment by nukeop** [comment]
Not sure, the other is a complete crash.

**Comment by PandaTR** [comment]
Thanks 👍 

Shown on My site 

[https://www.pandamedya.com.tr/](Web Tasarım)

**Comment by trekiteasy** [comment]
This is in SoundContainer / index.js : 
```
streamUrl = (getSelectedStream(currentSong.streams, plugins.defaultMusicSource) || {}).stream;
```
When `currentSong.loading` is `true` then `currentSong.streams` is `undefined`. 
I'm not sure how we shoudl deal with it : if the song is loading, we should wait a bit for the loading and try again after that or have a kind of listener on the song loading porcess.

**Comment by ghostslayer989** [comment]
Same issue on Linux Mint 19.1 (Ubuntu 18.04).

**Comment by trekiteasy** [comment]
For me this is a big "no go" for new users / contributors as it is one of the first feature a user will try.
I don't know how to fix it, but would prioritize it quite high.

**Comment by trekiteasy** [comment]
This is now fixed in dev version, thanks to @charjac
