### ISSUE TITLE
Search does not work if the search bar is already filled

### ISSUE THREAD

**Issue by ivyjsgit** [nukeop/nuclear#196]
Steps to reproduce:
1. Search an album or artist or something. Press enter
2. Click off of the search view into another view.
3. Click search bar again
4. Press enter without clearing the search bar.
Expected behavior:
The search page for whatever query the user entered is brought back up
Actual result: 
Nothing happens.

**Comment by nukeop** [comment]
Yeah, pressing enter does nothing by design, search happens when you don't type for a few seconds. To go back to search results you have to select it from the lefthand menu, since there's no point in searching for the same thing twice.
