### ISSUE TITLE
Under Home>Genres, you can't directly play a song

### ISSUE THREAD

**Issue by ivyjsgit** [nukeop/nuclear#200]
Steps to reproduce:
1. Go to dashboard
2. Click Genres
3. Click a Genre
4. Click a song from the list.
Expected result:
Should display "Play song"
Actual result:
Only displays "add to queue"

**Comment by WalkerFrederick** [comment]
Can we close this issue? @nukeop

**Comment by nukeop** [comment]
Sure, i thought it'd close automatically.
