### ISSUE TITLE
Missing Font MavenPro?

### ISSUE THREAD

**Issue by uliska** [nukeop/nuclear#21]
I cloned the repository, installed through `sudo npm install` (see https://github.com/nukeop/nuclear/pull/20) and launched the app with `npm run dev` as suggested by the README.md

However, I was receiving a somewhat "empty" window:

![bildschirmfoto vom 2017-02-24 17-13-42](https://cloud.githubusercontent.com/assets/1812148/23310969/acb3b39a-fab4-11e6-8a91-09bd99452d77.png)

The error message indicates a missing font:

```
ERROR in ./~/css-loader?sourceMap!./app/app.global.css
Module not found: Error: Cannot resolve 'file' or 'directory'
../resources/external/fonts/MavenPro/font.css in /home/uliska/git/software/nuclear/app
 @ ./~/css-loader?sourceMap!./app/app.global.css 7:10-114
```

and indeed the folder `resources/external/fonts` only contains two entries for FrancoisOne and Questrial. This is consistent with the content of the folder in the repository, so I think *either* this is missing in the repo (not committed?) or a failure to fetch something externally during set-up/installation.

**Comment by g5codyswartz** [comment]
I'm on mac and experiencing this
