### ISSUE TITLE
Dev build of nuclear hangs; NPM warns about write-file-atomic and 'worker-threads'

### ISSUE THREAD

**Issue by mknepper** [nukeop/nuclear#212]
So when I try to build Nuclear using NPM, this happens:

`WARNING in ./node_modules/write-file-atomic/index.js`
`Module not found: Error: Can't resolve 'worker_threads' in '/media/mknepper/Storage/Home/Git/nuclear/node_modules/write-file-atomic'`
` @ ./node_modules/write-file-atomic/index.js`
` @ ./node_modules/conf/index.js`
`@ ./node_modules/electron-store/index.js`
` @ ./app/persistence/store.js`
 `@ ./app/actions/playlists.js`
` @ ./app/reducers/playlists.js`
 `@ ./app/reducers/index.js`
 `@ ./app/store/configureStore.js`
` @ ./app/index.js`
 `@ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./app/index.js`
`Child html-webpack-plugin for "index.html":`
  `   1 asset`
  ` Entrypoint undefined = index.html`
 `  [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 2.54 KiB {0} [built]`
  `  [./node_modules/lodash/lodash.js] 527 KiB {0} [built]`
 `   [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]`
`ℹ ｢wdm｣: Compiled with warnings.`

Once it gets to the `ℹ ｢wdm｣: Compiled with warnings.`, nothing happens - it just sits there, hanging. 

I followed the instructions on the README.md exactly, and still ran into this. Tried deleted the node_modules directory, making sure everything was up to do, building just for my OS, etc. Running Xubuntu 18.04.1 LTS. 

**Edit:** Node version is `v8.10.0` and npm is version `v3.5.2`.

**Comment by mknepper** [comment]
I upgraded npm to 6.7.0 and Node to 10.15.0. Same issue.

**Comment by jacekk** [comment]
Same here:

```
$ node --version && npm --version
v10.15.0
6.7.0
```

**Comment by nukeop** [comment]
If you're missing worker_threads, it's an issue with your node installation, since it's a built-in node module. Try nvm or https://www.npmjs.com/package/n.

**Comment by jacekk** [comment]
I believe I am using NVM :/

```
$ nvm ls
->     v10.15.0
         system
default -> 10 (-> v10.15.0)
node -> stable (-> v10.15.0) (default)
stable -> 10.15 (-> v10.15.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/dubnium (-> v10.15.0)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.16.0 (-> N/A)
lts/carbon -> v8.15.0 (-> N/A)
lts/dubnium -> v10.15.0
```

**Comment by charjac** [comment]
you node 11.7 in order to use worker_threads without using a flag.
https://medium.com/lazy-engineering/node-worker-threads-b57a32d84845

**Comment by nukeop** [comment]
I'm using 8.11 on my home PC, and it builds fine. Maybe try 8 instead of 10 for some reason?

**Comment by charjac** [comment]
we could add a .nvmrc at the root of the project.
```bash
node -v > .nvmrc
```

**Comment by jacekk** [comment]
Works great after `nvm install 11 && nvm use 11`. Linux build completed. Music is playing. Thx :)

**Comment by mknepper** [comment]
I'll add those into the README.

**Comment by nukeop** [comment]
We already have this, thanks to @trekiteasy :
https://github.com/nukeop/nuclear/wiki/Contributing

>Make sure you're using the latest version of Node and NPM.

**Comment by jacekk** [comment]
@nukeop IMHO, that is not specific enough.

Version **10** is the latest **LTS**. Travis is testing & building against node in version **8**. I've checked on my newer Mint distro (v19.1), and I had the same issue as before (on Mint v18.3). Builds are not passing on `8.15.0` or on `10.15.1`. Both distro were "saved" with NVM and switching to `11.9.0`. Not that obvious if someone does use default node version for his/her distro.

My biggest mindf**k right now; why everything passes in TravisCI with such a node version(?) :/

**Comment by nukeop** [comment]
Because that's what I originally developed for, and still develop for on both my development machines. So naturally that's what I set Travis to use.

**Comment by jacekk** [comment]
@nukeop So ... is the following sentence true or false?

> Make sure you're using the latest version of Node and NPM.

No, because **8** is NOT the **latest** version. Additionally, it is misleading, as **10** is the latest LTS version.

**Comment by nukeop** [comment]
Since Node is backwards compatible, having the latest version will not hurt, and there's no point in installing an older one (typically). Both 8 and 10 work and I imagine they'd work on Travis too, I'm gonna check that.

**Comment by nukeop** [comment]
https://travis-ci.org/nukeop/nuclear/jobs/493499632

Yes, works with 10 too.

**Comment by jacekk** [comment]
@nukeop Interesting "warning" -->  https://travis-ci.org/nukeop/nuclear/jobs/493499632#L893 :/

Additionally, the node 8 build also had such a zero-ended "warning" --> https://travis-ci.org/nukeop/nuclear/jobs/493209448#L560

Plus the `osx` build failed on node 10 --> https://travis-ci.org/nukeop/nuclear/jobs/493499631#L583 :/

Are you sure these builds are configured correctly?

**Comment by nukeop** [comment]
It fails on Mac due to a bug in electron-builder, I think it's a known issue there.

I just realized that the first post of this thread is actually invalid, it's supposed to "hang" after compiling, since now it watches the code for changes, and the code is being served from localhost:8080. It's a dev build, so it's configured for hot reloads.
