### ISSUE TITLE
Code deduplication

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#219]
This thread will be dedicated to finding and eliminating instances of needless code duplication. Anyone wanting to contribute something easy to do can either remove a duplication they find or submit one here for removal/refactoring.

**Comment by trekiteasy** [comment]
In most cases, I think we can come up with something similar... and this would remove a lot of duplicated code and simplify further maintenance on track actions. This is work in progress. Will submit pull request when ready.

**Comment by jonatascastro12** [comment]
I was thinking about using Wrapper and Factory pattern to handle TrackRow creation, as we have code duplication of TrackRow creation at:

app/components/PlaylistView/index.js
app/components/ArtistView/PopularTracks/index.js
app/components/AlbumView/index.js
app/components/SearchResults/TracksResults/index.js
app/components/Dashboard/ChartsTab/index.js
app/components/TagView/TagTopTracks/index.js

Does it make sense @nukeop, @trekiteasy?

**Comment by nukeop** [comment]
It does to me and I'll be glad if you show me how to do something better. Nobody's even looked at the pile of code I churned out in the past 2 years for a long, long time, and I'm sure there are many spots where things can be improved a lot.
