### ISSUE TITLE
Multiple Popover in view 

### ISSUE THREAD

**Issue by Chandankkrr** [nukeop/nuclear#223]
Currently clicking through queued songs opens up an associated popup with stream information. Ideally would like to close existing popup before rendering a new one.

![image](https://user-images.githubusercontent.com/5574015/51975117-9b152900-24d5-11e9-89d1-1cbdaf4a6269.png)

**Comment by WalkerFrederick** [comment]
Same kind of thing happens when you click on a song in the top-charts, opens a context window but doesn't close existing ones.
