### ISSUE TITLE
Mute control

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#226]
A click on the volume symbol should
- put the volume to 0
- change the volume symbol to a "muted" symbol

Another click on the "muted" symbol should
- put back the volume to **where it was initially** 
- change the volume symbol back to the initial symbol

**Comment by Chandankkrr** [comment]
I can implement it later tonight

**Comment by Chandankkrr** [comment]
@nukeop @trekiteasy  Pushed a PR for implementing volume mute control. Had to introduce state in  `VolumeControl` component with `isVolumeMuted` and `volume` properties. 

Thought of implemeting mute control by passing in a flag to `react-sound` package but it does not have props that supports this. 

The way to implement mute control is by passing 0 to the volume props of the `Sound` component within `react-sound`. The value of the volume slider is stored in `volume` property of the state  to prevent the volume slider from jumping around when mute is on.

**Comment by trekiteasy** [comment]
This is implemented in current dev build. I close the feature request.

**Comment by SharlSherif** [comment]
Hi, but it doesn't visually drag the volume slider back to 0 when muted :
![image](https://user-images.githubusercontent.com/29375572/56507220-e5c89f00-6520-11e9-9252-64f675f71158.png)
is that intended or a bug ?

**Comment by SharlSherif** [comment]
incase its not an intended behavior, in `\app\components\VolumeControls\VolumeSlider\index.js`
i edited the `render` of `VolumeControls`  class from 

```
render () {
    return (
      <div className={styles.volume_controls_container}>
        <PlayOptionsControls
          toggleOption={this.props.toggleOption}
          settings={this.props.settings}
        />
        <div
          className={styles.volume_speaker_control}
          onClick={this.toggleMute.bind(this)}
        >
          <FontAwesome name={this.props.muted ? 'volume-off' : 'volume-up'} />
        </div>

        <VolumeSlider
          fill={this.props.fill}
          handleClick={this.handleClick.bind(this)}
        />
      </div>
    )
  }
```

to 
```
render () {
    return (
      <div className={styles.volume_controls_container}>
        <PlayOptionsControls
          toggleOption={this.props.toggleOption}
          settings={this.props.settings}
        />
        <div
          className={styles.volume_speaker_control}
          onClick={this.toggleMute.bind(this)}
        >
          <FontAwesome name={this.props.muted ? 'volume-off' : 'volume-up'} />
        </div>

        <VolumeSlider
          fill={this.props.muted ? 0 : this.props.fill} // this would drag the slider back to 0 if the audio is muted
          handleClick={this.handleClick.bind(this)}
        />
      </div>
    )
  }
```
![Webp net-gifmaker](https://user-images.githubusercontent.com/29375572/56509381-1d3a4a00-6527-11e9-9eba-406a7bdaa924.gif)

**Comment by SharlSherif** [comment]
after using the application for a while, i noticed when the audio is muted, you can't click on the `slider` to unmute & change the volume level at the same time like in most players (Youtube, Spotify etc..)

so i added this feature and thought you might be interested to implement it.

in `\app\components\VolumeControls\VolumeSlider\index.js`
edited the `VolumeControls` to look like that:
```
class VolumeControls extends React.Component {
  handleClick (value) {
    return this.props.updateVolume(value)
  }

  toggleMute () {
    this.props.toggleMute(!this.props.muted)
  }

  render () {
    return (
      <div className={styles.volume_controls_container}>
        <PlayOptionsControls
          toggleOption={this.props.toggleOption}
          settings={this.props.settings}
        />
        <div
          className={styles.volume_speaker_control}
          onClick={this.toggleMute.bind(this)}
        >
          <FontAwesome name={this.props.muted ? 'volume-off' : 'volume-up'} />
        </div>

        <VolumeSlider
          fill={this.props.muted ? 0 : this.props.fill} // explained in my last comment
          handleClick={this.handleClick.bind(this)}
          // passing these to add a `onClick` handler on the slider itself (wrapping it here caused the UI design to break)
          muted={this.props.muted}
          toggleMute={this.toggleMute.bind(this)}
        />
      </div>
    )
  }
}
```

in `\VolumeControls\VolumeSlider\index.js`

```

class VolumeSlider extends React.Component {
  handleClick (value) {
    this.props.handleClick(value)
  }

  render () {
    return (
      <div
        className={styles.volume_slider_container}
       // if the audio is already muted, unmute.  else pass empty function (there's probably a better way than this)
        onClick={this.props.muted ? this.props.toggleMute : () => {}}
      >
        <Range
          value={this.props.fill}
          fillColor={volumeSliderColors.fillColor}
          trackColor={volumeSliderColors.trackColor}
          thumbColor={volumeSliderColors.thumbColor}
          height={4}
          width='100%'
          onChange={this.handleClick.bind(this)}
        />
      </div>
    )
  }
}
```
Sorry if not meant to comment such changes here, i'm new to contributing in general.

**Comment by nukeop** [comment]
It's fine to talk about it here, and if you want to make some changes to the code, it'll be better if you open a pull request. Do you know how to do that? If not, I can point you to some guide.

This way your changes will be attributed to you and we'll be able to track them in history, etc, so it's way better that way.

**Comment by SharlSherif** [comment]
I did a PR.
