### ISSUE TITLE
Release 0.4.4

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#230]
Reminder to release 0.4.4 later today.
Many bugfixes have been added and we have a couple of new useful features.

Travis CI will build Linux and Mac artifacts, I will have to build Windows artifacts on a VM manually though.

**Comment by nukeop** [comment]
https://github.com/nukeop/nuclear/releases/tag/untagged-9d357a0bcb046e4013ab

Linux release works. Mac probably too, but I can't really test it.

**Comment by trekiteasy** [comment]
On Mac it launches well. I haven't been testing it more extensively.

**Comment by nukeop** [comment]
https://github.com/nukeop/nuclear/releases/tag/v0.4.4
