### ISSUE TITLE
Can we add more comments? or some kind of documentation.

### ISSUE THREAD

**Issue by WalkerFrederick** [nukeop/nuclear#231]
Most of the code is pretty straightforward and readable but I think it might make development faster or entice more people to help out if we included more comments.

**Comment by charjac** [comment]
what about something like this: https://github.com/whoisryosuke/gatsby-documentation-starter
If we add propTypes to nuclear components, it could be very usefull.
we could also include api docs and any other thing we want as .md, .mdx, .jsx

**Comment by nukeop** [comment]
Yeah I try adding prop types and default props to every component I add now.

There is some limited documentation on readthedocs:
https://github.com/nukeop/nuclear/tree/master/docs

More could be added here. It's a very popular format.
