### ISSUE TITLE
Add a "add to playlist" feature

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#233]
The feature should be accessible either from the queue or from the currently played song. When clicking on the button a drop down would ask us to which playlist we want to add the track (or the ability to create a new playlist).

**Comment by nukeop** [comment]
I decided to add a more advanced menu to the queue sidebar, looks like this:

![2019-04-22-212606_301x274_scrot](https://user-images.githubusercontent.com/12746779/56520892-57b2df80-6545-11e9-958c-eae027dc7968.png)

This also solves the problem of icons not being descriptive enough. I will also add icons to add tracks to favorites and playlists more easily from all places.

**Comment by nukeop** [comment]
![2019-04-23-010614_525x365_scrot](https://user-images.githubusercontent.com/12746779/56538691-01a16480-6564-11e9-82be-b4f5083643a5.png)

This is what I came up with for quickly selecting the playlist.

**Comment by HaiDang666** [comment]
implemented
