### ISSUE TITLE
UI/UX: Add platform specific common shortcut keys

### ISSUE THREAD

**Issue by peterloron** [nukeop/nuclear#239]
Using nuclear 0.4.4 on OSX 10.4.2, there does not seem to be support for common keyboard shortcuts. For example, <command-H> does not hide the application. When the app has focus, the space bar does not toggle play/pause. Arrow keys do not scan/skip in the current track, etc.

**Comment by maliMirkec** [comment]
Also, could you add "Play," "Pause," and "Stop" support for keyboard keys?

**Comment by maliMirkec** [comment]
Yes, the media keys are working for Deezer, for example. And if I open the Nuclear, I would like to use the keys, if possible.

**Comment by hibroseph** [comment]
Can we close this or are we still waiting for more support of media keys?

**Comment by nukeop** [comment]
We have some nice shortcuts thanks to @charjac, but I left this open to remind me to get back to it at some point and check support for global media keys shortcuts.
