### ISSUE TITLE
Playing wrong track (different album, different artist, nothing related)

### ISSUE THREAD

**Issue by vitosorriso** [nukeop/nuclear#245]
I was trying nuclear for the first time yesterday (0.4.4 on macOS 10.14.2 from Italy)
Searching for 'Chinese Man', going into the right artist, then going to the album 'Shikantaza (Remix)' (albumart is correct, playlist is correct), and then started to play track 16 (Step Back - ProleteR Remix): it started played a totally different track (different artist, different release, nothing related). Tried the full album, no chance to play the majority of tracks, but the other ones got a totally wrong and unrelated result too.
Tried right now with the same track (Step Back - ProleteR Remix), got the wrong track but a different track from yesterday (always a totally unrelated track)!

(it searches on youtube only, nothing changed in settings)

**Comment by Brn9hrd7** [comment]
Probably because of [#242](https://github.com/nukeop/nuclear/issues/242), this bug [has been fixed](https://github.com/nukeop/nuclear/commit/8166b60bcbeeb4ead8b8d8c43c0e4b672e991aee) today.

**Comment by nukeop** [comment]
Exactly, I wanted to say that myself but you were faster. 

Thanks for the report anyway

**Comment by vitosorriso** [comment]
Project cloned, tried the development version: fixed!
Good job ;)
