### ISSUE TITLE
Offline Usage

### ISSUE THREAD

**Issue by sambhavsaggi** [nukeop/nuclear#251]
When not connected to internet, Nuclear is stuck on the splash screen. Is there a way to run Nuclear without internet connection based just on the songs in the playlist? Maybe this can be with the Downloads support in the next release?

Release: 0.4.4 AppImage

**Comment by nukeop** [comment]
No, since it can only stream from online services. Once we add support for local library, it will be possible.

**Comment by charjac** [comment]
@nukeop maybe we should reopen this ?
