### ISSUE TITLE
Add title attribute to icon buttons

### ISSUE THREAD

**Issue by websterchris** [nukeop/nuclear#254]
**Nuclear Version** : 0.4.4
**OS**: Windows 10

Just stumbled across this repo and looks really great. 

I struggled initially trying to figure out what some of the icon buttons (e.g shuffle or queue repeat) did, so I wonder if it is worth adding a title attribute to the buttons to help the user understand what they are especially if the icon meaning is ambiguous?

**Comment by Chandankkrr** [comment]
@nukeop I can implement this. Nice feature suggestion @websterchris. I was struggling to figure out what the buttons did as well.

**Comment by Chandankkrr** [comment]
Could use `react-tooltip` https://react-tooltip.netlify.com/ if we want to control the position of the tooltip.

**Comment by nukeop** [comment]
We already have tooltips from Semantic UI, no need for an extra package, but this will do for now.

**Comment by nukeop** [comment]
Already implemented as a submenu with proper labels.
