### ISSUE TITLE
What about prettier, husky and lint-staged ?

### ISSUE THREAD

**Issue by charjac** [nukeop/nuclear#258]
https://prettier.io/
https://github.com/typicode/husky
https://github.com/okonet/lint-staged

**Comment by nukeop** [comment]
We use eslint for formatting. There is a list of enforced options in the root folder.

**Comment by charjac** [comment]
i make this proposition because i just forgot a console.log and a semi colon in a pr (i fixed it now), this could have been prevented with such tools.

**Comment by charjac** [comment]
with this lib https://github.com/prettier/eslint-plugin-prettier, prettier is integrated to eslint.

**Comment by nukeop** [comment]
Prettier enforces its own rules, which I don't want to use though.

**Comment by charjac** [comment]
ok for that
