### ISSUE TITLE
What about internationalisation ?

### ISSUE THREAD

**Issue by charjac** [nukeop/nuclear#268]
If you want i can do the job quickly with https://www.i18next.com/ with french / english translations.

**Comment by Vistaus** [comment]
I too am interested in internationalization so that I can translate Nuclear to Dutch :)

**Comment by charjac** [comment]
@nukeop any opinion on this ? it is really not a big deal and a huge improvement (a lot of friend of mine doesn't speak english :D)

**Comment by nukeop** [comment]
I think there are many strings that need to be translated. But if you want to work on this - sure, why not.

**Comment by nukeop** [comment]
@Vistaus 
Since @charjac has completed most of the hard work, all that remains is to create a Dutch translation for all the extracted strings, and open a pull request.

**Comment by Vistaus** [comment]
I'll take a look at how to do it ASAP :)
