### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by Cl1608Ho** [nukeop/nuclear#27]
When im launching it i get several font issues, copying the dev console output in it

```
Failed to decode downloaded font: http://localhost:3000/dist/c559fcc74ff2037d8e94e800e98538b6.woff2
app.html#/:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
app.html#/:1 Failed to decode downloaded font: http://localhost:3000/dist/f3652b29b2153ecf20d925efbed9e3cd.woff
app.html#/:1 OTS parsing error: incorrect file size in WOFF header
app.html#/:1 Failed to decode downloaded font: http://localhost:3000/dist/5ff5f78043aebaa12b0f39a120339b51.ttf
app.html#/:1 OTS parsing error: FFTM: table overruns end of file
```

(and other the like)

### How i set up the app

downloaded/git cloned the repo, ran `npm install` and then `npm run-script build` and `npm start` and `npm run-script dev` respective. Maybe I did something wrong there, please tell me

**Comment by nukeop** [comment]
What's your OS?

Try changing line endings. If that fails, try replacing the fontawesome fonts with freshly downloaded ones (http://fontawesome.io/assets/font-awesome-4.7.0.zip).

**Comment by Cl1608Ho** [comment]
Sorry, I forgot about that although I found a few results pointing to that via Google. 

Ubuntu gnome, 16.04

Another thing, (this one's for 0.2.0 as the master didn't run), nuclear should put its files into ~/.nuclear, not just in the home directory

**Comment by nukeop** [comment]
Did you install via .deb or .appimage?

**Comment by Cl1608Ho** [comment]
For the font issue: i tried it, didn't solve it. (I am using master) 

The thing about the home directory, 0.2.0 I installed via a deb package.

**Comment by nukeop** [comment]
Fixed on rewrite branch.
