### ISSUE TITLE
Artists with duplicate names are causing some problems

### ISSUE THREAD

**Issue by Brn9hrd7** [nukeop/nuclear#274]
I´ve noticed a few problems when selecting artists with duplicate names (they have a number in brackets behind their name):

It looks like the artist gets lost somewhere, I get this error in the console after trying to play a song from one of those artists:
```
error TypeError: Cannot read property 'similar' of undefined
    at getSimilarArtists (autoradio.js:185)
    at autoradio.js:174
```

The next issue is probably caused by the first one:

- From what I´ve seen these duplicate artists also don´t have the 'Popular-tracks'-list and 'Similar-Artist'-list (makes sense since `getSimilarArtists` is throwing an error).

- In some cases the wrong song gets loaded, for example after selecting the song [Genesis from E-Force (2)](https://www.discogs.com/release/13113893) the first search result is [this](https://www.youtube.com/watch?v=V-fyi5wjpek) (and therefore gets loaded). This isn´t caused by the missing artist, it´s because Youtube, Soundcloud, etc. are sometimes returning wrong results, which is caused by the number in brackets after the artist name. Possible solutions to this: Remove the number in brackets from the search, or manually determine which is the 'best' result.

**Comment by rsumner868** [comment]
**_````

````_**

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
