### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by a6d6061ed1** [nukeop/nuclear#276]
os: Windows 10 x64 bit Pro N
nuclear: 0.4.4

Sometimes I am getting stuck on "Stream still loading" forever even though I have 1gbps internet and modern pc. And also if I am listening to a song and play a new one I have to pause and unpause it in order to play it.

Really disappointed to see how bad this project is after like what, 3 years in development...

**Comment by nukeop** [comment]
Hey, at least we have a "clear queue" button after those 3 years, Spotify doesn't have that after 11.

**Comment by nukeop** [comment]
On a more serious note, both issues are already solved in the development version.

https://github.com/nukeop/nuclear/commit/4682f5331580c212dfb3cee88dc1a251dd212a4c
