### ISSUE TITLE
[Bug] trackrow popup doesnt hide when clicking another trackrow

### ISSUE THREAD

**Issue by charjac** [nukeop/nuclear#277]
I think this could be solved by putting the isOpen state in redux

**Comment by nukeop** [comment]
I don't follow, each popup has its own isOpen status. We need to figure out a way to cancel out all the other ones after clicking a new one.

**Comment by WalkerFrederick** [comment]
maybe something similar to what I did with the queue popups?

**Comment by nukeop** [comment]
Ok, I fixed this by unconditionally closing on all outside clicks. The caveat is that this will cause links to no longer work, since that closing click will be handled first. I worked around it by adding a tiny 10ms delay. Stupid hack, but it works.
