### ISSUE TITLE
soundcloud research doesn't return anything

### ISSUE THREAD

**Issue by esp13** [nukeop/nuclear#28]
Hi,

I just discover and installed nuclear on my linux mint 17.1 today.
The search engine doesn't find any title with soundcloud. (endless search animation without result).
It works with bootcamp or youtube.

Yann.

**Comment by nukeop** [comment]
Can you post steps to replicate?

What were you searching for?

**Comment by esp13** [comment]
i first launch a search with "bachata modern" without selecting any site.
then see the sites list and select soundcloud and launch a research (endless search animation without result)
then I do the same with "bachata" (endless search animation without result)
then i selected bootcamp+soundcloud and there the results appear for bootcamp (no soundcloud result)

**Comment by nukeop** [comment]
Thanks for bringing this to my attention. Looks like the soundcloud api key has been revoked. I will look into fixing this soon.

**Comment by esp13** [comment]
thank you for having fix this issue,
Is there a way to download the compiled corrected version or should I wait for the next stable release?

PS: you spoke about api key who was revoked. your soft depend on soundcloud api? is it not possible to work without api? for example by parsing on-line site (which don't need any account)?

**Comment by nukeop** [comment]
You can try running the dev version. However, the new release will be available later today.

Yeah I'm using the API because it's very easy. Later I might try to scrape the website contents (and do that for other search engines too), but it will probably be rather difficult.

**Comment by esp13** [comment]
thank you for having fix this issue,
Is there a way to download the compiled corrected version or should I wait for the next stable release?

PS: you spoke about api key who was revoked. your soft depend on soundcloud api? is it not possible to work without api? for example by parsing on-line site (which don't need any account)?

**Comment by esp13** [comment]
Ok thanks so I will wait for the release :)

Yes maybe more difficult and will need to be upgraded sometimes when the web structure of this sites evolve. Maybe using external files for parsing filter would be a nice option to be sure of easy update without having to recompile. But I don't know much so that's just some ideas.

**Comment by esp13** [comment]
thank you, now it works :)
