### ISSUE TITLE
How to delete playlist

### ISSUE THREAD

**Issue by comicsads** [nukeop/nuclear#283]
Maybe I'm just stupid, but I just installed nuclear, and can't find any option to delete a playlist. Since there's no "add to playlist" feature ( #233 ) I end up with duplicate playlists of the same name. I'd at least like to be able to delete the old ones. Re installation didn't help. 

Version info and stuff:
Version 0.4.4
Ubuntu 18.10
Try to right click a playlist from the playlist menu or click the hamburger menu button from inside the playlist itself.
Expected to see anything along the lines of "Delete this playlist"

**Comment by comicsads** [comment]
I also just realized playlist information is stored in ~/.config/nuclear/config.json. While this definitely isn't ideal, it can still function as a workaround for the time being.

**Comment by nukeop** [comment]
I guess we'll have to add more ways to manage playlists.
What's wrong with storing them in .config?

**Comment by hibroseph** [comment]
I could work on this one.

**Comment by hibroseph** [comment]
I would love to work on this once I figure out my issue with playing the playlists #285

**Comment by nukeop** [comment]
That would be cool. Before you start actual work, let me know so we can define the features we want to add here.

**Comment by hibroseph** [comment]
will do! I'll tell you when I figure out what is happening with the current playlist crashing behaviour!

**Comment by YajanaRao** [comment]
@nukeop  can I work on implementing this feature?

**Comment by nukeop** [comment]
I'm not sure what @hibroseph wants to take. What we'll need here:

- [ ] A button to delete a playlist in playlist view
- [ ] A way to edit playlists (add to/remove from playlist)
- [ ] Rename playlist button

**Comment by hibroseph** [comment]
I can take the first one.

**Comment by YajanaRao** [comment]
![image](https://user-images.githubusercontent.com/38914337/54510018-bb0f8780-4971-11e9-8e97-0087967fc735.png)

I have made some progress on deleting the playlist.

**Comment by YajanaRao** [comment]
For Renaming the playlists I have created a PR #297

**Comment by YajanaRao** [comment]
> I'm not sure what @hibroseph wants to take. What we'll need here:
> 
> * [ ]  A button to delete a playlist in playlist view
> * [ ]  A way to edit playlists (add to/remove from playlist)
> * [ ]  Rename playlist button

@nukeop  Can you give more inputs on `A way to edit playlists (add to/remove from playlist)` feature.

**Comment by nukeop** [comment]
When looking at a playlist, we need an X button somewhere to the far left or far right that will appear on hover, clicking it should remove that song from that playlist.

As for adding songs, I'm not sure yet, I'll need some more time to figure out the best way to do it.

**Comment by Yajan** [comment]
Shall I work on removing the songs from the playlist?

**Comment by YajanaRao** [comment]
Shall I work on implement the removing song from playlist feature?

**Comment by nukeop** [comment]
Yeah if @hibroseph hasn't started yet

**Comment by hibroseph** [comment]
sorry about me going MIA. uni hit hard the last few weeks and the semester is wrapping up. im going to actually forgo this for now @YajanaRao you can work on this
