### ISSUE TITLE
Music control bar moves to top when saving playlist

### ISSUE THREAD

**Issue by hibroseph** [nukeop/nuclear#284]
When you save a playlist, the music bar displays at the top.

I am not sure if this is intentional or not.
Machine: Linux Mint 

![image](https://user-images.githubusercontent.com/28901411/54292141-499b9780-4573-11e9-8b93-d6844a0744a5.png)

![image](https://user-images.githubusercontent.com/28901411/54292203-63d57580-4573-11e9-99d2-52f8b9e81c07.png)

**Comment by nukeop** [comment]
I think the dialog does something weird and I ignored that because it's in the background.
