### ISSUE TITLE
Adding disabling features to the play button/skip buttons

### ISSUE THREAD

**Issue by hibroseph** [nukeop/nuclear#286]
Adding the feature of what was added to the navigation buttons where there is no hover or active state and it is darkened for the buttons to stop or skip music. When you are able to perform an action, there is an active state and hover state.

**Comment by nukeop** [comment]
@charjac I was pretty sure you added something like this a while ago?

**Comment by charjac** [comment]
I just add a css style when button is not clickable:

```css
.player_button_disabled a {
  cursor: not-allowed;
}
```
I am sure it would be much better with darkened or shadow style.

**Comment by charjac** [comment]
https://github.com/nukeop/nuclear/commit/8028caa17a1fd9cec9b109067b0466b7278e8c8a

**Comment by nukeop** [comment]
Ah, ok, now I remember. In this case yes, this would be a great improvement.

**Comment by hibroseph** [comment]
Great! I'll take it on. I am going to take a lot from what we did with the history button. Is there anything else you want me to be aware of?

**Comment by nukeop** [comment]
Not really, we'll talk more when you submit your code. Thanks for the help.
