### ISSUE TITLE
Minimize, Maximize and Close option is not there in Windows 10

### ISSUE THREAD

**Issue by YajanaRao** [nukeop/nuclear#291]
I downloaded the latest nuclear application. I am unable to find Minimize, Maximize and Close button. So I am not able to close or restart the application.

OS Windows 10

![image](https://user-images.githubusercontent.com/38914337/54414939-cddf4d80-4720-11e9-9114-5c4f49db7b6c.png)

**Comment by YajanaRao** [comment]
I am able to find the settings to get the settings related to frame less window. But I think by default It will be good to have the option disabled.

**Comment by nukeop** [comment]
I think it's been reported and maybe fixed some time ago. Broken due to inverted condition checking if the window is frameless somewhere.

**Comment by nukeop** [comment]
Yep, I just checked and it's fixed in the dev version.
