### ISSUE TITLE
Clicking multiple songs opens multiple popups

### ISSUE THREAD

**Issue by hibroseph** [nukeop/nuclear#293]
This was to be fixed in #223 but I believe it was just fixed for the playlist view. If you search and go to the songs, you are able to click multiple songs and the same thing will happen.

![image](https://user-images.githubusercontent.com/28901411/54415322-8fff0c80-46c1-11e9-8f45-ddd9365a5768.png)

**Comment by nukeop** [comment]
Already submitted here: https://github.com/nukeop/nuclear/issues/277
