### ISSUE TITLE
unhandled exception when starting electron dev

### ISSUE THREAD

**Issue by hibroseph** [nukeop/nuclear#294]
A system message that displays when starting with npm run electron:dev

![image](https://user-images.githubusercontent.com/28901411/54470240-08b9a380-476a-11e9-8011-762b86f461ad.png)

**Comment by nukeop** [comment]
It's a problem on your machine. The API works on port 3000, but something on your machine is already using it. You can change it in the source file.

**Comment by hibroseph** [comment]
Is there no way to handle this more gracefully. maybe it tries a different port?

**Comment by nukeop** [comment]
You can set the api port in the settings. 

However, on linux it sets it to 3000 anyway (in dev configuration):
https://github.com/nukeop/nuclear/blob/45edc7528c0b790bbc2e09f7d8719044d9d955cc/server/main.dev.linux.js#L175

It could use https://www.npmjs.com/package/get-port instead I guess.
