### ISSUE TITLE
UI: Back Button for browsing genres, artists, etc...

### ISSUE THREAD

**Issue by finartist** [nukeop/nuclear#299]
I use nuclear Version 0.4.4 on Ubuntu 18.04 and there seems to be no "back" button for browsing genres, artists, albums etc. If I accidentally clicked on something or just want to check it out and then go back to the previous page, I need to start all over again from the dashboard which is annoying.

**Comment by nukeop** [comment]
It's already been fixed in the dev version and there are now back and forward buttons. Thanks for noticing.
