### ISSUE TITLE
DBus Integration

### ISSUE THREAD

**Issue by Cl1608Ho** [nukeop/nuclear#30]
Maybe not really priority, but it would be of course nice to have to add dbus support to control the whole app (and shouldn't be too hard)

**Comment by nukeop** [comment]
I'll need to do what I mentioned in the last comment of #12 first.
When I do it, I'll probably be able to use this:

https://www.npmjs.com/package/dbus

**Comment by Cl1608Ho** [comment]
Actually I'd love to help you but there is very little documentation (except I didnt see it)

**Comment by nukeop** [comment]
mpris implemented here:
https://github.com/nukeop/nuclear-rewrite

will replace upstream soon
