### ISSUE TITLE
Support for YouTube Live Streams

### ISSUE THREAD

**Issue by TylerCode** [nukeop/nuclear#31]
A lot of music channels will do music streams now and again. It would be nice to have this included in a final release. Currently, on the latest release, It plays a few seconds, then stops. Pressing play will start what I assume is the cached audio, over again. I may take a look at this if I get some free time.

**Comment by TylerCode** [comment]
A good one to test since it's always active is https://www.youtube.com/watch?v=xJ6IoIBohbM or any of the NASA live channels https://www.youtube.com/watch?v=qzMQza8xZCc

**Comment by nukeop** [comment]
The way I'm separating the audio from video gives me a link that will only contain a few seconds of audio in the case of streams, and won't be updated. There won't be an easy way to fetch live streams without also downloading video, and even then it might be difficult. I'll look into including this in 0.4.0.

**Comment by TylerCode** [comment]
I understand, to me, it seems like more of an enhancement than a bug. You could even hide live streams if you wanted to.

**Comment by GNOME-IS-LIFE** [comment]
Any update on this?

**Comment by nukeop** [comment]
I've changed the search model in 0.4.0 so you're not selecting music sources manually.
This might be implemented at some point as an extra feature, separate from the main functionality, so I'm not closing this issue yet.

**Comment by olafur-palsson** [comment]
What about having this as a settings option where you can list sources from most preferred to the least in a list?

**Comment by HaiDang666** [comment]
I'm currently working on this

**Comment by HaiDang666** [comment]
youtube live stream integration in https://github.com/nukeop/nuclear/pull/940
