### ISSUE TITLE
At the end of a track, doesn't play next track

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#312]
On current dev version, on windows : 
- when I choose "Play now" on a track, it plays well
- when the song is at its end (or if I press the "next" control), the following song is loaded but never starts playing
- I have to click on "pause" and then "play" to have the song playing
I'm not sure since when it happens as I was not around for a while.

**Comment by nukeop** [comment]
Might have something to do with the check that was added to ensure we only start playing tracks that have streams.

**Comment by SharlSherif** [comment]
@nukeop can you link me to that change ? i'll try to fix it.

**Comment by nukeop** [comment]
I'm not sure what causes this, actually. The code handling playing audio is in SoundContainer/index.js, if you're up to some investigation. I think the component fails to update after switching to the new track, maybe there's a bug in shouldComponentUpdate.

**Comment by trekiteasy** [comment]
For me, this is fixed with new sound component

**Comment by nukeop** [comment]
Can't confirm, actually I'm getting an error:

```
Uncaught TypeError: memo is not a function
at Module../node_modules/react-hifi/dist/react-hifi.es5.js
```
@charjac

**Comment by charjac** [comment]
in react-hifi i use the brand new fonctionnal feature of react 16.6. I am pretty sure updating the react version in nuclear package.json to the latest will fix this.

```json
{
  "peerDependencies": {
    "react": "^16.8.6"
  }
}
```

https://scotch.io/tutorials/react-166-reactmemo-for-functional-components-rendering-control

**Comment by charjac** [comment]
a lockfile could avoid this in the future.
npm suck at it actually :( but yarn works just fine.

**Comment by charjac** [comment]
I delete my last 2 comments they were wrong ....
react-hifi need the last version of react, simply run npm install and it will work

**Comment by nukeop** [comment]
I updated the packages and pushed to master, everything works and I can confirm that the issue described in this thread has been fixed too.
