### ISSUE TITLE
Playlist reordering

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#315]
We should be able to reorder tracks in playlists, this could be achieved with the same drag and drop package the play queue is using. This will be easier when I merge https://github.com/nukeop/nuclear/tree/feature/queue-menu, as this contains actions for updating playlists.

**Comment by charjac** [comment]
i give this a try

**Comment by nukeop** [comment]
I already merged it and there were no conflicts.

**Comment by charjac** [comment]
i am on it

**Comment by Michael-Hudson** [comment]
Can this be worked on?

**Comment by nukeop** [comment]
Yep!

**Comment by Falgu9** [comment]
Hi ! Can I work on it ?

**Comment by nukeop** [comment]
Yes, sure

**Comment by Falgu9** [comment]
Ok thanks, I just compiled it and I'm ready to start the work. Do you have some information for me to start on ?

**Comment by nukeop** [comment]
Yep, if you want to implement drag and drop reordering, you can look here:
https://github.com/nukeop/nuclear/blob/4ba36b51c0ba720b6f174c96fb1c3e03dfd37b74/packages/app/app/components/PlayQueue/index.js

We're using `react-beautiful-dnd` for this, and it's worthwhile to make it work uniformly everywhere.

**Comment by devanshim2207** [comment]
Hi could you tell where changes are to be made ?

**Comment by nukeop** [comment]
Hi, sorry, I forgot to assign this to myself, I'm already working on it.

**Comment by HaiDang666** [comment]
implemented in https://github.com/nukeop/nuclear/pull/958
