### ISSUE TITLE
Update screenshots in readme

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#316]
The screenshots are quite old and need to be replaced.
We could also get rid of the mockups or replace them with better ones.

**Comment by pikap3w** [comment]
I can help out with this one ✅

**Comment by nukeop** [comment]
Great, thanks.

**Comment by YudiR** [comment]
Hey! Is this issue available?

**Comment by pikap3w** [comment]
Hey! Yes it is! I got busy with work and forgot about this one so it's yours if you want it

**Comment by YudiR** [comment]
Great!

**Comment by nukeop** [comment]
@YudiR - if you want, feel free to also update these https://github.com/nukeop/nuclear/tree/master/resources/media/presskit/screenshots

Or add more, showcasing some new features.

**Comment by YudiR** [comment]
@nukeop - Will do.

**Comment by Korb** [comment]
There are currently no screenshots in the `README.md`. Was it decided not to include them in the app's short description? What was the rationale behind this decision?

**Comment by nukeop** [comment]
Come on man, I'm still doing the migration. Give me a day or two to finish it. Screenshots will be there.
