### ISSUE TITLE
Mini-player

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#325]
This feature would be enabled by a small button in a convenient location that would be always available (maybe the queue menu).
Clicking it turns the program window smaller, and only shows absolutely essential components - track progress, player controls, currently playing track with its art, etc.

**Comment by chahala** [comment]
Hi! Is there still interest in this feature? Has anyone taken it up? I'm interested in giving it a shot, if possible. :)

**Comment by nukeop** [comment]
I don't think anyone's started working on it yet. I'm still planning to do it at some point, but feel free to take it if it sounds interesting to you. Let me know if you need any help.

**Comment by chahala** [comment]
I'm trying to get the development environment set up using lerna (I'm on macOS, so not using docker workflow), but when I run `lerna bootstrap`, I get the following error:

lerna notice cli v3.19.0
lerna info Bootstrapping 0 package
lerna info Symlinking packages and binaries
lerna success Bootstrapped 0 package
node[69169]: ../src/signal_wrap.cc:159:void node::DecreaseSignalHandlerCount(int): Assertion `(new_handler_count) >= (0)' failed.
 1: 0x100b8ff9a node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000832c4 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10008307c node::AppendExceptionLine(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Message>, node::ErrorHandlingMode) [/usr/local/bin/node]
 4: 0x1000f7e52 node::HasSignalJSHandler(int) [/usr/local/bin/node]
 5: 0x1000f85ad node::(anonymous namespace)::SignalWrap::Close(v8::Local<v8::Value>) [/usr/local/bin/node]
 6: 0x10003eb76 node::Environment::CleanupHandles() [/usr/local/bin/node]
 7: 0x10003ed2f node::Environment::RunCleanup() [/usr/local/bin/node]
 8: 0x1000b4a3a node::NodeMainInstance::Run() [/usr/local/bin/node]
 9: 0x100060f13 node::Start(int, char**) [/usr/local/bin/node]
10: 0x7fff64b4d3d5 start [/usr/lib/system/libdyld.dylib]
Abort trap: 6

Any thoughts? I tried recloning the repo and reinstalling lerna.

**Comment by nukeop** [comment]
Did it install the packages? Can you start the development environment?

**Comment by chahala** [comment]
`npm i -g lerna` ran successfully, but running the next line produced the above output. I tried running `lerna run start` afterwards and the 'Welcome to nginx!' page opens up.

**Comment by nukeop** [comment]
We don't use nginx in nuclear. I suspect something on your machine uses the same port as the development server. Try either changing the dev server port (add `--port 3100` or some other number here https://github.com/nukeop/nuclear/blob/master/packages/app/package.json#L11 ) or figure out what's using the port (with netstat).

**Comment by schippas** [comment]
Hey, I worked on some mini player stuff several months back, and I had it in a state where it could minimize it properly and look decent. I think my issue was creating the button logic that would toggle consistently between the two states. I might rebase my code and look into it again soon if no one else decides to work on this.

**Comment by nukeop** [comment]
Awesome, even if you have issues bringing it to completion, open a pull request anyway, and then I can help you out or merge your code and finish it for you.
