### ISSUE TITLE
Last.fm API fuckery

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#327]
https://getsatisfaction.com/lastfm/topics/api-announcement-dac8oefw5vrxq

Long story short, they're crippling their api for no clear reason after years of it working. Apparently they're now returning invalid urls for images on purpose. So we're gonna need a scraper to restore artist images.

**Comment by nukeop** [comment]
Apparently there's something called fanart.tv that could be used to substitute the urls that last.fm broke, worth investigating.

**Comment by nukeop** [comment]
Musicbrainz also shares some covers although it might not work for all albums/artists.

**Comment by nukeop** [comment]
artist.getInfo is the crippled call. Discogs could also be used.

**Comment by olafur-palsson** [comment]
Been looking into this.

I saw that LastFm provids 'mbid' (MusicBrainz). This can be used reliably to get coverart from `coverartarchive.org` by `http://coverartarchive.org/release/{ mbid }` type of requests.

**Comment by olafur-palsson** [comment]
Update: 

LastFm gives MusicBrainz id's that point to nothing for some reason. When they do exist then they usually don't include cover art from coverartarchive.org.
