### ISSUE TITLE
can this run in a browser?

### ISSUE THREAD

**Issue by misterhat** [nukeop/nuclear#328]
just wondering if it's possible to host this on a server and use it from home (self-hosted) rather than just electron? i was about to write my own similar application for another service, but i was considering adding it to here instead. my only concern was being able to run it on a server with faster download/upload speeds and accessing it from my phone.

edit: if not, how do you think it might be possible to implement a p2p (limewire-esque) provider into the client? maybe a separate server that handles the entirety of p2p while just providing REST endpoints for the files?

**Comment by nukeop** [comment]
Nope, probably can't run on a server as of right now.
There is a http API exposed that allows you to remote control some stuff. This presumably could also be used to expose the interface itself.
Your idea at the bottom sounds ok, you can take a look at how we've implemented support for Youtube, Soundcloud or Jamendo.

**Comment by misterhat** [comment]
yup i checked those out. very intuitive actually so i'd be interested in experimenting with it soon! thanks
