### ISSUE TITLE
Suggestion : Play directly the tracks in search results without need to add them in queue list

### ISSUE THREAD

**Issue by esp13** [nukeop/nuclear#33]
I propose to add an option that when you play a song from the search result, when the track is ended, it plays automatically the next one (in search result).

As on soundcloud website for example.

What do you think about?

**Comment by nukeop** [comment]
I could implement this by adding a button that will simply add all search results to the queue and start playing.

**Comment by Cl1608Ho** [comment]
@nukeop furthermore, I don't know if this issue exists, but it might be useful that elements that get added to the queue tale their info from the previous search request, not make a request instantly, but only when you are playing that song (so you won't hit rate limits)

**Comment by nukeop** [comment]
In case of youtube items, the path to audio is found without using the API, so rate limits won't be an issue.

The program tries to find audio path as soon as the song is added to the queue, and only loads actual audio when the song is about to be played.

**Comment by nukeop** [comment]
Play queue works differently than before now so this doesn't apply anymore.
