### ISSUE TITLE
Skip, regenerate or remove stuck tracks

### ISSUE THREAD

**Issue by loonies** [nukeop/nuclear#330]
It happens that some tracks will not play and then the queue gets stuck. It's annoying as I have to reach to the player and skip the track.

Probably related but I don't see issue opened:

> I noticed that too, it's a different problem than the original one in this thread. It happens because apparently saved stream URLs are no longer valid after some time, and need to be regenerated.

_Originally posted by @nukeop in https://github.com/nukeop/nuclear/issues/122#issuecomment-461086219_

**Comment by nukeop** [comment]
I investigated this and I remembered that actually if an invalid stream is saved in a playlist, a new URL will be generated and play pretty much seamlessly. Not sure how to reproduce this issue, or if it even affects the current version.
