### ISSUE TITLE
downloads glitch

### ISSUE THREAD

**Issue by advaithm** [nukeop/nuclear#332]
I am running a built version of nuclear 4.50 and there are a few issues with the download percentages. i have made a big discovery nuclear does download the correct file but displays the download percentage as the first in download list. secondly it downloads the mp4a file and stops working. i believe this is due the fact nuclear can`t convert mp4a to mp3 and can`t read the mp4a files.

**Comment by nukeop** [comment]
Thanks for reporting, I'll check what causes this. It shouldn't matter what the file format is, but maybe some server responses are not handled correctly.

**Comment by advaithm** [comment]
no there it is a problem with ff-mpeg. youtube-dl has a similar issue when running ff-mpeg  where ff-mpeg refuses to download the mp4 format instead it downloads two files and merges them into a mkv file. i would recommended using something else. also you are right in saying the file format should not matter but when downloaded the tracks lack title album and  the artist hence nuclear categorize them as one track and can`t run them as when trying to run the single song it tries to run all the songs as one song which means it can`t play the song. 
i am sorry i could not be of more help. i am not very good at electron.

**Comment by nukeop** [comment]
No problem, you gave me a very good description of the issue and I know where to look now. I'll try to figure out how to handle conversion better...

**Comment by nukeop** [comment]
I've tried to reproduce this but no luck so far, even using the songs you provided as examples. This should probably also be reproducible using youtube-dl, if this is a problem with ffmpeg.

**Comment by advaithm** [comment]
i can reproduce every time on windows with youtube-dl and nuclear but i moved to linux now
