### ISSUE TITLE
Autotagging with Acoustid

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#335]
https://www.npmjs.com/package/acoustid

This could solve problems like #331, as well as improve the quality of user's local library. Possible problems include bundling the binaries on non-Linux systems.

**Comment by charjac** [comment]
hi i'm back !!!
maybe the second answer of this could help
https://stackoverflow.com/questions/33152533/bundling-precompiled-binary-into-electron-app

**Comment by charjac** [comment]
i will start work on it tomorow

**Comment by nukeop** [comment]
awesome, especially if we can figure out a way to bundle different precompiled binaries for different systems
