### ISSUE TITLE
Add current track to favorites/playlist - bug if the queue is empty

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#336]
If the queue is empty this function will add a garbage empty track. Needs to be solved.

**Comment by mallowcat** [comment]
I'll work on this if you want to assign to me  (=^ω^=)

**Comment by nukeop** [comment]
Sure, feel free to take this issue. I can't assign you since we can only assign maintainers with full access to the repo, but I'm sure nobody else will work on this.

**Comment by mallowcat** [comment]
Fixed by not allowing tracks without least the name defined. Wasn't sure if there are scenarios where the artist is left undefined? I could add a check for that too if the artist name is always expected.

https://github.com/nukeop/nuclear/pull/343

**Comment by nukeop** [comment]
Closed by #343
