### ISSUE TITLE
Deleting tracks from playlist

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#337]
We need some better playlist management, this is one of the needed features.

**Comment by Hansen1992** [comment]
Hey @nukeop, I'll like to look at the "deleting tracks from playlist" issue, if this is still an issue?

**Comment by nukeop** [comment]
Yep, sure. Try to do the UI part similarly to how I did it in favorite tracks, for consistency.

**Comment by Hansen1992** [comment]
great, I'll have a look at it :-)

**Comment by Hansen1992** [comment]
Hey @nukeop I'm currently looking at a folder where it would be fitting to try to add the "deleting tracks" function, but do you have a folder that you find fitting? I'm quite new to Github as well as coding and I'm constantly trying to improve. 
Also, do you know how to get the app up on a live server, so I can test if my code is working correctly? I'm trying to get some of the html pages in Nuclear to show on a live server using VS code, but I can't really find any that lets me see the changes I make.
Hope you might be able to help me :-)

**Comment by nukeop** [comment]
So Nuclear is composed of two parts - the first part is Electron, which is like a stripped down web browser which creates an environment for the other part to run in. This also lets us interact with the user's system, since normally web apps run in a sandbox for security reasons. The code for this part lives in the `server` folder. The second part is the web app, which lives in the `app` folder. This mainly forms the interface and executes calls to external services. To get the development version running, you have to run both parts together. Since they're interconnected, the web app part won't run in a normal browser.

This section describes how to run this setup for development: https://github.com/nukeop/nuclear#dev-build-process

If you're on Linux, you'll need to run `npm run watch` and `npm run electron:dev:linux`. On non-Linux system,  run `npm run watch` and `npm run electron:dev`. This will hopefully open a window where you can see your changes live with hot reload (if it doesn't reload for any reason, try ctrl+R, or command+R).

Are you familiar with React and/or Redux? If you are, then actions and the reducer for playlists are here:
https://github.com/nukeop/nuclear/blob/master/app/actions/playlists.js
https://github.com/nukeop/nuclear/blob/master/app/reducers/playlists.js

And the playlist view is here:
https://github.com/nukeop/nuclear/blob/master/app/components/PlaylistView/index.js

You'll need to use updatePlaylist, probably. This handles all the existing updates, like renaming, and deleting could be implemented by dispatching an update action with the deleted track removed.

If you're not familiar with React and/or Redux, then I recommend reading some basics about these first, so you know what actions and reducers are, and what they're for. I hope everything's clearer now and if you have any more questions feel free to ask here.

**Comment by Hansen1992** [comment]
Thanks a lot! That really helped get me going!

**Comment by Hansen1992** [comment]
hey @nukeop, even though I follow the instructions above, the setup still won't run. If I run both the server folder and the app folder with npm run electron:dev in two separate terminal-windows, an error occurs: 
![2019-06-14 (8)](https://user-images.githubusercontent.com/50966456/59567698-3667fe80-9071-11e9-88c4-eb8b5a5809ea.png)

If I just run the npm run electron:dev in \nuclear\ in my node.js command promt, the same thing happens as last time where an image of the Nuclear logo appears, but where there is no possibility for actually seeing the entire app. 

Do you know, what I'm doing wrong?

**Comment by nukeop** [comment]
Something else on your PC is using the port 3000. You could hardcode the port to be something else, just for development (don't commit this change).

https://github.com/nukeop/nuclear/blob/master/server/http/server.js#L47

Here's where the http API is initialized. Just change the port to something else that's not in use.

**Comment by Hansen1992** [comment]
Thanks, I really appreciate the help. But it seems like the first terminal command 
nuclear\server>npm run electron:dev interferes with the port because when I change the port to 1021 or any other port the error comes up with the port I just changed it to when I fire the second command
nuclear\app>npm run electron:dev in another terminal.
I have tried to reverse the commands but it didn't help. Have you experienced this type of error before?

**Comment by nukeop** [comment]
If it's acting up you could just comment out the lines that are starting the API, you don't need it for the playlists.

https://github.com/nukeop/nuclear/blob/master/server/main.dev.js#L140

https://github.com/nukeop/nuclear/blob/master/server/main.dev.js#L124
124-128

Once you get it to run you can disable the API in the settings. Instead of commenting these lines out, you could also try finding the settings file and manually disabling it there, so it doesn't start. I think I will start a new issue for this since it could prevent some features from working.

**Comment by Hansen1992** [comment]
I'll try that, thanks for the support!

**Comment by nukeop** [comment]
It could be the case that the second command is launched twice somehow, and it tries to start the api again on the same port. You could try looking it up in windows process list. I don't know how that could happen though.

**Comment by Hansen1992** [comment]
I'll definitely take a look at it.

**Comment by Hansen1992** [comment]
The error is still the same as previously, even though I comment out line 124-28. 
Line 140: doesn't exist anymore as far as I can see. 
my lines where line 140 is included looks like this:
app.on('ready', () => {
  createWindow();

  if (getOption('api.enabled')) {
    setOption('api.port', 3000);
    httpServer = runHttpServer({ log: true, port: 3000 });
  }
});

app.on('window-all-closed', () => {
  closeHttpServer(httpServer).then(() => app.quit());
});

**Comment by nukeop** [comment]
Try pulling the newest changes, a contributor added a fix for this issue that ensures only available ports can be used.

**Comment by Hansen1992** [comment]
I tried that as well, but unfortunately, the same error with the conflicting port emerged. It might just be my computer, I guess.

**Comment by leonlafa** [comment]
@Hansen1992  yeah, pull latest changes in the master branch.   You should now see:
`app.on('ready', () => {
  createWindow();

  (async () => {
    const availablePort = await getPort({ port: getPort.makeRange(3000, 3100) });
    if (getOption('api.enabled')) {
      setOption('api.port', availablePort);
      httpServer = runHttpServer({ log: true, port: availablePort });
    }
  })();
});
`

**Comment by Hansen1992** [comment]
Thanks, I'll try that :-)

**Comment by leonlafa** [comment]
How are you getting on Hansen1992, did you manage to pull the new changes into your branch?

**Comment by Hansen1992** [comment]
hey @leonlafa, yes I have pulled the new changes, and the port-error didn't pop-up but another error did: 
![2019-06-20 (1)](https://user-images.githubusercontent.com/50966456/59868219-a4be0100-9390-11e9-967d-7c807901ba16.png)

Is this a common error?

**Comment by nukeop** [comment]
See this: https://github.com/nukeop/nuclear/issues/360

I will fix this today

**Comment by Hansen1992** [comment]
Thanks, I'll pull the changes later and see if everything works.

**Comment by nukeop** [comment]
I unified the dev files for the server, it should work the same on all platforms now.

**Comment by Hansen1992** [comment]
Hey @nukeop  I have tried again and it finally worked! I'm in and everything is showing. It says that "React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work" in my console, is this a problem? 
I'll have you know what I did to make the app work in my devtools for future reference:
The API is still causing problems. I got the same problem with the two terminals trying to launch the same API which left me with the Nuclear logo in my chrome devtools. I commented out

https://github.com/nukeop/nuclear/blob/master/server/main.dev.js#L140

https://github.com/nukeop/nuclear/blob/master/server/main.dev.js#L124
124-128
and the error disappeared due to the API no longer being launched as we have previously discussed.
I then changed composeEnhancers() to compose in this line
https://github.com/nukeop/nuclear/blob/6bdb737aec7505a5dc85ada1c7fda71fc5ccbbcc/app/store/configureStore.js#L15
 
First when all of this was changed, it worked.

**Comment by nukeop** [comment]
I've seen that some people on Windows have been experiencing issues with Redux dev tools. I can't replicate this on Linux though.

**Comment by Hansen1992** [comment]
Hey all, I'm currently looking into React and Redux, as this is my first project using it. Before I can see whether my coding works or not, I need to add a "delete track" button to the playlist-display. 
Does anyone know, how I add buttons to the Nuclear-app?

**Comment by nukeop** [comment]
If you want to add a button to the playlist view, the best place would be to modify the TrackRow in PlaylistView. TrackRow already has props called `withDeleteButton` and `onDelete`, so all you have to do is to pass the track deleting function to it so it's linked to the button and set `withDeleteButton` to true.

If you look at the favorite tracks section, an analogous functionality has already been implemented by me.

**Comment by Hansen1992** [comment]
Hey @nukeop 
I have inserted some code in PlaylistView which is heavily inspired by the favorite tracks section. 
Even though the code renders and the app updates with no errors displayed in my console, the delete-button isn't showing like in favorite tracks. Do you know why based on the code beneath? 
I am terribly sorry for my inadequacy but I'm learning a lot from this project.

 deleteTracks () {
    {tracks,
    deleteTrack}
        return (
          <TrackRow
            key={'track' + i}
            track={track}
            index={i}
            withDeleteButton={ true }
            onDelete={ e => {
              e.stopPropagation();
              deleteTrack(track);
            } }
          />
        );
      }

**Comment by nukeop** [comment]
If you want to post code in a comment, try using markdown tags: wrapping the code block in \``` will render it as code with indents. You can also start it with \```javascript to highlight syntax. Refer to this: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

You don't need a new function for this, because the tracks are already being rendered, you just need to adjust the existing function a little. 
This part is where the playlist's tracks are rendered:
https://github.com/nukeop/nuclear/blob/master/app/components/PlaylistView/index.js#L163

From this you can tell that we're telling the TrackRow to render with a cover and the artist name. You need to also tell it to render with a delete button, by adding `withDeleteButton` to the props, just like `displayCover` and `displayArtist` are added now. This will render a button next to each track, but it won't do anything yet. You can use the `onDelete` prop to supply a function that will be called upon pressing it. For now, try adding something like this: `onDelete={ () => alert('test') }`. If you click on the delete button now, it should display an alert window.

The next step will be to create an action that can delete a track (preferably here: https://github.com/nukeop/nuclear/blob/master/app/actions/playlists.js ), and then pass that action down to PlaylistView, and connect it to those TrackRow buttons. You can either try doing it yourself, or if you feel lost at any point you can ask me for help again and I'll do my best to get you on the right track.

The best way to do this would be if you forked this repo and started committing your changes to your own fork, then started a pull request, even if your work isn't finished. This way I would see all the changes you've made and could comment on them directly.

**Comment by Hansen1992** [comment]
Thanks a lot, it worked now! 
I'll see if I can create an action that deletes a track and then I'll try to start a pull request containing my best effort. 
Thanks again for the help!

**Comment by AmirBraham** [comment]
Is this still an open issue ? Because I can work on this feature !

**Comment by nukeop** [comment]
It's almost done: https://github.com/nukeop/nuclear/pull/378

I need to get around to reviewing the changes and merge it.

**Comment by primeapple** [comment]
How is the PR for this issue going? Are there any plans to continue working on it, @Hansen1992 ?  
Otherwise I would like to take over!

**Comment by devanshim2207** [comment]
is it still an open issue?
