### ISSUE TITLE
Downloads management

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#338]
We need a way to delete tracks from downloads, pause/resume downloads, sort the list, etc.

**Comment by saimfd** [comment]
I can help in this one. Currently working on sorting the list.

**Comment by nukeop** [comment]
Cool, thanks. Don't forget to pull the latest changes, there's been a lot of refactoring done yesterday.

**Comment by saimfd** [comment]
Sure, will do.

**Comment by Michael-Hudson** [comment]
Hey is this still available to work on?

**Comment by nukeop** [comment]
Yep, no pull requests yet.

**Comment by Michael-Hudson** [comment]
what is the command to go on developer  mode on windows?

**Comment by nukeop** [comment]
`docker-compose up dev` should work if you have docker and docker-compose. If not, try this:
```
$ npm install
$ npm run watch
```
In another console:
`$ npm run electron:dev`

**Comment by Michael-Hudson** [comment]
Ok our team is currently working on all three feature requests. would you be ok with  us creating a pull request if we are able to get one of the features done ? In addition you have a delete all finished tracks feature already in place, are you looking for a feature that deletes tracks that are currently still downloading?

**Comment by nukeop** [comment]
Yep, feel free to make pull requests as soon as you want. We're looking for features that make download management easier, so anything you can do that achieves that is very welcome.

**Comment by apekshya** [comment]
So as we were looking at the download manager, we realized that sometimes there was a lag between the percentage in the completion tab and the status displayed. Do you think it will be a good idea to have these in the same tab? For eg. the status will show % when it is downloading and display "finished" after it completes?

**Comment by Michael-Hudson** [comment]
@nukeop  FYI this is the team, @apekshya , @Samita, @magordon97  Currently working on the download management issue

**Comment by nukeop** [comment]
Wow, amazing that so many of you are contributing. This is really cool and I am very grateful.

Downloading and its status might be a bit wonky, because it needs to pass messages between the renderer and the main process, and I'm not 100% sure if I implemented that in a foolproof way. Downloading is handled through this package: https://www.npmjs.com/package/electron-dl, which is supposed to update the download progress and status, but as you've noticed sometimes it doesn't reflect the true state accurately. If you guys feel like it, you can try to get to the bottom of this and figure out why. You can also implement what @apekshya suggests which will get rid of the problem in a different way. Up to you.

**Comment by Michael-Hudson** [comment]
Hey Nukeop, we just made our first pull request **https://github.com/nukeop/nuclear/pull/482 on** download management. Hopefully more to come soon.

**Comment by nukeop** [comment]
Awesome, thank you. I will review the code soon!

**Comment by Michael-Hudson** [comment]
We are working on changes for #482. It should be ready soon. We made another Pull request #497 . I tested and run all pull requests together and they worked perfectly.

**Comment by nukeop** [comment]
Nice! I'll take a look today. I saw there's a lot of files - maybe rebase would be possible? I changed the architecture in a major way recently.

**Comment by Michael-Hudson** [comment]
Looks like most of those changes are auto generated. It looks like it was adding the classes. Could there be a reason this happened?

**Comment by nukeop** [comment]
I think it's because I made a lot of changes recently... The best thing to do in this case is to stash, then go back to master, fetch latest changes, checkout a new branch, then apply the stash making sure it's applied correctly, then commit again. Or just rebase or cherry pick those commits.
