### ISSUE TITLE
0.4.5 Search does not work

### ISSUE THREAD

**Issue by penhs** [nukeop/nuclear#346]
Nuclear version: 0.4.5
Operating system: Windows 10 Pro (x64)
Node.js version: 10.16.0

Reproducible steps:
1. `$ npm run build:dist`
2. `$ npm run electron:prod`
3. Attempt to search "keith sweat"

What I expected to see: Keith Sweat search results.
What I actually saw: A quick flash of the Nuclear logo and nothing happens.

What's interesting is that searching for "keith sweatr" (an accidental typo) actually brings up some search results. I also ran Nuclear production version 0.4.4 and the search appears to function correctly when I searched for "keith sweat". 

For 0.4.4, when searching, the terminal outputs a single line of `renderer > {}` for a single search but for 0.4.5 it outputs it numerous times for a single search: 

![image](https://user-images.githubusercontent.com/46614782/59107205-f4aabb80-88ec-11e9-9adb-1e513a5d2442.png)

**Comment by nukeop** [comment]
definitely a bug, since there is data in Discogs. I'll take a look once I'm home

**Comment by charjac** [comment]
this one is on me .... sorry for that i refactor too many things in my last pr.
I fix this this evening.

**Comment by charjac** [comment]
I let all "this" in functionnal components ............

**Comment by charjac** [comment]
we need some minimal tests to avoid this in the future

**Comment by nukeop** [comment]
ah, right. we could add enzyme and write some simple tests that ensure that components render without errors with some mocked data, this would catch this bug.
