### ISSUE TITLE
Program doesn't start if the http API port is in use

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#356]
Described in more detail here: https://github.com/nukeop/nuclear/issues/337#issuecomment-502473060

To prevent this bug, we could use this package:
https://www.npmjs.com/package/get-port

And inform the user about the new port in the settings section.

**Comment by schippas** [comment]
Hello, I am interested in working on this project, Is anyone else working on this issue already, or can I work on it?

**Comment by nukeop** [comment]
You can take it, I haven't started working on it yet.

**Comment by leonlafa** [comment]
Are you going to look into this @schippas?  If not I can have a PR in the next 30 mins or so...
