### ISSUE TITLE
Improve language selection UX

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#358]
The dropdown for selecting languages needs 2 changes:
- Change the styles (possibly using the dropdown from Semantic UI) so that the look & feel is similar to the rest of the program
- Display user friendly names for available languages

**Comment by schippas** [comment]
I am looking into it right now.

**Comment by nukeop** [comment]
Brilliant! I made this more as a reminder to myself when I get home, but if you want to try fixing this, even better.

**Comment by nukeop** [comment]
Finished.
