### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Nyhaalm** [nukeop/nuclear#360]
After running `npm install` and `npm run watch` in one terminal and then` npm run electron:dev `in a new terminal, I get the exception:

```
Uncaught Exception:
ReferenceError: regeneratorRuntime is not defined
    at App.eval (webpack:///./server/main.dev.js?:147:35)
    at App.emit (events.js:187:15)

```

![image](https://user-images.githubusercontent.com/5989118/59701819-b370b080-91f6-11e9-8cda-307a8c9d5453.png)

After clicking OK, the program still runs, but with more errors and is stuck with the logo screen.
![image](https://user-images.githubusercontent.com/5989118/59702239-8ec90880-91f7-11e9-9c2f-dd1f87e0b010.png)

Any idea how to fix this?

Node version : v10.16.0 (but also tested with v12)

**Comment by nukeop** [comment]
You need to import `babel-polyfill` at the top of the index server file, like here: https://github.com/nukeop/nuclear/blob/master/server/main.dev.linux.js#L1
I think this line is missing on non-Linux platforms (by mistake).

**Comment by Nyhaalm** [comment]
Thanks. That got rid of the first error. But I still have the one when the app is running 
![image](https://user-images.githubusercontent.com/5989118/59708064-4fed7f80-9204-11e9-97e6-36bb8ac5380d.png)

**Comment by Nyhaalm** [comment]
I managed to fix it by changing composeEnchancers to compose in:
https://github.com/nukeop/nuclear/blob/6bdb737aec7505a5dc85ada1c7fda71fc5ccbbcc/app/store/configureStore.js#L15

Not sure if this is good but it makes the program run without any problems.

**Comment by nukeop** [comment]
Maybe there was a problem with downloading the redux extension?
