### ISSUE TITLE
Frequent HTTP 403 errors with YouTube plugin

### ISSUE THREAD

**Issue by Mongogamer** [nukeop/nuclear#362]
- **Nuclear version**: 0.4.5 commit 02776aa6989a10ff73b72b6d61a707af26ab14e3, fdbdc3a8f27ebba6d58fe4f7aed7aba4b0ba36ae
- **OS**: Windows 10 Pro x64 1903
- **NodeJS version**: 10.16.0
---
**Description of the issue**: The YouTube plugin is currently encountering very frequent HTTP 403 errors when trying to search for results and streaming audio. Sometimes the search does not encounter a 403 and loads the metadata of the track but audio will still 403 and not play. The only way to get audio to play is to switch to either local or Soundcloud source. The problem seems to be caused by the YouTube API quota being exceeded.

**Expected behavior**: HTTP 403 errors obviously aren't intended to happen. Expected bevavior would be a HTTP 200.

---

**Steps to reproduce**:

1. Set YouTube plugin as default music source.
2. Search for any song (I used Blossom by Au5)
3. Attempt to play the song.

---

**Possible solution**: Let users provide their own YouTube API key as an advanced option or automatically switch to Soundcloud whenever a 403 is encountered.

---

[Devtools output when trying to play song while quota is exceeded](https://i.imgur.com/pFHhA25.png)
[Devtools network information for failed request](https://i.imgur.com/nCRk3N4.png)
[Devtools response from YouTube API](https://i.imgur.com/ejvt855.png)

**Comment by nukeop** [comment]
Thanks for a very detailed report. I've seen a similar issue with mpsyt and it was possible to clear the cache to get it to work again. I think the key itself is fine, but we might have to find a way to clear the cache automatically to avoid this.

**Comment by Mongogamer** [comment]
Deleting cache and data inside of electron devtools sadly did not fix the problem for me. Deleting the cache files from the filesystem also did not help. At the moment metadata is loading for me and not throwing 403 errors anymore but playback is still receiving them. Very rarely playback starts working even if the cache is not cleared.

The problem seems to be caused by ytdl-core as I found this issue https://github.com/fent/node-ytdl-core/issues/434 with lots of users complaining about constant 403 errors.

I assume this will be fixed by the developer of ytdl-core soon.

**Comment by nukeop** [comment]
Time to update the package then.

**Comment by Mongogamer** [comment]
The problem is fixed with the new package version. However when starting a production version it throws this error ![](https://i.imgur.com/zV18xOT.png)

**Comment by nukeop** [comment]
I'll test later if this is related.

**Comment by nukeop** [comment]
Seems to work on Linux. I'm currently refactoring and unifying the server files, sine there's no longer any need to keep them separate. When I finish that it should fix this issue.

**Comment by nukeop** [comment]
I was able to reproduce this when building on Windows. Seems to be related to settings as it goes away after launching the program a second time, maybe something's uninitialized.

**Comment by Mongogamer** [comment]
It seems to be caused by toggling the HTTP API on/off. I assume this is due to the recent change with ports?

**Comment by nukeop** [comment]
No idea if it's because of that change, but I tracked it down to `swagger-spec-express`, specifically this line: https://github.com/eXigentCoder/swagger-spec-express/blob/48fd05b98a277f50b78e76eb6f34fe75a5e87ada/lib/generate.js#L21

Trying to get rid of it so we can release.

**Comment by nukeop** [comment]
This can be fixed in a somewhat hacky manner by editing `n.apply` in the compiled js and changing n to `require("async")`. Not sure how to fix it in the long term.

**Comment by nukeop** [comment]
The above won't work in the packaged version though. I need a better solution.

**Comment by nukeop** [comment]
I suppressed the error window for the release, but it breaks loading the api docs (swagger). It complains about swagger.json.

**Comment by Mongogamer** [comment]
The simplest solution would be to wait until the package gets fixed by the author. That might take a while though.

I believe I have successfully modified swagger-spec-express to not throw this error anymore by simply not using `async.apply`. The modified file can be found [here](https://pastebin.com/raw/DmFuKUAr). I have yet to see this error appear again when building with the modified file.

**Comment by Mongogamer** [comment]
My fix got merged into swagger-spec-express and version 2.0.15 was released. Updating the package should fix the issue and allow 20a4e38c8d907333480532ca6894ab80e5e08ab4 to be reverted.

I may have found another issue but I'll have to test around some more. I will open a new issue if I did indeed find a new problem.

**Comment by Mongogamer** [comment]
Since the issues are now fixed I will go ahead and close this.

**Comment by nukeop** [comment]
Thanks. I'm sure this issue will return later, it's a part of an ongoing arms race with Youtube.
