### ISSUE TITLE
Where is Bandcamp??

### ISSUE THREAD

**Issue by Nzzyme** [nukeop/nuclear#367]
Is there some issue with the program currently as I do not see results from Bandcamp. Where is the plug-in for Bandcamp?

**Comment by nukeop** [comment]
We had support for Bandcamp some time ago, but it was dropped after we switched to a new search model. It could be restored in the future, or if some contributor feels like adding it.

**Comment by Nzzyme** [comment]
Really disappointing to know that. I infact recommended a friend to install this because of band camp and now I get this news. Do you have a plug-in that I can install?

**Comment by nukeop** [comment]
We'll surely add support for it in the future, but there's nothing now.

**Comment by sj-on** [comment]
![image](https://user-images.githubusercontent.com/46680993/113971712-f205ae00-9856-11eb-869f-c300ae811970.png)

Hello. Just wanted to know if selecting an option from the dropdown e.g. Bandcamp fetches results only from that service??

**Comment by nukeop** [comment]
This dropdown chooses the provider for metadata, i.e. search results, artist and album data. Yo change the source for streams you need to select it in plugins.

**Comment by sj-on** [comment]
Thanks. I need to learn a lot about this.
