### ISSUE TITLE
Introduce Travis Windows environment

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#368]
https://docs.travis-ci.com/user/reference/windows/

We could automate Windows builds on Travis, which until recently were only possible using Wine, but that would fail to build every time. Now Travis offers Windows environments for building, which might be better for this purpose. Apparently Node is supported so it could work.

Solving this issue would also include the required modifications to .travis.yml to automate building and releasing Windows binaries. Afterwards, we could switch to rolling release model (#288) and release after every push to master.

**Comment by tusharchitti** [comment]
Hi. I would like to work on this issue. This will be my first open source task.

**Comment by nukeop** [comment]
Did you ever use Travis with Windows? I've been building binaries manually for releases, and the procedure is the same as on other systems, but I'm not sure how to do it on Travis (I expect it's not going to be too complicated though). Anyway, your help is appreciated.

**Comment by tusharchitti** [comment]
Hi
I have figure out yesterday how to build it on windows using travis. I made
changes to the travis.yml and deployed it to travis. The build is
successful. I am attaching the screenshot of the build. I will create a
pull request. Please review it once. If it is not correct, let me know. I
will work further on it.



[image: image.png]


Thanks

**Comment by nukeop** [comment]
Windows build works.
