### ISSUE TITLE
Investigate other CI solutions

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#369]
Apparently Travis has been acquired by some sketchy company that immediately fired many people who helped build the system, and they're trying to squeeze more money out of it. Right now, many open source maintainers report slow builds and lower priority, probably to put pressure on free tier users to upgrade. For Nuclear, I've noticed a 20-25% slowdown.

This looks like a good time to consider switching to a different CI provider. I've heard some good things about Circle CI, and Codeship also looks nice. Recommendations and comments are welcome.

**Comment by urielfcampos** [comment]
I found some other options as that are worth taking a look at :
- [Jenkins](https://jenkins.io/) This one is open source and really popular, can be used for CI and CD
- [TeamCity](http://www.jetbrains.com/teamcity/) I just found about this one, but it's a jetbrains product and usually their products are very good, they also have a [free license](http://www.jetbrains.com/community/opensource/) for open source projects, but they have some tough restrictions on it, which might be a big downside to this option.

**Comment by nukeop** [comment]
https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

Github has a CI now, could be a viable option too.
