### ISSUE TITLE
Switch to a different donation service provider (current one: Beerpay)

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#370]
Beerpay only supports payouts via Stripe, which does not support many countries, and it locks our development money out. Stripe also requires an insane amount of extremely sensitive private information to activate an account. 

A different solution is needed, or maybe it could be dropped altogether. Recommendations and comments are welcome.

**Comment by urielfcampos** [comment]
Maybe start using the new service github launched ? [Github Sponsors](https://github.com/sponsors).
I think that's a pretty good option.

**Comment by nukeop** [comment]
I signed up for the wait list already, no reply so far.

**Comment by urielfcampos** [comment]
Ah, how about setting up a [Patreon](https://www.patreon.com/) from what i see, it's a pretty popular option among creators, devs and etc. But I've never used it so i can't comment if it's better than Beerpay.

**Comment by nukeop** [comment]
I think Patreon creates some obligation to deliver new content to the people who pay you. I just want a convenient way for people to donate something if they really really want to (that's why the button is at the very bottom of the readme). I can cover the costs of developing the software and related to that, I have my own business and customers. I just want to make sure we use cost-effective solutions.

**Comment by urielfcampos** [comment]
I see, i looked around a bit and found some FOSS options :
- [Bountysource](https://www.bountysource.com/)
- [Open collective](https://opencollective.com/)
- [Open source grants](https://foundation.travis-ci.org/grants/) This is made by the travis-ci foundation, which you mentioned in issue #369 was acquired by a shady company, so it's not the best option i guess
- [Liberapay](https://liberapay.com/)

[reference](https://itsfoss.com/open-source-funding-platforms/)

**Comment by nukeop** [comment]
I got into the Sponsors beta on Github, so that's what I'll be using from now on.
