### ISSUE TITLE
Switch to a different newsletter subscription service provider (current one: Mailchimp)

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#371]
Mailchimp used to be okay but now they demand exorbitant amounts of money for the service rendered ($30-$70 for sending an email to a list once every few months). Now that there are more than 2500 subscribers, Mailchimp holds the subscription list hostage and refuses to send emails if we don't pay them.

It's time to switch to a different provider. All we need is the ability to store subscribed addresses and send emails to them every now and then. Maybe there's a service somewhere that provides a free tier for open source projects? Recommendations and comments are welcome.

**Comment by urielfcampos** [comment]
Hello !
I looked around a bit and found two options, one is self-hosted and one is a SaaS i think
Self hosted option:
[Mailtrain](https://mailtrain.org/)
SaaS:
[phpList](https://www.phplist.com/pricing) They have a lot of pricing options

The self hosted option is free, but there is the downside of needing to set it up yourself and run it with all the problems that creates

**Comment by nukeop** [comment]
Nice, thanks for the recommendation. It even looks like we'd be able to fit in the $1 plan, at least for a while (we're around 2300 subscribers now).

A selfhosted option would be great, except for two things: 1) most VPS providers charge extra or don't allow sending emails, and 2) Gmail (at least 70% of subscribers) and other mail providers dump everything from small time domains and servers straight into spam.

**Comment by urielfcampos** [comment]
Yeah, That would be a really big downside for the selfhosted option. 
Seems like phpList is a good option, up to 10 thousand subscribers, which is 45 dollars (Not that cheap but also not that expensive i think).

I also found another option :[Mautic](https://www.mautic.org/) It seems like they offer selfhosted and cloud-hosted service, but their site is a bit confusing. Worth a try maybe ?

**Comment by nukeop** [comment]
Top candidate now: https://github.com/knadh/listmonk
