### ISSUE TITLE
Receiving YouTube manifest instead of playback doesn't start audio playback

### ISSUE THREAD

**Issue by Mongogamer** [nukeop/nuclear#377]
- **Nuclear version**: 0.4.5 commit 4841bd427674baa506c5e624e46b63d634a8b57f
- **OS**: Windows 10 Pro x64 1903
- **NodeJS version**: 10.16.0
---
**Description of the issue**: Currently on some very rare occasions audio playback will not start as Nuclear is supplied with a YouTube manifest instead of an audio link. This seems to cause Nuclear to think there is no valid source. Nuclear correctly loads thumbnail, video id and title of the song but playback never starts.

**Expected behavior**: Playback starts normally.

---

**Steps to reproduce**:

1. Set YouTube plugin as default music source.
2. Find any song that returns a manifest (I used Plus Ultra by Shuji Katayama)
3. Attempt to play the song.

---

**Possible solution**: The YouTube source plugin may need to be updated to include these cases. Issue #399 in ytdl-core might be helpful.

---

[Devtools console output when trying to play song with manifest](https://i.imgur.com/F8OnfTW.png)
[Devtools network information of the request](https://i.imgur.com/aw150xt.png)

**Comment by nukeop** [comment]
Thanks for reporting this. I'll update some packages later today and will try to reproduce this.
