### ISSUE TITLE
Shuffle, "go foward" and more

### ISSUE THREAD

**Issue by abacao** [nukeop/nuclear#383]
Some suggestions:

# Shuffle
Shuffle only works if the player itself ends the previous track. 
When I have the shuffle turned on and I skip to the next track, the action it to go to the next music in queue and does not shuffle. I would like to have the same behaviour if the shuffle is on.

# Moving Foward.
Like said before, the shuffle only works if the song ends by itself or if I move foward until the track ends and Nuclear shuffles to the next.
Would like to be able to skip X amount of seconds when "moving foward or back". Maybe a setup in settings

# Tooltips in Settings.
Can you please add tooltips in settings? For example: I don't understand what Autoradio does. Maybe a tooltip will work.

# API
Using the HTTP API in the port 8080 can break some other systems. Could you change it to start with another port by default?
Also, can you provide in the HTTP API settings a link to a reference page to use the API?

Please continue with the awesome work.

**Comment by nukeop** [comment]
1. is sensible.
2. would need the addition of 2 new buttons for skipping a few seconds. The same action can be achieved by clicking the seekbar, so it would be redundant.
3. is a good idea, but maybe it just needs better descriptions that are visible at all times.
4. is configurable in the settings, but I agree that a link to the swagger docs would be nice.

**Comment by abacao** [comment]
2. No need. I'm using the arrows to fast forward but the times could be  setup in the settings.

Another question, it possible to add time played, time to to end of the track?

**Comment by nukeop** [comment]
Sure, definitely. I thought that it's in there something but apparently it's not.

**Comment by nukeop** [comment]
![2019-07-01-234537_1735x88_scrot](https://user-images.githubusercontent.com/12746779/60468584-65c66000-9c5a-11e9-8f2e-4147bedf1e03.png)

I came up with this UI element for displaying the track duration. Can be hidden in the settings. Displayed by default.

**Comment by abacao** [comment]
Will test as soon as it is available and give you my honest feedback

**Comment by nukeop** [comment]
Ok, I just pushed this change to master.

**Comment by abacao** [comment]
Wow, awesome. Will you provide a new release? 0.5.1 perhaps?

**Comment by nukeop** [comment]
From now on we'll switch to continuous releases, as soon as the changes needed to build Windows binaries are merged. This means that there will be a new release with every push, so no need to number them anymore. This will be implemented very soon.

**Comment by abacao** [comment]
Great to know. I can test it in Linux if you want.
The 00:00 is correct? What if the time displayed was at the en of the progress bar and was someting like this:
`02:47/20:30` or if you would like to have the time till the end `-12:34/20:30`

**Comment by nukeop** [comment]
That was a mockup.

In the real program the time on the left corresponds to the time elapsed since the beginning of the song and the time on the right represents the time remaining to the end of the song.

**Comment by nukeop** [comment]
Shuffle is now applied no matter what triggers the change to next/previous track.

**Comment by abacao** [comment]
If you select the "previous track", it will shuffle?
Doesn't make sense for me.

Example: Listening to a future shared playlist. I'm skippings songs with shuffle turned on. 
Skipped one too many and I want to get back to that skipped song. 
If the shuffle works going back, I cannot find the song I skipped by mistake.

I would only enable shuffle going forwards. Going back, I would expect to "go back in history" of the tracks played before.

**Comment by nukeop** [comment]
Since we seem to have different conceptions around this feature, I'll make your version the default and make it configurable in the settings.

**Comment by abacao** [comment]
A toggle in settings is always better (can make everyone happy) :+1:

**Comment by nukeop** [comment]
I added a possibility to adjust the number of seconds skipped when pressing the arrow keys.

**Comment by nukeop** [comment]
I changed the default port to 3100 and added an API docs link to the API settings section. It opens in the default browser. I think that's all for this particular issue.
