### ISSUE TITLE
Adding tracks to favorites from queue

### ISSUE THREAD

**Issue by BuLLHACK** [nukeop/nuclear#385]
I'm using v0.5.0 and I'm triying to add tracks to favorites from the queue while autoradio is on and I'm having only the first track of the queue being added again and again to the favs playlist and I can't even delete duplicates from that list.

**Comment by nukeop** [comment]
You should be able to add the currently playing track to favorites. Wha happens when you click that? Does it only add the first track from the queue?

**Comment by BuLLHACK** [comment]
Exactly! and when I try to drag n drop the track to the list it just gets stuck and displays in a weird way. If you want a video on how it behaves I'll be happy to help

**Comment by nukeop** [comment]
Drag and drop only works within the queue. But if it only adds the first queue item it's definitely a bug, thanks for reporting.

**Comment by BuLLHACK** [comment]
You're welcome, I'll be glad to help if there's something I could do

**Comment by nukeop** [comment]
Fixed!
