### ISSUE TITLE
Create Enzyme tests for all major views

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#387]
We need to create some tests that will let us at least test if all the major views render correctly with some mocked data. This will let us avoid regressions that keep happening recently. This will likely be implemented in parts as there are many different views that need to be safeguarded like that.

"Good first issue" applies to any number of tests, even if it's just one small test for one component.

**Comment by ItzAmir** [comment]
What about snapshot tests? you can test if component renders correctly and also be aware of changes. If you think they can help tell me to start writting them!

**Comment by ItzAmir** [comment]
Are there any components which need to have a test more than others?

**Comment by nukeop** [comment]
Any of the following, in random order:
- Play queue and its items
- Play controls (play button, previous/next)
- Left hand menu
- Album view
- Artist view

All of these are the most important elements that are responsible for the most commonly used functionality.

**Comment by ItzAmir** [comment]
I will work on AlbumView and ArtistView

**Comment by jenyeeiam** [comment]
I just made a PR for the Play controls 
https://github.com/nukeop/nuclear/pull/447

**Comment by mahimshridhar** [comment]
Can i try anything here ?

**Comment by nukeop** [comment]
Sure, pick whatever you like.
