### ISSUE TITLE
Log output to terminal

### ISSUE THREAD

**Issue by abacao** [nukeop/nuclear#388]
In order to understand some issues, I as a user would like to see an output in the terminal.

In the following image, I opened nuclear, loaded a playlist, played some tracks with some skips and no output was shown in the console.

[https://matrix.org/_matrix/media/v1/thumbnail/matrix.org/ueScBsvjzcfRVWUGIKYrkcQJ?width=800&height=600](https://matrix.org/_matrix/media/v1/thumbnail/matrix.org/ueScBsvjzcfRVWUGIKYrkcQJ?width=800&height=600)

ex: some tracks are not being played. The track loads (name), is in play mode but no progress or sound. I need to skip to the next track in order for nuclear to get out of that "hole" because If i don't skip, it stays like that forever.

**Comment by nukeop** [comment]
I improved logging, all errors during stream lookup will now be logged via electron-timber.
