### ISSUE TITLE
server refacto

### ISSUE THREAD

**Issue by charjac** [nukeop/nuclear#393]
This part of the app is a little messy (and absolutely untestable).
I propose to refactor it using http://inversify.io/ and homemade decorators to manage ipc (in the way https://docs.nestjs.com/controllers does for http routes).
And then add minimal tests.

**Comment by nukeop** [comment]
dependency injections is doable without any frameworks in js, but if you know this tool and want to use feel free to do so. I might learn something new too. then we might try to use higher order components to on react's side to provide ipc methods to some containers.

**Comment by charjac** [comment]
i just made this lib: https://github.com/charjac/electron-api-ipc

**Comment by nukeop** [comment]
cool, this makes ipc less of a pain to work with, and way more testable too
