### ISSUE TITLE
Containers share common code.

### ISSUE THREAD

**Issue by olafur-palsson** [nukeop/nuclear#396]
Majority of the lines that are unique are found in render functions, which is a relatively small part of each file.

**Comment by nukeop** [comment]
This is a consequence of the organic growth of the codebase. Containers also need to have their mapStateToProps and mapDispatchToProps, which are going to end up pretty similar most of the time. Can you provide any examples of code that could be refactored?

**Comment by olafur-palsson** [comment]
I'll start working on a prototype container when I get back to my laptop. (I'm on vacation but I wanted to add this to my todo-list)

**Comment by nukeop** [comment]
Cool, keep me updated.

**Comment by nukeop** [comment]
We've refactored the code in a huge way since then, I think this can be closed now.
