### ISSUE TITLE
Translation Wiki page?

### ISSUE THREAD

**Issue by lizzyd710** [nukeop/nuclear#398]
Might I recommend making a wiki page for how to translate nuclear? That way all the information is in one place and easy to find for people that are interested in translating. Or if the wiki isn't really your style I could write up a translating.md file or something.

**Comment by nukeop** [comment]
This is a good idea. As a start, I copied @charjac 's post here: https://github.com/nukeop/nuclear/wiki/Translating

Feel free to propose any changes.
