### ISSUE TITLE
button PlayNow in context menu of track doesn't have implementation

### ISSUE THREAD

**Issue by G-Milevski** [nukeop/nuclear#403]
Hello.
When i am investigating project I found that button playNow has action playSong but the action doesn't have implementation. In console is had an error "Uncaught TypeError: actions.playSong is not a function".

I can try to fixed this issue.

I'm sorry if this issue is duplicate. I newbie in opensource comunity. It's project my first try =)

**Comment by olafur-palsson** [comment]
I think this could be caused by the doubleclick thing that was added today. The problem should be related to 'TrackRow' and 'TrackPopupContainer'.

**Comment by G-Milevski** [comment]
@olafur-palsson Thanks for your fast answer and fixing.

**Comment by nukeop** [comment]
Fixed by that pull request.
