### ISSUE TITLE
nukeop link in help button opens in app

### ISSUE THREAD

**Issue by locness3** [nukeop/nuclear#406]
Clicking the "?" button at the top-right, and then clicking the "nukeop" link gives this :
![Screen Shot 2019-07-14 at 13 22 15](https://user-images.githubusercontent.com/37651007/61182912-612a8000-a63a-11e9-87e5-72f7c2325b9d.png)

**Comment by nukeop** [comment]
Thanks for showing me, I'll change it so that it opens in the default browser instead.

**Comment by locness3** [comment]
Ok.
