### ISSUE TITLE
Graphic designs contributions are welcome

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#412]
This isn't really an issue, but an attempt to encourage potential non-technical contributors.

We welcome all kinds of contributions, not only code. In particular, I'd like to make clear that graphic designs of all kinds are also very much appreciated. Example of what could be contributed in this regard:

- A graphic illustrating a proposed redesign of some functionality to improve its UX
- A new logo proposal
- A proposal of a completely new skin for the entire program
- Graphic assets for the official website, such as backgrounds, screenshots, or images
- Advice regarding the UX design of some functionality
- CSS changes to improve styling
- Merchandise designs, such as stickers or t-shirts
- Ideas for new functionalities, possibly with mockups illustrating a proposed GUI

Those are just some of the things you could contribute if you're not coding, but would still like to help. You can even do it without using git at all, just open an issue and we'll help you find the best way to add whatever you create.

**Comment by awalus** [comment]
Hello, I have some suggestion for a logo. (It's not ready yet, it's just an idea.)

![Nuclear Logo Proposition](https://user-images.githubusercontent.com/55683811/68019035-e776da80-fc9a-11e9-8741-49578be77aa3.png)

**Comment by CodeWithBlaze** [comment]
hello i want to contribute to this project .i have never cotributed before please guide me how can i get started in this project

**Comment by nukeop** [comment]
What would you like to contribute?

**Comment by CodeWithBlaze** [comment]
i am a coder . i know javascript and java almost 60% and i like your project and just want to contribute . so anything for me??

**Comment by nukeop** [comment]
Almost 60% of what?

**Comment by CodeWithBlaze** [comment]
java and javascript

**Comment by nukeop** [comment]
You can look at the open issues and pick anything in the bug or feature request category.

**Comment by CodeWithBlaze** [comment]
Okkk thnx
