### ISSUE TITLE
Local File Not  Found

### ISSUE THREAD

**Issue by modernduck** [nukeop/nuclear#413]
![Screen Shot 2562-07-23 at 11 22 46](https://user-images.githubusercontent.com/12221877/61682551-522f8600-ad3c-11e9-97a2-e774f693afd5.png)
Hi I'm try to use the local file (.m4a) to see if this work but won't find any song in the list. 

Is it because it not support .m4a ? if so How do I find how many file type it supported. thank you

**Comment by nukeop** [comment]
Yep, the supported extensions are here: https://github.com/nukeop/nuclear/blob/2461dab74b2f35dcb419a45854da50c9a8193e1d/server/local-files.js#L40

However, those are only the ones we scan for, it's possible that we could just add m4a to the list and it would work. Needs some testing.

**Comment by nukeop** [comment]
I added support for more formats but m4a seems to be unsupported by the audio api: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats
