### ISSUE TITLE
Release after every push to master

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#415]
Ideally I'd like to have new binaries available after every push to master. This requires some fiddling with electron-builder, and I'm not sure yet how to completely automate that. I'll do that at some point, but if anyone wants to contribute, feel free to take this issue.

Would also be nice to automatically build & release snap packages and flatpaks.

**Comment by brianRey2017** [comment]
I would like to contribute if you still need help. 
Some advice about how can i tackle it :dog2: ?

**Comment by nukeop** [comment]
We already have some comprehensive CI configured here: https://github.com/nukeop/nuclear/blob/master/.travis.yml

You could either look at electron-builder docs (which are kinda bad) and figure out how to force it to publish on every push, or alternatively just build the artifacts on travis and use travis' publshing mechanism. Currently, electron-builder only publishes on tagged commits.

**Comment by brianRey2017** [comment]
I can tackle this the weekend if that's ok for you :sweat_smile: .

**Comment by nukeop** [comment]
Of course, thank you for the help.

**Comment by brianRey2017** [comment]
Can you assign it to me?

**Comment by brianRey2017** [comment]
I am without laptop for now. Is this urgent? In that you can assign it to another person if you want

**Comment by nukeop** [comment]
No problem, take as much time as you need.

**Comment by JurisMajors** [comment]
iirc there are no snap/flatpack packages for this project.

So, what exactly you'd like the CI to do is unclear to me.

**Comment by nukeop** [comment]
Why would snaps and flatpaks be required for publishing from CI?

**Comment by nukeop** [comment]
And btw, there is a snap package: https://github.com/nukeop/nuclear/releases/download/v0.5.1/nuclear-7e3bac.snap

**Comment by JurisMajors** [comment]
> Why would snaps and flatpaks be required for publishing from CI?
In the original issue description:
> also be nice to automatically build & release snap packages and flatpaks
Nevertheless, I'd like to take this up, but i have never worked with electron before.
What exactly do you expect from a `publish` step? Where does the binary go? Where can I how electron-builder is called for the tagged commits?

**Comment by nukeop** [comment]
For now we publish to Github releases, but I'm working on getting added to snap store.

I'd like to move away for Travis now that we have Github actions. Apparently electron-builder detects tagged commits automatically, but I wasn't able to figure out how to make it publish on every push. Apparently passing `--always` is not enough:

https://github.com/nukeop/nuclear/blob/master/packages/app/package.json#L20

I was thinking that maybe we can forgo that mechanism altogether, and only use it to build binaries, then publish manually in a different way. If you decide to try this issue the decision is all up to you.

**Comment by nukeop** [comment]
https://snapcraft.io/nuclear

**Comment by nukeop** [comment]
Done in a way
