### ISSUE TITLE
[Linux] desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [nukeop/nuclear#42]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).

Reference: https://github.com/AppImage/AppImageHub/issues/2

**Comment by nukeop** [comment]
Thanks, this will be fixed in the new (rewritten from scratch) release.
Here's the branch this is on: https://github.com/nukeop/nuclear/tree/rewrite

And here's the specific line:
https://github.com/nukeop/nuclear/blob/48db31cd847563e5d401f84f2ec0113b7ee6f643/package.json#L105

I've also updated electron-builder to the newest version.

**Comment by probonopd** [comment]
Thank you. Please ping me once the new release is out so that I can include it in the AppImageHub central repository of AppImages.

**Comment by nukeop** [comment]
The appimage should have correct categories set now.

**Comment by nukeop** [comment]
@probonopd

**Comment by probonopd** [comment]
Thanks,
