### ISSUE TITLE
I can't play music behind a proxy server

### ISSUE THREAD

**Issue by UsernameIsAlreadyTakenByMe** [nukeop/nuclear#420]
Hi,

I'd like to play music behind a proxy server. Could we use default network settings of windows or add separate proxy settings in nuclear?

Cheers,
Zoli

**Comment by nukeop** [comment]
I don't know how it works in Windows, we'll need to figure that out and probably add a section for these settings.

**Comment by devcshort** [comment]
I'd be willing to take a look in to this

**Comment by nukeop** [comment]
Cool, thank you.

**Comment by devcshort** [comment]
I've yet to contribute to open source projects, so I'm not sure how this works.

However from what I could find, it seems like the best route to go with this, is to use Electrons ["net"](https://electronjs.org/docs/api/net) api. It allows doing http(s) requests using Chromium's native networking which is able to handle the proxy settings on the system.

- Automatic management of system proxy configuration, support of the wpad protocol and proxy pac configuration files.

- Automatic tunneling of HTTPS requests.

- Support for authenticating proxies using basic, digest, NTLM, Kerberos or negotiate authentication schemes.

- Support for traffic monitoring proxies: Fiddler-like proxies used for access control and monitoring.

**Comment by nukeop** [comment]
We're using fetch everywhere for requests, switching to Electron's net api would involve a lot of work, unless you have an idea for integrating this with isomorphic-fetch.

Apparently there's a drop-in replacement for isomorphic-fetch that works behind a proxy: https://www.npmjs.com/package/fetch-with-proxy

Might be worth investigating. If you have any questions regarding contributions, let me know and I'll try to explain everything and help you.
