### ISSUE TITLE
Nuclear refuses to play

### ISSUE THREAD

**Issue by f0x52** [nukeop/nuclear#422]
Browsing/searching songs work fine, and they appear in the 'now playing' bar, but they won't ever start playing.
This might be due to a YouTube api change, but there doesn't seem to be any error output anywhere. Playing worked just fine two days ago

I'm using the latest AppImage release on debian

**Comment by nukeop** [comment]
I'm pretty sure this is an issue with ytdl-core, but would you be able to provide any specifics? Like what songs you've tried to play, and if their streams loaded correctly (you can check that by rightclicking them in the queue)?

**Comment by f0x52** [comment]
I've tried with multiple songs, so quite certain it's a general issue. When trying Portal: Still Alive by Jonathan Coulton, the metadata loads but that's it:
![image](https://user-images.githubusercontent.com/23422690/62402811-d29a8600-b589-11e9-9616-e16da3e79ae7.png)

**Comment by nukeop** [comment]
Yes, I seem to be getting the same bug here for some reason. I'll see what I can do about that.

**Comment by nukeop** [comment]
This was caused by youtube's shenanigans. Updating ytdl-core seems to have fixed the issue.
