### ISSUE TITLE
Music not loading anymore

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#425]
Hi, I recently retried nuclear after a couple of weeks.
I can't get the musics to load anymore (on PC and mac) on dev and release versions... Is it a known issue ?
I can add tracks to the playlist, but it always stays in "loading" mode. Is it something to  do with  a youtube api key quota or something like this ??

**Comment by nukeop** [comment]
Yeah, I released 0.5.1 to fix that. It was an issue with ytdl-core.
