### ISSUE TITLE
Could you rename the new binaries of the new release to fit the naming scheme of the other versions?

### ISSUE THREAD

**Issue by mikelpint** [nukeop/nuclear#427]
Otherwise, I cannot update the AUR package.

**Comment by nukeop** [comment]
Thanks for notifying me.
Soon we'll be switching to a model where we release a new version on every push to master, and I planned to name them with the commit hash instead of semantic versions. Is it possible to switch to such a model from your side?

**Comment by mikelpint** [comment]
I'll try.

**Comment by mikelpint** [comment]
There are two tags for the 0.5.1 version. Can you fix that issue?

![Captura de pantalla de 2019-08-03 20-58-36](https://user-images.githubusercontent.com/25373557/62415893-8a36a300-b631-11e9-83a7-d5bfaa7ea2fb.png)

**Comment by nukeop** [comment]
I deleted that tag earlier (it was created 1 commit too  early) then created it again on a newer commit.

**Comment by mikelpint** [comment]
No problem, I'll use that name.

**Comment by nukeop** [comment]
Great, thanks. Will it cause you any trouble if we switch to a continuous release model? Are you able to automate it?
