### ISSUE TITLE
Migrate to Jest for testing

### ISSUE THREAD

**Issue by karevn** [nukeop/nuclear#435]
It's more contemporary and provides a lot of features out-of-the-box. And I'm willing to do that  as soon as https://github.com/nukeop/nuclear/pull/430 will be merged.

**Comment by nukeop** [comment]
What does it have that mocha+enzyme don't provide? I'm pretty sure these two are as contemporary as it gets since they're still actively maintained.

**Comment by karevn** [comment]
It's just an all-in-one solution that's very close to Mocha when it comes to the API, plus quickly becomes a de-facto standard for JS testing. So, it's like Electron after nwjs :) We use it as our everyday testing framework at my daytime job, and can't be any happier.

**Comment by nukeop** [comment]
I am... not really convinced, especially since we already have some nontrivial amount of tests written using mocha and enzyme, but I do remain open to any changes that improve and simplify our code. If anything, I really took a liking to ava, thanks to a very simple api, flexibility, and multi threading.

**Comment by karevn** [comment]
I'll take a look at it too!
Jest runs tests in parallel by default, btw, and does a great job supporting Enzyme and mocks of all kinds - I used to work with sinon, "bare" chai, so on, and was sold to Jest the moment my colleagues wrote the very first piece of code using it :)

**Comment by nukeop** [comment]
I changed the testing library  in the ui package to jest, ava was giving me problems with typescript.
