### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by mikelpint** [nukeop/nuclear#44]
I am writing an AUR package at the moment. The name will be nuclear-player.

**Comment by nukeop** [comment]
Cool, remind me to add it to Readme.md when you're done.
Or you can do it yourself and make a pull request.
Would you like to be notified on new releases so you can update the package?

**Comment by mikelpint** [comment]
Yes, that would be cool.

**Comment by mikelpint** [comment]
I will pull resquest the package in 7 hours because I have go yo the school  :(

**Comment by nukeop** [comment]
I added your package to readme.

**Comment by nukeop** [comment]
I saw the discussion on AUR, I was experimenting with releasing through travis and the first few builds were unstable. This one is ok, and built correctly with mpris support.
