### ISSUE TITLE
Add "Favourite artists" section - the same way it's done with albums

### ISSUE THREAD

**Issue by karevn** [nukeop/nuclear#448]
The title says it all :)

**Comment by nukeop** [comment]
Yep, it's in the pipes - I'll get around to it eventually, I just don't have too much free time lately.

**Comment by karevn** [comment]
I can take care of it, gotta some energy to spend on contributing.

**Comment by nukeop** [comment]
Awesome, much appreciated. If there are any improvements to the currently existing views for favorites, feel free to let me know. I was thinking about switching to a single tabbed view too, if that's something that sounds interesting to you, you could try implementing it as well.

**Comment by karevn** [comment]
I think it's good as it is - you're always one click away from any type of favorites you want. Having them in separate tabs on the same page would add one useless extra click.
