### ISSUE TITLE
Can't add local high definition music

### ISSUE THREAD

**Issue by taneher** [nukeop/nuclear#450]
I can't seem to add these songs to my local library. When I go to 'Local Library' --> 'Add folders' and select either my whole music library (with mixed songs, mp3, FLAC, AAC, M4A) or a folder with only FLAC or M4A, it is not getting loaded. 
However, if the added folder only contains MP3 files, it loads without any problem. 
Is this a bug or is FLAC/M4A simply not supported (yet)?

Running Nuclear 0.5.0 installed from .deb on a Debian Unstable (Kernel 4.19.0-5)

**Comment by nukeop** [comment]
Hi, thanks for the feedback. Currently, we only scan a limited subset of formats: https://github.com/nukeop/nuclear/blob/2461dab74b2f35dcb419a45854da50c9a8193e1d/server/local-files.js#L40

I'm not sure if FLAC (and other formats) are supported by HTML5 audio API. If this is something the users (like yourself) want, we'll need to take a look at it soon.

**Comment by taneher** [comment]
Hey, thanks for the quick reply to confirm that it‘s not a misconfiguration on my part. 

According to [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats) FLAC should be supported (except for Opera and IE, which shouldn’t be a problem for Electron).

**Comment by nukeop** [comment]
It will scan and add flac and aac now.
