### ISSUE TITLE
Add links to the "about" modal

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#452]
Links to mastodon, twitter, github, etc. need to be added to the help window that currently displays some basic information.

**Comment by jenyeeiam** [comment]
Do you have the mastadon svg? It's not available in the font-awesome version 4.7

**Comment by nukeop** [comment]
Yep, there's one here: https://github.com/nukeop/nuclear/blob/gh-pages/_includes/icons/mastodon.svg
