### ISSUE TITLE
Remove from favorites not working

### ISSUE THREAD

**Issue by emlautarom1** [nukeop/nuclear#456]
Currently you can't remove a favorite using the `X` button in any song. Seems like a the action `REMOVE_FAVORITE_TRACK` gets dispatched but makes no effects.

**Comment by emlautarom1** [comment]
So, it looks like the remove functionality depens on the track `uuid` wich is missing, so the favorites lists never gets updated. I don't know where this `uuid` should be coming from.

Adding to favorites does not store a `uuid`. Should we generate it when adding a track to favorites?

**Comment by nukeop** [comment]
uuid is added to all tracks here: https://github.com/nukeop/nuclear/blob/master/app/actions/queue.js#L19

Sometimes when you add a track from a different source, this uuid might be missing. I added code to add this uuid when adding tracks to favorites if it's missing.
