### ISSUE TITLE
Duplicated/Repeated favorites

### ISSUE THREAD

**Issue by emlautarom1** [nukeop/nuclear#457]
Currently you can add a track multiple times to favorites, resulting in duplicated/repeated entries.

A expected behaviour should be that the user can't add a track once it's already in favorites, disabling/hidding the option to `Add to favorites`.

For example, here I have **"bad guy"** twice in my favorites:

![duplicated_favorites](https://user-images.githubusercontent.com/31224949/63228049-2c26c580-c1c4-11e9-9edf-5e5cd8ebf78f.png)

Also, as you can see, even if the track is already in favorites, the popup still displays the action.

![add_twice](https://user-images.githubusercontent.com/31224949/63228057-5bd5cd80-c1c4-11e9-808a-9e4ecd4b87a0.png)

**Comment by s0meon3** [comment]
hey @nukeop I'd like to take a look and try to fix it as my first contribution, could you tell me where do I start? Where do you store the favorited musics and where is the pop-up component?

**Comment by nukeop** [comment]
Favorites are stored in redux and sync'd with the config file on disk, related actions can be found here: https://github.com/nukeop/nuclear/blob/master/app/actions/favorites.js

The logic controlling whether the popup has certain buttons is here: https://github.com/nukeop/nuclear/blob/854795b1b7b55d1629c84bad94023413788e7bd0/app/components/TrackRow/index.js#L111

The solution to this problem should involve switching to comparing tracks for equality by artist name and song title, instead of unique ids like it's being done right now.

**Comment by nukeop** [comment]
1. Nope, it's fairly complicated. But luckily, it's been done many times already, so there's plenty of examples.

There are some special components called containers: https://github.com/nukeop/nuclear/tree/master/app/containers

These containers are created by processing regular components with a higher order component `connect`, which accepts two functions: `mapStateToProps` and `mapDispatchToProps`. `mapStateToProps` defines what subtree of the whole Redux store will be available to the container, and whatever keys you select will be passed as props to the container. You can see this mechanism in action in pretty much all of the containers in the project. The containers then pass their data to the components lower in the rendering tree.

2. The part you linked are default props, which are applied whenever there's no prop with the corresponding name passed. To control whether a popup has the favorites button, you'll need to set `withAddToFavorites` in the `TrackRow` component in the view you're interested in. You can either pass a boolean value, like here: https://github.com/nukeop/nuclear/blob/c8db4e1af1b7fa7883a0224499e7f3e76312b087/app/components/FavoriteTracksView/index.js#L64

Or you could pass a more complex expression that e.g. determines if a track is already on the favorites list.

**Comment by mahimshridhar** [comment]
Can i take this ?

**Comment by s0meon3** [comment]
I'm having some problems with my laptop so yeah, go on
