### ISSUE TITLE
Certain songs not playing

### ISSUE THREAD

**Issue by nathanwfranke** [nukeop/nuclear#466]
I am on version 0.5.1-953

It seems that certain songs do not play at all.
For example, search "Dimrain47 109650" and the first few results will be stuck on pause.

**Comment by SjefVelthuizen** [comment]
unsubscribe

Op 1 september 2019 16:51 uur schreef Nathan Franke <notifications@github.com>:



I am on version 0.5.1-953

It seems that certain songs do not play at all.
For example, search "Dimrain47 109650" and the first few results will be stuck on pause.

**Comment by nukeop** [comment]
Does it find any videos for that song?

If you can, could you try downloading that with youtube-dl to see if it'll work? Or adding it to downloads in nuclear?

**Comment by ctsstc** [comment]
When I right click the song in the queue it just says "Stream still loading"

**Comment by Mongogamer** [comment]
Commit 5c4bd7020ba5a170d55c69941a00d8fdf8586362 seems to be able to play all of those songs. Can you confirm if any are still unplayable?

**Comment by nathanwfranke** [comment]
@Mongogamer Thanks, I built the latest and I can play these songs now. I will re-open this if I get further problems.
