### ISSUE TITLE
[Feature Request] Play next button

### ISSUE THREAD

**Issue by mmboyce** [nukeop/nuclear#476]
### An option to insert a song to play next on the queue

Let's say you already have a queue of multiple songs, and you want to have a song you searched to be the next song to play.

Instead of either hitting Play Now and clearing the queue in the process, or adding to the queue and dragging it to the top I'd like to propose a play next button!

1. Click on the song
2. Select play next button in the popup menu
3. Voila

**Comment by Tarotato** [comment]
Hi, can I have a go at this?

**Comment by GordonDrop** [comment]
Anyone works on issue? I'd like to implement the feature.

**Comment by Tarotato** [comment]
Yes! I am

**Comment by GordonDrop** [comment]
Haven't noticed PR. Sorry :)

**Comment by MadRealm** [comment]
Hey, I saw that the PR adressing this issue still hasn't been closed, is this issue still available ?

**Comment by HaiDang666** [comment]
I'm gonna work on this
