### ISSUE TITLE
Allow choice of audio download format (and auto-tagging?)

### ISSUE THREAD

**Issue by klongmore** [nukeop/nuclear#478]
**Nuclear Version 0.5.0**

*Arch Linux (i3) using recommended AUR package.*

When downloading, I am not given the option to download in anything other than .m4a. This is an issue, as 'Local Library' will only see tagged mp3 files.

Therefore, if I want to download and then play a song with Nuclear, I must 

1) Download the song 

2) Use a third-party converter to convert the file from a .m4a to a .mp3 

3) Use 'EasyTag' (or similar) to tag the .mp3 file.

To avoid this, the user can be given the option to download in other formats (e.g. mp3). 
To avoid having to tag the audio files also, these could be auto tagged as:

*Title:* Name of video
*Author:* Unknown Artist

... or something similar.

**Comment by nukeop** [comment]
I think m4a is supported in local files now, maybe it's not released. At any rate, the format it downloads in is what youtube exposes. To change the format we'll need to convert. Maybe the manual process could be automated by using third party tools and tagging the output file.

**Comment by klongmore** [comment]
Do you have any instructions on how to build this myself if I'm on arch? I found some build tutorials, but they aren't relevant to arch-based systems (and although the AUR package is great, it's lagging behind a bit). Cheers!

**Comment by nukeop** [comment]
Pretty sure this should work on all distros: https://github.com/nukeop/nuclear#development-process

If you don't want to use docker, run `npm install`, followed by `npm run watch` and in a separate terminal, `npm run electron:dev`. This should open the development version. For the production version, check the releases tab on Github, there are many formats available including appimage and plain tar.gz.

**Comment by D-u-c-k-s-e-l** [comment]
I have the same issue but with `.wav` files. Nulear does not read the files' tags.
I have tried clearing the cache and reopening but nothing seems to work here.
I'm stuck between using `.mp3`s and not being able to group by artist.

**Comment by nukeop** [comment]
Transcoding added in https://github.com/nukeop/nuclear/commit/ac8bdac813613e02826bb58fde73a7353908e96e
