### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by mikelpint** [nukeop/nuclear#48]
Is Spotify going to be avaliable as a service in the app?

**Comment by nukeop** [comment]
Likely not; I don't want to use their proprietary javascript (the official sdk or the web api) in the program, as that would make it subject to any rules Spotify wants to enforce, and I found it very hard to reverse engineer the communication protocols the web client uses.

I don't know how feasible it is to decode their streams via scraping and some clever math, but it would be the motherlode when it comes to nuclear.

**Comment by mikelpint** [comment]
Ok 😄

**Comment by Cl1608Ho** [comment]
And even then they would probably be able to enforce rules like "by using Spotify as a source of music you agree to xxx"

**Comment by nukeop** [comment]
If I were able to scrape and decode the streams myself, they wouldn't get to enforce anything.
I could try applying for an api key and use the Spotify SDK, then let users log in from nuclear, but if that's in violation of their terms of service, my key would be revoked and the functionality would be instantly broken. I don't want any companies to have any power over my program, so I cannot include that.
