### ISSUE TITLE
Download song via Queue

### ISSUE THREAD

**Issue by syncrocat** [nukeop/nuclear#480]
Currently you can only download songs by setting them as the active song and using the top-right menu, or through the main UI section. Being able to download directly from the queue through the song's context menu would be nice

**Comment by jairathnem** [comment]
Anyone working on this? I would like to work on this.

**Comment by jairathnem** [comment]
Trying to get this setup on windows, I get the below error when running "npm run electron:dev". Am I missing something?
![image](https://user-images.githubusercontent.com/6557230/66013479-f77b7e80-e490-11e9-9ce3-3b123a9b5803.png)

**Comment by badsketch** [comment]
I'm getting the same error.

Wondering if @Mongogamer is still able to build and run on windows?

**Comment by Mongogamer** [comment]
Looks like [Bluebird](https://github.com/petkaantonov/bluebird) was updated to version 3.7.0 and is causing this issue. You can fix this by going to `nuclear/packages/app/package.json` and replacing `"bluebird": "^3.5.3"` with `"bluebird": "3.5.3"`. After that it compiles fine again.

**Comment by badsketch** [comment]
Why didn't I think to look there? Awesome find! Works for me now.

**Comment by nukeop** [comment]
I'll update the dependency to make sure it builds

**Comment by jairathnem** [comment]
This is what I have come up with so far. 
![image](https://user-images.githubusercontent.com/6557230/66438727-2e9ee200-e9f3-11e9-8b3f-a25320289836.png)

**Comment by nukeop** [comment]
Could you move the button to the context menu? It contains more actions that act upon the currently playing item, and logically most people would expect to find it there. Thanks for contributing!

**Comment by jairathnem** [comment]
The context menu has a download option already?
![image](https://user-images.githubusercontent.com/6557230/66445318-ffe13580-ea0b-11e9-8843-f0fe14337264.png)

**Comment by nukeop** [comment]
Sorry, not this one. I meant the one that appears after clicking a particular song.

**Comment by jairathnem** [comment]
Did you mean this one? 
![image](https://user-images.githubusercontent.com/6557230/66526328-ded91d00-eabd-11e9-88b9-83a53184564f.png)
Sorry, just checking to make sure.

**Comment by nukeop** [comment]
Or alternately, there could be an additional menu bar at the bottom of the queue that will feature buttons letting you download the current track, and do other stuff with it. Your call.

The right side of the queue item will instead have the duration displayed.

**Comment by jairathnem** [comment]
I feel that would be too many menus for the current song. We already have the "..." menu and the "source, stream, track" menu. I am a bit confused on this honestly. UI is just not my thing I guess :)

**Comment by nukeop** [comment]
I suppose. But still, I would rather not place any buttons other than "delete" in the queue item itself. Maybe you're right that we should avoid adding new buttons to the context popup too.

I have a better idea - enable dragging queue items directly to downloads list to start the download. Not sure how to accomplish this yet.

**Comment by Ayplow** [comment]
Are you still working on this @jairathnem ?

**Comment by jairathnem** [comment]
@Ayplow If you read the comments above the original idea is not being implemented/wanted. I am not sure how to proceed with dragging items into downloads directly. I havent researched into it yet. You can work on it if you'd like.

**Comment by TheThinker277** [comment]
Hi @nukeop, Is anyone working on the drag and download feature?

**Comment by nukeop** [comment]
It's already been implemented via the context menu
