### ISSUE TITLE
Download status stuck at "Waiting"

### ISSUE THREAD

**Issue by syncrocat** [nukeop/nuclear#481]
Download reaches 100% and file appears locally and is playable. However, the status does not change from waiting to done and the "Clear finished tracks" button has no effect.

After clicking the button and restarting nuclear, however, the track was already properly cleared.

![image](https://user-images.githubusercontent.com/19702661/65482197-39d80680-de66-11e9-8ce3-84a869b6d572.png)

**Comment by billy-le** [comment]
Hello syncrocat, I would like to take a look at this.

**Comment by nukeop** [comment]
Nice, thanks for offering your help. I'm not sure where to start debugging, but this has to be a problem with the interprocess communication. Maybe some messages from the main process aren't getting processed?

**Comment by jenyeeiam** [comment]
I don't see this behavior. Has it been resolved?

**Comment by billy-le** [comment]
I haven't started work on this yet. Can someone confirm that this bug exists?

**Comment by ctsstc** [comment]
This is going on for me, but it stays at 0, this happens with some songs like "billie eilish - bad guy" but not for "Mariah Carey - All I Want for Christmas"

**Comment by rNoz** [comment]
This issue affects me.

My version: 0.5.0

Eg. I search "rozalen", then I click in "Comiendote a besos" > Play. It never starts. Right click: "Stream still loading".

In the terminal:

```
renderer › Error while looking up streams for Rozalén Comiendote A Besos on Soundcloud
renderer › {}
renderer › Error while searching  for Rozalén Comiendote A Besos on Youtube
renderer › {}
```

If I try to download it:

```
renderer › {}
renderer › Error while looking up streams for Rozalén Comiendote A Besos on Soundcloud
renderer › {}
renderer › Error while searching  for Rozalén Comiendote A Besos on Youtube
renderer › {}
    main › Error: This video is unavailable
    at t.getBasicInfo (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:356:22043)
    at t.cache.has.r (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:356:23176)
    at o (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:356:21116)
    at PassThrough.n.on (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:263:36493)
    at PassThrough.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
renderer › { error: {} }
renderer › {}
```

It happens with more songs.

**Comment by nukeop** [comment]
I think it's because of old ytdl-core. It should be gone in 0.6.0.

**Comment by tiotrom** [comment]
Same here. Nuclear version 0.6.3 on Arch Manjaro

**Comment by nukeop** [comment]
Improvements implemented by @mahendraHegde recently should make downloads way more resilient soon.

**Comment by ifndev** [comment]
0.6.3, download status is stuck on waiting, and no file is downloaded
