### ISSUE TITLE
Deleting tracks from the queue also adds random track to the queue

### ISSUE THREAD

**Issue by sajjadpz** [nukeop/nuclear#486]
I have added few tracks to the queue and after I tried to delete them, every-time I press delete, it gets deleted however a new track is automatically added to the queue.
`version 0.5.0`

**Comment by nukeop** [comment]
It's the autoradio setting, that adds new tracks automatically if the queue is at the last track. You can disable it by clicking the magic wand icon or doing so in the settings.

**Comment by sajjadpz** [comment]
Got it, it however also adds two tracks for the first time, Which imo isn't a good user experience. Shouldn't it only add the track while the _delete song actions_ is called.

**Comment by nukeop** [comment]
Yeah, maybe it is overzealous. I'll mark this as a bug.

**Comment by sajjadpz** [comment]
May I take it up then? What would you suggest from which part of codebase I should start debugging it. I have recently cloned the project and fairly new to the codebase.

**Comment by nukeop** [comment]
That would be really great.

The best place to start debugging is here: https://github.com/nukeop/nuclear/blob/b9feeb853b5c5644a36442e33d21fca3075a3d01/packages/app/app/containers/SoundContainer/index.js#L53

This is where the tracks are added. As you can see there is only a simple condition that checks if a track should be added, which in this case doesn't give us the behavior that we expect. Coming up with a better condition will be the key here.
