### ISSUE TITLE
A file is being downloaded even though download queue is empty

### ISSUE THREAD

**Issue by badsketch** [nukeop/nuclear#489]
Even when the download queue is empty, it allows me to click 'download', and an unknown file begins downloading. This file becomes `undefined - undefined.m4a`. 

<img width="299" alt="Screen Shot 2019-09-30 at 11 00 55 PM" src="https://user-images.githubusercontent.com/8953212/65931078-3993ba00-e3d6-11e9-9d90-344e0d5c0b93.png">
<img width="744" alt="Screen Shot 2019-09-30 at 10 57 33 PM" src="https://user-images.githubusercontent.com/8953212/65930974-cc802480-e3d5-11e9-91b7-5dd42d19913b.png">
<img width="219" alt="Screen Shot 2019-09-30 at 10 57 41 PM" src="https://user-images.githubusercontent.com/8953212/65930979-d0ac4200-e3d5-11e9-98b0-ac14694ca011.png">

Could I tackle this issue? Possibly remove the option to download when the queue is empty? Open to other suggestions. Would love to contribute.

**Comment by nukeop** [comment]
Yes, this is a good idea. I'll be very glad if you decide to fix it.

**Comment by badsketch** [comment]
Sweet, I'm on it!

I could remove the download option if the queue is empty, but after looking at `<QueueMenuMore />, it seems like none of the options would apply if the queue is empty.
<img width="159" alt="Screen Shot 2019-10-02 at 12 11 16 AM" src="https://user-images.githubusercontent.com/8953212/66017603-88f6ea80-e4a9-11e9-8527-037779899009.png">

There's no queue to clear, no playlist to save, no current track, etc. 
Therefore, do we want to maybe remove the QueueMenuMore vertical `...` button entirely if the queue is empty?

**Comment by nukeop** [comment]
Maybe don't remove it altogether but disable it instead?

**Comment by badsketch** [comment]
Gotcha, so reduce opacity and make it non-clickable?

**Comment by nukeop** [comment]
Yes. You could grep the code for "disabled" and see what styles are applied to other such buttons.
