### ISSUE TITLE
Add shuffle and repeat

### ISSUE THREAD

**Issue by as3mbus** [nukeop/nuclear#49]
sorry i keep adding issues, but i'm really interested in this music player. so just as the title says it would be nice to add shuffle and repeat to the play queue.
oh yeah is there any guide on how to build the rewrite one, since there r no readme files. i'd really like to try XD.

**Comment by nukeop** [comment]
I added it to the to-do list for 0.4.0: https://github.com/nukeop/nuclear-rewrite/projects/1
It's great to see someone enthusiastic about my program, so don't feel bad about opening new issues.

To build the dev version of the rewrite project, do the following:

- Check out https://github.com/nukeop/nuclear-rewrite
- cd into the project's directory and run `npm install`
- `npm start`

I tested this on Mac OS and GNU/Linux.

**Comment by nukeop** [comment]
This is high priority now. Will likely be added somewhere along the way before 0.5.0.

**Comment by juancjara** [comment]
@nukeop Hi can I reopen and take this issue?
