### ISSUE TITLE
Lerna sometimes fails to see the "start" script

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#494]
```javascript
$ lerna bootstrap
$ lerna run start
```

The above will normally start the project, but sometimes lerna will say that there is no "start" script in any of the packages. Not sure why.

**Comment by EmberCS15** [comment]
Hi,

I am seeing this when I run _sudo docker-compose up dev_ - 

> dev_1      | lerna success run No packages found with the lifecycle script 'start'

**Comment by nukeop** [comment]
Turns out that it also sometimes modifies package.json and deletes the scripts for some reason.

**Comment by dhuang612** [comment]
I would like to investigate into this

**Comment by dhuang612** [comment]
Is this only happening in Linux or other operating systems?

**Comment by nukeop** [comment]
I've only seen this on Linux but the OS shouldn't be a factor in this case.

**Comment by dhuang612** [comment]
I'm looking under the wiki contributing and it says this:
```
Node.JS, see package.json for appropriate version
```

I've checked inside the one under the root / app / core and ui. 
However, I don't see any node versions mentioned?

**Comment by nukeop** [comment]
It means the node version on your pc. The minimal requirement for Nuclear is 8.

We use 8 in Travis: https://github.com/nukeop/nuclear/blob/master/.travis.yml

For github actions build, I decided to use 10: https://github.com/nukeop/nuclear/blob/master/.github/workflows/build.yml

It shouldn't matter too much though, I think.

**Comment by dhuang612** [comment]
I've been switching node versions to see if I could get nuclear to launch.
Running into similar issues as this:
https://github.com/nukeop/nuclear/issues/212

I also noticed at the bottom you said it can't run on macs right now because of an electron issue?

**Comment by nukeop** [comment]
Not sure about macs, I think it should run fine on them. The warning in #212 doesn't matter, it's been there for a long time and it can be ignored

**Comment by akpark** [comment]
are you sure lerna ever had a `lerna start` command? 
https://github.com/lerna/lerna/tree/master/commands doesn't have `lerna start`
