### ISSUE TITLE
Unexpected dragging behavior from play queue

### ISSUE THREAD

**Issue by badsketch** [nukeop/nuclear#500]
Dragging outside the play queue causes errors.
To Reproduce:
1) Add a song to queue
2) Drag the song outside of the queue. It should pop back to the queue
3) Drag the song again outside of the queue. It will freeze in place

![Screen Shot 2019-10-04 at 12 30 56 AM](https://user-images.githubusercontent.com/8953212/66181371-8083e880-e63e-11e9-91dd-4dfae3bec214.png)

Could I investigate this issue and improve dragging functionality?

**Comment by badsketch** [comment]
ohhhh yikes, updating to v11 complete breaks the play queue and causes it to crash. I'll get these errors nonstop until the app basically crashes.
<img width="1372" alt="Screen Shot 2019-10-05 at 12 59 04 AM" src="https://user-images.githubusercontent.com/8953212/66250093-d2df0b00-e70b-11e9-8bf5-7ff9be960092.png">

Should I make an issue into transitioning the app to react-beautiful-dnd version 11, or keep it at 9 for now and fix the current issue?

**Comment by nukeop** [comment]
I think we'll need to update the package at some point anyway. If you want, you can do this too (there should be a release log detailing any breaking changes).

**Comment by badsketch** [comment]
I was able to update the package successfully 👍 and am now trying to fix some other issues I've noticed prior to the update. Could you help me confirm some of the drag behavior?

1) When a **non** currently playing song is dragged to another **non** currently playing song, the order of the songs between the source index and destination index gets jumbled. 

![NonCurrentReordering](https://user-images.githubusercontent.com/8953212/66265401-c332f580-e7e3-11e9-95fa-32edc501f419.gif)
Can I fix it so that the 'final' state right before the user lets go of the mouse should be the resulting queue?

2) When a currently playing song is dragged to a different location, the index of the previously playing song starts playing. For example, if item 2 is currently playing and dragged to item 5, then whatever item is at item 2 is now playing (not related to gifs below). 

(It's kind of confusing because issue 1) is happening as well)
![PlayingReordering](https://user-images.githubusercontent.com/8953212/66265422-39375c80-e7e4-11e9-8ec8-996281a40455.gif)
Another example
![PlayingReordering2](https://user-images.githubusercontent.com/8953212/66265429-4a806900-e7e4-11e9-9355-c9f2f8517683.gif)

Can I fix it so that the currently playing song stays where I drag it? If item 2 is playing and dragged to item 5, then it remains the currently playing song only now in position 5. The player doesn't have to know what index is playing, just what song is next and dragging is just a reordering of what is the next song?

**Comment by nukeop** [comment]
I was surprised to see this but it seems that this is a regression because it used to work fine.
Reordering needs to change the index of the current track. And also it looks like it doesn't reorder the remaining tracks correctly either. This shouldn't be too hard to fix, so feel free to have a crack.

While you're at it, you could also add some tests for the reordering function so we can catch these kinds of regressions later if someone edits this behavior again.

**Comment by badsketch** [comment]
hey i did some more investigating and i've decided against using the current way of setting up the `draggableId`
<img width="652" alt="Screen Shot 2019-10-11 at 12 43 17 AM" src="https://user-images.githubusercontent.com/8953212/66625051-92c2d100-ebc0-11e9-82a4-a9b91a5eeee5.png">
this was how we did it before, except there's that flicker I mentioned in the above PR #509 . I couldn't narrow down the issue for that and since react-beautiful-dnd as well as the official react docs advises against using `index` as a `key` value or `draggableId`, I thought it'd be better to use the track `uuid` as the `key`:


<img width="649" alt="Screen Shot 2019-10-11 at 1 00 33 AM" src="https://user-images.githubusercontent.com/8953212/66625538-95262a80-ebc2-11e9-8da6-f4b646a5dd14.png">
So now we run into this other issue which is caused by the animations:

![uuid](https://user-images.githubusercontent.com/8953212/66625151-1c729e80-ebc1-11e9-8e52-1ce884a108df.gif)

Initially I thought it was due to superfluous rerendering, but after testing it out on a forked version of an official react-beautful-dnd demo (https://codesandbox.io/s/vertical-list-blkfy), now I can see that it's just expected behavior (including how dragging upwards causes different fade animations from dragging down). onDragEnd causes a rerender, and because we have animations on renders, then the `fade-in` animation is triggered.

How about we disable the keyframe animation for now in favor of improving the dragging UX? 
![no_fade](https://user-images.githubusercontent.com/8953212/66625617-fcdc7580-ebc2-11e9-9566-4c96e0f5ad50.gif)
 I'll look into creating an issue on the react-beautiful-dnd repo, or checking out libraries that will allow us to conditionally add animations.

One more issue I caught is that since uuid's are linked to a track, if you click play on a playlist twice, then two copies of the song will appear that have the same `key`. This will cause drag issues as well. I'm considering generating an additional `queue-uuid` when songs are added to the playqueue to get around this. Thoughts?

**Comment by nukeop** [comment]
Yes, disabling the animations is a good idea, they make the whole thing way slower than it needs to be.
