### ISSUE TITLE
Having trouble with development environment

### ISSUE THREAD

**Issue by jenyeeiam** [nukeop/nuclear#504]
Hi I've been away a while and would like to start contributing again. I see the development process uses docker now and I'm having trouble setting it up. Can anyone provide some guidance esp as it relates to xhost and connecting to X11 display. I'm on macos mojave and I just installed xquartz

**Comment by badsketch** [comment]
If you're on mac, under Development Process, try the second set of commands that uses `lerna`. That helped to get me up and running without docker and xquartz. I think those are intended for Linux environments only.

**Comment by nukeop** [comment]
xhost is required for docker to be able to forward X.
On other platforms you can use the old method. Either via lerna, or directly.
```shell
$ npm i -g lerna
$ lerna run start
```

If you don't want to install lerna
```shell
$ cd packages/app
$ npm start
```

**Comment by jenyeeiam** [comment]
Thank you!

**Comment by jenyeeiam** [comment]
@nukeop do you want me to update the readme with these instructions?

**Comment by nukeop** [comment]
The bit concerning lerna is already in the readme.
