### ISSUE TITLE
keep seeing Cannot find module 'timers' in bluebird library

### ISSUE THREAD

**Issue by akpark** [nukeop/nuclear#508]
```
bluebird.js:29 Uncaught Error: Cannot find module 'timers'
    at s (bluebird.js:29)
    at bluebird.js:29
    at bluebird.js:677
    at bluebird.js:690
    at module.exports (bluebird.js:729)
    at module.exports (bluebird.js:2937)
    at Object.4../promise (bluebird.js:252)
    at s (bluebird.js:29)
    at e (bluebird.js:29)
    at bluebird.js:29
```

when starting the app, it doesn't pass rendering the logo.

**Comment by Venryx** [comment]
I had the same error here: https://github.com/nukeop/nuclear/issues/506

Try pulling the latest version of the master branch, then running "npm install". (the latest version of bluebird causes the issue, and the package.json was recently updated to lock the version to one without that issue)

**Comment by akpark** [comment]
that solved it, thanks!

**Comment by akpark** [comment]
_but still seeing security warnings from electron (node.js integration with remote content)_

**Comment by nukeop** [comment]
Yes, that's normal. Both Electron and React like to spam a lot of warnings.
