### ISSUE TITLE
README translation to portuguese

### ISSUE THREAD

**Issue by s0meon3** [nukeop/nuclear#522]
The current code has only an english version of the README and all the other .md files. I'm able to translate it to brazilian portuguese, would that be a good addition to the codebase?

**Comment by nukeop** [comment]
Sure, why not. You could add it to the docs folder and link it in the main readme somewhere near the top (after the badges).

**Comment by nukeop** [comment]
BTW, according to Snapcraft, Nuclear is quite popular in Brazil: https://snapcraft.io/nuclear

So making it easier for Brazilian users to use the program or contribute to the codebase is a huge plus.

**Comment by s0meon3** [comment]
ok, then! I'll start working on it tomorrow :)
