### ISSUE TITLE
Image size is not equal in Local Library

### ISSUE THREAD

**Issue by YajanaRao** [nukeop/nuclear#526]
Images of local songs are displayed with unequal sizes
![image](https://user-images.githubusercontent.com/38914337/66741598-82964480-ee93-11e9-80ff-9ee5bc2289fe.png)

**Comment by YajanaRao** [comment]
@nukeop  Shall I work on this?

**Comment by nukeop** [comment]
Sure, thanks!

**Comment by YajanaRao** [comment]
Hey it is taking me some time to create the setup. Mean while if any one is interested in fixing the issue, please go ahead.

**Comment by xevenheaven** [comment]
I took a look at this, but was unable to repro the issue.

That said, I made a small enhancement to ensure that the album arts maintain the original image aspect ratio.

**Comment by nukeop** [comment]
Merged
