### ISSUE TITLE
 Import specific methods from lodash

### ISSUE THREAD

**Issue by YajanaRao** [nukeop/nuclear#527]
Hi,
Instead of importing the whole library from lodash can we import specific methods from lodash. 
that is instead of 
` import _ from 'lodash'; `
We can use
` import map from 'lodash/map'; `
` import tail from 'lodash/tail'; `

By this we can reduce the bundle size.

What is your thoughts on this? 
Reference
https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark/

**Comment by nukeop** [comment]
Full lodash is 24kB gzipped. I don't think it's worth it - this is not a website, and bundle size doesn't matter.

**Comment by YajanaRao** [comment]
Alright then I will close this issue.
