### ISSUE TITLE
Program not opening

### ISSUE THREAD

**Issue by s0meon3** [nukeop/nuclear#529]
I'm trying to open the program using the following commands on a win32 system:

`lerna bootstrap
lerna run start
`
it runs, but l get is a white screen. I think I'm doing something wrong so I need some help here

**Comment by nukeop** [comment]
Did you try the docker workflow?

**Comment by s0meon3** [comment]
I think docker doesn't work on 32 architecture

**Comment by nukeop** [comment]
Huh? Docker is available on Windows: https://docs.docker.com/docker-for-windows/install/

You can also try to cd into `packages/app` and run `npm run watch` to see the error messages, if there are any.

**Comment by s0meon3** [comment]
Yep, it´s available on Windows, but only on 64 Windows so it won´t work on my machine.

I´m running the command again now but the last time it gave me an error and got stuck in the loading page with the nuclear logo.

**Comment by s0meon3** [comment]
It compiled with a warning:
`WARNING in ./node_modules/write-file-atomic/index.js
Module not found: Error: Can't resolve 'worker_threads' in 'C:\Users\Corrêa\Desk
top\programming\open-source\nuclear\packages\app\node_modules\write-file-atomic'

 @ ./node_modules/write-file-atomic/index.js
 @ ./node_modules/conf/index.js
 @ ./node_modules/electron-store/index.js
 @ ./app/persistence/store.js
 @ ./app/i18n.js
 @ ./app/index.js
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:8080
webpack/hot/only-dev-server ./app/index.js`

Now I´m running `npm run electron: dev`

**Comment by nukeop** [comment]
This warning is normal and expected.

**Comment by s0meon3** [comment]
I really have no idea what is happening lol, this morning lerna worked for some reason and now it doesn't. I'll try to uninstall and install some stuff here. Pretty sure that the problem is in my machine. Anyway, thank you for the help man and sorry to bother.

**Comment by Venryx** [comment]
I've also had issues using "lerna run start" (slower starts then calling "npm run start" in packages/app directly, sometimes it not starting, etc.).

I suggest doing the above "npm run start" -- or even better, just manually opening two shell windows, one with "npm run watch", and the other "npm run electron:dev". (this way, you can leave the "npm run watch" open persistently, and just rerun the second command after making changes)

**Comment by nukeop** [comment]
What's your node/npm version?

**Comment by s0meon3** [comment]
node: v10.16.3
npm: v6.9.0

**Comment by s0meon3** [comment]
I deleted the nuclear from my machine, cloned it again and ran npm install. When it executed the postinstall script it generated this error after some time:

> lerna notice cli v3.18.1
lerna info Bootstrapping 3 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@nuclear/ui'
lerna ERR! npm install stderr:
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Pleas
e, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellane
ous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a req
uest error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/
popper.js: Integrity verification failed for sha512-7tLFLVmmIAV9vxTqSw5GFllTY+Fs
+shobqJNLfx/r6MucbwlRqT3KWEyPuNfakeqFOflVkbVRD1ZQeCiqawiOw== (C:\Users\Corrêa\Ap
pData\Roaming\npm-cache\_cacache\content-v2\sha512\ee\d2\c52d59a620057dbf14ea4b0
e4616595363e16cfac8686ea24d2dfc7fafa32e71bc2546a4f72961323ee35f6a47aa14e7e55646d
5443d5941e0a2a9ac223b)

**Comment by s0meon3** [comment]
The debug log:

> 19810 verbose stack Error: nuclear@0.5.1 postinstall: `lerna bootstrap --no-ci`
19810 verbose stack Exit status 1
19810 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
19810 verbose stack     at EventEmitter.emit (events.js:198:13)
19810 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
19810 verbose stack     at ChildProcess.emit (events.js:198:13)
19810 verbose stack     at maybeClose (internal/child_process.js:982:16)
19810 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19811 verbose pkgid nuclear@0.5.1
19812 verbose cwd C:\Users\Corrêa\Desktop\programming\open-source\nuclear
19813 verbose Windows_NT 6.1.7601
19814 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
19815 verbose node v10.16.3
19816 verbose npm  v6.9.0
19817 error code ELIFECYCLE
19818 error errno 1
19819 error nuclear@0.5.1 postinstall: `lerna bootstrap --no-ci`
19819 error Exit status 1
19820 error Failed at the nuclear@0.5.1 postinstall script.
19820 error This is probably not a problem with npm. There is likely additional logging output above.
19821 verbose exit [ 1, true ]

**Comment by nukeop** [comment]
Unrelated to Nuclear. This looks like a problem with your network. If there's a problem with integrity checks or downloading from npm something may be interfering with your connection.

**Comment by s0meon3** [comment]
Yep, it was related to my npm cache. I cleaned it and lerna bootstrap finally ran! But, I tried the commands and none of them worked:

`npm run start`: blank page, no errors on the terminal.
`lerna run start`: blank page, no errors on terminal.
`npm run watch && npm run electron:dev`: npm run watch got stuck several times around 67%, the few times it worked I got the same result as the other commands.
`yarn watch && yarn electron:dev`: it got me into the loading page but it never actually loads. 8 warnings related to security and 1 error. 

> Uncaught TypeError: composeEnhancers is not a function
    at configureStore (configureStore.js:15)
    at Module../app/index.js (index.js:14)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Object.0 (bundle.js:410377)
    at __webpack_require__ (bootstrap:726)
    at bootstrap:793
    at bootstrap:793

>

**Comment by nukeop** [comment]
Change composeEnhancer to just compose, should fix it if it fails to download redux dev tools, the downside is that you wont have access to those dev tools

**Comment by s0meon3** [comment]
So the solution would be downloading redux-devtools or changing the composeEnhancer to compose?

**Comment by Venryx** [comment]
The longer term solution would seem to be changing the `composeEnhancer(...)` line to `(composeEnhancer || compose)(...)`, but yeah, that should fix it. (I never got that error since I had the redux devtools installed in Chrome from the start -- it appears to copy the devtools from Chrome to the local electron instance automatically)

**Comment by s0meon3** [comment]
Yeah, I googled it and about the compose that's it. I installed react-devtools locally, do you think downloading redux-devtools locally too would cause any problems?

**Comment by nukeop** [comment]
I don't think it copies anything from Chrome. It's supposed to download the extension from the store: https://github.com/MarshallOfSound/electron-devtools-installer#how-does-it-work

Since this isn't Chrome, installing the devtools in your browser won't change anything. You don't need `redux-devtools`, we already have the above installer.

**Comment by nukeop** [comment]
You can, however, use remote redux devtools from your browser as a temporary solution.

**Comment by s0meon3** [comment]
Concerning the electron-devtools-installer, where should I write the requires and installExtension function?

**Comment by nukeop** [comment]
It's already here: https://github.com/nukeop/nuclear/blob/b7ff2bb95e9bd33005ac49db38ae161b305458ce/packages/app/server/main.dev.js#L54

**Comment by nukeop** [comment]
devtools installer and build process should be fixed now.
