### ISSUE TITLE
Playqueue resets to first song when adding playlist or album even with queue items

### ISSUE THREAD

**Issue by badsketch** [nukeop/nuclear#530]
When a playlist or album is added to the playqueue, it immediately begins playing at the first song. However, if there are already songs in my playqueue and I am in the middle of it, then it results in resetting at the beginning so I lose my progress. Maybe we could add a check to only reset the `currentSong` to 0 if the queue is empty? If so, could I make the change?

I also want to ask, if I were to implement this, I see that one way is to add a conditional to check if queueItems is empty and then `selectSong(0)` in the following snippet
```
  addPlaylistToQueue (
    streamProviders,
    playlist,
    addTracks,
    selectSong,
    startPlayback
  ) {
    addTracks(streamProviders, playlist.tracks);
    selectSong(0);
    startPlayback();
  }
```

However, the conditional would have to involve access to redux `state.queueItems`, and I would have to add that to `mapStateToProps` in the `<PlayListViewContainer/>`. Would that cause overhead? Would it be better to handle this logic inside an action to isolate it from the component? Thanks!

**Comment by nukeop** [comment]
Your idea is pretty good. As you've noticed the fix will be quite easy.

No, there's no conceivable overhead caused by getting access to more store data. It might be good to turn this into its own action (thunk), since it's basically a composition of existing actions. If you want to take care of this, the decision is up to you.

**Comment by badsketch** [comment]
Think I made a mistake on the intended behavior. Looks like pressing play on an album clears the queue and starts playing. There's also an option from the '...' menu to add to the end of the queue, which doesn't disrupt the currentSong. This mimics what spotify does when playing an album, so I guess it's working correctly 👍 

The bug only applies to playlists, where hitting 'Play' will add to the end of the queue automatically and set the first song to play. I have a fix for this ready so that it adds to the end and keeps the currentSong. 

However, Spotify treats playlists sort of like albums where pressing 'Play' clears the queue and starts at the first song. Do we want to mimic that and add an option to '...' to 'add to the end of the queue' and playing defaults to clear the queue just like our albums view? Hope this makes sense.

**Comment by nukeop** [comment]
Yes, it would be great to match how albums behave.
