### ISSUE TITLE
Typing text into the Local Library "filter" box clears UI

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#533]
Typing text into the Local Library "filter" box (such that it matches no tracks) clears the UI, making it say "Your local library is empty".

First off, this is confusing -- instead it should say "No results for your search".

More importantly, it hides the filter textbox itself! Thus, there is no way to restore the filter UI and view your local library contents again.

The fix should be pretty simple:
1) Have the `length == 0` check occur for just the list, not the filter box.
2) Change the message if the only reason the length is 0 is due to the filter.

**Comment by Venryx** [comment]
Created a pull request with the fix here: https://github.com/nukeop/nuclear/pull/535

**Comment by badsketch** [comment]
Nice catch!

Btw, don't know if you know this, but you can reference this issue in the PR and the PR will appear here automatically. :smiley:

**Comment by Venryx** [comment]
Pull request was accepted, so closing.
