### ISSUE TITLE
Mac touch bar support

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#543]
It would be nice to create some touch bar buttons for controlling basic functions like play/pause, next, and previous. Electron has a touch bar api: https://electronjs.org/docs/api/touch-bar

**Comment by jenyeeiam** [comment]
This article could be useful. It's a bit complex though https://hackernoon.com/winds-2-1-building-touch-bar-support-for-macos-in-electron-with-react-e10adb811c91

**Comment by nukeop** [comment]
Nice, thanks. I have access to a Mac with a touch bar now, so I'll be able to work on this soon.

**Comment by nukeop** [comment]
Implemented
