### ISSUE TITLE
When developing, window refuses to load if error occurs during startup

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#545]
The code for launching the electron window, in development, is here: https://github.com/nukeop/nuclear/blob/b7ff2bb95e9bd33005ac49db38ae161b305458ce/packages/app/server/main.dev.js#L35-L140

Note this section:
```
win.once('ready-to-show', () => {
  win.show();
});

win.webContents.openDevTools();
```

That looks innocent, and usually it works fine.

However, guess what happens when an error occurs during program startup?

First, the dev-tools are opened. Then, the error gets hit. This causes the just-opened dev-tools to pause execution, which causes the `ready-to-show` event to never trigger, meaning the window is never shown!

The fix is simple -- open the dev-tools *after* the window is shown:
```
win.once('ready-to-show', () => {
    win.show();
    // this must run after win.show(), otherwise startup errors cause
    // dev-tools to pause execution, causing "ready-to-show" to never trigger
    win.webContents.openDevTools();
  });
```

I can confirm this fixes the issue -- at least for the startup error I was getting (the normal errors on library startup, in their browser-functionality-testing try-catch sections; the problem is that I had "Pause on caught exceptions" enabled from the previous run).

I'll submit the fix soon (as part of my virtual-list pull-request).

**Comment by nukeop** [comment]
I don't recall ever hitting this bug, which might be why it escaped my notice. Glad you solved it though.
