### ISSUE TITLE
Prepare a press kit

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#55]
Create a press kit containing useful media resources for writing articles, blog posts, and so on.
Should contain some logos, colour palette, etc.

**Comment by nukeop** [comment]
Taking suggestions on this now, I'll need to have this ready before 0.5.0 release.

**Comment by mknepper** [comment]
I'm interested. I'll see what I can cook up.

**Comment by mknepper** [comment]
Any examples of what you want to see in a press kit? Perhaps an example of another programs press kit?

**Comment by nukeop** [comment]
Nothing fancy really, in fact I didn't even expect anyone to contribute to this and made this issue more as a reminder to myself. But any help is of course appreciated.
Some of the resources that will serve as a base for this live here: https://github.com/nukeop/nuclear/tree/master/resources/media
And I think I also have the svg version of the logo somewhere.

What we'll ideally make:
* A short, one paragraph description for anyone looking for an introduction for an article
* Some logos (various standard sizes, colored, black, and white versions) in raster and vector formats
* Some icons (standard sizes from 1024x1024 to 16x16, including vector, and black/white variants)
* A couple of edited screenshots (not raw ones like in the readme, more like the one at the top of the promotional page)
* Contact info (nuclear[at]gumblert.tech)
* A list of all contributors (can be extracted from "insights" tab)

**Comment by mknepper** [comment]
Alrighty, I'll start work on this. I also know a bit of HTML/CSS, but I'm unfamiliar with Javascript and Electron, so I don't think I can be much help there. Can you assign this issue to me as well? Also, do you want an introductory paragraph summarizing Nuclear and some of its features and what it aims to do? Journalists could use that paragraph wherever in their article.

**Comment by nukeop** [comment]
Don't worry about coding here, this is all about graphics and text. I can't assign you to the issue, because only people  with master access to the repository can be assigned. Yeah an introductory paragraph is one of the things we'll need.

**Comment by mknepper** [comment]
Mkay. I'm going to search around the web for decent examples. I should have something reasonable in less than a day. I plan to have the introductory article for journalism use. As for icons, I can just take the main one you have and convert it to difference sizes, formats and colors.

**Comment by mknepper** [comment]
For the screenshot, do you want an in-application window screenshot during use? Like what's on the main website, where it's in-application with a drop shadow over a texture background? As for the icons, I see you do have some - I'm guessing you want them recreated in vector format, so it's clearer and can be resized?

**Comment by mknepper** [comment]
- [x] Some icons (standard sizes from 1024x1024 to 16x16, including vector, and black/white variants)
- [ ] A short, one paragraph description for anyone looking for an introduction for an article
- [ ] Some logos (various standard sizes, colored, black, and white versions) in raster and vector formats
- [ ] A couple of edited screenshots (not raw ones like in the readme, more like the one at the top of the promotional page)
- [ ] Contact info (nuclear[at]gumblert.tech)
- [ ] A list of all contributors (can be extracted from "insights" tab)

Created pull request for HQ SVG icons in several variations. Here's what I came up with:

![256](https://user-images.githubusercontent.com/12740958/51589294-2f670680-1eac-11e9-8a10-b12009ccd388.png)


There is a variant without the drop shadow as a vector file. Working on vector logos now.

**Comment by mknepper** [comment]
Awesome. I'll add to my fork, and make pull requests, once you get that original .svg project out.

**Comment by nukeop** [comment]
https://www120.zippyshare.com/v/nTqn4NkG/file.html

Here's the original project file, along with some alternate prototype logos. You should be able to create everything needed here with that.

**Comment by mknepper** [comment]
Starting work on it now. Are you going to reorganize the folders and stuff? I don't know really know how specific you want each directory to be; I was just going to do a folder for the color icons, a folder for the light icons, folder for dark, and then a folder for the logo. If it's circular or something I'll give it its own directory to. Sound okay or do you have a different plan for the directory tree/hierarchy?

**Comment by nukeop** [comment]
The press kit should have its own folder, then each category of assets should be in its own folder as well, so we can distribute the whole thing as a zip file.

**Comment by mknepper** [comment]
![image](https://user-images.githubusercontent.com/12740958/51637437-76dbaa00-1f21-11e9-8997-8ba7b718245f.png)

^ There is the folder tree for the icons. This look okay? Text example below.

└───icons
    ├───color
    │   ├───green
    │   └───violet
    │       └───circle
    ├───greyscale
    │   ├───dark
    │   └───light
    └───scalable

**Comment by nukeop** [comment]
Looks ok, don't include the green and circle ones though.

**Comment by mknepper** [comment]
Updating you; I'll be forking Nuclear with my changes to resources/media/presskit for you to look over sometime later today or early tomorrow.

**Comment by mknepper** [comment]
Sent a pull request. :)
