### ISSUE TITLE
Can't change music source

### ISSUE THREAD

**Issue by Zalaxx** [nukeop/nuclear#550]
After the commit 9ad3bbf (pr #517), it is impossible to choose another music source. At the interface level, you can select another source, but as soon as you change tabs (on Nuclear) to go back to the plugins, the source displayed is always Youtube. And it's not a display bug, since all the tracks remains loaded from youtube. (btw i'm french, sorry for my bad english)

**Comment by Zalaxx** [comment]
The commit id don't seems to be correct, it must be the 8c52f8d. In any case, it's after the #517 pr

**Comment by nukeop** [comment]
Thanks for reporting, it looks like the `selectStreamProvider` action is not dispatched on click. At the moment I'm working on a different feature but I'll fix it on that branch and merge it to master later.

**Comment by nukeop** [comment]
I used a wrong action by mistake, it's fixed on the feature branch and will soon be merged to master too.
