### ISSUE TITLE
Full album downloads

### ISSUE THREAD

**Issue by emye** [nukeop/nuclear#553]
Hello,

We are a team of students that would like to help improve the download feature for this application. We would like to be able to download entire albums. Will it be fine for us to begin implementation of this feature? Thanks.

**Comment by nukeop** [comment]
Hi, thank you for offering to contribute, but downloading albums is already in the program, available from the album view:
https://github.com/nukeop/nuclear/blob/master/packages/app/app/components/AlbumView/index.js#L51

Unless you had something different in mind? You're of course more than welcome to come up with another feature that you think would be interesting to implement.

**Comment by emye** [comment]
Hey nukeop, thanks for the quick response. We are having some trouble accessing the feature in the album view. Is the feature not available from the 0.5.1 binary taken from the webpage?

**Comment by nukeop** [comment]
Yes, I think it was added after the last release. You should be able to see it in the dev version. I will probably release a new version soon, after I complete the album grid feature.

**Comment by emye** [comment]
Thanks for the clarification. If you have any suggestions for what issues we can assist in, we would love to support Nuclear.

**Comment by nukeop** [comment]
If you want to improve downloads, we still need the following:
- Reordering downloads items (drag and drop like the queue)
- Stopping/pausing/removing individual items (via some kind of context menu)
- Pausing all downloads

**Comment by emye** [comment]
Thanks for the suggestions. Should we open new issues for those features, or do they have open ones already?

**Comment by nukeop** [comment]
No need to open issues, just open a new PR if you decide to do any of those.
