### ISSUE TITLE
scroll up when click music card

### ISSUE THREAD

**Issue by sglee487** [nukeop/nuclear#557]
I found that new music content's scroll is maintained when clicked other music card.
So I add an action to reset scroll when clicked.
 
![Record_2019_11_27_01_14_45_712 mp4_20191127_013214](https://user-images.githubusercontent.com/33611003/69652965-ce085900-10b5-11ea-8c36-c8ee78abfb47.gif)

**Comment by nukeop** [comment]
Thanks for reporting. Did you finish working on this?

**Comment by sglee487** [comment]
Yes. Could I create pull request?

**Comment by nukeop** [comment]
Sure, feel free. In the future, don't even create an issue if you fix something, just create a pull request directly.
