### ISSUE TITLE
“Official Audio” sources should be preferred over “Official Video” on YouTube

### ISSUE THREAD

**Issue by kenogo** [nukeop/nuclear#566]
Music videos often contain distracting sound effects to go along with the video, for example in the [music video of _Doves in the Wind_ by SZA](https://www.youtube.com/watch?v=Zg165-mZ7x8). That song, however, also has an [audio-only version](https://www.youtube.com/watch?v=ydmNO1go0mw) on YouTube. Right now, the video version is chosen by nuclear instead of the audio one.

**Comment by nukeop** [comment]
Good point. We're using a very simple heuristic for finding audio, so we can start figuring out how to differentiate those versions from user uploads and music videos with extra stuff.

**Comment by badsketch** [comment]
@nukeop @kenogo Is this taken? I'd be interested in looking more into this. 🙂

**Comment by nukeop** [comment]
Nope, not yet. If you decide to tackle this, here's the best place to start:
https://github.com/nukeop/nuclear/blob/02c70a47db69a8025902e674c63643bc99401ee7/packages/app/app/plugins/stream/YoutubePlugin.js#L28

(currently this only takes the top search result, feel free to add any heuristics that could improve the results)
