### ISSUE TITLE
Is it trade-free?

### ISSUE THREAD

**Issue by tiotrom** [nukeop/nuclear#567]
I see you have a "popular" section, does that mean you collect data about what people listen through this player? In that sense, do users have to trade anything to you or any other service when using the Nuclear player? Like say data?

Cheers!

**Comment by nukeop** [comment]
Nope, we don't track anything you do. The popular tracks come from last.fm, and the list is generated with data their users submit voluntarily.

The only thing that could concern you is Sentry, which aggregates errors thrown by the program so I know if I ship something buggy.

**Comment by tiotrom** [comment]
Thank you! And do you think is a good idea to make "Sentry" opt-in like many FOSS applications do? I really like your application. We have a custom distro tromjaro.com and we test and promote trade-free applications, and try to help the community.

**Comment by nukeop** [comment]
I guess that would be possible, but then I might as well remove it altogether, because nobody would ever opt in, and I don't want to add shitty nagware popups. I get what you mean (I block sentry via ublock and umatrix myself) though. It's not invaluable so if it's an obstacle I can very well just get rid of it altogether.
I would use a selfhosted solution if there was one.

**Comment by tiotrom** [comment]
I understand and I like your honesty. Opt-in is always better for the user but I get that people may decide not to opt.in. Maybe if it is nicely integrated into the application and it is the first thing people see? Like, "Can you please help us by sending anonymous (if that's the case) data in order for us to detect bugs and improve the application?". Something like that. I've seen many doing that including LibreOffice. It is a good way to respect people's privacy I'd say. 

Can I, at least, opt-out?

**Comment by nukeop** [comment]
No, I'm going to remove it altogether. I just reviewed the logs and decided that I'm not getting that much value from it. Mainly it's useful as a way of gauging how many people are using the program, and typically it doesn't give me any insight about any kind of unknown bugs. I would sure like to know what sorts of features are the most useful to people, etc, but I can live without it. I know I'd be the first to block stuff like that. It'll be gone before the next release.

**Comment by tiotrom** [comment]
Much appreciated your attitude!

**Comment by nukeop** [comment]
Sentry is removed (commented out for now in case we want to replace it with something else later or restore it while making it opt in), so I guess I can close this.
