### ISSUE TITLE
Albums with Various Artists fetch incorrect music

### ISSUE THREAD

**Issue by fer22f** [nukeop/nuclear#57]
For example, trying to play Time Bomb from Monstercat 007 - Solace results in https://www.youtube.com/watch?v=xkgNsE9Uhzc instead of the correct song https://www.youtube.com/watch?v=ihDkZC5PmiA.

It lists the song as having artist "Various".

**Comment by nukeop** [comment]
Thanks for reporting this. It's a consequence of the way the Discogs search is used. When the youtube plugin is searching for streams, it gets the album artist, the title of the song, and it's duration, if present. Looks like I didn't account for albums where different songs were made by different artists. Luckily, this information is already in the json we're getting from Discogs API when searching for songs. Here's the json for this album you've mentioned:

https://api.discogs.com/masters/1298914?token=QDUeFOZNwIwOePlxpVziEHzamhbIHUdfENAJTnLR

The fix will be to include the track's "artists" and "extraartists" fields when searching for streams, and when adding songs to the queue. I will also make sure the correct artist shows up when the song itself is clicked.

BTW, I will also be including advanced options for queue items, and if the automatic search picks the wrong song somehow, you'll be able to "re-roll" and force it to choose a different stream. I will take a look at implementing a solution to this bug this week.

**Comment by nukeop** [comment]
The fix for this issue has been pushed and will be released this weekend.
