### ISSUE TITLE
Nuclear mobile version - planning phase

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#570]
@charjac 
@Venryx 

I don't want to target iOS, since there's no way Apple would allow Nuclear on its store. I'd like to support Android and PureOS, possibly other platforms if they're popular enough. Developing for iOS  would be a wasted effort.

**Comment by JadyLiu98** [comment]
Why won't Apple allow it?

**Comment by nukeop** [comment]
Because it would compete with iTunes.

**Comment by charjac** [comment]
For debian based os like PureOs, maybe electron-builder arm build will be ok ?

**Comment by nukeop** [comment]
I think the UI will be sorely inadequate for mobiles.

**Comment by AafaaqAli** [comment]
Looking forward to joining the team in contributing to Android-based  Application :)

**Comment by ammiko** [comment]
hi just wanted to know if this is still being worked on, if so are the targeted devices still only linux and android phones?
also this repo was removed https://github.com/nukeop/nuclear-mobile 
is it because mobile development is not on the radar anymore

**Comment by nukeop** [comment]
I know next to nothing about mobile phones, and I don't own a smartphone of any kind. So if this were to happen, it would need to be done by another dedicated maintainer.
The repository was deleted because I wanted to switch to a monorepo so any future mobile projects will need to be created within its scope.
