### ISSUE TITLE
Strange error when downloading

### ISSUE THREAD

**Issue by osmarks** [nukeop/nuclear#572]
![2019-12-16-223639_545x181_scrot](https://user-images.githubusercontent.com/10486993/70949144-f94aec00-2054-11ea-81fb-7ccbf29e158d.png)

Some time after I start downloading a track, this error appears in a dialog box which reopens (or doesn't close) when I click OK. When this occurs the main window is no longer usable. After closing the application the file it's been downloading exists, but is cut off at the end. This doesn't appear to be localized to a particular track, but I haven't tested very many. I'm using the latest version from the `master` branch as of a few hours ago.

**Comment by nukeop** [comment]
`isDestroyed` is a window property, which makes me think the window pointer might be undefined somewhere. Or maybe it's on a stream and we need dropped connection handling.

**Comment by charjac** [comment]
I start working on this, and its very strange, it worked fine just after the ts refactor and now its like the window is not registered correctly by electron ...

**Comment by charjac** [comment]
The inheritance was responsible for this, I push a fix soon.
