### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#575]
Hi, good job on the latest commits ! Not a lot of time for me to give a hand these days (weeks, months...).
When do you plan a future release (last one is from early august) ? That would be easier to share the love with others !

**Comment by nukeop** [comment]
I've stopped developing any new features and want to focus on fixing bugs and other annoyances, at least the ones that are the most apparent, and after I feel the program is in a good shape, I'll do a new release and newsletter announcement. Nice to know you're still keeping in touch!

**Comment by ctsstc** [comment]
I was just back last week checking back in on the project recently as well, thanks for continuing this :)

**Comment by nukeop** [comment]
Thanks, encouragement from our wonderful users keeps me (and I'm sure other contributors) going!
