### ISSUE TITLE
Stuck in splash screen - Deepin

### ISSUE THREAD

**Issue by gothistanic** [nukeop/nuclear#578]
I installed nuclear via snap on Deepin Linux. 
When I open the program, it only shows the splash screen. I waited for almost 20 minutes and still stuck with it. 

Any clue to see what could be the problem ?
![DeepinScreenshot_20191225001652](https://user-images.githubusercontent.com/34812625/71426566-e61aca80-26ab-11ea-94de-4e1f53ae4cdc.png)

**Comment by nukeop** [comment]
I've never tested on Deepin, and there could be a number of things that went wrong. Are you able to run the dev version with debug output? If not I can try running the snap on a Deepin VM. If everything else fails, I can update the snap.

**Comment by gothistanic** [comment]
How could I run it in debug mode?

**Comment by nukeop** [comment]
You can clone the repository, do `npm install` then `npm start`. However, I understand if you don't want to do this. I could build the newest snap for you and upload it for you to test.

**Comment by gothistanic** [comment]
I think that It will be ok if you could provide a snap and upload it. I checked my envireonment and I have to install nmp and  node.js what I fail so far to do :)

**Comment by nukeop** [comment]
Try this build: https://mega.nz/#!KnADnAaK!W3ot3n6UJjPQMhiGvJ-yI1T88dbZPaf6xJ9KbNsJgko

**Comment by gothistanic** [comment]
Just installed the snap package as : 
sudo snap install --dangerous 'path to the downloaded snap'. 

This time when i click, nothing does happen, no screen no window

**Comment by nukeop** [comment]
Hm, this snap installs and runs on my machine normally. I'll check on a Deepin VM then.
