### ISSUE TITLE
New desktop file for Linux

### ISSUE THREAD

**Issue by mikelpint** [nukeop/nuclear#58]
I modified the desktop file and I was wondering if you would like to adopt it.

New features/fixes:
- Added support for Spanish.
- Fixed a problem with the icon: It wasn't recognized as nuclear.

```
[Desktop Entry]
Name=Nuclear
Name[es]=Reproductor de música Nuclear
Comment=Streaming music player that finds music sources automatically.
Comment[es]=Reproductor que retransmite música desde fuentes encontradas automáticamente.
Exec="/opt/nuclear/nuclear" %U
Terminal=false
Type=Application
Icon=/usr/share/icons/hicolor/0x0/apps/nuclear.png
Categories=Audio;AudioVideo;Network;Player;Music;
```

**Comment by nukeop** [comment]
Yep it would be great. I'm using electron-builder to generate binaries, and the desktop files are also generated by it. It's possible to add desktop file entries by modifying the build section of package.json. Here's the relevant bit of the electron-builder docs:

https://www.electron.build/configuration/linux

Would you like to add these to package.json and open a pull request?

**Comment by mikelpint** [comment]
OK

**Comment by mikelpint** [comment]
I will try to do that tomorrow afteenoon.

**Comment by mikelpint** [comment]
I will try to do that tomorrow afteenoon.
