### ISSUE TITLE
typescript in other packages ?

### ISSUE THREAD

**Issue by charjac** [nukeop/nuclear#581]
if all packages were in ts we could simplify dev and test env.
@nukeop What do you think ?

**Comment by charjac** [comment]
build is failling on travis because of this (i remove the builded files from common package)

**Comment by nukeop** [comment]
I'm all for it. If you see a good place to use typescript, feel free to do it whenever you contribute.

**Comment by charjac** [comment]
typescript is cool everywhere :) (way better than proptypes for react)

**Comment by nukeop** [comment]
Yeah, we can get rid of proptypes. I think we can replace them with a generic interface for each component.

**Comment by charjac** [comment]
- [ ] app
- [x] common
- [ ] core
- [x] main
- [ ] ui

**Comment by charjac** [comment]
@nukeop What about merging common and core package, i am really sure there is a difference between them.

**Comment by charjac** [comment]
I start converting ui package. Do you have wip on it ?

**Comment by nukeop** [comment]
>@nukeop What about merging common and core package, i am really sure there is a difference between them.
Yes, what's in common could have started as core modules really.

>I start converting ui package. Do you have wip on it ?
Not right now, but I wouldn't consider it a priority to convert everything right away. I want to release a new version soon so I'm focusing on fixing bugs and making small commits to master.

**Comment by charjac** [comment]
ok with that. I will just merge core and common packages.
If you have in minds some bugs i could help with, don't hesitate :)

**Comment by nukeop** [comment]
I'm just clicking through the whole program trying to find and remove stuff that looks wrong, got slightly broken for some reason, or is just embarrassing and not hard to fix. Things that could discourage first time users after the release.

**Comment by nukeop** [comment]
Also one big thing I plan to finally get rid of is duplicate favorites - I don't have time to do that today, but I'll definitely do it this weekend and then I think we'll be ready for release. If you think you can be faster than me then you could take that too.

Btw, if you want to develop new features or do any major refactors, let's merge to a "dev" branch temporarily and merge it back to master after releasing.

**Comment by charjac** [comment]
I fail to reproduce it locally.
How did you do to get duplicate favorites ?

**Comment by nukeop** [comment]
I guess this can be closed now

**Comment by Venryx** [comment]
> Not right now, but I wouldn't consider it a priority to convert everything right away. I want to release a new version soon so I'm focusing on fixing bugs and making small commits to master.

At what point would it be good to convert more of the code-base to typescript?

As a new contributor to the project, I've found it to be hard to make changes without hoverable type-data, full-fledged "jump to definition", compiler type-checks, etc., enough to where I'd actually be more comfortable just doing the up-front conversion work project-wide rather than having to fight with the blind-coding anymore.

If the project's not ready for a typescript overhaul just yet, is there a list of tasks that need to be completed beforehand so I can keep them on my radar, and/or help complete them?

**Comment by nukeop** [comment]
We've introduced typescript to ui, core, and main packages and whenever I work on something I typically first convert it to ts if it's possible to move it to one of those packages. The main app packages is still js only, but I guess that change is coming too at some point. If you work on a new feature, feel free to use ts wherever you like (I'd say at this point it's even preferable).

**Comment by Venryx** [comment]
> I typically first convert it to ts if it's possible to move it to one of those packages.

Is there a page somewhere describing what sorts of files are supposed to be moved to the ui/main/core packages?

I'd assume:
UI: Components to be used from multiple places, ie. not having a canonical "path" in the UI.
Main: Code for the NodeJS backend code?
Core: Functionality common to both the frontend and backend code?

**Comment by nukeop** [comment]
You are 100% correct. Ultimately I'd like to stick to the component-container pattern in all cases, with the ui package holding all the purely presentational components, while the app package will contain only more complex views (compositions made of ui components) and their corresponding containers.
