### ISSUE TITLE
Show top contributors in help screen

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#583]
There's a short "about" section that displays some basic info.
It would be nice if we could get a list of contributors from Github and display the top 10 (maybe more) most prominent contributors underneath as a way of saying thanks. This could include avatars, usernames, and links to profiles that open in the browser, plus maybe how many commits/LOC a person contributed.

**Comment by charjac** [comment]
I remember a node script written by kentcdodds who where doing this for Readme.md. I will try to find it on github.

**Comment by mahimshridhar** [comment]
hey @nukeop can i work on this ?

**Comment by nukeop** [comment]
Sure, feel free to.

**Comment by Burzo** [comment]
Hello there, my bad, I'm a bit late to the party. I started working on this yesterday, but didn't know I'd need to reserve it like this - just started with open source contribution. Should I continue and submit my pull request @nukeop, once finished? Mostly styling left, most of the logic is implemented.

Sorry if I'm causing confusion...

**Comment by nukeop** [comment]
@mahimshridhar , have you started working on this? Ultimately you'll have to work out what parts each of you can do, if any.

@Burzo , you can create a pull request now, and mark it as `do not merge` until you're finished, this way it can be seen you're working on this (and you can also reference this issue by adding `#583` to the pull request thread so it shows up here).

**Comment by mahimshridhar** [comment]
I have not started working on this. and @Burzo, you can continue if you want to.

**Comment by Burzo** [comment]
Thank you both, @nukeop  and @mahimshridhar . I'll just create a pull request once its finished then, as to not confuse everything further.

**Comment by charjac** [comment]
I know this has already been implemented, but i just find this, and it looks interesting, so i put it here:
https://github.com/all-contributors/all-contributors

**Comment by nukeop** [comment]
I know about this thing. We keep all assets in the repo though, so people who contribute translations, docs, and graphics, are all de facto contributors, so no need to acknowledge them separately.
