### ISSUE TITLE
react hooks in ui package

### ISSUE THREAD

**Issue by charjac** [nukeop/nuclear#586]
There is a lot of withHandler hoc usage in ui package.
what about replacing them with the useCallback hooks ?

**Comment by nukeop** [comment]
Can you show me an example of what you'd like to do?

**Comment by charjac** [comment]
For example with the component UserPluginItem
It make eslint happier and fit better with typescript.

```jsx
const UserPluginsItem = ({
  path,
  name,
  description,
  image,
  author,
  loading,
  error,
  deleteUserPlugin,
  onAuthorClick
}) => {
  const handleDelete = useCallback(() => {
    deleteUserPlugin(path);
  }, [path, deleteUserPlugin]);

  const handleAuthorClick = useCallback(() => {
    onAuthorClick(author);
  }, [author, onAuthorClick]);

  return (
    <div
      className={cx(
        common.nuclear,
        styles.user_plugins_item,
        { loading, error }
      )}
    >
      {
        image && !loading &&
        <div className={styles.plugin_icon}>
          <img src={image}/>
        </div>
      }
      {
        loading &&
          <div className={styles.plugin_icon}>
            <Loader type='small' />
          </div>
      }

      <div className={styles.plugin_info}>
        <div className={styles.plugin_name}>
          {name}
        </div>
        <div className={styles.plugin_path}>
          <label>Installed from:</label>
          <span>{path}</span>
        </div>
        <div className={styles.plugin_description}>
          {description}
        </div>

        <div className={styles.plugin_footer}>
          <div className={styles.plugin_author}>
            <label>Author:</label>
            <span className={styles.link} onClick={handleAuthorClick}>
              {author}
            </span>
          </div>
          <Button basic inverted icon
            className={styles.delete_button}
            onClick={handleDelete}
          >
            <Icon name='trash alternate outline'/>
            Uninstall
          </Button>
        </div>

        <div className={styles.error_footer}>
          {
            error &&
            <div className={styles.error_message}>
            This plugin could not be loaded correctly.
            </div>
          }
        </div>
      </div>
    </div>
  );
};
```

**Comment by nukeop** [comment]
Ideally, I would make every component purely presentational and inject logic from containers as props. Hooks such as `useState` or `useCallback` have to be defined inside the component, so they ruin that flow, that's why I dislike them. HOCs make it real easy to separate the logic from the declarative presentation code, and they can be cleanly tested if desired; they also make dependency injection easier (e.g. I export a hoc-augmented version of the component but for testing the "clean" version can also be exported and injected with mocks, spies, and whatnot).

If you find hooks easier to work with feel free to use them, but I'd rather not modify the existing components yet.

**Comment by charjac** [comment]
I totally agree with you with the role of pure presentation of react components, (that's what make me really love react & flux at the beginning).

For me these kinds or hooks or hoc are the same thing, it depend on everyone's taste.
The only advantage i see for usage of useCallback, is that props are more easy to read and understand, they are not transformed by "the component in the middle".

But its really not a big deal, in france we have an idiom for that kind of conversation : "enculer une mouche" litteraly "fuck a fly by the ass "  :D.
