### ISSUE TITLE
Queue context popups should be displayed on the left

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#595]
The popups currently obscure the queue, they should be displayed to the left of the clicked track. And there's a small issue with the arrow where the border is drawn inside it.

**Comment by charjac** [comment]
This one is pretty thought.
I tried a few things, it looks like the semantic-ui Popup is fucked up. (not completely sure about it)
The only things that works is a dirty negative margin ..... and a top override (!important).

**Comment by nukeop** [comment]
I used a `target` prop in `AlbumPreview`: 
https://github.com/nukeop/nuclear/blob/a95f3b454097672b1664e77e58281849016649d1/packages/ui/lib/components/AlbumPreview/index.js

Maybe we could do something like this. I want the popups to always be in the same place, exactly to the left of the queue item.

**Comment by charjac** [comment]
thx !!! I will give this a try
