### ISSUE TITLE
Weird loading screen behavior

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#597]
I think this is caused by `preload.js`.

The initial loader is not animating, then progresses directly to the program without the fade in that used to play over 1s.

If you comment out `render(App)` in `index.js`, you can notice that the logo is initially larger, then becomes smaller and starts animating.

**Comment by nukeop** [comment]
Looks like the animation freeze is related to this: https://github.com/electron/electron/issues/9719

**Comment by nukeop** [comment]
more info: https://medium.com/actualbudget/the-horror-of-blocking-electrons-main-process-351bf11a763c

**Comment by charjac** [comment]
oops...  sorry for breaking that just to make fun with web components ..... :/

**Comment by nukeop** [comment]
I think it can still work with web components but I'll need to edit css.

**Comment by nukeop** [comment]
I'll leave it as it is for the release but this issue of main thread blocking needs to be addressed at some point.

**Comment by nukeop** [comment]
getMetas uses glob.sync, this might be what's blocking the UI at startup
