### ISSUE TITLE
Local library index optimization

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#600]
The index is huge even if we only have a couple of albums, and it looks like most of that is taken by the album art, which is replicated in each individual track. This will be the lowest hanging fruit to be handled when optimizing the index.

**Comment by tracker1** [comment]
Should probably consider sqlite, and for the album art, referencing a hash of the image, so the same reference can be used.

Also, not sure if child directories are added when a directory is added, I tried adding my audio directory (thousands if files, several gb of music) and the app blew up.

**Comment by nukeop** [comment]
Yeah, that's probably because of the index performance.

**Comment by charjac** [comment]
Hi @tracker1, is it possible for you to build the branch fix/local-images, and test if the app still crash when parsing your library please ? (I have not enough mp3 to do "stress test", and i am too lazy to dl the whole pirate bay for my test).
