### ISSUE TITLE
Local library index contains 2 copies of each track when rebuilt from scratch

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#602]
To reproduce, delete `~/.config/Electron/nuclear-local-library.json` and add the library folders, then re-scan them.

**Comment by nukeop** [comment]
Scanning folders fails in many cases, e.g. sometimes when selecting a folder that only contains files. Looks like there are some incorrect assumptions about the structure of the library folders.

**Comment by charjac** [comment]
I take this one (if possible)

**Comment by nukeop** [comment]
Ok. I think the glob pattern is at fault here. I can't always reproduce the duplicates issue though.

**Comment by charjac** [comment]
I am not able to reproduce :/
I tried with simple folder with file, and with a 4 lvl structure.

**Comment by nukeop** [comment]
Ok, maybe it's already fixed. I'll close this.
