### ISSUE TITLE
Make Stream ID a clickable link

### ISSUE THREAD

**Issue by mascherone108** [nukeop/nuclear#609]
When you right click on a track in the queue, it shows only text Steam ID even though the ID actually is a part of YouTube's (for example) URL. That way I can  check if I'm actually listening to a correct song as sometimes the accuracy isn't perfect.

**Comment by nukeop** [comment]
You're right, we display some details of the stream in that popup but in some cases it might not be enough.

**Comment by nukeop** [comment]
I also noticed that it would be useful to allow a link to the underlying youtube video to be copied (e.g. when you want to share it with a friend).

**Comment by AlexAndriyanenko** [comment]
I would like to work on this one.
