### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#61]
Thread for gathering materials that might facilitate adding Spotify support in some form.

https://www.npmjs.com/package/spotify-playlist

**Comment by ivanhuay** [comment]
that would be great!

this library looks more complete https://www.npmjs.com/package/spotify-web-api-node

**Comment by nukeop** [comment]
If I remember correctly using Spotify WebAPI is out of question, since it requires a unique api key for every application, and it's likely we'd just get banned.

**Comment by HaiDang666** [comment]
duplicated https://github.com/nukeop/nuclear/issues/945
