### ISSUE TITLE
Change queue popup into a context menu

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#612]
Queue popups currently display stream info and allow rerolling streams.

I would like to change these into a regular context menu (similar visually to the one at the top of the play queue) that lets users interact with queue items more freely and download them, add them to favorites, playlists, etc.

**Comment by mr00z** [comment]
Hi, can I work on this issue?

**Comment by nukeop** [comment]
Sure, I haven't started yet.

**Comment by mr00z** [comment]
Would it be something like this?

![Screenshot_2020-02-28 Storybook](https://user-images.githubusercontent.com/22932530/75549104-293c4580-5a2f-11ea-97ca-00352b2d5bea.png)

Also, should I preserve current functionality of the Queue Popups (with displaying stream info etc.) or should it be something like in the Track Popup (song info with image at the top and actions at the bottom)? 
Or maybe those two combined - stream info at the top and actions at the bottom? I wonder only if the context menu wouldn't be too big in this case.

**Comment by nukeop** [comment]
Instead of a separate button, let's make it appear on right click, just like the current popups.

I think the best way to do this would be to have a section at the top of the context menu with the stream info, and action buttons separated by a horizontal line under that.

You can see [here](https://react.semantic-ui.com/collections/menu/#content-header-vertical) how to achieve that. We also have a component called `QueueMenuMore` that uses this layout.

**Comment by mr00z** [comment]
Ok. Yes, I was thinking about something like this.
