### ISSUE TITLE
add remove specific songs from playlist + remove playlists

### ISSUE THREAD

**Issue by advaithm** [nukeop/nuclear#616]
the title should explain this pretty well

**Comment by nukeop** [comment]
Thanks for the suggestion! Sorry, I suffer from tunnel vision so I don't realize all the use cases other people have, even if they seem obvious. I'll get this done ASAP.

**Comment by githubtefo** [comment]
Maybe, and just maybe, this could help? https://github.com/Ritiek/Spotify-Downloader
I was able to get an .m3u playlist with youtube links from there (and somewhat related, it would be great to be able to import these playlists to nuclear).

**Comment by nukeop** [comment]
It's already possible to import youtube playlists. It was a hidden functionality. You can paste a link to a playlist into the search box.

**Comment by githubtefo** [comment]
Hi nukeop!
Thanks for the heads up! Although it is not exactly the same (I was thinking in the kind of .m3u files this Python App creates), I think it is a great hidden functionality.
I am trying to use it but when I pase a whole playlist youtube link into the search box I get a "Nothing found" answer. I also tried with youtube video links and get the same result.
Thanks!

**Comment by nukeop** [comment]
Which version are you using?

**Comment by githubtefo** [comment]
0.6.3-1 (https://aur.archlinux.org/packages/nuclear-player-bin/)

**Comment by TWINGSISTER** [comment]
There is a wealth of music on Internet Archive (IA) , (and that's obvious). Less obvious is the fact that it is not organized as just the dump  of  WAVs in CDs. Songs are carefully presented as individal mp3. What is even more incredible is that you can put a .m3u list (readily available on IA) pointing to these mp3 in a player like Clementine and IA has enough bandwidth to send it just in time for Clementine to play. So i tried to put in the search bar or in the URL import for this e.g. https://archive.org/download/u2-the-joshua-tree/u2-the-joshua-tree_vbr.m3u but nothing happens. Any idea?
