### ISSUE TITLE
Nuclear doesn't show mp4 files in local library

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#617]
For at least some songs on YouTube, downloading it yields an mp4 file; this shouldn't be any issue, since Nuclear can play mp4 files, right?

Well, while it's true Nuclear can play mp4 files by dragging them onto the playlist area, the problem is that Nuclear doesn't show mp4 files in the local library.

To reproduce, just copy an mp4 file into the folder set for the local library, then rescan/refresh the local library. The mp4 track will not show up.

OS: Windows 10

**Comment by nukeop** [comment]
You're right, it's a bug.

Apparently we're missing a file association: https://github.com/nukeop/nuclear/blob/6fa42c74cc6f4df4162c1340d93480e840296c75/package.json#L97

**Comment by nukeop** [comment]
The correct entry to add will be:
```json
{
  "ext": "mp4",
  "mimeType": "audio/mp4"
}
```

**Comment by nukeop** [comment]
Fixed by a974c99
