### ISSUE TITLE
Add a 'Play All' button in Favorite Tracks

### ISSUE THREAD

**Issue by tghgg** [nukeop/nuclear#621]
I add songs to Favorite Tracks so I can easily listen to them all, however right now if I want to play all my Favorite Tracks I have to manually add each song to queue. Quite frustrating. An 'Add all to queue' or 'Add selected tracks to queue' button would make it easier to listen to your favorite songs.

**Comment by nukeop** [comment]
Good suggestion

**Comment by kangwritescode** [comment]
<img width="398" alt="Screen Shot 2020-01-23 at 10 42 12 AM" src="https://user-images.githubusercontent.com/57216395/73013455-34b3a580-3dcd-11ea-8a4b-420b74df628d.png">
Are you looking to add a button with this same style?

**Comment by nukeop** [comment]
If you implement it, you decide, but this could be an ok choice (especially if paired with another button that spawns a popup)

**Comment by kangwritescode** [comment]
Awesome. going to take a crack at this.

**Comment by tghgg** [comment]
Closing the issue as the button is implemented in 0.6.1.
