### ISSUE TITLE
automatic AUR publish

### ISSUE THREAD

**Issue by charjac** [nukeop/nuclear#622]
I dont know if its possible but it could be cool.

**Comment by nukeop** [comment]
@mikelpint would you like to co-operate on this?

**Comment by nukeop** [comment]
We could also publish automatically to Snapcraft (and maybe flatpak repository once I figure out how to build that).

**Comment by advaithm** [comment]
if i am not wrong this is possible but it would require read/write access to the git repo that hosts the AUR repo. after that you will need a script that polls git for new release downloads said release. use something like [deptap](https://aur.archlinux.org/packages/debtap/) with the -q flag repackages it into a AUR package then run it through some checks to see if it installs and finally use shh or something along those lines to publish it to the AUR repo. you would just need to put this as a cron job(all of this has to be done on arch linux or a distro like manjaro)
this is what you would have to do for AUR i don`t know how you would implement it for Snapcraft or flatpak(if i am not wrong flatpak already implements this  and you just need update the pkg info)

**Comment by nukeop** [comment]
electron-builder has support for snaps, so that would be even easier. With AUR we need to contact @mikelpint who is the maintainer.

**Comment by advaithm** [comment]
@nukeop you could make your own. It's not difficult. Many apps on AUR have multiple repos and if it maintained by you. You can ensure that there is no malicious code

**Comment by nukeop** [comment]
I wanted to avoid duplication and minimise wasted effort but I can go with that. We could support building from scratch in PKGBUILD as opposed to using the .deb.

**Comment by advaithm** [comment]
I understand. If you need any help I won't mind doing this

**Comment by johnbrz** [comment]
I think it would be a good option to have the git package of nuclear in the aur. Currently, only the compiled version is available.
ping @mikelpint

**Comment by nukeop** [comment]
Done
