### ISSUE TITLE
'Play Now' button removes all song from the current queue

### ISSUE THREAD

**Issue by fsnowdin** [nukeop/nuclear#624]
![Peek 2020-01-21 03-23](https://user-images.githubusercontent.com/35988882/72755608-d0bd9100-3bc2-11ea-9a02-24d53841ff84.gif)

Nuclear 0.6.0 on Fedora 31.

**Comment by nukeop** [comment]
Yes, that's the intended behavior. Play now replaces your queue with what you clicked. Works the same way in some other music players. To add something without clearing the queue, try the "add to queue" option.

Btw, if this wasn't intuitive, maybe it's a chance to improve the UX. What did you expect to happen after clicking this?

**Comment by tghgg** [comment]
I thought it was just going to play the song without doing anything to the queue. Like testing the waters first before adding it to the queue. If I'm trying to find a song, I don't want to have to go through a bunch of tracks by first adding it to the queue, then play it and if it's not what I'm looking for, remove it. It's tedious especially for newcomers who are curating their tracks. 

The button should just do one thing, play the selected track. Maybe add a variant that add the track to the queue and play it automatically.

**Comment by nukeop** [comment]
Ok, sounds good. I think it's a good idea to have this option. I'll think of a fitting name.

**Comment by skyawmyint** [comment]
As I was going through and trying/testing out the application, I had the similar thought in how the play song and the queue would function as tghgg.

**Comment by TROMsite** [comment]
Same here. I was not expecting that playing a song will remove all of the songs from queue. This is not something I've experienced with any music players. I think the best is to play the song and add it to queue without removing any from queue. ;)

**Comment by nukeop** [comment]
I modeled these behaviors after Mediamonkey, which was my favorite music player 10 years ago.

**Comment by TROMsite** [comment]
I see. I guess it is subjective but I have tested tens of music players for the past year for our tromjaro.com Linux OS to choose a good one, and pretty much all are the way I described above. I feel like is more useful to not remove the queue songs ;)

**Comment by HaiDang666** [comment]
Not gonna implement
