### ISSUE TITLE
Import favorites from last.fm

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#631]
It was suggested on Mastodon by https://mstdn.io/@bueno that it would be useful to be able to import favorites from Last.fm. We already allow connecting accounts for scrobbling so it shouldn't require too much additional work.

**Comment by vignesh-md** [comment]
I am wishing to contribute. I am a newbie to the contributing community. Can you suggest to me where to look into for a headstart?

**Comment by nukeop** [comment]
Sure. Functions for communicating with last.fm api can be found here:
https://github.com/nukeop/nuclear/blob/master/packages/core/src/rest/lastfm.ts

And we'll need to support this method:
https://www.last.fm/api/show/user.getLovedTracks

This would be a good place to start.

**Comment by o-ali** [comment]
I'm going to try and tackle this. I'm new to the contributing scene so if anyone else wants to, feel free to also try :D

**Comment by buen0** [comment]
Wow, thank you for considering and working on my suggestion! :)
