### ISSUE TITLE
check if internet connection exists

### ISSUE THREAD

**Issue by advaithm** [nukeop/nuclear#643]
If internet is down and you launch nuclear it (at least i feel) should open the downloaded music. a way I thought could be used would be too ping a website and if 100% of the pings for a set amount of time result in losses then nuclear could open the downloads page.

**Comment by nukeop** [comment]
No need to ping any extra websites, since we open the dashboard with reviews by default, so if loading them fails, we could redirect to local library.

**Comment by charjac** [comment]
I implemented this last month, on linux it looks like its still working.
If no connection, the router redirect to the localLibrary and lock search and dashboard view.

**Comment by nukeop** [comment]
Yeah I thought we already had that. Any issues on Windows?

**Comment by advaithm** [comment]
On linux the latest release of nuclear does not work it actually crashes when Internet is lost

**Comment by charjac** [comment]
Ok I will check whats going wrong today, thanks for the report.

**Comment by charjac** [comment]
Actually i can't reproduce.
On which page does the crash happen ?
what is your version off the app ?

**Comment by advaithm** [comment]
@charjac the latest relase of nuclear and it was on the dashboard

**Comment by charjac** [comment]
I finally achieve to reproduce, and its very strange.
When i use gnome topbar widget to shut down connection (wired or wireless), it works just fine, events fired properly (i can plug the cable in and out and everything still works fine).
But when i remove the cable (wifi shut down), events doesnt fired.
But if i plug the cable in then plug it out, here the events fired properly......

I found nothing on stack-overflow, if someone has a clue, i take it :).
