### ISSUE TITLE
Wrap all text in i18next functions

### ISSUE THREAD

**Issue by PalleKarlsson** [nukeop/nuclear#647]
Hi!

This is somewhat related to #345 

While adding the Swedish translation I noticed that there are several texts that are hard-coded and not going through i18next. I'm not sure if you have other plans for handling translations, or if it just is low-priority in relation to other issues. But I wanted to fix it, and just continued coding after finishing the translation. :)

I have a PR that I hoped of getting feedback on. You can find it [here](https://github.com/nukeop/nuclear/pull/648).

**Comment by nukeop** [comment]
Nice catch, I probably didn't notice. We've integrated translations some time ago and over time we probably didn't wrap all strings properly. Thanks for fixing this.

**Comment by odiaz95012** [comment]
Hello, is it okay if I work on this issue? It's my first time working on an open-source and it seems like a good place to start.

**Comment by nukeop** [comment]
Ok, you can try hunting down all the strings that are still not translated. They should be added to `en.json` and you should use the hook provided by our i18n library to get them. Once they're in `en.json`, they will propagate to other languages.
