### ISSUE TITLE
Tracks not loading

### ISSUE THREAD

**Issue by trekiteasy** [nukeop/nuclear#649]
Since yesterday, whatever track I add to the playlist, it stays in a never ending loading state.
It worked well the day before.
On MacOS, Nuclear 0.6.0.

No specific changes or updates on my side.

Changes in the youtube api / download ?

**Comment by nukeop** [comment]
Jamendo API is returning a 500, and that's causing other searches to fail (I know this sucks).
Maybe they banned us?

**Comment by nukeop** [comment]
Other api keys don't work, maybe it's an outage on their end. I'm refactoring stream lookups now and will try to make them independent.

**Comment by buen0** [comment]
This is also happening to me for the last 2-3 days on Windows 10, 0.6 version.

**Comment by nukeop** [comment]
For future reference, the way we're searching for streams is by using Promise.all. However, this method doesn't allow failures - if any plugin fails (e.g. returns 500), the whole search fails.

**Comment by nukeop** [comment]
I fixed the issue, will do a release now.
