### ISSUE TITLE
Implement download queueing

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#657]
Currently, every track added to downloads immediately starts downloading. Downloads are therefore behaving inconsistently, are not saved over program restarts, and can fail randomly without properly notifying the user. The following improvements are proposed:

* Store the list of downloads in db/on disk somewhere. The main process will manage this list.
* Allow the renderer process to query the main process for the list of downloads and their status.
* Download tracks one at a time (potentially configurable). Indicate errors. Allow retries, just like any modern browser. Retry interrupted downloads over program restarts.
* (optional) Add convenience features - popup with a list of recently added downloads and their statuses, button to open downloads folder, button to clear downloads list. Display an error toast when a download fails.

**Comment by mahendraHegde** [comment]
@nukeop I'd like to work on it.

**Comment by nukeop** [comment]
Ok, as this is a big feature, pick one of the things on the list first and let's iterate on it together.

**Comment by mahendraHegde** [comment]
I'll start with `Store the list of downloads in db/on disk somewhere. The main process will manage this list.` I'm new to nuclear code base so can you guide me from where should I start.

**Comment by mahendraHegde** [comment]
I'm planning to store downloads as Plain array of download `items` in `store` and modify as per actions . and load to downloads state on app load.

**Comment by nukeop** [comment]
Ok, you can use `electron-store` and create a separate file for the download queue.

**Comment by mahendraHegde** [comment]
>Retry interrupted downloads over program restarts

it seems not possible to resume downloads over app restart, since `DownloadItem` returned by the downloader onStart callback is an eventEmmiter and  cannot be  stored(restart download facility can be provided).

we can also add pause and resume downloads feature which will resume downloads if possible or restarts(over app restarts)

I've started here https://github.com/nukeop/nuclear/pull/658
please provide your reviews.
@nukeop

**Comment by nukeop** [comment]
>it seems not possible to resume downloads over app restart, since DownloadItem returned by the downloader onStart callback is an eventEmmiter and cannot be stored(restart download facility can be provided).

What we can do is store the status (completed/incomplete/error), and start over on restart, deleting the incomplete download first.

**Comment by mahendraHegde** [comment]
should we auto start those downloads(Error/incomplete) or should we provide a resume retry icon so that user can retry them whenever he wants.

**Comment by nukeop** [comment]
Browsers wait for manual restart, so I think we should also follow that pattern.

**Comment by mahendraHegde** [comment]
@nukeop  I'm working on this
`Download tracks one at a time (potentially configurable). Indicate errors. Allow retries, just like any modern browser. Retry interrupted downloads over program restarts.
`

**Comment by nukeop** [comment]
Great, this will be a very useful next step.

**Comment by alizeh12** [comment]
Hi, I would like to work on this with my partner @nfeygin if possible

**Comment by nukeop** [comment]
Ok, let me review this and I'll tell you what parts of this haven't been worked on yet.

**Comment by alizeh12** [comment]
sure

**Comment by alizeh12** [comment]
Hi nukeop, were you able to review the code? can you let me know asap so I can try working on this

**Comment by alizeh12** [comment]
@nukeop can you also let me know how to open the app in developer mode

**Comment by nukeop** [comment]
Sorry, I forgot about this.
The next most useful thing to implement would be the last step in the original post in this thread. All of the features in it can be implemented separately, one at a time, or all at once.

The development process is explained here: https://github.com/nukeop/nuclear#development-process

**Comment by 1onyng** [comment]
@nukeop can I work on the last step: (optional) Add convenience features?

**Comment by nukeop** [comment]
Sure, feel free to pick any of the features mentioned there.
