### ISSUE TITLE
Allow using back/forward media keys to navigate

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#659]
We have navigation buttons, would be good if using the keys that some keyboards and mice have also worked.

**Comment by JohnRawlins** [comment]
Can I try working on this feature?

**Comment by nukeop** [comment]
Closed by #665, thank you @JohnRawlins

**Comment by nukeop** [comment]
Not closed yet actually, we still need support for navigating pages back and forward.

**Comment by JohnRawlins** [comment]
![nuclear](https://user-images.githubusercontent.com/42707277/76172417-fcdda300-616b-11ea-8234-f2ee653c1bc7.png)

By navigating pages, do you mean using the forward and back media keys as shortcuts for these buttons?

**Comment by nukeop** [comment]
Yep, exactly!

**Comment by JohnRawlins** [comment]
@nukeop I was thinking that we can use the [alt] + [left arrow] and [alt] + [right arrow] keys, instead of the media keys to control the navigation between pages. This is similar to the shortcuts used in Chrome. What do you think about this solution?

**Comment by nukeop** [comment]
This needs some rethinking, so thanks for raising this. I realized there are no dedicated back/next keys or buttons, they're actually for controlling music players. So the plan would be:

- Alt + arrows like you suggested for previous/forward navigation. This can be defined with Mouse trap here: https://github.com/nukeop/nuclear/blob/master/packages/app/app/containers/ShortcutsContainer/index.js
- Media keys "next track" and "previous track" for switching to the next/previous track in the queue. This can be implemented the way you did this previously. Additionally, we could try using the globalShortcut Electron API to make the program respond to those globally: https://www.electronjs.org/docs/api/global-shortcut

**Comment by alizeh12** [comment]
Hi, I would like to work on this if the issue hasn't been resolved already @nukeop

**Comment by nukeop** [comment]
Sorry, it's been already implemented, I just forgot to close the issue.

**Comment by allanlaal** [comment]
mouse back/forward keys do nothing in:

          ID: org.js.nuclear.Nuclear
         Ref: app/org.js.nuclear.Nuclear/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2dd909
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 319,5 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: 4c46d954ea1f868e9ed46095abfd05daafaeef0abbd2b2dbd5092ac5468a2176
      Parent: 8401cc04e34e9562344a8e2f3752fbe1fe20900202c0c1696b6a6c3c7f77487b
     Subject: Update to 2dd909 (228a9843)
        Date: 2022-04-07 07:17:16 +0000
