### ISSUE TITLE
Not Able To Listen Any Music From Youtube

### ISSUE THREAD

**Issue by ozgurakyazi** [nukeop/nuclear#66]
I installed nuclear and I cannot listen to any music. I am using elementary os, 
elementary OS 0.4.1 Loki 64 bit, 
Built on "Ubuntu 16.04.3 LTS", 
Linux 4.4.0-103-generic, 
GTK+ 3.18.9. 

I open the app, and search from youtube resources, find the music I want. All good until here. When I click on the song to play, it does not play. I tried several of them and the result is same.

**Comment by ozgurakyazi** [comment]
I dont see any version number. I also tried running "nuclear --version"  "nuclear -v", no result.
I am downloading the latest version now. Let you know how it goes.

**Comment by ozgurakyazi** [comment]
Here is my experience:

I downloaded v 0.4.2, installed and opened. I searched for "şanışer" no results(he has music in youtube). Then removed this version and install 0.4.0, result is same. Installed 0.4.2 again, and tried another music.
I pressed play, did not play. I waited and pressed add to queue, and it is added to queue. I pressed play at the bottom, then music played(source is youtube :+1: ). 

I also could not download any music(no buttons for that.). The most similar button was save button, which saves playlists.

**Comment by nukeop** [comment]
Yeah, download is not implemented yet. I'm using discogs for music info, so if somebody has no released albums and/or not added to discogs, he won't show up in search. Still looking for a better search provider.

**Comment by ozgurakyazi** [comment]
Ok thank you for the info. I think the problem is gone, so closing the issue. Do you need any help from me?

**Comment by nukeop** [comment]
No, but thanks for telling me what features you're looking for, I'll know what to prioritize.
