### ISSUE TITLE
Discord Rich Presence counts elapsed even if song is paused

### ISSUE THREAD

**Issue by nathanfranke** [nukeop/nuclear#660]
You can't actually pause the start time in the Discord API so instead it should just say paused. When you play it the start time is set to the current time minus the position so it shows at the right spot

**Comment by nukeop** [comment]
Thanks for catching this, needs to get fixed.

**Comment by nathanwfranke** [comment]
I am not too familiar with how this project works but this is the code that should work
```js
let activity = {
  details: `${track.artist} - ${track.name}`,
  largeImageKey: 'logo'
}
if (paused) {
  activity["details"] += "\nPaused";
} else {
  activity["startTimestamp"] = Date.now() - elapsed;
}
await this.rpc.setActivity(activity);
```

**Comment by advaithm** [comment]
Fast forwarding or rewinding need to be included to.

**Comment by charjac** [comment]
Could i close this ?
