### ISSUE TITLE
[bug] - White page when connecting to Github

### ISSUE THREAD

**Issue by Olyno** [nukeop/nuclear#661]
# Description

I tried to connect my Github account to Nuclear's app.

# Reproduce

So the popout to log me is showed, I enter my Github email and password, and then white page.

Restart Nuclear doesn't fix the problem.

**OS:** Windows 10
**Using:** nuclear-fca030.exe

# Demonstrative

![Demonstrative issue available at https://i.imgur.com/B7ghdFe.gif](https://i.imgur.com/B7ghdFe.gif)

**Comment by nukeop** [comment]
The white window is expected (after logging in, Github redirects that popup window to localhost, and we get the token from the URL). The problem is that it still doesn't log you in. Thanks for reporting this, I'll look into it.
