### ISSUE TITLE
KDE connect media player

### ISSUE THREAD

**Issue by advaithm** [nukeop/nuclear#662]
on kde connect the media played shows that there are 2 windows open for nuclear and alternates songs between them.
for example you are playing song A and the next track is song B.
on kde connect song A is played on nuclear<2>(the second window it thinks is open)
when song B is played it is shown to be playing in nuclear(the first window)

on manjaro kde edition

**Comment by nukeop** [comment]
Does it use mpris?

**Comment by advaithm** [comment]
i believe they do use mpris

**Comment by nukeop** [comment]
Ok, I'll try to debug this soon.

**Comment by charjac** [comment]
I just made some test in the last manjaro kde, and it work as expected.
@advaithm  do you still have the problem?

**Comment by advaithm** [comment]
yeah sorry i didn't update. yeah the problem is no longer present. its
probably some weird edge case
