### ISSUE TITLE
Cannot start on Arch Linux

### ISSUE THREAD

**Issue by alifarazz** [nukeop/nuclear#666]
Cannot start nuclear 6.3 AppImage due to this error:
```
$ ./nuclear-fca030.AppImage
      main › something fail during app bootstrap
      main › Error: unknown address type:disabled
    at /opt/nuclear/resources/app.asar/dist/main.js:1985:16671
    at e.exports (/opt/nuclear/resources/app.asar/dist/main.js:1985:16778)
    at c (/opt/nuclear/resources/app.asar/dist/main.js:1985:5395)
    at Object.e.exports.sessionBus (/opt/nuclear/resources/app.asar/dist/main.js:1985:5597)
    at lt.p.init (/opt/nuclear/resources/app.asar/dist/main.js:2187:46373)
    at new p (/opt/nuclear/resources/app.asar/dist/main.js:2187:46190)
    at new lt (/opt/nuclear/resources/app.asar/dist/main.js:2292:403761)
    at Object.t.resolveInstance (/opt/nuclear/resources/app.asar/dist/main.js:2149:35651)
    at /opt/nuclear/resources/app.asar/dist/main.js:2149:37852
    at Array.map (<anonymous>)
```
The situation with the AUR version(`nuclear-player-bin`) is also the same.

**Comment by nukeop** [comment]
I develop on Arch, so this must be unrelated to the distro, and caused by something else.

The second line makes me think it might be related to starting the api, needs further debugging.

**Comment by martikyan** [comment]
Btw I use arch,
The app works great after installing it from AUR - nuclear-player-bin

**Comment by alifarazz** [comment]
Seems to be a problem with my system only.

**Comment by TOertel** [comment]
I have the same problem with v0.6.6 AppImage on Void Linux.

Running the git version I get this:
`@nuclear/main: node[14872]: pthread_create: Invalid argument
@nuclear/main:       main  development Env variables loaded
@nuclear/main:       main  Initialized settings store at /home/manax/.config/Electron/config.json
@nuclear/main:       main  something fails while trying to install devtools
@nuclear/main:       main  Sqlite database created at /home/manax/.config/Electron/nuclear-local-db.sqlite
@nuclear/main:       main  Something failed during app bootstrap
@nuclear/main:       main  Error: unknown address type:disabled
@nuclear/main:     at createStream (webpack:///./node_modules/dbus-next/lib/connection.js?:57:17)
@nuclear/main:     at createConnection (webpack:///./node_modules/dbus-next/lib/connection.js?:73:31)
@nuclear/main:     at createClient (webpack:///./node_modules/dbus-next/index.js?:9:20)
@nuclear/main:     at Object.module.exports.sessionBus (webpack:///./node_modules/dbus-next/index.js?:40:10)
@nuclear/main:     at LinuxMediaService.Player.init (webpack:///./node_modules/mpris-service/dist/index.js?:192:20)
@nuclear/main:     at new Player (webpack:///./node_modules/mpris-service/dist/index.js?:184:8)
@nuclear/main:     at new LinuxMediaService (webpack:///./src/services/@linux/system-api.ts?:62:9)
@nuclear/main:     at _createInstance (webpack:///./node_modules/inversify/lib/resolution/instantiation.js?:21:12)
@nuclear/main:     at Object.resolveInstance (webpack:///./node_modules/inversify/lib/resolution/instantiation.js?:41:18)
@nuclear/main:     at eval (webpack:///./node_modules/inversify/lib/resolution/resolver.js?:72:42)
@nuclear/main:     at Array.map (<anonymous>)
@nuclear/main:     at Object.resolveInstance (webpack:///./node_modules/inversify/lib/resolution/instantiation.js?:40:67)
@nuclear/main:     at eval (webpack:///./node_modules/inversify/lib/resolution/resolver.js?:72:42)
@nuclear/main:     at Object.resolve (webpack:///./node_modules/inversify/lib/resolution/resolver.js?:96:12)
@nuclear/main:     at eval (webpack:///./node_modules/inversify/lib/container/container.js?:319:37)
@nuclear/main:     at Container._get (webpack:///./node_modules/inversify/lib/container/container.js?:310:44)
`

**Comment by alifarazz** [comment]
> I have the same problem with v0.6.6 AppImage on Void Linux.
> 
> Running the git version I get this:
> 
> ```
> @nuclear/main: node[14872]: pthread_create: Invalid argument
> @nuclear/main:       main  development Env variables loaded
> @nuclear/main:       main  Initialized settings store at /home/manax/.config/Electron/config.json
> @nuclear/main:       main  something fails while trying to install devtools
> @nuclear/main:       main  Sqlite database created at /home/manax/.config/Electron/nuclear-local-db.sqlite
> @nuclear/main:       main  Something failed during app bootstrap
> @nuclear/main:       main  Error: unknown address type:disabled
> @nuclear/main:     at createStream (webpack:///./node_modules/dbus-next/lib/connection.js?:57:17)
> @nuclear/main:     at createConnection (webpack:///./node_modules/dbus-next/lib/connection.js?:73:31)
> @nuclear/main:     at createClient (webpack:///./node_modules/dbus-next/index.js?:9:20)
> @nuclear/main:     at Object.module.exports.sessionBus (webpack:///./node_modules/dbus-next/index.js?:40:10)
> @nuclear/main:     at LinuxMediaService.Player.init (webpack:///./node_modules/mpris-service/dist/index.js?:192:20)
> @nuclear/main:     at new Player (webpack:///./node_modules/mpris-service/dist/index.js?:184:8)
> @nuclear/main:     at new LinuxMediaService (webpack:///./src/services/@linux/system-api.ts?:62:9)
> @nuclear/main:     at _createInstance (webpack:///./node_modules/inversify/lib/resolution/instantiation.js?:21:12)
> @nuclear/main:     at Object.resolveInstance (webpack:///./node_modules/inversify/lib/resolution/instantiation.js?:41:18)
> @nuclear/main:     at eval (webpack:///./node_modules/inversify/lib/resolution/resolver.js?:72:42)
> @nuclear/main:     at Array.map (<anonymous>)
> @nuclear/main:     at Object.resolveInstance (webpack:///./node_modules/inversify/lib/resolution/instantiation.js?:40:67)
> @nuclear/main:     at eval (webpack:///./node_modules/inversify/lib/resolution/resolver.js?:72:42)
> @nuclear/main:     at Object.resolve (webpack:///./node_modules/inversify/lib/resolution/resolver.js?:96:12)
> @nuclear/main:     at eval (webpack:///./node_modules/inversify/lib/container/container.js?:319:37)
> @nuclear/main:     at Container._get (webpack:///./node_modules/inversify/lib/container/container.js?:310:44)
> ```

That's not the same issue I had with nuclear, judging from error messages.
I suggest you create a new issue and discuss the matter there. Have a look at this https://github.com/nukeop/nuclear/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
By the way, which version of neclear do have? AppImage? or ...?

**Comment by TOertel** [comment]
I suspect it is related, since running the appimage gave basically the same stack trace and error.
```
user@host# /tmp/nuclear-v0.6.6.AppImage 
node[31202]: pthread_create: Invalid argument
      main  Something failed during app bootstrap
      main  Error: unknown address type:disabled
    at /tmp/.mount_nucleaEiP5Jw/resources/app.asar/dist/main.js:2310:17193
    at e.exports (/tmp/.mount_nucleaEiP5Jw/resources/app.asar/dist/main.js:2310:17300)
    at c (/tmp/.mount_nucleaEiP5Jw/resources/app.asar/dist/main.js:2310:5923)
    at Object.e.exports.sessionBus (/tmp/.mount_nucleaEiP5Jw/resources/app.asar/dist/main.js:2310:6125)
    at er.p.init (/tmp/.mount_nucleaEiP5Jw/resources/app.asar/dist/main.js:2717:44369)
    at new p (/tmp/.mount_nucleaEiP5Jw/resources/app.asar/dist/main.js:2717:44188)
    at new er (/tmp/.mount_nucleaEiP5Jw/resources/app.asar/dist/main.js:2849:415211)
    at Object.t.resolveInstance (/tmp/.mount_nucleaEiP5Jw/resources/app.asar/dist/main.js:2679:35651)
    at /tmp/.mount_nucleaEiP5Jw/resources/app.asar/dist/main.js:2679:37852
    at Array.map (<anonymous>)
```
 I was guessing the appimage is compressed.  Running the git version gives the same error message, although different stack trace.  Yes, I thought about opening a separate issue, but they do seem related to me.

The git version was trunk from a few days ago.

You said it was a problem with "only your system".  Did you actually resolve it?

**Comment by alifarazz** [comment]
> You said it was a problem with "only your system". Did you actually resolve it?
It magically went away after a `pacman -Syu` (Arch Linux equivalent of system upgrade).
