### ISSUE TITLE
Nuclear is marked as malicious software reported by hybird analysis

### ISSUE THREAD

**Issue by spicru2** [nukeop/nuclear#672]
![image](https://user-images.githubusercontent.com/62023889/76763301-cfc56c00-67cd-11ea-814b-1d45364466a4.png)

I try to install windows version but monitored by security department with this report. I have to reinstall the system as demand. 

Hopefully nuclear can solve this issue and pass all the anti-virus testing.

**Comment by nukeop** [comment]
Where did you get the installers from?

**Comment by spicru2** [comment]
@nukeop github release, the lastest version `nuclear-Setup-fca030.exe`

**Comment by nukeop** [comment]
Releases are built on Travis VMs straight from this repository. Unless Travis has been infected with something that injects malicious code, the antivirus is showing false positives.
