### ISSUE TITLE
Playback stops if shuffle randomly reaches the last song

### ISSUE THREAD

**Issue by nathanfranke** [nukeop/nuclear#677]
If I queue 10 songs (named 1-10 for example)
shuffle might go from song 5, to 3, to 6, to 10 but once it reaches 10 and 10 finishes playing, the song will stop playing completely

**Comment by nukeop** [comment]
Right, the queue end check should also check if this setting is enabled.
This will also cause issues with single track looping: https://github.com/nukeop/nuclear/issues/475

**Comment by dejesusj** [comment]
I would like to work on this!

**Comment by nukeop** [comment]
Great, thank you. The best place to start would be here: https://github.com/nukeop/nuclear/blob/master/packages/app/app/containers/SoundContainer/index.js#L69

This functions controls what happens after a song has finished playing.

**Comment by dejesusj** [comment]
@nukeop Apologies for the delayed response, I was unexpectedly busy recently. Based on my understanding of how queues work on most music streaming platforms, I have a number of questions.
- Once a song is played, should it be removed from the queue?
    - If so, then could we just remove each played song from queueItems, and keep playing from the queue until queueItems is empty?
- If songs should not be removed from the queue after they are played, then how should the queue function? 
    - Currently it seems to function as a temporary playlist of some sort.
        - If that is the case, then should all songs be played at least once, and then once all songs have been played, either stop playback or continue looping the queue based on settings?
            - If Loop is toggled, then keep playing from the queue
            - If Loop is not toggled, and Autoradio is not toggled, then stop playback

**Comment by nukeop** [comment]
No, songs should not be removed from the queue automatically. The only change for this issue should be that we continue to the next random track regardless of which one we're currently at. Autoradio should not add new tracks, and the player should continue selecting new tracks randomly until user action.

**Comment by nukeop** [comment]
Fixed, thank you @dejesusj !
