### ISSUE TITLE
Volume not saved after restart

### ISSUE THREAD

**Issue by nathanwfranke** [nukeop/nuclear#679]
It always changes to max volume after restarting

**Comment by nukeop** [comment]
Right, thank you for reporting. This needs to be saved in the store.

**Comment by dejesusj** [comment]
If no one's working on this, I'd also like to give this a try.

**Comment by nukeop** [comment]
Thanks. Settings are defined in this file: https://github.com/nukeop/nuclear/blob/master/packages/core/src/settings/index.ts

So you'd need to add a new option somewhere in there, then make sure this action saves the current volume in it: 

https://github.com/nukeop/nuclear/blob/20772c637d70e28bd1a27ebe6099f6931e7968ba/packages/app/app/actions/player.js#L64

There are also a few places that read volume; those will need to use the new setting. Let me know if you have any problems.

**Comment by zephy20** [comment]
Is this still on pending? If yes, I'd like to give a try to this.

**Comment by nathanwfranke** [comment]
Go ahead since it's been 11 days since someone else wanted to fix it

**Comment by nukeop** [comment]
Yep, go ahead. What I wrote earlier still applies.

**Comment by dejesusj** [comment]
Could someone point me to the places that use Volume, specifically upon restart?

**Comment by nukeop** [comment]
Currently volume is initialized by redux, using an initial state:
https://github.com/nukeop/nuclear/blob/master/packages/app/app/reducers/player.js#L25
