### ISSUE TITLE
Allow making the bottom bar smaller

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#681]
It was suggested on Discord that the bottom bar takes too much space on some resolutions, it would be useful to be able to make it smaller.

**Comment by nukeop** [comment]
Ok, sure. You'll need to come up with a way to handle this, in terms of design. Feel free to hide some elements, such as the autoradio/shuffle icons, etc.

**Comment by envious777** [comment]
@nukeop I have a proposed solution and I'd like to work on this issue unless @dejesusj has done some work on this. Thanks!

**Comment by norakrantz** [comment]
@nukeop is this issue still open?

**Comment by nukeop** [comment]
Sure, there's an isolated component for the bar here: https://github.com/nukeop/nuclear/blob/846fd56fbf4237800e7c47f63a831bdded484e1d/packages/ui/lib/components/PlayerBar/index.tsx

The corresponding container is here: https://github.com/nukeop/nuclear/blob/995e1ca87c6b217d265d961928b478c2490015b2/packages/app/app/containers/PlayerBarContainer/index.tsx

**Comment by dipayanDebTheCoder** [comment]
@nukeop  Thanks for the reply. I will start working on this immediately.

**Comment by schaudry98** [comment]
Hi, I have not seen this issue resolved in any pull request yet, so would love to give it a try! :)

**Comment by nukeop** [comment]
Ok, I assigned it to you.

**Comment by schaudry98** [comment]
#917

**Comment by schaudry98** [comment]
I have created a pull request to try and resolve this feature request. Please let me know if there is anything that I will need to change! 
#917

**Comment by nukeop** [comment]
Implemented
