### ISSUE TITLE
"build" script cannot run on Windows

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#683]
The root `build` script fails on Windows, due to it using the `rm` command (which Windows does not have).

Same thing for the `start` script in `packages/main/package.json`, called by the root `start` script (which I've been trying to run).

Solution: add shx as a dev-dependency, and have the script call `shx rm` instead: https://github.com/shelljs/shx

I've used `shx` in multiple projects, and it's worked well for providing cross-platform equivalents of the linux `rm`, `cp`, `mkdir`, etc. commands (list of commands [here](https://github.com/shelljs/shelljs#command-reference)).

EDIT: I can confirm that after inserting `shx ` before the two `rm` calls mentioned above, running `npm run start` works as expected now on Windows. (launches program without errors)

**Comment by nukeop** [comment]
Right, we don't use the build script in CI, only `lerna run build`, so i didn't catch that. Thanks for the suggestion.
