### ISSUE TITLE
[feature request] Tree-view for local library

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#685]
Most of the long-term music players I've used in the past have had a way to display one's local library within a tree view, matching the folder/file structure.

For example, in foobar2000:
![](https://i.imgur.com/Hm8zNYS.png)

It would be nice to have an option to display one's local library like this in Nuclear as well. By displaying the actual folder/file structure, it allows you to categorize and subcategorize by your own criteria (for example, the `@Games` folder above), without it all just getting "flattened" as in the regular track/album views. Those views are good for many people, but some prefer the full control of having the raw directory tree represented.

I'm willing to work on this (as I also need it for [my plugin](https://github.com/Venryx/nuclear-vplugin) anyway), but would like to start the discussion here first to know if/how @nukeop would like me to approach it.

**Comment by nukeop** [comment]
Yep, this is a great idea. I'd check first if there are any react/electron plugins that already implement something like this.

**Comment by Venryx** [comment]
Does this library seem fine for implementing the tree-view?

https://github.com/react-component/tree

**Comment by nukeop** [comment]
Yes, react-redux-grid seems to be the most customizable one and the best for our purposes.

**Comment by Venryx** [comment]
Making good progress:
![](https://i.imgur.com/nksLg5I.png)

Things working:
* Expanding and contracting folders in the view
* Seeing tracks from multiple root folders
* Virtualized/infinite scrolling
* Search/filtering (still shows in tree structure, but only shows the paths with matching entries)

Things left to do:
1) Add the track context menu (to add to queue, etc.)
2) Have the expand/contract states persisted between panel navigations and app launches (I might add this later)

**Comment by Venryx** [comment]
Okay, just got the track context menu working:
![](https://i.imgur.com/hNSLbfN.png)

The basic functionality appears to be ready -- unless you see something it still needs.

----

Note that I hit _several_ pretty substantial issues with the program while preparing to develop the new folder-tree view...

I'm not sure if @nukeop and the other developers are hitting them or not, though they seem hard to miss:
1) Playing local files just doesn't work. It says it's playing (shows pause button), and there's no error, but time doesn't progress and no audio is played. (this seems a kinda big one XD)
2) For playing online tracks, I get an error: "The audio playback can not be loaded, either because the server or network failed or because the format is not supported." It appears to be the same issue hit [here](https://github.com/nukeop/nuclear/issues/676#issuecomment-601556060).
3) Hot-reloading is broken for me, as mentioned here: https://github.com/nukeop/nuclear/issues/692
4) The UI has a lot of delay whenever Redux actions are dispatched. (There must be a lot of subscriber components, and/or one of the components is very slow to render -- it's slow on every page. Perhaps it's due to the chromium Redux extension -- even when not opened?)
5) The [ui/TrackRow component](https://github.com/nukeop/nuclear/blob/ed0320465ff1489e21bc1a2ced17a529884ea51c/packages/ui/lib/components/TrackRow/index.js#L99) has code for handling the `artist` field as an `object`, or as a `string`, yet the `PropTypes` requires it be a `string`. This is inconsistent, and on my computer, actually causes an error (due to my local library yielding an object for the `artist` field), breaking the UI. I had to comment out the line for it in the `PropTypes` struct. (this sort of thing would be easy to avoid with a project-wide TypeScript revamp 😃)
6) The simple list-view for the local library has a scrollbar issue, as mentioned previously in [this comment](https://github.com/nukeop/nuclear/issues/568#issuecomment-568819669).

I pulled the latest code from this repo's master, and ran `lerna bootstrap`, so I don't see how I could be using outdated code/builds. Yet, the program seems less stable when running from my development watch/build versus the 0.6.3 release from a couple months ago, so I'm wondering what's going on.

Some possibilities:
1) Was there a recent code revamp that hasn't been ironed out yet?
2) Are they just some bugs that the core developers haven't hit much, so haven't yet been fixed?
3) Or am I somehow missing an update step that has me running buggy-but-since-fixed code?

**Comment by nukeop** [comment]
Hey, really good work, excited to merge this into master soon.

I might have broken some things on the master branch when reworking the code related to finding metadata recently, and didn't have much time to work on nuclear recently. Local playback could be one of the victims. This was a pretty big refactor, and I might have missed some things.

As for Redux, there are some heavy state updates that need to be refactored, particularly related to playback, as they happen very quickly and often. We had some problems with disk i/o causing lags too, but I think that's gone by now.

ui/TrackRow is supposed to replace the TrackRow from `app`, so if you see any inconsistencies preventing you from using it, feel free to fix them. I think I used an `object | string` type to keep it compatible with the way the track rows were used previously (you could either pass an artist name or an object like `{name: 'artistname'} because of the way data from various APIs was structured).

We can replace the virtualized list with the library you found after we merge this feature, just to keep the changes in each PR minimal.

**Comment by Venryx** [comment]
> Hey, really good work, excited to merge this into master soon.

Great. Should have it done in a couple days.

> I might have broken some things on the master branch when reworking the code related to finding metadata recently, and didn't have much time to work on nuclear recently. Local playback could be one of the victims. This was a pretty big refactor, and I might have missed some things.

Can you do a quick test for me? Can you try playing any mp3 audio file from the local library of the latest Nuclear master branch?

If that works for you, then I know it's an issue with my build or library, so can investigate there; if it _doesn't_ work for you, then I know it's something wrong with the codebase itself, so will start the regular debugging process.

> As for Redux, there are some heavy state updates that need to be refactored, particularly related to playback, as they happen very quickly and often. We had some problems with disk i/o causing lags too, but I think that's gone by now.

Since the slowdowns only occur in the development launches (`npm run start`) rather than the last release, it must either be related to compilation-dependent optimizations not being present, or due to some debugging process only enabled for the dev builds.

Regarding the severity of the slowdowns: It's severe enough that unless it's specific to my setup, it should be easy to notice by other devs. It's not just during playback, even opening several of the panels from the sidebar causes second+ delays:
* Dashboard: ~7s
* Downloads: ~1s
* Favorite Albums: ~1s
* Favorite Tracks: ~1s
* Local Library: ~3s

Do you experience these delays as well? (and this is with an empty playlist, dev-tools panel closed)

> ui/TrackRow is supposed to replace the TrackRow from app, so if you see any inconsistencies preventing you from using it, feel free to fix them. I think I used an `object | string` type to keep it compatible with the way the track rows were used previously (you could either pass an artist name or an object like `{name: 'artistname'}` because of the way data from various APIs was structured).

It seems like it would be worth normalizing the artist field to always be an object; if the source data only has the name available, it should just wrap it as `{name: 'artistname'}`, instead of causing a maintenance burden by storing a raw string instead.

Would it be okay if I made the change above to resolve the issue? (I'm more motivated toward that than placing a bandaid over the problem by widening the PropTypes definition)

> We can replace the virtualized list with the library you found after we merge this feature, just to keep the changes in each PR minimal.

Sounds good.

**Comment by nukeop** [comment]
Regarding the slowdown, can you check if your `~/.config/electron/config.json` is large?

We've moved the local library index into a separate file, but if you created it when it still was in the config, that could explain the slowdowns caused by electron-store. In that case, just delete the config so it can be re-created.

**Comment by Venryx** [comment]
Update on the slow navigation issue: It appears it's due to a super-super large `C:\Users\[user]\AppData\Roaming\Electron\config.json` file -- 46 megabytes!

On opening it, most of it appears to be from a "localMeta" key -- containing base64 encodings of the thumbnail for every track in my library.

After deleting that, the filesize went down to 30 kilobytes, and Nuclear finally is responsive again!

I think I remember seeing this issue mentioned before. I assume it's since been resolved? It seems to be, since relaunching the program retained its speediness, without increasing the `config.json` file's size anymore.

**Comment by Venryx** [comment]
> We've moved the local library index into a separate file, but if you created it when it still was in the config, that could explain the slowdowns caused by electron-store. In that case, just delete the config so it can be re-created.

Ah okay; yep, that solved it.

**Comment by nukeop** [comment]
You're right that local playback is messed up, although the queue items are added correctly (with the correct stream and `local` flag), but playback doesn't start. Probably something simple, maybe I forgot to handle the local playback special case when determining the selected stream in SoundContainer.

**Comment by Venryx** [comment]
Added my own Youtube api key, so that web tracks play now. This lets me compare between web and local playback to see what's missing for local.

I added a `console.log('Rendering sound:', currentStream);` line to SoundContainer.render.

Results: For online tracks, it returns valid data, but for local tracks it logs: `Rendering sound: undefined`.

Will track back from there looking for the missing/incorrect local-stream handling code.

**Comment by Venryx** [comment]
Okay, the problem seems to be that the higher-order-component for `SoundContainer` is trying to use the user-selected "music stream source" (default: Invidious) to play local files, even though local files only have one stream source available (type: Local), so retrieving the `currentStream` for `currentTrack` fails.

Some ways to fix it:
1) If the preferred stream source is not available, then just use the first stream source available. (generic approach which I slightly prefer)
2) If it's a local file, always use the "Local" source.

For now I've implemented approach 1 in the code, and it works fine:
```
withProps(({ currentTrack, plugins }) => ({
  currentStream: Boolean(currentTrack) && (_.find(currentTrack.streams, { source: plugins.selected.streamProviders }) || currentTrack.streams[0])
}))
```

**Comment by nukeop** [comment]
I think there was a special case for tracks with the local flag, which I forgot to handle when refactoring this part, your solution is fine for this purpose.
