### ISSUE TITLE
Transitioning to React Hooks (especially for react-redux)

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#693]
While implementing the folder-tree view of the local library feature (issue [here](https://github.com/nukeop/nuclear/issues/685)), I noticed freezing/skipping of the playback when it was open, and then found that the tree-view was constantly rerendering.

This led me to use the profiler and see what was going on "upstream" that would cause the tree-view to have to constantly render.

The problem seems to be that the playback is constantly sending out `UPDATE_PLAYBACK_PROGRESS` redux actions, which trigger the `mapStateToProps` function of `LibraryViewContainer`, which returns a new `tracks` field (since it applies, sorting, etc.), which rerenders `LibraryView`, which rerenders `LibraryFolderTree`, which is currently unoptimized so makes the UI stutter.

While I could optimize the LibraryFolderTree code, I'm much more concerned about the chain of unnecessary rerenders that's occurring that makes it a problem in the first place. (better to solve the problem in one place upstream rather than be forced to hyper-optimize every component underneath it)

In my projects, I use [MobX](https://github.com/mobxjs/mobx) rather than Redux, as it handles "fine-grained" updates (updates that only limited areas of the UI care about) more easily. But since this project is using Redux, I'd suggest the following optimization pattern: switching to using React Hooks throughout the project for subscribing to (and transforming) the Redux store data.

How does using React Hooks solve/mitigate the problem? Well, there are a few reasons (such as allowing finer-grained subscriptions to reduce "extraneous re-transforming" by in-same-func code), but mainly: because it makes it easy to "memoize" transformations that occur to data from the store, such that they only reprocess when the source data changes.

For example, here is how I used React Hooks to solve the performance issue above...

Old code:
```
function mapStateToProps(state) {
  const lowercaseFilter = _.lowerCase(state.local.filter);
  const checkFilter = string => _.includes(_.lowerCase(string), lowercaseFilter);
  const unfilteredTracks = _.values(state.local.tracks);
  const filteredTracks = _.filter(unfilteredTracks, track => {
    return _.some([
      checkFilter(track.name),
      checkFilter(track.album),
      checkFilter(_.get(track, 'artist.name'))
    ]);
  });

  let tracks = sortTracks(filteredTracks, state.local.sortBy);
  return {
    sortBy: state.local.sortBy,
    [...]
    tracks: state.local.direction === 'ascending' ? tracks : tracks.reverse(),
  };
}

function mapDispatchToProps(dispatch) {
  return {
    actions: bindActionCreators({ ...LocalActions, ...SettingsActions }, dispatch),
    queueActions: bindActionCreators(QueueActions, dispatch),
    playerActions: bindActionCreators(PlayerActions, dispatch)
  };
}

LibraryViewContainer = connect(
  mapStateToProps,
  mapDispatchToProps
)(LibraryView);
```

New code: (now without the unnecessary `LibraryViewConnector`)
```
const LibraryView = () => {
  const sortBy = useSelector(state => state.local.sortBy);
  [...]

  const unfilteredTracks = useMemo(() => _.values(tracks_map), [tracks_map]);
  const tracks = useMemo(() => {
    const checkFilter = string => _.includes(_.lowerCase(string), lowercaseFilter);
    const lowercaseFilter = _.lowerCase(filter);
    const filteredTracks = _.filter(unfilteredTracks, track => {
      return _.some([
        checkFilter(track.name),
        checkFilter(track.album),
        checkFilter(_.get(track, 'artist.name'))
      ]);
    });
    const tracks_preDirection = sortTracks(filteredTracks, sortBy);
    return direction === 'ascending' ? tracks_preDirection : tracks_preDirection.reverse();
  }, [unfilteredTracks, filter, sortBy, direction]);
  const filterApplied = useMemo(() => tracks.length < unfilteredTracks.length, [tracks, unfilteredTracks]);

  const dispatch = useDispatch();
  const actions = bindActionCreators({ ...LocalActions, ...SettingsActions }, dispatch);
  const queueActions = bindActionCreators(QueueActions, dispatch);
  const playerActions = bindActionCreators(PlayerActions, dispatch);

  return (
    [...]
  );
};
```

Because of the `useMemo` calls in the new approach, the `LibraryView` component no longer receives/passes-on a new `tracks` prop each time it renders. Thus, the `react-redux-grid` library's `Grid` component receives the exact same `treeConfig` data each render, which it then realizes is the same so doesn't rerender its internals.

This _drastically_ improved performance of the user-interface when the local-library panel was open. (ui rerender time went from ~400ms to ~30ms -- which is still not _great_, but is much better and usable)

Is this optimization approach suitable for expansion to the rest of the user-interface? Optimization was necessary at least for the local library, but it should help improve responsiveness in many other areas that use HOC components (with transformations) as well. (plus it keeps the codebase cleaner in my opinion to not have to have two files/folders for each redux-connected component -- though this is more of a coding-style/personal-taste factor)

**Comment by nukeop** [comment]
We can use `shouldComponentUpdate` to make most components ignore playback progress changes, or even move the currently playing track and its progress to a separate subtree kept isolated from anything else than the track progress bar.

Your solution is also appropriate (we could alternately use `React.memo`). I know that hocs are a pain to type correctly in typescript, and hooks make it a lot easier, so I guess we should use hooks for anything that will benefit from being later translated to typescript.

I like the component-container pattern though as it separates the concerns well (container only cares about gathering data and providing callbacks, component only cares about the presentation, it's also easier to test).

**Comment by Venryx** [comment]
> We can use shouldComponentUpdate to make most components ignore playback progress changes

It's not that straightforward, though; `shouldComponentUpdate` isn't designed such that you're able to say "ignore this type of action". Instead, it has to wait for the redux connector to run (regardless of if the accessed data is unchanged), and only after that, check whether the returned-from-connector data is equivalent to the previous set.

And how do you check whether the data is equivalent? Normally, you just do a shallow compare, to see if all the properties returned from the connector are the same. However, that does not work for the `LibraryView` case, because the connector returns a new `tracks` array every time, regardless of if the actual contents are the same (since it applies filtering and such). Thus, you'd have to do a "deep compare" if you took this approach, which is much more computationally intensive (especially for libraries with many thousands of tracks).

More abstractly, `shouldComponentUpdate` is not as powerful as React Hooks (specifically, `useMemo`) for optimization, because:

1) It can only allow/block updates for the component as a whole, eg. if there is a "heavy" transformation that occurs for property 1, and a secondary property 2 that's unrelated, whenever property 2 gets updated, the whole component must rerender (and therefore run the heavy property 1 transformation), even though [information/staleness]-wise this shouldn't be necessary. (note that "heavy transformation" can either be from the transformation code itself taking long to compute, or just that it gives a new reference each time, breaking shallow-comparing for components underneath that make use of it)

2) Currently, the [referential/shallow-compare]-breaking code for `LibraryView` is occurring in the `mapStateToProps` function in `LibraryViewConnector`; I'm not aware of a way to use `shouldComponentUpdate` to conditionally run the `mapStateToProps` connector (it runs for every store change). You could of course move this into `LibraryView` itself (such that `shouldComponentUpdate` can use shallow-compare again), but then that transformation code will also run whenever the component's state changes. If you don't often change its state (such that the shallow-compare breaking only occurs rarely), I suppose that's not a problem however -- though this does mean you must then pass everything from the store that you'd need to perform the transformation (complicating the component's passed-props set).

> or even move the currently playing track and its progress to a separate subtree kept isolated from anything else than the track progress bar

I think this is probably a good idea; but even if you move the "greatest offender" to another store, it would still be the case that the HOC pattern doesn't provide an easy way to "memoize" specific pieces of data, making optimization require more context awareness (of secondary prop updates, connector transformations, etc.). In contrast, React Hooks' `useMemo` provides isolated memoization of each property/transformation, which makes it easier to confirm (and preserve) the optimization of each transformation, and also enables optimization of some cases that otherwise would not be possible (eg. optimizing/memoizing one heavy transformation, in the midst of minor secondary property updates).

I can see how the HOC pattern is nice for testing, however; I suppose that for React Hooks, you'd override the `useSelector` function to return data from a customized store data-tree for the test, though that is a bit more work than just passing a set of props directly.

**Comment by Venryx** [comment]
> I like the component-container pattern though as it separates the concerns well (container only cares about gathering data and providing callbacks, component only cares about the presentation, it's also easier to test).

I just thought of a "compromise" that could be made between HOC and hooks: use hooks, but require all of the `useSelector` hooks to be called from a `selectState` function, which the parent component can override (thus enabling easy testing).

For example, if this is the current HOC code:
```
function mapStateToProps(state) {
  return {
    tracks: state.local.tracks,
  };
}
LibraryViewContainer = connect(mapStateToProps, mapDispatchToProps)(LibraryView);

const LibraryView = ({tracks})=> {
  return <div>{tracks.map(track=>track.title)}</div>;
};
```

Here it is with basic hooks:
```
const LibraryView = ({tracks})=> {
  const tracks = useSelector(state=>state.local.tracks);
  return <div>{tracks.map(track=>track.title)}</div>;
};
```

And here it is with the "compromise" approach:
```
function selectState_default() {
  return {
    tracks: useSelector(state=>state.local.tracks)
  };
}

const LibraryView = ({selectState})=> {
  const {tracks} = (selectState || selectState_default)();
  return <div>{tracks.map(track=>track.title)}</div>;
};
```

Benefits:
1) Like the HOC approach, has the store-access code separated into its own function, for separation of concerns. (personally I don't see this as that important, but for those who prefer it, it provides it)
2) Like the HOC approach, provides an easy way to make tests for the component. (just pass in a custom `selectState` function, which returns the desired store test-data)
3) Like the hooks approach, enables you to use the `useMemo` hook, enabling full flexibility of memoization ensuring that child components don't ever re-render more than they need to. (including cases which are not possible to solve using `shouldComponentUpdate`, as described in my previous post)

Anyway, what are your thoughts on this "compromise" approach? Is it acceptable as an alternative to the previous two (HOC, render-func-hooks) approaches?

**Comment by nukeop** [comment]
I like your approach a lot, and it's similar to what I'm using at work. You can also add reselect library for memoizing selectors.

The best and most testable way for LibraryView and really all the views in general would be to have a purely presentational component that only has markup in it, and to supply everything (state, callbacks, i18n) as props to it. This way it doesn't matter if we use hocs or hooks or something else, and we can easily mock anything. In the past, I've written lots of components that receive actions/redux state from their containers, but define their own callbacks and compose actions into more complex sequences. I think the way forward is to define those in the containers too, and let the component receive everything from above. 

I was on the fence regarding the hooks for some time but I have since found out that they can be used in essentially the same way as hocs and are way easier to type correctly with TS (with hocs you need to define a generic type for the input class and output class, with hooks you're only interested in the things they themselves return so the typings are much simpler).
