### ISSUE TITLE
Update DevBuildProcess in Contributing Wiki Page

### ISSUE THREAD

**Issue by primeapple** [nukeop/nuclear#696]
Hi everyone,

I suggest to update the "Contributing" WikiPage ( see https://github.com/nukeop/nuclear/wiki/Contributing ). The last update was over 1 year ago and since this you seem to have moved more towards docker! Please update and also include the docker instructions from https://github.com/nukeop/nuclear/blob/master/README.md

Also I found, that the building is not working correctly? With docker I get the error:
```
dev_1      | lerna ERR! Error: ENOENT: no such file or directory, rename '/nuclear/packages/main/package.json.lerna_backup' -> '/nuclear/packages/main/package.json'
dev_1      | lerna ERR!     at Object.renameSync (fs.js:754:3)
dev_1      | lerna ERR!     at cleanup (/usr/local/lib/node_modules/lerna/node_modules/@lerna/npm-install/npm-install.js:70:10)
dev_1      | lerna ERR!     at done (/usr/local/lib/node_modules/lerna/node_modules/@lerna/npm-install/npm-install.js:78:7)
dev_1      | lerna ERR!     at /usr/local/lib/node_modules/lerna/node_modules/@lerna/npm-install/npm-install.js:94:19
dev_1      | lerna ERR! lerna ENOENT: no such file or directory, rename '/nuclear/packages/main/package.json.lerna_backup' -> '/nuclear/packages/main/package.json'
```
However, after this, the starting continues until 
```
dev_1      | + lerna run start
dev_1      | lerna notice cli v3.20.2
dev_1      | lerna success run No packages found with the lifecycle script 'start'
```

With the manual method by using lerna, I can build nuclear successfull, but when starting with `npm start`, I also get: 
```
lerna success run No packages found with the lifecycle script 'start'
```

However, `npm run build` gives me 
```
sh: shx: Kommando nicht gefunden.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! nuclear@0.6.3 build: `shx rm -rf dist && lerna run build && npm run pack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nuclear@0.6.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

Do you have any ideas?

**Comment by Venryx** [comment]
The "shx" command was recently added (by me) as a cross-platform way of running the "rm" command.

You should be able to just rerun "npm install" to have it installed as a dev-dependency.

**Comment by primeapple** [comment]
I understand what you mean, however, this does not explain why the docker doesnt build?
I tried docker again, this time getting:

```
dev_1      | + lerna bootstrap
dev_1      | lerna notice cli v3.20.2
dev_1      | lerna info Bootstrapping 5 packages
dev_1      | lerna info Installing external dependencies
dev_1      | lerna ERR! npm install exited 1 in '@nuclear/ui'
dev_1      | lerna ERR! npm install stderr:
dev_1      | npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
dev_1      | npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
dev_1      | npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
dev_1      | npm WARN deprecated chokidar@2.1.8: Upgrade to chokidar 3 with 15x less dependencies. Chokidar 2 will break on node v14.
dev_1      | npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
dev_1      | npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
dev_1      | npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
dev_1      | npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
dev_1      | npm ERR! cb() never called!
dev_1      | 
dev_1      | npm ERR! This is an error with npm itself. Please report this error at:
dev_1      | npm ERR!     <https://npm.community>
dev_1      | 
dev_1      | npm ERR! A complete log of this run can be found in:
dev_1      | npm ERR!     /root/.npm/_logs/2020-04-20T06_34_51_514Z-debug.log
dev_1      | 
dev_1      | lerna ERR! npm install exited 1 in '@nuclear/ui'
dev_1      | lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
dev_1      | + lerna exec npm rebuild node-sass
dev_1      | lerna notice cli v3.20.2
dev_1      | lerna info Executing command in 5 packages: "npm rebuild node-sass"
dev_1      | lerna success exec Executed command in 5 packages: "npm rebuild node-sass"
dev_1      | + lerna run start
dev_1      | lerna notice cli v3.20.2
dev_1      | lerna info Executing command in 5 packages: "npm run start"
dev_1      | lerna ERR! npm run start exited 2 in '@nuclear/i18n'
dev_1      | lerna ERR! npm run start stdout:
dev_1      | 
dev_1      | > @nuclear/i18n@0.6.3 start /nuclear/packages/i18n
dev_1      | > tsc
dev_1      | 
dev_1      | error TS2318: Cannot find global type 'Array'.
dev_1      | error TS2318: Cannot find global type 'Boolean'.
dev_1      | error TS2318: Cannot find global type 'Function'.
dev_1      | error TS2318: Cannot find global type 'IArguments'.
dev_1      | error TS2318: Cannot find global type 'Number'.
dev_1      | error TS2318: Cannot find global type 'Object'.
dev_1      | error TS2318: Cannot find global type 'RegExp'.
dev_1      | error TS2318: Cannot find global type 'String'.
dev_1      | 
dev_1      | lerna ERR! npm run start stderr:
dev_1      | npm ERR! code ELIFECYCLE
dev_1      | npm ERR! errno 2
dev_1      | npm ERR! @nuclear/i18n@0.6.3 start: `tsc`
dev_1      | npm ERR! Exit status 2
dev_1      | npm ERR! 
dev_1      | npm ERR! Failed at the @nuclear/i18n@0.6.3 start script.
dev_1      | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
dev_1      | 
dev_1      | npm ERR! A complete log of this run can be found in:
dev_1      | npm ERR!     /root/.npm/_logs/2020-04-20T06_34_57_158Z-debug.log
dev_1      | 
dev_1      | lerna ERR! npm run start exited 2 in '@nuclear/i18n'
dev_1      | lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

**Comment by Venryx** [comment]
> I understand what you mean, however, this does not explain why the docker doesnt build?

Right, that doesn't explain the docker issue.

Was just giving some info for that last error in your original post. (about "shx: command not found")

**Comment by primeapple** [comment]
So I debugged some of the problems. We have the following:

1. You are missing an `npm install` in your instructions. This is what @Venryx refered to, thank you btw.
2. Why do we have a `npm i -g lerna` in the Readme? Since lerna is a dev dependency, we could just use `npm install` (which has to be done anyways) and `npx lerna bootstrap`. This way, we don't need any global npm packages (which are controversal anyways).

I will provide a pull request, once I finished debugging the docker issue.

**Comment by nukeop** [comment]
Lerna is a useful tool to have to manage the repository and perform all sorts of operations affecting packages (managing versions, cleaning, linking, installing dependencies, checking what's changed, etc), that's why it's recommended to install it globally. This way you can use it in other contexts than the root directory of the project.

**Comment by nukeop** [comment]
I'm checking if the docker development process works on a newly cloned repo.

**Comment by nukeop** [comment]
It works for me with a caveat: `lerna bootstrap` has to run first outside of docker, otherwise lerna will mess up the `package.json` (not sure why) and refuse to install dependencies correctly.

**Comment by primeapple** [comment]
> Lerna is a useful tool to have to manage the repository and perform all sorts of operations affecting packages (managing versions, cleaning, linking, installing dependencies, checking what's changed, etc), that's why it's recommended to install it globally. This way you can use it in other contexts than the root directory of the project.

I understand what you mean, however, I don't agree with you on this. But it's your project after all, so this is fine :)  
However, I would at least add the option to not install lerna. We could add it as a comment for example.

I think the docker should work completely independent. So just running `docker-compose up dev` should bring up the project, REGARDLESS if lerna was used before or not. I would like to create a seperate Issue for this, because I also have some questions about your docker config. Also for me docker on a newly cloned repo is not working working anyways (you have to at least run `npm install` before).

**Comment by primeapple** [comment]
Ok, I changed my mind. I would strongly suggest to remove lernas global install. Reasons:

1. `npx lerna` does basically the same. Also from other contexts than the root directory of the project.
2. With a global install, you come to a point (for example when using `lerna clean`, where you will get into permission issues and have to sudo your way through it. That is neither good practice, nor helpful.
3. We already have lerna as a dependency in `$Root/package.json`. Since it is getting installed anyways, we can just use it, right?

Other thoughts about this: https://dev.to/tallyb/when-to-use-global-npm-installs-rarely-2dm3

The thing is, you can still use your global lerna installation if you would like. However, for new developers, this should be the best practice. Anyone who knows what he is doing, can decide themselves if they want global installs.

**Comment by primeapple** [comment]
I created a pull request for this. Please check if it is fine for you.

**Comment by primeapple** [comment]
Is there any interest from your side about this issue? Otherwise I would close it, as sad as it would be. It's your project after all.

**Comment by kwesiopon** [comment]
Hi also new to dev building and encountering similar issues. Anytime I  try to run "npm install" I  get this:
`adrianopon@Adrians-Air nuclear % npm install       

> nuclear@0.6.3 postinstall /Users/adrianopon/Documents/Projects/nuclear/nuclear
> lerna bootstrap --no-ci

lerna notice cli v3.21.0
lerna info Bootstrapping 5 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@nuclear/main'
lerna ERR! npm install stdout:

> electron-media-service@0.2.2 install /Users/adrianopon/Documents/Projects/nuclear/nuclear/packages/main/node_modules/electron-media-service
> node-gyp rebuild


> register-scheme@0.0.2 install /Users/adrianopon/Documents/Projects/nuclear/nuclear/packages/main/node_modules/register-scheme
> node-gyp rebuild


lerna ERR! npm install stderr:
npm WARN package.json @nuclear/main@0.6.3 No README data
npm WARN optional dep failed, continuing @nodert-win10/windows.media.playback@0.2.96
npm WARN optional dep failed, continuing @nodert-win10/windows.foundation@0.2.96
npm WARN optional dep failed, continuing @nodert-win10/windows.storage.streams@0.2.96
npm WARN optional dep failed, continuing @nodert-win10/windows.media@0.2.96
npm WARN peerDependencies The peer dependency register-scheme@github:devsnek/node-register-scheme included from discord-rpc will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/14.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adrianopon/Documents/Projects/nuclear/nuclear/packages/main/node_modules/electron-media-service
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/14.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adrianopon/Documents/Projects/nuclear/nuclear/packages/main/node_modules/register-scheme
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional dep failed, continuing electron-media-service@0.2.2
npm ERR! Darwin 19.2.0
npm ERR! argv "/usr/local/Cellar/node/14.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v14.2.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! register-scheme@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the register-scheme@0.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the register-scheme package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs register-scheme
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls register-scheme
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adrianopon/Documents/Projects/nuclear/nuclear/packages/main/npm-debug.log

lerna ERR! npm install exited 1 in '@nuclear/main'

npm ERR! Darwin 19.2.0
npm ERR! argv "/usr/local/Cellar/node/14.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v14.2.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! nuclear@0.6.3 postinstall: `lerna bootstrap --no-ci`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nuclear@0.6.3 postinstall script 'lerna bootstrap --no-ci'.
npm ERR! This is most likely a problem with the nuclear package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap --no-ci
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nuclear
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls nuclear
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adrianopon/Documents/Projects/nuclear/nuclear/npm-debug.log`

Please advise. Also, your Wiki makes no mention of how Docker is used in the dev building process, could I  get a resource that could help me out with that?

**Comment by nukeop** [comment]
I'll come back to this once I finish working on adding TS to the app package, since it may affect this. Thanks for the patience and don't worry, your work will not be wasted.

**Comment by nukeop** [comment]
@kwesiopon It looks like you have a very old npm version, try upgrading to v6.

**Comment by spongechameleon** [comment]
Another Contributing wiki page problem.

The startup instructions are:

> Make sure you're using the latest version of Node and NPM. To develop the project locally, you should only do:
> `$ npm install`
> `$ npm run watch`

But should be:

> Make sure you're using the latest version of Node and NPM. To develop the project locally, you should only do:
> `$ npm install`
> `$ npm start`

As the watch script no longer exists. Obviously a small inconvenience (the README is correct) but figure I'd mention it anyways. Can't figure out how to edit the wiki pages myself.

**Comment by nukeop** [comment]
You're right, I edited it to match the current state.
