### ISSUE TITLE
Change Discord application name to fit "Playing" status

### ISSUE THREAD

**Issue by nathanfranke** [nukeop/nuclear#709]
![image](https://user-images.githubusercontent.com/14253836/81198632-53f2cf00-8f87-11ea-9f82-97d22e8c61f9.png)
_Notice "Play..." rather than "Player"_

I propose renaming the application to "Nuclear" (Or "Nuclear Music", but I prefer the former)

<sub>Note: This issue cannot be solved in a Pull Request, but rather on [Discord's application manager](https://discord.com/developers/applications)</sub>

**Comment by nukeop** [comment]
@charjac created the application on Discord, so he has the keys 🗝️

**Comment by charjac** [comment]
I will make the change

**Comment by charjac** [comment]
@nukeop does "Nuclear" is ok as discord application name ?

**Comment by charjac** [comment]
@nukeop I created a dev team on discord developer portal, what is your discord userId please ?

**Comment by nukeop** [comment]
> @nukeop is "Nuclear" ok as discord application name ?

Sure

> @nukeop I created a dev team on discord developer portal, what is your discord userId please ?

It's 226015340436520960

**Comment by charjac** [comment]
@nukeop i need something like this: "name#id"

**Comment by nathanfranke** [comment]
User ID is a number and abcd#1234 is a tag

**Comment by charjac** [comment]
@nathanfranke i am just an old person who miss his good old mumble ;) 
thx for the info.

**Comment by nathanfranke** [comment]
Haha no problem. To be fair, unique usernames are a way better system in my opinion

**Comment by nukeop** [comment]
> @nukeop i need something like this: "name#id"
nitehawk #9164

**Comment by charjac** [comment]
@nathanfranke is it ok now ?

**Comment by nathanfranke** [comment]
I won't be able to check for a few days but it should be fine. Thanks for fixing
