### ISSUE TITLE
Closing the window when in frameless mode does not close it completely

### ISSUE THREAD

**Issue by nathanfranke** [nukeop/nuclear#711]
If you add to `main.ts`
```js
app.on('window-all-closed', () => {
  logger.log("Hello World"); // Window is being closed properly
});
```

https://github.com/nukeop/nuclear/blob/f8a19d5918347addd823b75d1ee5265e978f5054/packages/main/src/services/window/index.ts#L49

Changing this line to `frame: false,` makes the window not close properly. (Hello World not printed)
Changing it to `frame: true,` makes it close properly. (Hello World Printed)

Edit 1: Cannot reproduce this in an empty electron project. OS: Linux Mint 19.3 and Compiz WM

Edit 2: The call to `store.getOption('framelessWindow')` does not cause this, since issue still reproducible even if I make a temporary variable.

**Comment by nukeop** [comment]
Thanks for reporting, definitely sounds odd. Needs investigation if it's just this one setting that's causing this.

**Comment by nathanfranke** [comment]
On Manjaro KDE now. Nuclear never closes when I hit the "X" button, even if the frame is visible or not.

```
@nuclear/main:       main › All windows closed, quitting
@nuclear/main:       main › clear discord activity
^C
```

**Comment by nukeop** [comment]
I tried debugging this recently. And it turns out that all the events in the Electron shutdown sequence are fired correctly, but even after the last one finishes with no errors thrown, it still won't kill the process. Makes me think we need to make it exit more brutally if we can't get to the bottom of this.

**Comment by nathanfranke** [comment]
My only thought is that it might be a stray async function or listener that is never closed. Is there any way to debug and find those?

**Comment by nukeop** [comment]
I don't know how yet. I'll need to take a look at any modules that are accessing files on the disk, maybe not freeing file handles is causing it to wait forever.

**Comment by nathanfranke** [comment]
Output from [`wtfnode`](https://www.npmjs.com/package/wtfnode)

```
@nuclear/main:       main › All windows closed, quitting
@nuclear/main:       main › clear discord activity
@nuclear/main:       main › [WTF Node?] open handles:
@nuclear/main:       main › - File descriptors: (note: stdio always exists)
@nuclear/main:       main ›   - fd 1 (stdio)
@nuclear/main:       main ›   - fd 2 (stdio)
@nuclear/main:       main › - Sockets:
@nuclear/main:       main ›   - fd 138
@nuclear/main:       main ›   - fd 185
```

Not very clear where they are exactly, but hopefully this is a step in the right direction

**Comment by nukeop** [comment]
Thanks, handy tool. Didn't know about that.

**Comment by nukeop** [comment]
I tried reproducing this now and it doesn't occur anymore.
