### ISSUE TITLE
Downloads stuck at "waiting" 0%

### ISSUE THREAD

**Issue by Kusurisan** [nukeop/nuclear#712]
if you click download on a song and it gets added to the download queue, it gets stuck at "Waiting" and stays at 0%. sometimes it works and downloads the song, but in 95% of the cases it don't works. i use the windows version with win10, tried my own youtube data api key, tried the setup and portable version but nothing seems to work. playing songs works fine, just not downloading.

**Comment by nukeop** [comment]
Thanks for reporting, what song is giving you trouble?

**Comment by Kusurisan** [comment]
> 
> 
> Thanks for reporting, what song is giving you trouble?

"[:SITD:] - Herbsterwachen", "Jerome - Light", "Lucky Luke - F.E.E.L", "Beattraxx - Project Well" and a few others - actually a LOT of the songs i found in in the "Genres" tab for music.

the weird part about this is thought - when i tried a few other songs yesterday, they didn't worked.. but some of them now worked suddenly when i tried again to see which ones don't work. so it seems to be random if it works or not somehow.

**Comment by nukeop** [comment]
This is probably related to the fact that downloading still relies on the youtube api, and our api key is restricted/banned. It might help to provide your own key, but the correct long term solution is to move to Invidious.

**Comment by Kusurisan** [comment]
i used my own api key when i encountered the bug, so it isn't 100% your api key. i tried the build in api key and my own - both had the same issue. and since my api key isn't used in any other project, it isn't related to restriction / banns.

**Comment by tiotrom** [comment]
Yes I can confirm it here. Download does not work.

**Comment by PhoenixDiscord** [comment]
Same.

**Comment by mYnDstrEAm** [comment]
Same here. Why isn't `youtube-dl` being used?

**Comment by nukeop** [comment]
> Same here. Why isn't `youtube-dl` being used?

Because we're using node-ytdl and electron-dl. Bundling native binaries is troublesome as it is.

**Comment by mYnDstrEAm** [comment]
I haven't checked `@nuclear/core/src/rest/Invidious` is it using `node-ytdl`?

Youtube-dl wouldn't need to be bundled but maybe it would be possible to e.g. run bash commands from Nuclear so that users only need to install  it separately (if they haven't installed it yet). But this wouldn't work for the Windows .exe I guess.

In any case: youtube-dl works while Nuclear's download doesn't. The proper way would probably be using `node-ytdl` in some form. What's meant with the commit message "Use invidious for downloads"? Would this solution also work with e.g. SoundCloud like with youtube-dl?

**Comment by mlovizio** [comment]
Hi, I was going to report this in a new issue but it seems to be well covered here so I will just add what I was experiencing here:
&nbsp;

# Downloads  only works for the 1st song
## The issue
The downloads **works** but only starts when there is no other song in the download queue at the time the track tries to download.

https://user-images.githubusercontent.com/74993598/125164615-91de1b00-e169-11eb-8bed-41252cbecd74.mp4

OS: W10

Nuclear: at least from 0.60.15 & 0.6.16
* * *
_The behavior varies a little depending on the song ( some will download in the condition  showed above, some don't but those who won't download won't do it in any case, that seems to be an issue of the track in particular)_
