### ISSUE TITLE
Native window decoration

### ISSUE THREAD

**Issue by tiotrom** [nukeop/nuclear#714]
Would you consider a native window decoration? In linux that would be great! There are some functionalities such as allowing a window to be visible on any virtual screen or on top of any window and such. It also looks better on linux to have all applications use the native window decoration of the system. cheers!

**Comment by nukeop** [comment]
You can already use the native frame by unchecking the frameless window option in settings.

**Comment by tiotrom** [comment]
Ohh ok I had no idea about that. For one, shouldn't this be default? This way it integrates better with Linux systems. And second, once I disabled that option I had no easy way to restart the application so I had to shut down the process itself from the system monitor to then be able to reopen it to see it taking effect. Maybe force restart of the app once that option is selected or deselected by adding a button that users can click to restart.

But I honestly think that it should be deactivated by default so it integrates with whatever Desktop Environment you have.

Cheers!
