### ISSUE TITLE
Choose audio sources

### ISSUE THREAD

**Issue by Caduser2020** [nukeop/nuclear#716]
Some songs are exclusive to one audio provider, but other songs have similar names in different providers. This could be easily avoided by providing a setting to choose allowed audio providers.

I have forked the project and am working on a patch and settings to easily enable and disable audio providers.

**Comment by nukeop** [comment]
What do you mean? You can already choose stream providers in the plugins section, and per song.

**Comment by Caduser2020** [comment]
As I understand it, the plugins "select default music source" specifies the audio provider tried first. I would like a setting to completely disable certain audio providers that I do not need.

**Comment by nukeop** [comment]
Oh ok. Yes, you are right, this would be a useful thing to have.

**Comment by nukeop** [comment]
Audio providers are exclusive now so those not selected will not be used
