### ISSUE TITLE
Service plugin

### ISSUE THREAD

**Issue by GameMaster1315** [nukeop/nuclear#717]
I try to change the plugin from Invidious to Soundcloud on version 0.6.3, but when I restart the app, it reverts back to Invidious. I need to find a way on how to keep it on the Soundcloud plugin.

**Comment by nukeop** [comment]
Must be a regression since it used to be saved normally

**Comment by GameMaster1315** [comment]
How would you be able to fix the issue I'm having with the player?

**Comment by nukeop** [comment]
Plugin selections will now be saved in config.json.
