### ISSUE TITLE
[Regression] Cannot play songs

### ISSUE THREAD

**Issue by nathanfranke** [nukeop/nuclear#718]
In master I cannot play any songs.

I'm not very good with git but this is my reproductions in these two commits.

Working (I can play songs) - f8a19d5918347addd823b75d1ee5265e978f5054
Not Working (I cannot play songs) - fab9203312658cf5532f36494b871c3b2727465a

https://www.youtube.com/watch?v=0VZXogSQ3as

**Comment by nukeop** [comment]
Thanks for reporting, let me take a look
