### ISSUE TITLE
[Build] Invalid configuration object: unknown property 'loaders'

### ISSUE THREAD

**Issue by Houkime** [nukeop/nuclear#72]
OS: Arch Linux as of 22.06.2018 
after `$npm install`.

`$ npm run build:dist`

```
> nuclear@0.4.3 build:dist /home/user/nuclear
> webpack --progress --colors --env=prod --define process.env.NODE_ENV=production && cp loader.css dist

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:                                        
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }         
   -> Options affecting the normal modules (`NormalModuleFactory`).                                                           
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuclear@0.4.3 build:dist: `webpack --progress --colors --env=prod --define process.env.NODE_ENV=production && cp loader.css dist`
npm ERR! Exit status 1

```

Problem also shows up when running `npm run watch`

[2018-06-22T18_47_27_632Z-debug.log](https://github.com/nukeop/nuclear/files/2128808/2018-06-22T18_47_27_632Z-debug.log)

**Comment by nukeop** [comment]
This is probably because the configs are incompatible with Webpack 4. Looking at package.json, it specifies version 4 point something, which is incorrect. I'll take a look after the weekend and resolve it.

**Comment by BrandonS8** [comment]
I fixed this problem for me by downgrading to webpack 3.1.4 and also downgrading webpack-dev-server to 3.0.0 since it relied on Webpack 4.

**Comment by Houkime** [comment]
Well, downgrading never seems like a _strategically_ right choice cause it tends to cause all sorts of troubles for users over time.
It is more like the configs need to be updated and not Webpack downgraded.

**Comment by nukeop** [comment]
I think you can just replace 'loaders' with 'rules' and it'll work with Webpack 4.
