### ISSUE TITLE
Local music from added folder not being added to Local Library

### ISSUE THREAD

**Issue by skyawmyint** [nukeop/nuclear#720]
**Version of nuclear (written under the main logo)**
0.6.3

**Your operating system**
Windows 10 Home

**Reproducible steps (1... 2... 3...) that cause the issue**
Step 1: Go to the Local Library tab from the left menu
Step 2: Click on add folders button
Step 3: Go to a folder that has music in it and click select folder
Step 4: Click the refresh button next to add folder

**What you expected to see, versus what you actually saw**
When adding a folder from the local desktop, the directory is made path, but none of the songs from that folder is being brought onto the application and the Local Library remains empty.  There is also no button to add songs to the Local Library.
Expected the songs from the folder that was specified in the add folders should be in the library now. The actual results were that the songs from the folder that was specified in the add folders was not added to the library. The library shows the it is still empty.

Images, animations, or a link to a video showing the issue occurring
![LocalLibrary_Example1](https://user-images.githubusercontent.com/44180667/83703021-3125fb80-a5c3-11ea-9ef3-bb1b7b70c2f8.jpg)

**A code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally**
N/A

**Comment by nukeop** [comment]
What formats of files are inside your library? Could you please give me an example of an album folder?

**Comment by masoud-msk** [comment]
It happened for me when adding a large directory containing 4000 files. I narrowed the problem down to a single file which caused the error `ipc api › error in event set-localfolders => pictureType should be defined`.
Note that *VLC* can successfully play the file with album art.

**Comment by Venryx** [comment]
I'm getting an issue, possibly the same, where Nuclear gets stuck scanning/refreshing the files in my library:
![](https://i.imgur.com/Hw8UAQJ.png)

I searched Process Hacker 2 for the list of commands running under the Nuclear root folder, and it showed the many `fpcalc` instances as it attempted to scan the files. When the scanning stopped in Nuclear's UI, I checked that list again, and no `fpcalc` commands. So it's not fpcalc hanging, it's something higher level.

It's worth noting that _some_ files from my library folder did end up showing up in Nuclear after the scan-freeze. But only those from the "Foreign" folder, not the other two.

It's odd because Nuclear used to be able to scan and present the file from my entire library. So some change in the last half year or so has caused it to choke on certain files, apparently.

**Comment by Venryx** [comment]
I looked at the console, and found this:
```
@nuclear/main:       main › Error: ERROR: Empty fingerprint
@nuclear/main:     at cp.stderr.pipe.concat_stream__WEBPACK_IMPORTED_MODULE_4___default (webpack:///./src/services/acoustic-id/index.ts?:107:38)
@nuclear/main:     at ConcatStream.eval (webpack:///./node_modules/concat-stream/index.js?:37:43)
@nuclear/main:     at ConcatStream.emit (events.js:187:15)
@nuclear/main:     at finishMaybe (webpack:///./node_modules/readable-stream/lib/_stream_writable.js?:624:14)
@nuclear/main:     at endWritable (webpack:///./node_modules/readable-stream/lib/_stream_writable.js?:643:3)
@nuclear/main:     at ConcatStream.Writable.end (webpack:///./node_modules/readable-stream/lib/_stream_writable.js?:571:22)
@nuclear/main:     at Socket.onend (_stream_readable.js:628:10)
@nuclear/main:     at Object.onceWrapper (events.js:273:13)
@nuclear/main:     at Socket.emit (events.js:187:15)
@nuclear/main:     at endReadableNT (_stream_readable.js:1092:12)
@nuclear/main:     at process._tickCallback (internal/process/next_tick.js:63:19)
[...]
@nuclear/main:    ipc api ›  <== local-files-error: TypeError
```

**Comment by Venryx** [comment]
I was able to prevent breaking of the library-scanning by adding a try-catch just inside the `if (this.config.isConnected) {` block of the `parseMeta` function. (in `packages/main/src/services/local-library/index.ts`)
```
private async parseMeta(filesPath: Array<{ file: string; folder?: LocalFolder }>, onProgress?: ProgressHandler): Promise<NuclearMeta[]> {
    const metas = await Promise.all(filesPath.map(({ file }) => parseFile(file)));

    const formattedMetas = await Promise.all(filesPath.map((file, i) => this.formatMeta(metas[i], file)));

    if (this.config.isConnected) {
      try {
        const formattedMetasWithoutName = formattedMetas.filter(meta => !meta.name);
    
        if (formattedMetasWithoutName.length) {
          await this.fetchAcousticIdBatch(formattedMetasWithoutName, onProgress);
        }
      } catch (er) {
        // simply catch the error (already console-logged); track recognition should not break whole local-library scan
      }
    }

    return formattedMetas;
  }
```

My library now loads correctly again.

@nukeop Does this seem like a suitable fix for the error I hit? The error still gets logged to the console (for diagnostic purposes), but it's a "safety net" for preventing random errors with individual-track scanning from breaking the entire local-library functionality.

**Comment by nukeop** [comment]
Yeah this should be fine. Even better if there's a way to stop on an individual track level (but that might slow the whole process down if we don't submit them in a batch).

**Comment by Korb** [comment]
Same problem. First, I tried to add a folder with the entire local media library (about 40 thousand files in MP3, FLAC, m4a, ogg and WAV formats). After a few hours of scanning, the animation stopped without any messages, and the message "The library is empty. Try adding some music using the button above" was still displayed.

I specified another folder with only three MP3 files, but in this case I did not succeed.

Nuclear 0.6.17, Microsoft Windows 10.0.19043.1889.

**Comment by EmirLogas** [comment]
I have same issue. Cant add local library from folder. When I select the location and click the refresh button, nothing happens. I downloaded 3 mp3s and tried again. Running as administrator didn't solve it either.
Nuclear b6e5b2, Windows 10 build 19044.1889
