### ISSUE TITLE
[Feature Request] Organize/Sort songs in Favorite Tracks Page

### ISSUE THREAD

**Issue by skyawmyint** [nukeop/nuclear#722]
**Location of Improvement**
In the favorite tracks page
**Description of Improvement**
Currently, there is no way to organize how the list of songs in the favorite tracks page is laid out. The songs are added in there based on how recent it was added. I think eventually, there needs to be a way to organize it also by artist or title too. Having a way to organize it such as by dragging or clicking options and sorting would be beneficial as well.

**Comment by kacperkoza34** [comment]
Hello, I would like to work on this one if possible.

**Comment by WildLeons** [comment]
Hi @kacperkoza34,
Are you still working on that feature or not?

**Comment by kacperkoza34** [comment]
Hi @WildLeons
I'm still working on this feature

**Comment by Blakelist7** [comment]
Hello, I would like to contribute to this project as a beginner so could someone help me?
Please.

**Comment by anontyro** [comment]
hey, this looks interesting as there seems to be not much movement here I'll start to play around with this and see what I can do :)

**Comment by Edu93Jer** [comment]
Hi, @skyawmyint is this issue still open?
I am newbie to this project and would like to contribute to it.
I'd like to work on this issue if no one is.

**Comment by ahmedtarabia** [comment]
Hey @nukeop , I would like to look into this if no one else is.

**Comment by nukeop** [comment]
Ok, sure. Do you want me to assign you?
Please remember that we require each new functionality to be covered by tests to a sensible degree.

**Comment by ahmedtarabia** [comment]
Yes, please. I will report back if I run into any issues. 
Thanks

**Comment by mashazyu** [comment]
Hey @nukeop ,

I'd like to work on this issue, if no one else is working on it at the moment. Therefore,
- Does anyone actively work on this issue, or I can go ahead and give it a try?
- If(when) I have further questions, can I just write you directly in Discord?

**Comment by nukeop** [comment]
You can give it a try, I'll assign you. Feel free to contact me on Discord with anything.

**Comment by nukeop** [comment]
Please note that this will be best implemented by adding an ability to sort tracks in the TrackTable component, which will also enable it everywhere this component is used. This should be toggleable with a prop, since we won't want to be able to sort some lists, like albums.
