### ISSUE TITLE
[Feature Request] Ability to delete albums from favorite albums page

### ISSUE THREAD

**Issue by skyawmyint** [nukeop/nuclear#723]
**Description of Improvement**
Currently, the only way to delete an album from the favorite albums tab is to click on the album to go into the album page and unstar it as seen in the second screenshot. 

![album-star](https://user-images.githubusercontent.com/44180667/83705105-d8f1f800-a5c8-11ea-9d8d-ec0bcc49c546.jpg)

As show on the first screenshot below, there is no option to delete it in the favorite album tab. A way to improve it to make it easier and less screens to delete it from the favorite album list is to add a delete album option or an X mark in that list.  I think maybe this is something to implement as the app grows with more users and people start to have tons of favorite albums to their collection.

![favorite album page](https://user-images.githubusercontent.com/44180667/83705157-00e15b80-a5c9-11ea-82fb-a8e829cf99b8.jpg)

**Comment by nukeop** [comment]
I already started some dev work on it, I'm adding a button in the corner of those cards that will pop up a menu on clicking it. If you'd like, I can let you know once I'm finished with this so you can add the delete button to the menu in this screen.

**Comment by WildLeons** [comment]
Hi,

Yes, I'd like to add this button when you're done.
In the meantime, can I work on that feature ?
https://github.com/nukeop/nuclear/issues/722

**Comment by ManuelPortero** [comment]
Hi ! Can I join on this ? is my first contribution and having people guiding me I think would be a good start 
Regards

**Comment by nukeop** [comment]
I turned this into a larger task of overhauling certain components, such as cards and the bottom bar, and have already done a lot of work on that, but I'm still not finished with it. I'll try to close this by the end of this week and will let you know once I'm done.

**Comment by kartikcode** [comment]
Hi everyone! I am newbie to this project and would like to contribute to it.
I just wanted to confirm if @nukeop is still working on it? If not, I would love to work on it.

**Comment by nukeop** [comment]
> Hi everyone! I am newbie to this project and would like to contribute to it.
> I just wanted to confirm if @nukeop is still working on it? If not, I would love to work on it.

I made some changes on another branch but decided to scrap them. If you want to pick this up you're more than welcome to. Let's start with adding some sort of a popup with a menu to the album cards.

**Comment by kartikcode** [comment]
Oh, cool. I will right away start with this issue.

**Comment by kartikcode** [comment]
Also, what all options are you wanting to add to the menu list? @nukeop

**Comment by nukeop** [comment]
For now, just removing from favorites. Later on we can think about e.g. add all to queue.

**Comment by sirdarthvader** [comment]
@nukeop Is this issue assigned to someone? If not I would like to work on it. Let me know at the earliest.

**Comment by nukeop** [comment]
Nope, not yet. Feel free to take it.

**Comment by sirdarthvader** [comment]
@nukeop can you assign this to me.

**Comment by erikujczo** [comment]
@sirdarthvader Hey are you still working on this one? If not, I would like to take it 👍

**Comment by Edu93Jer** [comment]
Hi, everyone I am newbie to this project and would like to contribute to it.
Can you put me in line, is anyone working on the issue?

**Comment by erikujczo** [comment]
Hi @Edu93Jer  I already made the PR but it’s still waiting for reviews. Feel free to check my solution.
