### ISSUE TITLE
Cannot play music via Youtube

### ISSUE THREAD

**Issue by kortewegdevries** [nukeop/nuclear#724]
**System Details** 
```
 Kernel: 5.4.0-33-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
 Desktop: Xfce 4.14.2 Distro: Ubuntu 20.04 LTS (Focal Fossa) 
```
**Nuclear Version**
0.6.3 deb package

**Reproducible steps**
Search for a song and select to play it via Youtube.

**Expected Outcome**
Song would load and play.

**Actual Outcome**
Song loads in right pane but doesn't play.

Terminal output:
```
:~/$ nuclear
      main › (node:18482) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  renderer › Error while searching  for Leonard Cohen Suzanne on Youtube
  renderer › {}
  renderer › The audio playback can not be loaded, either because the server or network failed or because the format is not supported.
```
I am using my own YouTube Data v3 API key, it's new,so no rate limitation. Tried reinstalling and removing all cache/config doesn't help. Not a network error, reproducible on multiple songs via youtube. Soundcloud/Jamendo works fine.

**Comment by nukeop** [comment]
Do you have a video ID for this song? I tried reproducing this issue but I can play it.

**Comment by kortewegdevries** [comment]
Here,

svitEEpIO7E (Suzanne)
pojL_35QISI (Not ready to make nice, Dixie Chicks)
apObKCLDGkY (Sound of Silence Simon and Garfunkel). Somehow every instance of this song redirects to a 1 hour compilation video.

**Comment by kortewegdevries** [comment]
@nukeop  I'm closing this for now, seems the problem is on YouTube's part.
