### ISSUE TITLE
Regression - Volume shows up in settings with no name or description

### ISSUE THREAD

**Issue by nathanfranke** [nukeop/nuclear#725]
This shouldn't show up in the first place
I believe this is a regression from #700 @dejesusj 

![image](https://user-images.githubusercontent.com/14253836/85349604-8cf9eb00-b4c4-11ea-8db6-f67daf437cee.png)

**Comment by nukeop** [comment]
Thanks, I think there's no toggle to hide certain settings from this screen, that's why it showed up here...
