### ISSUE TITLE
Newly added songs not playing

### ISSUE THREAD

**Issue by dido-b** [nukeop/nuclear#726]
Tried to play the new Bob Dylan album Rough and Rowdy ways, but not possible. Also, some of the newer additions do not work. This happens rather frequently with new additions, older ones seem to be intact.

**Comment by nukeop** [comment]
Surprisingly this album is available on youtube. I'll look into why it's not being picked up.

**Comment by charjac** [comment]
I can't reproduce. @dido-b. Do you still have the problem ?

**Comment by dido-b** [comment]
Yes - but it is not a big problem, I can switch to youtube as you have indicated. I have noticed that on some other sources the same problem appears, but very seldom.

Thanks for following up.
________________________________
Von: Charles Jacquin <notifications@github.com>
Gesendet: Mittwoch, 22. Juli 2020 09:18
An: nukeop/nuclear <nuclear@noreply.github.com>
Cc: dido-b <d.beraha@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nukeop/nuclear] Newly added songs not playing (#726)


I can't reproduce. @dido-b<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdido-b&data=02%7C01%7C%7C5307d84237694ebf826708d82e0f6437%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637309990915946636&sdata=1QoTb%2BiTENl8wuPeKqGFV0jy8uO6AMOXWetPken9JRw%3D&reserved=0>. Do you still have the problem ?
