### ISSUE TITLE
[Linux] webpack-dev-server.js & bundle.js:ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Houkime** [nukeop/nuclear#73]
### Simptoms

* Release version of nuclear for Linux (from-source) doesn't work and produces an endless loading screen.

* The same behavior occurs when run with `electon:dev` WITHOUT "watching" in the background.
In the output console - 2 error lines right at start.
![image](https://user-images.githubusercontent.com/32805122/42005789-eb6f2844-7a65-11e8-8bf3-3cc8c5d7a40e.png)

* The same thing with `electron:prod` regardless of watcher running/not.

* This behavior is abscent if run with `electron:dev` with watcher in the background.

### My guess 

Maybe wrong production config which requests devserver while being supposed to run without it (and doesn't see it even when watcher runs for some reason).

**Comment by nukeop** [comment]
Is this the behavior you're getting out of the box, without touching any files after cloning?

There are actually two processes that need to run, one builds the main electron process, and the other builds the react app that runs in the electron instance. If it looks for the dev server in production build, I probably linked it to the wrong html. I think i will replace it with webpack's html plugin to automatically generate correct html from a template.

**Comment by Houkime** [comment]
Touching files only by running 
`npm install`
[tested with and without]` npm run watch`
`npm run build:dist`
`npm run build:electron`
`npm pack`

**Comment by nukeop** [comment]
I reproduced this issue and fixed it, the dev environment will now correctly request all the files from webpack dev server, instead of looking at a static html on the disk and getting javascript and other assets from the server. This should be more robust.
