### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by advaithm** [nukeop/nuclear#730]
I wanted to build a flatpak version of nuclear. i wanted to confirm if it was fine if i can make a flatpak version.

**Comment by nukeop** [comment]
Definitely, even better if you can integrate it into the existing electron-builder workflow.

**Comment by advaithm** [comment]
From what I have seen you can't use electron builder to make a flatpak rather you need to use flatpak builder

**Comment by advaithm** [comment]
From what I have seen you can't use electron builder to make a flatpak rather you need to use flatpak builder.
