### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by michaelding123** [nukeop/nuclear#735]
nuclear version 0.6.3
ubuntu 20.04 LTS as well as windows 10
Running nuclear with npm start creates this error:

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @nuclear/main@0.6.3 start: `shx rm -rf build && webpack --env.NODE_ENV=development && electron build/main.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @nuclear/main@0.6.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael/.npm/_logs/2020-07-14T00_25_24_067Z-debug.log

Is there a way to fix this problem?

**Comment by kortewegdevries** [comment]
Did the dependencies install correctly and can you clean the cache and run a install test? Also you should attach the log file. I couldn't reproduce this in Xubuntu 20.04.

**Comment by michaelding123** [comment]
[log.txt](https://github.com/nukeop/nuclear/files/4920068/log.txt)

**Comment by nukeop** [comment]
Can you run lerna with npx?

**Comment by michaelding123** [comment]
Also didn't work.

**Comment by nukeop** [comment]
Does it produce any output? Can you run lerna installed globally?

**Comment by MSandeep96** [comment]
I had a similar error. Running `npm i shx` fixed it for me. Can you try this once?

**Comment by eg7eg7** [comment]
can you try:
git clean -d -f -X (resets git repo to be cleaned, as if you just cloned it)
npx lerna init
npx lerna bootstrap
npm install

Had problems with npm install as well and it worked, if it says that some peer dependencies are missing and you should install by yourself you can do:
npm install -g npm-install-peers

**Comment by michaelding123** [comment]
I got this error.

> nuclear@0.6.3 start /home/michael/nuclear
> lerna run start --stream

lerna notice cli v3.22.1
lerna info Executing command in 5 packages: "npm run start"
@nuclear/core: > @nuclear/core@0.6.3 start /home/michael/nuclear/packages/core
@nuclear/core: > tsc
@nuclear/i18n: > @nuclear/i18n@0.6.3 start /home/michael/nuclear/packages/i18n
@nuclear/i18n: > tsc
@nuclear/ui: > @nuclear/ui@0.6.3 start /home/michael/nuclear/packages/ui
@nuclear/ui: > tsc && copyfiles -u 1 ./lib/**/*.scss ./dist
@nuclear/main: > @nuclear/main@0.6.3 start /home/michael/nuclear/packages/main
@nuclear/main: > shx rm -rf build && webpack --env.NODE_ENV=development && electron build/main.js
@nuclear/app: > @nuclear/app@0.6.3 start /home/michael/nuclear/packages/app
@nuclear/app: > webpack-dev-server --inline --env.NODE_ENV=development
@nuclear/app: ℹ ｢wds｣: Project is running at http://localhost:8080/
@nuclear/app: ℹ ｢wds｣: webpack output is served from /
@nuclear/app: ℹ ｢wds｣: Content not from webpack is served from /
@nuclear/app: ℹ ｢wdm｣: Compiled with warnings.
@nuclear/main:       main › development Env variables loaded
@nuclear/main:       main › Initialized settings store at /home/michael/.config/Electron/config.json
@nuclear/main:       main › Parsing /home/michael/.config/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/manifest.json failed.
@nuclear/main:       main › SyntaxError: Unexpected end of JSON input
@nuclear/main:     at JSON.parse (<anonymous>)
@nuclear/main:     at getManifestFromPath (/home/michael/nuclear/packages/main/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:41:21)
@nuclear/main:     at Function.BrowserWindow.addExtension (/home/michael/nuclear/packages/main/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:376:22)
@nuclear/main:     at Function.BrowserWindow.addDevToolsExtension (/home/michael/nuclear/packages/main/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:408:40)
@nuclear/main:     at eval (webpack:///./node_modules/electron-devtools-installer/dist/index.js?:80:30)
@nuclear/main:       main › Parsing /home/michael/.config/Electron/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd/manifest.json failed.
@nuclear/main:       main › SyntaxError: Unexpected end of JSON input
@nuclear/main:     at JSON.parse (<anonymous>)
@nuclear/main:     at getManifestFromPath (/home/michael/nuclear/packages/main/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:41:21)
@nuclear/main:     at Function.BrowserWindow.addExtension (/home/michael/nuclear/packages/main/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:376:22)
@nuclear/main:     at Function.BrowserWindow.addDevToolsExtension (/home/michael/nuclear/packages/main/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:408:40)
@nuclear/main:     at eval (webpack:///./node_modules/electron-devtools-installer/dist/index.js?:80:30)
@nuclear/main:       main › something fails while trying to install devtools
@nuclear/main:       main › Sqlite database created at /home/michael/.config/Electron/nuclear-local-db.sqlite
@nuclear/main:       main › something fail during app bootstrap
@nuclear/main:       main › TypeError: Cannot read property 'thumbnail' of undefined
@nuclear/main:     at LinuxMediaService.playlistMapper (webpack:///./src/services/@linux/system-api.ts?:102:38)
@nuclear/main:     at Array.map (<anonymous>)
@nuclear/main:     at new LinuxMediaService (webpack:///./src/services/@linux/system-api.ts?:77:61)
@nuclear/main:     at _createInstance (webpack:///./node_modules/inversify/lib/resolution/instantiation.js?:21:12)
@nuclear/main:     at Object.resolveInstance (webpack:///./node_modules/inversify/lib/resolution/instantiation.js?:41:18)
@nuclear/main:     at eval (webpack:///./node_modules/inversify/lib/resolution/resolver.js?:72:42)
@nuclear/main:     at Array.map (<anonymous>)
@nuclear/main:     at Object.resolveInstance (webpack:///./node_modules/inversify/lib/resolution/instantiation.js?:40:67)
@nuclear/main:     at eval (webpack:///./node_modules/inversify/lib/resolution/resolver.js?:72:42)
@nuclear/main:     at Object.resolve (webpack:///./node_modules/inversify/lib/resolution/resolver.js?:96:12)
@nuclear/main:     at eval (webpack:///./node_modules/inversify/lib/container/container.js?:319:37)
@nuclear/main:     at Container._get (webpack:///./node_modules/inversify/lib/container/container.js?:310:44)
@nuclear/main:     at Container.get (webpack:///./node_modules/inversify/lib/container/container.js?:230:21)
@nuclear/main:     at controllers.forEach (webpack:///./src/utils/container.ts?:36:37)
@nuclear/main:     at Array.forEach (<anonymous>)
@nuclear/main:     at Container.listen (webpack:///./src/utils/container.ts?:33:26)
@nuclear/main:       main › (node:9559) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
