### ISSUE TITLE
Songs load but don't play even after changing the API Key

### ISSUE THREAD

**Issue by AafaaqAli** [nukeop/nuclear#736]
Read closed issue #724  by advaithm, The issue has been closed due to "youtube site fault" but in my case source is "youtube" , but also I changed it to "invidio" but still no luck.

Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	        20.04
Codename:	focal

**Comment by nukeop** [comment]
Youtube and invidious search resolve to the same stream urls. This probably means you're being geofenced. Try searching on youtube and see if the stream in question is blocked in your country.

**Comment by AafaaqAli** [comment]
@nukeop Checked the URLs it's not geofenced, nor other songs which are only playing on sound cloud, not on invidious and youtube

**Comment by AafaaqAli** [comment]
I think there is indeed a problem on the youtube side. Should I close the issue or you further want to investigate it?

**Comment by nukeop** [comment]
I'll try updating node-ytdl to see if it fixes the problem.

**Comment by gabriellluz** [comment]
Same happens to me.

**Comment by AafaaqAli** [comment]
> I'll try updating node-ytdl to see if it fixes the problem.

have you updated the node-ytdl because the problem still persists mate

**Comment by nukeop** [comment]
This should be fixed now
