### ISSUE TITLE
Application icon is missing when installing the .deb file on Debian

### ISSUE THREAD

**Issue by mYnDstrEAm** [nukeop/nuclear#737]
When installing Nuclear 0.6.3 on Debian10/KDE via the .deb release no application icon is set.

**Comment by nukeop** [comment]
Yes, this is an old, old issue connected to electron-builder: https://github.com/electron-userland/electron-builder/issues/2577

**Comment by mYnDstrEAm** [comment]
Thanks for the info/link. @SimonBrandner posted a solution just after you commented. Could you give a try?

**Comment by mYnDstrEAm** [comment]
Again (or still?) no icon is being set. See #374
