### ISSUE TITLE
Please add more ways to add tracks to playlists

### ISSUE THREAD

**Issue by mYnDstrEAm** [nukeop/nuclear#738]
Currently the only way to add a track to a playlist is to play each individual track, wait until it loaded and then click on the three dots in the upper right and choose "Add to playlist >".

It would be very useful if there more ways to add tracks to playlists. Including:

* an option to add a track to a playlist in the left-click context-menu when clicking on tracks (e.g. in the search or the local library)
* a "create new playlist" function (e.g. under a clickable "Playlists")

Especially for the latter it would be useful to be able to multiselect tracks for adding them to a (in this case: new) playlist.

**Comment by nukeop** [comment]
I think this is already in the works, will let you know when it's done.

**Comment by MuhammedSheref** [comment]
if possible please add drag and drop songs to the queue area.

**Comment by HaiDang666** [comment]
implemented
