### ISSUE TITLE
Nuclear freezes (with electron glitches) when refreshing the large local library

### ISSUE THREAD

**Issue by mYnDstrEAm** [nukeop/nuclear#745]
When clicking on the refresh button in Local Library after successfully having folders with many files Nuclear often freezes with glitches. Sometimes it works. I think this is because the local library is large.

[Here is an exemplary screenshot of parts of Nuclear when it freezes.](https://i.imgur.com/jDkXUSz.png)

Then, if one closes nuclear (the close button in the upper right still works sometimes and if not one can right click the tab->Close) it does not shut down nuclear entirely: 2 of 3 nuclear processes remain running.

Furthermore, it did not detect a .wav file I recently placed in one of the folders of the Local Library. But that might be a separate issue.
<strike>I tried playing the file from within the folder that was added to the Local Library during the library scan by Nuclear and it had errors so it didn't play.</strike> I copied the file in another time (to replace the file with the same filesize) and the refresh went through <strike>and the file can get played from within the folder</strike>. But it does not show up in the search results. I also removed the folder where the file is located in and added it again and then pressed refresh with the same result.
Then I removed a mp3 file from one of the folders of the local library, did a refresh but it still shows up in the search results (and can't get played).

Sometimes Nuclear does not freeze when these glitches occur after refreshing the local library. The newly added .wav file was detected but <strike>after refreshing (not during) it still had errors when trying to play it with another audio player.</strike>

<strike>I did some further experimentation and the file does still play with the mpv Media Player, but not the VLC player even though the same file in another folder, that is not part of the Local Library, can still be played with the VLC player (it only gets these errors with the file in the local library folder after refreshing the local library). Update: the file not playing anymore seems to be related to firejail. It's strange that I can play files with right click->Open with->VLC but not anymore after the library scanning.</strike> The text that I have stroke through is caused by a firejail problem with symbolic links: https://github.com/netblue30/firejail/issues/836

**Comment by nukeop** [comment]
What's the size of the library you're trying to load?

**Comment by mYnDstrEAm** [comment]
About 50 GB in 3 folders. I think Nuclear should ultimately work with libraries far larger than that too.

Something else I forgot to mention in the issue: it would be great if there was a way to keep the library in sync without having to manually refresh it. Maybe something like fswatch could be used as a directory-monitor.
One idea would be creating "hashes for directories" that automatically change whenever a file within it is changed or removed or added - I'm not sure if this has been implemented yet (probably in one way or another), if it would be hard to implement (in external software, probably not in Nuclear) and if it would be really useful.
Maybe other music players have already built some solutions for this that could improve the synchronization of the library here.

**Comment by nukeop** [comment]
Our implementation of library crawling is very naive. I'm sure there's lots of room for improvement. I don't really have the knowledge to implement this is in an efficient way, will need to read up on this topic.

**Comment by mYnDstrEAm** [comment]
Okay. Maybe the methodology of library scanning by Mixxx, which works fairly well and fast with larger libraries, could be useful: https://github.com/mixxxdj/mixxx/blob/master/src/library/scanner/libraryscanner.cpp

**Comment by mYnDstrEAm** [comment]
The problem with the files not playing anymore might be a separate issue. I'm also getting it with other files in the library now. They still play with MPV. In VLC I get a permission error. I'm not sure why as they are still owned by my username and have -rw-r--r-- set.

**Comment by mYnDstrEAm** [comment]
Once when I ran nuclear without firejail it froze to a white rectangle had these two errors in the console:

> [number/number:FATAL:memory.cc(22)] Out of memory. size=65536
> [number/number:FATAL:memory.cc(22)] Out of memory. size=262144

The other times it also had glitches without any error messages after the loading went as usual for a few seconds (rotating loading icon in the refresh button).

**Comment by nukeop** [comment]
New scanner will solve that
