### ISSUE TITLE
Copy console output to terminal or log otherwise

### ISSUE THREAD

**Issue by Houkime** [nukeop/nuclear#75]
While trying to sort out what happens to electron:prod why it is not loading while electron:dev loads (still not loading) I found.. 

well... infuriating?...

the fact that there's literally *no way* to see console output when devtools are not up (which they aren't in prod and shift+ctrl+I does nothing).
So the idea is either to make console output visible in the terminal (father terminal is stdout in c++, idk how it is in node.js. It is visible only when the program is called from terminal) or make some simple logfiles even in release and prod (obviously 1st is more convenient).

Making output visible in the father terminal is a default debugging practice because this way you will see  info about error *no matter what* as long as your terminal is ok (e.g. as long as you're on a healthy OS, even android).

**Comment by nukeop** [comment]
https://www.npmjs.com/package/electron-log
https://www.npmjs.com/package/electron-timber

these two could be helpful to copy the renderer process log to terminal, then we could use tee to log to a file.

**Comment by nukeop** [comment]
With https://github.com/nukeop/nuclear/commit/17a09b914826e60107318508e575ce15577ade25, I started work on adding logging to all actions that interact with external services, so we can figure out when fetching something goes wrong. Now it will log if it can't find a song or an album on Discogs. I need to also add toast notifications inside the program.

**Comment by nukeop** [comment]
Using electron timber it's not logged in the terminal.
