### ISSUE TITLE
Invidious instances

### ISSUE THREAD

**Issue by fabianski7** [nukeop/nuclear#756]
The official instance of invidious [will be deactivated](https://omar.yt/posts/stepping-away-from-open-source) at the end of this month and it will be necessary to use others available.

Maybe it's time to use the available instances API?
https://instances.invidio.us/instances.json

You can follow their uptime here 
https://uptime.invidio.us/

The official wiki
https://github.com/iv-org/invidious/wiki/Invidious-Instances

**Comment by nukeop** [comment]
This one looks pretty good: https://invidious.snopyta.org

**Comment by fabianski7** [comment]
I'm thinking of using this one too. Far from the U.S., that's good
