### ISSUE TITLE
Track images / cover art don't load

### ISSUE THREAD

**Issue by mYnDstrEAm** [nukeop/nuclear#758]
In the bottom left and in the search results the images on the left of tracks don't load on Debian10/KDE.

The images for artists load. The images for tracks in the local library load in the bottom left and within the local library.

I think the images should be loaded from some kind of database which has cover arts linked with their track titles. Only if the image is not found in these databases the image should be loaded from the streaming source such as a frame-thumbnail from a file on Youtube.

**Comment by nukeop** [comment]
> I think the images should be loaded from some kind of database which has cover arts linked with their track titles.

There is no such database. There was last.fm, but now it only returns empty covers with stars. There are no good sources for track images anymore, and not every track has an associated album.

**Comment by mYnDstrEAm** [comment]
In that case it imo should be created. However, afaik there are some databases and/or scrapable sites that have such data - like these: https://www.lifewire.com/best-album-art-websites-2438773
If something needs to be built for it, it should probably be either a change or an extension to an existing database like MusicBrainz.
It wouldn't link albums to covers but tracks to covers (as above).
Furthermore, tracks for which no cover art could be downloaded could fetch a cover from SoundCloud or a YouTube frame even if this doesn't always work well.

**Comment by nukeop** [comment]
Top tracks were replaced by Deezer charts and they now have icons.
