### ISSUE TITLE
A way to find out what's causing tracks from the search results (not the Local Library) to not play or load very long

### ISSUE THREAD

**Issue by mYnDstrEAm** [nukeop/nuclear#760]
Often tracks in the search results take very long to load or don't load at all. There should be a way to find out what's causing this. (And additionally whatever that is should be resolved.)

I only get these errors in the console:

```
renderer › Error while searching  for track-name on Youtube
renderer › {}
```

**Comment by nukeop** [comment]
This is typically due to being geoblocked. But I agree the reason should be visible in the logs

**Comment by mYnDstrEAm** [comment]
Indeed. For example I can play these youtube videos when opening them in the browser so I think it might be caused by something else.
It would even be more useful to display the url as well. For example because another problem that I've noticed (should probably go into a separate issue) is that some tracks are actually videos of something else and I couldn't find the video for it. This is probably a problem with detecting which videos contain the respective track. Outputting more information could help solve these and issues now and later on.

**Comment by nukeop** [comment]
Sometimes a video can be blocked for playback in non-youtube domains, so that's why you might be seeing this.

**Comment by mYnDstrEAm** [comment]
If that is the case a probably fail-proof solution would be to make Nuclear/Electron open a browser window within Nuclear. But I'm sure that there are some better solutions to this.
It happens very often - so much that I currently can't really use Nuclear. Does outputting the error (or logging it) require a change in some external software?

**Comment by lucanomax** [comment]
have you tried changing invidio.us instance? I changed it from the standard invidio.us to a germany instance and works pretty well.

**Comment by Lynnporter1212** [comment]
I hate you all you have ever done is lie and cheat. What’s wrong with me that I am not enough? Don’t worry I have seen enough you don’t have to block me I will move on. It really hurts me

**Comment by lucanomax** [comment]
> 
> 
> I hate you all you have ever done is lie and cheat. What’s wrong with me that I am not enough? Don’t worry I have seen enough you don’t have to block me I will move on. It really hurts me

are you ok m8?

**Comment by Lynnporter1212** [comment]
No I’m not

**Comment by nukeop** [comment]
wat

**Comment by Venryx** [comment]
@Lynnporter1212 Are you referring to the incidence last Friday? Or speaking more generally about changes in your relationship?

**Comment by nukeop** [comment]
> have you tried changing invidio.us instance? I changed it from the standard invidio.us to a germany instance and works pretty well.

I don't think that should make a difference since ultimately all streams are loaded from youtube anyway (invidious just helps us find them).

**Comment by mYnDstrEAm** [comment]
I'm still having this problem. Changing the invidio.us instance didn't help (btw maybe the option could be made into an editable dropdown which fetches data from https://instances.invidio.us/ but that's a separate issue).
The videos should play and aren't geoblocked (and geoblocked tracks should not display in search results or elsewhere in the app but that's also a separate issue).
If for whatever reason a track doesn't play the app should detect this and try another source in addition to displaying an error message in the logs / console output.
Because of this problem the app currently isn't usable beyond testing in my and probably some other cases.

**Comment by lucanomax** [comment]
@mYnDstrEAm invidio.us doesn't exist anymore and from my experience others invidious instances work 1 time out of 3.
I'm not using this app anymore, but take in mind that invidious isn't reliable anymore.

**Comment by mYnDstrEAm** [comment]
I tried with YouTube being default music source (in the "Plugins" settings) before and I changed it back and **it still doesn't work**.

Other important problems include not being able to skip forward and as I just noticed "music playlists" with many tracks within one video but separated so that you always see which track is currently playing and can skip to the next track only play the first track. I already created an issue for the former problem and might create an issue for the latter later. However, doing so would be useless until this, the imo most important issue of the project, gets fixed because otherwise one can't really use Nuclear for listening to music anyway.

Please at the very least enable some output that helps finding out what's causing this problem.

**Comment by nukeop** [comment]
Should be gone now

**Comment by mYnDstrEAm** [comment]
Thanks. It still load too long at first start of something in the search results but the next track load quick and it's far quicker than earlier. Will comment if it happens again. I'm getting lots of `main › error trying to set discord activity` in the console.

**Comment by nukeop** [comment]
Yeah that should be a warning really, if you don't have discord open and it tries to use the discord rich presence feature, it keeps trying to detect it.
