### ISSUE TITLE
[feature request] easy adding music to repositories.

### ISSUE THREAD

**Issue by CardboardTurtle** [nukeop/nuclear#763]
Theres a big library, but I think it could be bigger if we make it easy for users to import songs onto the platform for others.

For example, i was searching for the star trek main theme earlier today, and could not find it. there were remixes, but not the original.

so why not have a menu in the left panel for adding songs? Just adding links to songs on soundcloud or youtube, and then adding that as a song for all users.

That way, not only do I get the star trek theme for me, but also for anyone else who wants to hear it.

I've had this same problem with other songs, such as the songs in Jojo's bizarre adventure, the Half Life OST, plants vs zombies theme, etc etc etc.

**Comment by mYnDstrEAm** [comment]
Whatever way Nuclear uses to identify music on streaming sources should be changed so that it properly detects these instead of allowing manual addition.

If manual addition / user-input is allowed it should allow for addition of detection-rules such as regexes and/or maybe databases.

**Comment by nukeop** [comment]
We now have heuristics that match songs better
