### ISSUE TITLE
[Feature Request] Local playlists

### ISSUE THREAD

**Issue by NeoKovacs** [nukeop/nuclear#765]
Would love to have a way to export playlists locally, so If I remove nuclear or install it on an another PC I could import it from that file, kinda like how I use mpv to have local playlist of my fav music, it basically contains links to all my favorite songs and I put it on an executable .txt file and put a keyboard shortcut for it and it shuffles through all the songs. But the problem with that method is that mpv doesn't know what link is what song and also there doesn't seem to be an easy way to get a list of all the songs either so I can't really choose specific song I'm feeling like listening to, instead I have to keep skipping songs till I land on one I like, that's why I would love to see Nuclear Implement this feature, also very sorry if none of this made any sense lol, I'm a bit of a dummy.

**Comment by nukeop** [comment]
The playlists are already saved in ~/.config/Electron/config.json, did you try using that file? It's probably impossible to make it work with mpv since we search for streams as songs start playing.

**Comment by NeoKovacs** [comment]
Oh cool! that's what I wanted to know
