### ISSUE TITLE
Compilation error: no such file or directory... "webpack-dev-server/node_modules/strip-ansi/index.js"

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#766]
I get the following error (visible in electron dev-tools console), when running latest code in master:
```
Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: ENOENT: no such file or directory, open 'C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\webpack-dev-server\node_modules\ansi-regex\index.js'
    at eval (webpack:///(:8080/webpack)-dev-server/node_modules/ansi-regex/index.js?:1:7)
    at Object../node_modules/webpack-dev-server/node_modules/ansi-regex/index.js (renderer.js:62638)
    at __webpack_require__ (renderer.js:727)
    at fn (renderer.js:101)
    at eval (webpack:///(:8080/webpack)-dev-server/node_modules/strip-ansi/index.js?:2:17)
    at Object../node_modules/webpack-dev-server/node_modules/strip-ansi/index.js (renderer.js:62650)
    at __webpack_require__ (renderer.js:727)
    at fn (renderer.js:101)
    at Object.eval (webpack:///(:8080/webpack)-dev-server/client?:6:17)
    at eval (webpack:///(:8080/webpack)-dev-server/client?:177:30)
```

However, when I open that folder, the file does exist!:
![](https://i.imgur.com/XNq8qxW.png)

I have tried running the following three commands (in sequence) (based on https://github.com/nukeop/nuclear/issues/735#issuecomment-660118818):
```
npx lerna init
npx lerna bootstrap
npm install
```

But afterward the same issue occurs.

OS: Windows 10

**Comment by Venryx** [comment]
To make sure it wasn't an issue with stale files somewhere, I decided to retry, with a fresh new clone in an empty folder, exactly following the instructions.

I did the following:
1) Created a new empty folder.
2) Git cloned the nuclear master branch.
3) Ran `npm install` in the root folder; no errors. (though there were some deprecation warning under the sqlite3 package: `<...>\node_modules\sqlite3\src\node_sqlite3.cc(38): warning C4996: 'Nan:ForceSet': was declared deprecated [C:\Root\Apps\@V\Nuclear\Temp2\node_modules\sqlite3\build\node_sqlite3.vcxproj]`)
4) Ran `npm start` in the root folder.
5) No compilation errors in console, but error in OP showed in Electron console.

**Comment by nukeop** [comment]
`lerna init` should only be used to create a new lerna monorepo.
`npm install` in the root should run ` lerna bootstrap` so no need to run that an extra time. Since lerna sets up the symlinks at that time, something might have gone wrong. Maybe try `lerna clean`, and then `npm install` in the root again?

**Comment by Venryx** [comment]
I tried `lerna clean` followed by `npm install`, and I get the exact same error.

Frustrating that others can't replicate, as it currently means I am unable to use Nuclear... (I can't use the official releases, because the last official release was a long time ago -- prior to the adding of the tree-view for the local library, which is important for my usage)

**Comment by Venryx** [comment]
Ugh, I finally figured it out.

See if you can as well:
![](https://i.imgur.com/TZtJj1D.png)

If you look at the "Start time" column, you can see that there is a second webpack-dev-server instance active -- started two weeks ago. Somehow that webpack-dev-server instance persisted past the closing of an earlier Nuclear instance. And apparently that second instance overshadowed/reserved usage of the `localhost:8080` port, despite me not noticing any sort of error message in the Nuclear start command-line. (it's possible it was there, but I didn't notice any such message)

And since I don't restart my computer for weeks at a time, the zombie instance never resolved -- and apparently kept on feeding the Nuclear frontend with "file doesn't exist" messages, even when the file actually did exist. (it apparently stopped updating its file-tree view or something)

Anyway, for others, to resolve:
1) Kill all existing instances of webpack-dev-server, using a task-manager (preferably with a command-line search function, like [Process Hacker 2](https://processhacker.sourceforge.io/)).
2) Run `./node_modules/.bin/lerna clean` in the root Nuclear-repo directory.
3) Run `npm install` in the root Nuclear-repo directory.

After that, `npm start` in the root directory should successfully compile and launch Nuclear. (actually, in my case I just created a whole new folder with a fresh repo clone -- my existing copy actually failed with the instructions above, with a `React.createElement: type is invalid` error in `PlayerBarContainer`, though I don't bother to debug exactly why)

An annoying issue, but finally resolved at least...
