### ISSUE TITLE
Music won't play

### ISSUE THREAD

**Issue by Vlad412** [nukeop/nuclear#773]
Hello,
I downloaded the Mac OS version of nuclear v0.6.5
I tried to play different musics and no music is playing
I tried to change the youtube API key (like told here [here](https://nuclearmusic.readthedocs.io/en/latest/troubleshooting/)) to a private one and nothing change 
someone know why ?

**Comment by nukeop** [comment]
Hi, I think this is due to Invidious API shutting down 2 days ago. I will need to change the instance and release a new version.

**Comment by nmaarse** [comment]
Hi, i have the same problem. Everything seems to load but music will not play. What i did so far:
-replaced youtube api key as mentioned in de docs.
-replaced invideous instance url to https://invidious.tube but the problem remains.
-restarted nuclear, reinstalled nuclear with latest version
Nuclear looks like this but now music is being played:
![image](https://user-images.githubusercontent.com/7762028/96701296-b81c1a80-1390-11eb-9dc2-c445bcb081aa.png)

**Comment by nukeop** [comment]
Can you try this with the new version? https://github.com/nukeop/nuclear/releases/tag/v0.6.6

**Comment by bmoren** [comment]
I'm having this issue in 0.6.6 and 0.6.5

**Comment by nukeop** [comment]
Can you try the Invidious plugin? The youtube api key is already used up.

**Comment by bmoren** [comment]
How do you enable it? I found where the API key for google is and the Invidious URL, is there something I need to do there to toggle something on?

**Comment by nukeop** [comment]
Nice, feel free to reopen if you have any other problems.
