### ISSUE TITLE
Grey, blank window on startup

### ISSUE THREAD

**Issue by Macr0Nerd** [nukeop/nuclear#776]
I installed Nuclear today as it seemed awesome. I couldn't download music, but once I set it away from Invidious to Soundcloud I could listen no problem. I was playing a song and tried to favorite and then download it (Sweather Weather by The Neighborhood) the app went completely grey and I can't move it, I can only seem to Alt+F4 it. I've tried restarting the app, restarting my system, and reinstalling but nothing has worked. When I start it, I get a flash of the layout and a number of red boxes on the left side of the window, but it's only there for a split second and I can't see anything else after that. It's just an immovable grey box.

**Version:** 0.6.5-2 (pulled from package info)
**OS:** Arch Linux running KDE Plasma
**Steps to reproduce:** No clue. See description above to see how I did it.

![NuclearIssue](https://user-images.githubusercontent.com/16966836/95108543-04b0f600-0701-11eb-9baa-5d4970bf4abe.gif)

**Comment by nukeop** [comment]
Can you try the new version? I was developing this one on Manjaro with KDE Plasma, which is basically Arch.
https://github.com/nukeop/nuclear/releases/tag/v0.6.6

**Comment by Macr0Nerd** [comment]
turns out i'm a dumbass and it was a config file issue. Deleted the config folder and reinstalled and good as new. Literally. Sorry for the trouble. Thank you!

**Comment by Macr0Nerd** [comment]
actually, it seems to happen when I add a song to my favorites. I tried downloading sweather weather by the neighborhood, and then adding it to my favorites and the grey screen happened.

**Comment by tehYosheh** [comment]
I had this issue on Win10 with version 0.6.7, the issue is indeed when you add a song to favourites and multiple reinstalls did not fix this issue. As Macr0Nerd pointed out this is an issue with the config.json file (Which on Win10 is stored in %appdata%\nuclear) and when I deleted that the program would open up correctly again.

**Comment by YaroslavMiloslavsky** [comment]
This happened to me as well, I selected an album from the favorite albums section when all the sudden my app became grey and unresponsive.
I'm on linux mint 20.1
