### ISSUE TITLE
Making it easier to translate the app

### ISSUE THREAD

**Issue by RubenHetKonijn** [nukeop/nuclear#778]
This is just an idea:

So you have a json file like `en-gb.json` and you have a file with keys like
`"addToPlaylist" = "Add to Playlist",`

And you print the text as `engbLang.addToPlaylist`

Keep in mind this is just an idea, but it will be much easier to translate and will make it able to easily add user made languages that aren't officially supported.

**Comment by nukeop** [comment]
This is almost exactly how it works: https://github.com/nukeop/nuclear/tree/master/packages/i18n/src/locales
