### ISSUE TITLE
The App does not sort my songs properly

### ISSUE THREAD

**Issue by L0ren2** [nukeop/nuclear#783]
i think this is a format issue rather than a sorting algorithm issue, but even if i rename my songs so that they should technically all be sorted, it still fails at doing this.
Example: i have two songs from Tuvi (classical guitar player) and a bunch of powerwolf songs (metal band). why does the player put a powerwolf song inmid of Tuvi songs when i sort by interpret? I know metal and classical are somewhat similar, but not that much

**Comment by nukeop** [comment]
Of there are any special characters at the start of a name, this might affect sorting
