### ISSUE TITLE
v0.6.6 - Error launching on Debian 10: The SUID sandbox helper binary was found, but is not configured correctly

### ISSUE THREAD

**Issue by mYnDstrEAm** [nukeop/nuclear#785]
When I run `firejail nuclear` (v0.6.6) I get this error:

`[FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/nuclear/chrome-sandbox is owned by root and has mode 4755.`

v0.6.3 still worked.

This is an Electron problem.

Just adding the `--no-sandbox` parameter is **not** the solution. Maybe an older version of Electron or a fork needs to be used. Maybe there's a new general solution for this problem by now. Looks like the best 2 solutions so far are:
* Using an older version or
* [Running](https://unix.stackexchange.com/questions/587828/electron-app-suid-sandbox-helper-binary-was-found-but-is-not-configured-corre) `sudo chown root chrome-sandbox` and `chmod 4755 chrome-sandbox`

See https://github.com/electron/electron/issues/17972

**Comment by kortewegdevries** [comment]
> This is an Electron problem.

Yea. This is known and an upstream Chromium/Electron issue where even passing `--no-sandbox` doesn't work under Firejail. It'd be best if you can mention it here or create an issue where it is being tracked: https://github.com/netblue30/firejail/issues/3586

I don't think it'd be the best idea to ask to downgrade the electron version.

**Comment by mYnDstrEAm** [comment]
Looks like the best improvised solution so far is: https://github.com/laurent22/joplin/issues/2246#issuecomment-740126395
Could you please implement this?

**Comment by mYnDstrEAm** [comment]
Still having this error with version 6.16; it can't be started.

**Comment by nukeop** [comment]
Looks like this is an issue with Firejail, not Debian. I'm not familiar with this software, and I don't want to spend development resources fixing it, but if anyone wants to, feel free to submit a PR.

The workaround from joplin (https://github.com/laurent22/joplin/issues/2246#issuecomment-753464558) looks like it needs to be performed on a client machine and it could break appimages for people not using chrome-sandbox.

**Comment by mYnDstrEAm** [comment]
Alright, asked about it here: https://github.com/netblue30/firejail/issues/4422

**Comment by mYnDstrEAm** [comment]
Maybe you could have a quick glance over the error message what the problem may be / what the missing permissions may be...is sqlite3 installed during launch somehow?

**Comment by nukeop** [comment]
Sqlite is compiled at build time and bundled in the .asar archive along with other dependencies. There's a little hack for it in electron builder's config: https://github.com/nukeop/nuclear/blob/master/package.json#L175

All of this happens at build time though.

**Comment by nukeop** [comment]
To be precise, sqlite is not exactly in .asar, it's next to it in <root dir>/resources/node_modules/sqlite3.

**Comment by mYnDstrEAm** [comment]
I updated https://github.com/netblue30/firejail/issues/4422: `firejail nuclear` is working again (maybe it was due to the upgrade from Debian 10 to 11). There are still some errors and it's taking a bit too long to load but it seems to be solved now.
