### ISSUE TITLE
Is there a login function?

### ISSUE THREAD

**Issue by adriasir123** [nukeop/nuclear#792]
I saw you have last.fm and github login, but that doesn't synchronize your data between devices.
I have a PC and a laptop, both running nuclear, but the data isn't shared.
I assume this is because we can't yet register an account, and therefore, data is just stored locally.

**Comment by nukeop** [comment]
Nope, there are no accounts and no data is ever collected, other than what you send to last.fm.

**Comment by adriasir123** [comment]
So no way to synchronize...

* Favorite albums/tracks
* Playlists

?

If that's the case, could I make this a feature request?

**Comment by nukeop** [comment]
It would be a huge effort to create and maintain a service for this. Unless there's a ready made solution, I'm afraid this will be a no. Essentially we only need to share the json with config for this.

**Comment by adriasir123** [comment]
If I have understood correctly, there's a json file with my nuclear config that I could copy if I wanted to my other computer?

**Comment by Trial-In-Error** [comment]
Ok, did some digging.

[This code](https://github.com/nukeop/nuclear/blob/551da3827d4cdca50bfafa756b3e94071b67c090/packages/core/src/persistence/store.js#L4) uses [electron-store ](https://www.npmjs.com/package/electron-store?activeTab=readme) with [the path set to 'userData'](https://www.electronjs.org/docs/api/app#appgetpathname).

A quick look-over with my (mostly default settings and a few playlists) doesn't show any settings that seem _bad_ to sync. Playlists with local file paths might fail in fun and exciting ways, perhaps?

I think if it's generally safe to sync this file, it would be great to mention the path in the README or documentation. Either way, I'll start syncing this and see how it goes!

**Comment by nukeop** [comment]
You're right that we use electron-config, all the relevant settings are saved there. Playlists with local file paths should work, if the files are deleted the sources will be re-acquired.
