### ISSUE TITLE
Songs don't play

### ISSUE THREAD

**Issue by valfrancois** [nukeop/nuclear#794]
I can't play any song in the last versions of Nuclear. The UI displays it as playing (play button turns to pause button), but the song stays stucked at 00:00 and there is no sound.

OS: Ubuntu 18.04

I found this in your troubleshooting section:

> Songs load but fail to start
> 
> Sometimes our Youtube API key gets too much traffic and becomes rate limited. This causes problems with loading streams. As a workaround, you can use your own API key by pasting it in the settings section, near the bottom.

However I get different errors depending on the versions when trying to play the same song, so I think my issue may not be linked with the Youtube API:

- v 0.6.6:
```
main › renderer › Error while searching  for Beast in Black Blind and Frozen on Youtube
main › renderer › TypeError: Cannot read property 'id' of undefined
    at file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2240:321478
```
- v 0.6.5:
Here the issue is different as I couldn't even start Nuclear:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/opt/nuclear/resources/app.asar/node_modules/sharp/lib/constructor.js:34:9)
    at Object.<anonymous> (/opt/nuclear/resources/app.asar/node_modules/sharp/lib/constructor.js:338:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/nuclear/resources/app.asar/node_modules/sharp/lib/index.js:3:15)
    at Object.<anonymous> (/opt/nuclear/resources/app.asar/node_modules/sharp/lib/index.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```
- v 0.6.3:
```
renderer › Error while searching  for Beast in Black Blind and Frozen on Youtube
renderer › {}
```
- v 0.6.1:
```
renderer › Error while searching  for Beast in Black Blind and Frozen on Youtube
renderer › {}
```
Same error, but the song actually starts playing! I'm just going to keep using 0.6.1 for now.

Each version was installed with the .deb files from https://github.com/nukeop/nuclear/releases

**Comment by Gontran-Macedoine** [comment]
Having the same issue on popOS

**Comment by IBArbitrary** [comment]
Having the same issue on Windows

**Comment by crthpl** [comment]
Having same issue on MacOS

**Comment by wickles** [comment]
Had the same issue. Fixed it yesterday by updating settings with my own API key and an alternate invidious instance (if you browse to the default one online it says it has shutdown and lists some alternatives). 

Today it won't work again, but the error is different. Now it tries to load the song, and shows a red error bar saying: "Could not find a working stream using this source. Try re-rolling." Not sure what re-rolling means if it's not just a joke or something.

**Comment by nukeop** [comment]
It means the particular song it found can't be played. You can reroll by using the arrows icon in the track details (right click a song).

**Comment by wickles** [comment]
It was happening for every song I tried including from top tracks and albums that worked fine yesterday. Anyway it seems to have fixed itself and all working again for me.

**Comment by mYnDstrEAm** [comment]
If this isn't fixed by the devs, the first step to allowing others to fix it would be improving the error messages output so that it can be debugged and the problem/s be found: see #794
(same issue on Debian)

**Comment by nukeop** [comment]
Should work in 0.6.7, can you check?

**Comment by PinkDev1** [comment]
Yes, it works now! (v0.6.7)
now the music player can actually play music XD

**Comment by nukeop** [comment]
Great

**Comment by wickles** [comment]
Still does not work reliably for me. Some songs play, some don't.

**Comment by nukeop** [comment]
This is a different issue. Youtube can change its interface at any moment and it takes time to correct it and release it. Happens sometimes.
