### ISSUE TITLE
Regression: "Add plugin" fails to add new plugins

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#798]
Title says it all. Just try to add a plugin through the UI, and you'll see that an error occurs (before even selecting the plugin file), and after selecting a file, no change occurs -- the plugin list remains empty, both in UI, and in `config.json` afterward.

Plugins themselves still work, but you have to manually add the entries to the `config.json` file using a text editor.

I've only tested this in the latest release (0.6.6), but I'm assuming it is present in `master` as well.

**Comment by nukeop** [comment]
It's screwed due to new Electron API. I will write test cases for it and will try to fix it then.

**Comment by nukeop** [comment]
Needed some tweaking but should work fine now. I also covered this with tests (electron API has to be mocked out so it's not ideal, but better than nothing).
