### ISSUE TITLE
VirusTotal detecting malware in setup

### ISSUE THREAD

**Issue by sudo-apt-get-updates** [nukeop/nuclear#803]
VirusTotal is detecting a malware called Spiderbanner in the nuclear.Setup.0.6.7.exe release from the repository.

In dropped files

https://www.virustotal.com/gui/file/1a7a28b10797614846bb3c3a0d841ae51c87f0b78b670f763986f973a1abc6b5/relations

https://www.virustotal.com/gui/file/996a259e53ca18b89ec36d038c40148957c978c0fd600a268497d4c92f882a93/detection

**Comment by nukeop** [comment]
This is a dll for the installer. If VirusTotal thinks it's malware, it's wrong. If you want to avoid this problem, get the portable version which doesn't use the installer (the regular .exe or .zip release).
