### ISSUE TITLE
Use portals for media controls

### ISSUE THREAD

**Issue by advaithm** [nukeop/nuclear#809]
media controls do not work on the flatpak version since nuclear doesn't use portals, Please implement this so nuclear behaves better in the container
docs on portals https://flatpak.github.io/xdg-desktop-portal/portal-docs.html

**Comment by nukeop** [comment]
I couldn't determine if Electron has portal support. Maybe we could use the API directly.

**Comment by advaithm** [comment]
I think electron has it since a lot of electron apps do use portals on flatpak
