### ISSUE TITLE
Create Flatpak packages

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#81]
https://flatpak.org/
https://flathub.org/

Creating a package for this distribution system would help reach a larger number of users.

**Comment by bilelmoussaoui** [comment]
Need some help with this? I have been helping third-party devs to push their apps to flathub recently.

**Comment by nukeop** [comment]
I will eventually, but I have to fix the broken build first. Building flatpaks seems kinda complex.

**Comment by bilelmoussaoui** [comment]
Not really. It seems complex as you said, but it's much easier than building deb/rpm packages, plus it gives you more control of the package and let the dev himself publish a new relase while being sure that every linux user will receive the update without having to make sure that every repo is up to date and all of those old complicated stuff

**Comment by nukeop** [comment]
The autoupdate feature is the best thing about this. Although, with electron-builder, it's pretty easy to build deb or snap packages, since it takes care of that. That's why I'd also like to add building flatpaks and automatic deployment to flathub to my travis config.

**Comment by nukeop** [comment]
Ok, now that the build is fixed I can look at this.

**Comment by corebots** [comment]
Hello please could you make your nice app available via flatpak please? can't run it on Fedora now, appimage gives segmentation fault. Thank you so much for making this!

**Comment by kinduff** [comment]
Consider using [electron-packer](https://github.com/electron-userland/electron-packager) instead of `electron-builder` to have flexibility on the distribution.

**Comment by mclucario** [comment]
I would love to have a rpm/Flatpak package so I can use this on my Fedora installation.

**Comment by mclucario** [comment]
Is anyone working on this yet?

**Comment by nukeop** [comment]
Nope, not yet, this will require changing the build tool and/or running a custom script after the tool. Appimage should work on Fedora though.

**Comment by mclucario** [comment]
AppImage seems to "work". Searches are a bit slow and the playlist is buggy. Is that normal?

**Comment by nukeop** [comment]
Searching works through discogs and playlists are being improved and worked on before the release.

**Comment by Eonfge** [comment]
@nukeop Here an example of combining custom actions with a Electron based app:
https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.yaml
