### ISSUE TITLE
Add tooltips to the icons in the player bar

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#811]
Some of the icons are not self-explanatory, they need tooltips saying what they do

**Comment by KashyapPavra** [comment]
@nukeop , I would love to work on this feature. Could you brief where and what you would like to name the tooltips?

**Comment by nukeop** [comment]
Ok, so to render the tooltips we should use this component: https://react.semantic-ui.com/modules/popup/

![image](https://user-images.githubusercontent.com/12746779/106177449-6dc8e780-6190-11eb-952c-ac064772a555.png)

These are the buttons that need them. Left to right they are: `repeat`, `shuffle`, `autoradio`, `miniplayer`. Of course these strings need to be placed in en.json and properly localized. For now we can only include the english names and worry about other languages later.

**Comment by KashyapPavra** [comment]
@nukeop  Great, I'll have a look at it this weekend. Can you assign me this issue?

**Comment by KashyapPavra** [comment]
@nukeop been trying to start the application using ``npm start`` on MacOS 11.1 but have been getting this error:

```
@nuclear/main: /Users/kashyappavra/Desktop/OpenSource/nuclear/packages/main/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGABRT
@nuclear/main: npm ERR! code 1
@nuclear/main: npm ERR! path /Users/kashyappavra/Desktop/OpenSource/nuclear/packages/main
@nuclear/main: npm ERR! command failed
@nuclear/main: npm ERR! command sh -c shx rm -rf build && webpack --env.NODE_ENV=development && electron build/main.js
```

Any idea what's causing this?

**Comment by nukeop** [comment]
Nope, but you can try following the process we use in CI which is guaranteed to work on the latest Mac OS (since we run it after every push to master): https://github.com/nukeop/nuclear/blob/master/.github/workflows/build.yml#L36

**Comment by KashyapPavra** [comment]
@nukeop still not able to get it running. Maybe you can assign this issue to someone else.

**Comment by HaiDang666** [comment]
I can take this if @KashyapPavra wants

**Comment by KashyapPavra** [comment]
> I can take this if @KashyapPavra wants

@HaiDang666 Sure I don't mind.

**Comment by HaiDang666** [comment]
fixed in https://github.com/nukeop/nuclear/pull/822
