### ISSUE TITLE
Broken version number in macOS download 0.6.8

### ISSUE THREAD

**Issue by suschizu** [nukeop/nuclear#813]
Hello!
all macOS downloads still contain version 0.6.7 instead of 0.6.8

![image](https://user-images.githubusercontent.com/16004333/106174548-7243cf00-6195-11eb-8e34-16844dd8f642.png)
![image](https://user-images.githubusercontent.com/16004333/106174565-77088300-6195-11eb-9a8e-2d32a1196471.png)

**Comment by nukeop** [comment]
Thanks for letting me know, I forgot to bump the version of the main package before building. However, the program should have all the newest content, it's just the version number that's displayed incorrectly.
