### ISSUE TITLE
Use error boundary to correctly handle program-crashing errors

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#816]
There is an error boundary that used to work but now it won't handle errors gracefully. This needs to be investigated, fixed, and properly tested to ensure a regression doesn't happen again.

**Comment by Yahyakiani** [comment]
@nukeop  i ll would like to take a jab at this issue.Any tips where I can start looking for it? Thanks

**Comment by nukeop** [comment]
The current ErrorBoundary is defined here: https://github.com/nukeop/nuclear/blob/d0b384789bd1eb3b8d5a136a4aa1dd46c4db3e97/packages/app/app/containers/ErrorBoundary/index.js

Here's a rundown on this topic: https://reactjs.org/docs/error-boundaries.html

**Comment by nukeop** [comment]
Already done
