### ISSUE TITLE
Garbage app sets everything to open with nuclear

### ISSUE THREAD

**Issue by friendlytherapist** [nukeop/nuclear#821]
I could live with the electron but I cant live with it setting all media files to open with this app. Wtf? Webms and mp4s? They dont even play in the app.

**Comment by nukeop** [comment]
We don't modify file associations. Webm and mp4 can be played though: https://github.com/nukeop/nuclear/blob/b4620c65616f27cb7d6af7fec0f59632f899c253/package.json#L135
