### ISSUE TITLE
Blank screen after search

### ISSUE THREAD

**Issue by minetrinitite** [nukeop/nuclear#83]
App goes to blank white screen after processing the search with query containing some symbols + "#", e.g. "#ddd", "ddd#". Happened when i've tried to search for the artist [Phoenix #2272](https://phoenix2772.bandcamp.com/). May be this happens with any other special symbols too.
Version: nuclear_0.4.2_amd64.deb@Ubuntu 18.04

**Comment by nukeop** [comment]
Might be an improperly escaped search string, I'll look into it and add tests covering this case.

**Comment by nukeop** [comment]
Looks like `encodeURI` doesn't strip the `#` sign, so the browser engine interpretes everything after it as an anchor, not arguments for the GET request, and the query is destroyed in the process. I'll have to remove it manually, I guess.
