### ISSUE TITLE
Integrating SponsorBlock into YouTube music source

### ISSUE THREAD

**Issue by Ririshi** [nukeop/nuclear#831]
I just started using nuclear and, while a bit rough here and there, it seems like a great application. One of the first things (me being a nerd and all) I did was to try to find some A Capella Science music. This is available on YouTube, but most videos have a pretty long outro where the artist is talking about the channel and what he's been up to. That's fine when watching on YouTube, but it isn't very nice if you're only listening to the music.

My proposal: to integrate [SponsorBlock](https://github.com/ajayyy/SponsorBlock/) into the YouTube music source. This way, any non-music parts can be filtered out of YouTube streams, and users can enjoy just the music, without interruptions. SponsorBlock has a [free, unlimited-use API](https://github.com/ajayyy/SponsorBlock/wiki/API-Docs) that allows anyone to make use of the SponsorBlock database.

With some fiddling around, I'm sure it will be possible to seamlessly skip non-music bits of YouTube videos :) Deciding which types of segments to skip may prove challenging, but I think a good starting point would be to skip literally every type.

I think this feature should either be a plugin (if feasible, I am not sure how elaborate the plugin API is), or a base part of Nuclear. Of course, it should be possible to enable and disable the skipping. The ability to use a custom database (like SponsorBlock allows) would also be nice, though not necessary.

Looking forward to hearing if this is something other users would like to see in Nuclear. I could probably work on the implementation, but (sadly) cannot devote much of my time to it.

Edit: I accidentally opened this issue as a bug, that was obviously not what I meant to do. Looks like I cannot remove the tag. Please remove the bug tag and attach feature proposal to it @nukeop.

**Comment by nukeop** [comment]
I recently opened a similar proposal: https://github.com/nukeop/nuclear/issues/810

**Comment by Ririshi** [comment]
Oh I am sorry, I searched for SponsorBlock and got no hits in the issues tracker.

**Comment by nukeop** [comment]
Closed via  #838
