### ISSUE TITLE
A dialog appears on every new music

### ISSUE THREAD

**Issue by alculete** [nukeop/nuclear#834]
Every time a new song starts the dialog below appears, I have to click yes every time to proceed. If 

![image](https://user-images.githubusercontent.com/2129497/108088972-be41af80-7081-11eb-951d-27231462225c.png)

OS: Ubuntu 20.04.2 LTS x86_64 
Kernel: 5.8.0-43-generic 
Shell: bash 5.0.17 
DE: GNOME 
Nuclear Version: 0.6.9

**Comment by nukeop** [comment]
Does it happen with any other package than snap?

**Comment by nukeop** [comment]
I can confirm and reproduce this with the snap package, probably caused by discord integration.

**Comment by alculete** [comment]
> Does it happen with any other package than snap?

Tested on deb. It seems to be just a snap problem

**Comment by thiras** [comment]
I also confirm the bug on Ubuntu 20.04 latest and nuclear snap

**Comment by nukeop** [comment]
Fixed, update your snaps and it should be gone after the first time.
