### ISSUE TITLE
Change Downloads Directory don't apply bug - macOS Big Sur

### ISSUE THREAD

**Issue by itayweb** [nukeop/nuclear#837]
Tried my first time in the software and tried to change the downloads directory to a different internal drive but it seems not to be applied and goes back to the default one.

**Comment by nukeop** [comment]
This was fixed here https://github.com/nukeop/nuclear/commit/29a4349ad4a72b77d186da9d8402e61ac6695cda

What version are you using?

**Comment by itayweb** [comment]
0.6.9

**Comment by nukeop** [comment]
Shuld work now
