### ISSUE TITLE
Album list doesn't load in artist view

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#844]
Needs to be investigated to determine cause and possible solution.

**Comment by HaiDang666** [comment]
I'll have a look. Can u give me more steps to reproduce

**Comment by nukeop** [comment]
I got this: 
<img width="171" alt="image" src="https://user-images.githubusercontent.com/12746779/109570783-8d7e6300-7ae2-11eb-936f-e5693483b13f.png">

From mastodon so reverse reading order applies

**Comment by HaiDang666** [comment]
fixed in https://github.com/nukeop/nuclear/pull/849
