### ISSUE TITLE
Search providers hide behind text fields in settings menu

### ISSUE THREAD

**Issue by binarica** [nukeop/nuclear#846]
#### Version of nuclear
- 0.6.9 (AppImage)

#### Your operating system
- Debian Testing

#### Reproducible steps (1... 2... 3...) that cause the issue
1. Go to settings menu
2. Open providers dropdown next to the search box
3. Scroll down the page

#### What you expected to see, versus what you actually saw
- Expected: Dropdown menu options should be visible on top of all other elements 
- Actual: Text fields hide dropdown options when both elements overlap

#### Images, animations, or a link to a video showing the issue occurring
![image](https://user-images.githubusercontent.com/9634969/109449723-ec32d680-7a27-11eb-9072-36541a2c8c2a.png)

#### A code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally
- Not applicable

**Comment by HaiDang666** [comment]
fixed in https://github.com/nukeop/nuclear/pull/847

**Comment by nukeop** [comment]
Thanks for fixing this @HaiDang666
