### ISSUE TITLE
Save an album or artist from search

### ISSUE THREAD

**Issue by feliciakrismanta** [nukeop/nuclear#85]
Maybe right-click from search thumbnail or from three dots in the detail page

**Comment by nukeop** [comment]
Locally stored library and favourites will be developed in 0.6.0, along with listening suggestions and flow mode, thanks for the idea.

**Comment by HaiDang666** [comment]
I'll working on favorite artist page

**Comment by nukeop** [comment]
> I'll working on favorite artist page

Ok, we already have a place for favorite artists in the redux store, so it should be relatively simple.
