### ISSUE TITLE
1 - It is not possible to be able to see all the created playlists, it is not possible to move up and down to scroll through all the playlists.  2- It is not possible to add music to the playlist without adding it to the play queue  3 - Please add follow artists

### ISSUE THREAD

**Issue by Magicos76** [nukeop/nuclear#853]
1 - It is not possible to be able to see all the created playlists, it is not possible to move up and down to scroll through all the playlists.

2- It is not possible to add music to the playlist without adding it to the play queue

3 - Please add follow artists

**Comment by HaiDang666** [comment]
1 - fixed in https://github.com/nukeop/nuclear/pull/869
2 - fixed in https://github.com/nukeop/nuclear/pull/895
