### ISSUE TITLE
Nuclear 0.6.10 takes way longer to open, both the Appimage and .deb and Butterchurn is lower quality

### ISSUE THREAD

**Issue by leirbag28** [nukeop/nuclear#854]
On ubuntu 18.04.5 MATE 64 bit, I recently installed the 0.6.10 both AppImage and .deb and they are slower in opening for sure...waaaaaayyy slower, and the Butterchurn visualizer seems to have been scaled down in quality. also it never changes visuals randomely...you have to do it manually every single time.
(would be great to be able to detach the Visualizer at will to put on a second monitor full screen)

**Comment by Magicos76** [comment]
Here the same thing happens

**Comment by nukeop** [comment]
We didn't change anything in the visualizer, do you have gpu rendering enabled?
