### ISSUE TITLE
Artist page not listing all albums 

### ISSUE THREAD

**Issue by azumukupoe** [nukeop/nuclear#860]
For example, [Sérgio Mendes](https://www.discogs.com/artist/27986-S%C3%A9rgio-Mendes)'s first album Dance Moderno is nowhere to be found in nuclear's artist page of him
It seems to be only listing recent releases from each album type ("Albums", "Singles & EPs", "Compilations" and "Miscellaneous")

**Comment by nukeop** [comment]
This depends on the metadata source, and can't be controlled by us.

**Comment by azumukupoe** [comment]
Then, maybe Musicbrainz should be set as the default metadata provider as it provides relatively better results?

**Comment by nukeop** [comment]
We tried that, but Musicbrainz is generally a lot slower.

**Comment by azumukupoe** [comment]
A lot? I'd say it's a bit slower and worth the wait.
