### ISSUE TITLE
Separate albums into "Albums", "Singles & EPs", "Compilations" and "Miscellaneous" inside artist page

### ISSUE THREAD

**Issue by azumukupoe** [nukeop/nuclear#861]
Discogs have them separated so I think this is achievable with their API

**Comment by HaiDang666** [comment]
Discogs return type value of a release only: 'master' or 'release'

**Comment by HaiDang666** [comment]
currently discorgs api doesn't support subtype for release

**Comment by nukeop** [comment]
Yeah I think it only gives us "release" and "master" (and we typically only use masters to avoid a huge number of duplicates).
