### ISSUE TITLE
Favorite Albums and Favorite Tracks should have different icons in the menu bar

### ISSUE THREAD

**Issue by azumukupoe** [nukeop/nuclear#862]
I think A and T inside the star should be enough

**Comment by HaiDang666** [comment]
I suggest use this for album
![Screen Shot 2021-03-08 at 13 19 52](https://user-images.githubusercontent.com/12780733/110282394-fac55300-8010-11eb-9e9a-237d38297855.png)

and this for track 
![Screen Shot 2021-03-08 at 13 20 13](https://user-images.githubusercontent.com/12780733/110282449-16c8f480-8011-11eb-8417-34691aa7e36e.png)

cos they are consistent with the rest

**Comment by nekonee** [comment]
T/A inside the star would be barely visible, I'm looking for other options
Those suggested by @HaiDang666 are nice, but I don't think they represent the idea of _favorite_

**Comment by nekonee** [comment]
![ummmm](https://user-images.githubusercontent.com/23231289/110362311-6e7f5400-8041-11eb-9ac9-e3121772c494.png)
I've tried adding the second icon (star) in the bottom right but the result is.. bad. I'll stick to just the main ones
