### ISSUE TITLE
Full album queued instead of title track 

### ISSUE THREAD

**Issue by azumukupoe** [nukeop/nuclear#863]
I have a problem with: 
Mike Oldfield/Platinum/Platinum
Mike Oldfield/QE2/QE2
Mike Oldfield/Crises/Crises
Mike Oldfield/Discovery/Discovery ...
(same should happen with albums that have tracks with the name of album title)

It happens when: Hitting play in album page

My OS is: Windows

I'm using Nuclear version:0.6.10

**Comment by HaiDang666** [comment]
When you click play button in an album page, the app will add all album's tracks to the queue in order to play the whole album. This is expected behavior.

**Comment by azumukupoe** [comment]
I don't think you understand me...
An entire album gets queued as a track because some people upload full album as one file on YouTube

**Comment by HaiDang666** [comment]
I get it now. The album track list is from Discogs. It has an 0 duration track and the app still search for it on youtube
<img width="843" alt="Screen Shot 2021-03-09 at 09 26 23" src="https://user-images.githubusercontent.com/12780733/110409281-9b6f4d80-80b9-11eb-9e4c-93586f739080.png">

**Comment by HaiDang666** [comment]
I'm working on this.
