### ISSUE TITLE
Nuclear opens but won't scroll down to let me see playlists and more

### ISSUE THREAD

**Issue by Scholar-Doctor** [nukeop/nuclear#875]
Nuclear opens but won't scroll down to let me see playlists and more. I am stuck with what you see here and cannot scroll down to view anything else: 

![Nuclear](https://user-images.githubusercontent.com/80606087/111053921-ecb27080-841c-11eb-98b3-1496be18110f.png)

**Comment by nukeop** [comment]
Looks like the sidebar menu got too long, I guess without enlarging the window vertically you won't be able to see these options.

**Comment by HaiDang666** [comment]
fixed in https://github.com/nukeop/nuclear/pull/869
