### ISSUE TITLE
Not finding artist "Arv V"

### ISSUE THREAD

**Issue by Quantalabs** [nukeop/nuclear#889]
**Fill in the form to describe your problem**
I have a problem with: Artist [Arv V](https://arv-v.bandcamp.com) on Bandcamp
It happens when: Search up artist "Arv V" and the artist is the first result, with provider Bandcamp. Then, click on the artist, and returns "Failed to find artist Arv V. Using Bandcamp Meta Provider," yet the artist shows up when searching.
![image](https://user-images.githubusercontent.com/55121845/112741180-26fd3100-8f38-11eb-8a16-738d199e8ea1.png)
![image](https://user-images.githubusercontent.com/55121845/112741217-70e61700-8f38-11eb-90d8-eabb4da0ebed.png)

My OS is: Windows
I'm using Nuclear version: 0.6.10

**Comment by HaiDang666** [comment]
It maybe related to internet connection, I can load this artist and his 2 albums

**Comment by Quantalabs** [comment]
Yeah I think so.
