### ISSUE TITLE
Overflow of left sidebar for small window size

### ISSUE THREAD

**Issue by rubenhorn** [nukeop/nuclear#891]
**Problem:**  
When using the app in non maximized mode with a small window size, the vertically overflowing part of the left sidebar is cut of without a scrollbar.  
This means that it is not possible to, for example, click on "Local Library" or my playlists without first resizing or maximizing the window.

**Proposed solution:**  
Make the left sidebar vertically scrollable (like the queue).

**Comment by nukeop** [comment]
Fixed in new release.
