### ISSUE TITLE
The flatpak package got jannied because the maintainer doesn't like your opinions

### ISSUE THREAD

**Issue by JustAHumanBean** [nukeop/nuclear#898]
I noticed a new "update" to the flatpak package. Apparently the maintainer discontinued the package because he doesn't like your opinions or something. For now I had to switch to the snap package.

![image](https://user-images.githubusercontent.com/17130206/113478188-4377fc80-9455-11eb-90e4-90d54e24e5ff.png)

**Comment by nukeop** [comment]
I know, working on it with flathub admins.
