### ISSUE TITLE
Nuclear 6.11 AppImage still slow to open as version 6.10 & Feature suggestion

### ISSUE THREAD

**Issue by leirbag28** [nukeop/nuclear#901]
Before you open a new issue, check this for solutions to some common problems:
https://nuclearmusic.readthedocs.io/en/latest/troubleshooting/
If you want to open a new issue anyway, delete this text.

Also 6.11 has problems finding the first song on my Favorites playlist as did 6.10, 6.9 works fine.
Have not tested the 6.11.deb though.  so I am still using version 6.9 both the .deb and the AppImage.

May I suggest a Feature:  Ability to detach the Visualizer to a window that can also go full screen by double clicking, pressing "f" and that it can randomize visuals on its own and NOT show the name of the songs embedded in the Visualizer.

**Comment by HaiDang666** [comment]
can u give the name of incorrect songs? or the whole playlist

**Comment by nukeop** [comment]
Upgrade to newer node and Electron improved startup time
