### ISSUE TITLE
Clicking "Log in with Github" causes white box to open.

### ISSUE THREAD

**Issue by goralight** [nukeop/nuclear#904]
**Note: This was after I logged in the first time.**
If you try and log in with github via the settings page, a white box appears and nothing happens.

Steps:
1. go to settings
2. click login to github
3. give details and login
4. notice how Nuclear is still stating to login
5. click login to github once more
6. white box appears and nothing happens

Nuclear still states that I am not logged in also.

**Comment by geckonyc** [comment]
Additionally, if you press sign up by accident, it also goes to a white box. All following attempts to login through settings will do the same

**Comment by nukeop** [comment]
This box should contain the github login page, I'll see if it stopped working.

**Comment by nukeop** [comment]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/12746779/114632167-9ea7bb80-9cad-11eb-9bc6-ff7ba8172357.png">

Looks like this on my PC

**Comment by zapormi** [comment]
I have the same problem as these guys, it only stops working *after* inputting login information. After clicking login or sign up it turns into a white box and no longer works, even after restarting.

**Comment by goralight** [comment]
Yeah, after you have given the login details, you then just get a white box. If you click on login once more you will just keep getting white boxes. Note, that I am on Windows 10

![](https://i.imgur.com/FquHZal.png)

**Comment by nukeop** [comment]
I removed this option since it does nothing at the moment.
