### ISSUE TITLE
Playback issue on Windows, tracks seemingly randomly jumping a few second back

### ISSUE THREAD

**Issue by markovicaleksandar1312** [nukeop/nuclear#906]
As the title says, during playback tracks will sometimes just jump a few seconds back and then keep playing normally, kind of similar to skipping you get with damaged CDs. Usually happens at the beginning of the track, so my guess would be some kind issue with loading.
I'm running Windows 10 1709 build 16229.1087

**Comment by nukeop** [comment]
What song is it? Can you copy the stream id?

**Comment by markovicaleksandar1312** [comment]
Happens with almost every song for the first 30 - 40 seconds. How do I copy the stream ID on Windows client?

**Comment by nukeop** [comment]
Right click the track in the queue and the id should be there, but if it happens with every song we'll need someone with Windows to confirm.

**Comment by markovicaleksandar1312** [comment]
The last one I tried is vVXVwiVVjrc, but as I said it appears to happen while the track is loading. I am currently replaying this same track after I already played it and it works fine

**Comment by nukeop** [comment]
Can you check the newest release and tell me if it still occurs? I have a suspicion this was caused by another bug that was fixed and slow disk i/o on Windows might have caused skipping playback.

**Comment by markovicaleksandar1312** [comment]
Works fine now. I'd say it's fixed
