### ISSUE TITLE
Add installation instructions to the readme and website

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#907]
Add a section with installation instructions for all the different distros, e.g.

| Distro | Installation method |
|:-:|:-:|
| Arch/Manjaro | `yay -s nuclear-player-bin` |

And so on for all the other ways to install Nuclear - flatpak, snap, appimage, homebrew, chocolatey...
Make it as easy as possible to just copy & paste the command and install.
Then we can do the same for the website (after styling it consistently with the rest of the page).

**Comment by UdattaChowdhury** [comment]
Hello Maintainer. I am a beginner in open-source. I would like to work on this issue. Would you please guide me?

**Comment by nukeop** [comment]
You could first take a look at all the packages we already have listed in the readme, and for each one add a code snippet that could be copy-pasted into the terminal to install that package. Ideally that would be a new column in the existing table.

 Then optionally, you could write instructions for each package in the release section.

**Comment by nukeop** [comment]
Closed by #920
