### ISSUE TITLE
FR: Named player in PulseAudio

### ISSUE THREAD

**Issue by gerroon** [nukeop/nuclear#914]
Hi

As of now the app shows up as "Chromium" under PulseAudio settings whichs means that it shares the same audio settings as Chromium. It would be nice if it shows up as its own player name so that the player have its own PA settings, sinks  etc.

![raw](https://user-images.githubusercontent.com/8519469/115431613-1e141e00-a1cb-11eb-91b4-909431081d7c.jpeg)

thanks

**Comment by nukeop** [comment]
Duplicate of #824
