### ISSUE TITLE
Icon now visible Debian Buster KDE 

### ISSUE THREAD

**Issue by swarupbhanjachowdhury** [nukeop/nuclear#916]
Before you open a new issue, check this for solutions to some common problems:
https://nuclearmusic.readthedocs.io/en/latest/troubleshooting/
If you want to open a new issue anyway, delete this text.

App Icon/Logo not visible in Debian Buster KDE version, Installed with .deb file.

 
![image](https://user-images.githubusercontent.com/55395995/115685857-3e341080-a376-11eb-9173-b2d1bf7cc90e.png)

**Comment by nukeop** [comment]
Duplicate of #374
