### ISSUE TITLE
Import by ur,

### ISSUE THREAD

**Issue by OhShitNation** [nukeop/nuclear#944]
**Platform: Dell 7220 Rugged Tablet (Windows 10)

**Nuclear version: 0.6.13

**Description of the issue: How do you? It suggests it because I have no playlists but there is no button to do so on the playlists page. :(

**Comment by nukeop** [comment]
If you add some songs to the queue you can use the queue dropdown to create a playlists from them. From that point, you can add songs to the playlist from any popup.
