### ISSUE TITLE
Unify dependency versions across packages

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#946]
When installing the dependencies, we get a lot of lines that look like this:
`lerna WARN EHOIST_PKG_VERSION "@nuclear/ui" package depends on babel-eslint@^7.2.3, which differs from the hoisted babel-eslint@^10.0.3.`

This happens when there is the same module with different versions listed as a dependency in different packages in our monorepo.

It would be good to use the same version of every package everywhere, where possible. This tool can help in bringing the dependencies up to date across multiple packages: https://www.npmjs.com/package/lerna-update-wizard

**Comment by HaiDang666** [comment]
resolved in https://github.com/nukeop/nuclear/pull/947
