### ISSUE TITLE
Add current track info/pause/next/previous track on top bar menu in macos

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#950]
<img width="285" alt="Screen Shot 2021-05-22 at 11 06 51 am" src="https://user-images.githubusercontent.com/12780733/119214030-d1837180-baed-11eb-8cb7-2e843688097f.png">

also replace the app name by nuclear icon

**Comment by nukeop** [comment]
I thought the icon worked (last time I tested it on mac was long ago).
