### ISSUE TITLE
Re-rolling is unclear

### ISSUE THREAD

**Issue by KyleFN** [nukeop/nuclear#953]
"Try re-rolling" is unclear. How do you reroll? I presume it's double-clicking the song in the queue, but I can't tell if that's correct because there's no visual feedback. 

Maybe pop-up an error message or show what link is being tried now, perhaps underneath the previous/next song buttons.

**Comment by nukeop** [comment]
You can reroll by right-clicking the song and clicking the rotating arrows icon. In the future, we will replace this with a list of all streams that were found for this particular track and you will be able to select one from a dropdown.

**Comment by KyleFN** [comment]
Sounds good. In the meantime I think it'd help a lot just changing "Try re-rolling" to "Right-click for re-rolling options" or similar. 

Also I'd recommend the YouTube and other links be made into hyperlinks, that way the user can see if they load in a browser and it'll help for reporters to more easily recognise when Nuclear should have been able to play a song but couldn't.

**Comment by nukeop** [comment]
This has been replaced with the dropdown
