### ISSUE TITLE
Playlists can't be created

### ISSUE THREAD

**Issue by jotyGill** [nukeop/nuclear#96]
Hi,
Thanks again for this amazing software. I am using the latest release (app image). I can't seem to add a song to a playlist. when I click on the save icon, it asks for the name of the playlist but when I type a name for it and press enter or click 'save' it just sits there as if I never clicked on it. Just wondering if it's a known issue.

**Comment by nukeop** [comment]
Thanks for reporting, I was able to reproduce this issue. I'll look into fixing it today.

**Comment by nukeop** [comment]
I pinpointed the bug, it was created when I changed the config file format. You'll have to delete your config file so it can be regenerated by nuclear. Or you can change the 'playlists' key in it from {} to [].

**Comment by Fyffe** [comment]
I downloaded Nuclear today and this bug is still present. My config was created with {} instead of [] in playlists key.

**Comment by nukeop** [comment]
Since this was fixed after the 0.4.3 release, you'll need to wait for 0.4.4.
