### ISSUE TITLE
UI issue: overlap album name and favorite icon

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#960]
<img width="483" alt="Screen Shot 2021-05-31 at 11 16 11" src="https://user-images.githubusercontent.com/12780733/120138962-b73e4780-c201-11eb-88aa-5f7c3dcc0349.png">

<img width="531" alt="Screen Shot 2021-05-31 at 11 15 22" src="https://user-images.githubusercontent.com/12780733/120138968-bb6a6500-c201-11eb-8eeb-97e58e38c397.png">

overlap `album name` and `favorite icon`

**Comment by nukeop** [comment]
There's an `ellipsis` mixin in the common scss file, this should do the trick.

**Comment by jamieeunice** [comment]
@nukeop I'm currently working on this.

**Comment by nukeop** [comment]
Nice, thank you.
