### ISSUE TITLE
[QUESTION/FEATURE REQUEST] assigning nuclear to only have certain services

### ISSUE THREAD

**Issue by lewlepton** [nukeop/nuclear#962]
**Platform:**
macOS

**Nuclear version:**
0.6.13

**Description of the issue:**
this is more of a request or question. but can nuclear *only* have specific services?
so if I wanted to only have Bandcamp, it only has bandcamp etc

if not, id like to ask if this could be put forward as a feature

thanks & thank you for the work on this
♥️

**Comment by nukeop** [comment]
What's the use case?

**Comment by lewlepton** [comment]
its to keep things simple. personally, I only use bandcamp. but aside from that, I feel its a good feature. but also for other services as well for other users that want specific things

basically, its to separate things to make it easier in the long run

I've found when I pop onto nuclear, it feels 'too much', since there are other things wanting to show me what they are. can become a bit much to deal with

again, thank you for the amazing work put into this
♥️

**Comment by nukeop** [comment]
If you don't change any settings, by default it will only play streams from youtube. The plugin you select as the streaming source, will be the only source for new songs added to the queue.

**Comment by lewlepton** [comment]
fantastic. I missed the plugins, evidently

again, thanks. but just as a side question. is there any way to log in to bandmp [or whatever service] from nuclear? just so I can access my library

thanks again
♥️

**Comment by nukeop** [comment]
Happy to help. Currently we don't have any way to log into bandcamp from Nuclear unfortunately.

**Comment by lewlepton** [comment]
fair enough. good to know

thanks
