### ISSUE TITLE
Broken list of playlist when clicking on single track in play queue

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#963]
this should display as same as clicking on queue popup

<img width="472" alt="Screen Shot 2021-06-02 at 15 21 57" src="https://user-images.githubusercontent.com/12780733/120581092-6b371100-c454-11eb-8711-88669f2ad316.png">

**Expected**

<img width="545" alt="Screen Shot 2021-06-02 at 15 21 49" src="https://user-images.githubusercontent.com/12780733/120581058-63776c80-c454-11eb-86fd-0f3ae653bcce.png">

**Comment by nukeop** [comment]
Maybe we could make it display the playlists in the same box as the popup, like Deezer?

**Comment by HaiDang666** [comment]
> Maybe we could make it display the playlists in the same box as the popup, like Deezer?

that is possible for when users have a laundry list of playlists

**Comment by GeorgeArubi** [comment]
Is this issue still open? And if it is can I be assigned to it?

**Comment by nukeop** [comment]
I assigned you.

**Comment by Pranjal-dew** [comment]
Hi, is this issue still open? Care if I take it?

**Comment by HaiDang666** [comment]
Sure, I think the previous guy abandoned it

**Comment by PriyanshX1902** [comment]
@HaiDang666 is this issue still open? can i take this issue?

**Comment by HaiDang666** [comment]
@PriyanshX1902 yes

**Comment by anthonyvkane** [comment]
hey is this still open

**Comment by HaiDang666** [comment]
Yes, it seems abandoned.

**Comment by anthonyvkane** [comment]
can i have it :)

**Comment by HaiDang666** [comment]
I assigned to u
