### ISSUE TITLE
Can not open Local Library

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#969]
**Platform: macOS**

**Nuclear version: 0.6.14**

**Description of the issue: **
I think it relates with `packages/main/src/services/local-library/db.ts`, need more investigation. 

<img width="517" alt="Screen Shot 2021-06-14 at 12 13 26" src="https://user-images.githubusercontent.com/12780733/121845899-5db13f00-cd10-11eb-9db5-8cfd447d6917.png">

when logging `localFolders`
<img width="375" alt="Screen Shot 2021-06-14 at 12 13 07" src="https://user-images.githubusercontent.com/12780733/121845951-6b66c480-cd10-11eb-9da3-06e9ee3b6bf9.png">

![Screen Shot 2021-06-14 at 13 06 37](https://user-images.githubusercontent.com/12780733/121846764-bcc38380-cd11-11eb-878e-d0eefed2db68.png)

**Comment by nukeop** [comment]
hmm, try deleting the index and rescanning?

**Comment by HaiDang666** [comment]
it looks fine now. I'm gonna close this.
