### ISSUE TITLE
Improve appearance when playing livestream

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#970]
<img width="1412" alt="Screen Shot 2021-06-15 at 09 43 22" src="https://user-images.githubusercontent.com/12780733/121985361-d1118a00-cdbe-11eb-8cfa-940ea300e2e1.png">

Design up to contributor.

**Comment by nukeop** [comment]
This should either say "live" or be removed altogether for live streams.

**Comment by HaiDang666** [comment]
yes, anything that directly showing the livestream is playing

**Comment by jyggiz** [comment]
Hello everyone, can I take this issue?

**Comment by nukeop** [comment]
Sure, I assigned you. It should be pretty easy, you just have to modify the QueueItem component.

**Comment by HaiDang666** [comment]
Is it better to make seekbar fill with full color?

**Comment by nukeop** [comment]
By default it should be full, if you want you can animate it as a bonus (like this: https://react.semantic-ui.com/modules/progress/#types-indicating or another type of animation)

**Comment by pcastro3** [comment]
Hi everyone, is this issue still open? I'd like to work on this as my first issue

**Comment by nukeop** [comment]
It's still open, and I assigned you to it.

**Comment by jreiser1** [comment]
Hello, my partner and I have a prototype solution to this, but we are still working out some minor bugs. Could we be assigned to this issue?

**Comment by nukeop** [comment]
Sure, I assigned you

**Comment by nukeop** [comment]
I saw some commits recently here: https://github.com/MSU-CS4360-Nuclear/nuclear

So I guess they're working on it.

**Comment by jreiser1** [comment]
I think I've found the source of the problem I mentioned before, but I'm having a hard time tracing the execution of the code to fix it. It appears that the startPlayback function in actions/player.js is being invoked prior to a URL being returned from SponsorBlock. This occurs when the user plays a livestream after playing a normal (i.e. non-livestream) song, and it results in the previous song being played for a few seconds until the SponsorBlock URL is returned. Once the SponsorBlock URL is returned, the prior song's audio stops, the livestream audio begins playing, and the livestream PlayerBar is rendered as expected. This audio/UI bug does not occur when toggling between other normal songs, nor while toggling between livestreams. Only playing a livestream after playing a normal song causes this problem. 

Other than that, the livestream UI works just fine. Any thoughts on how to proceed? Is there somewhere else that startPlayback is invoked that I should add a check for livestreams or something like that?

**Comment by nukeop** [comment]
Can you open a pull request? It will be easier to figure out what's happening. I tried looking for changes here https://github.com/MSU-CS4360-Nuclear/nuclear/blob/master/packages/ui/lib/components/Seekbar/index.tsx but I couldn't find anything new so I'm looking at the wrong code. I don't know why sponsorblock would influence this, since live tracks have a flag you can use to just render the seekbar differently.

**Comment by jreiser1** [comment]
Sure, I'll open a pull request. The rendering isn't the issue anymore, it's that a previous song will play for a few seconds before the SponsorBlock url is returned (may not be directly related, this is just the pattern I noticed), and then livestream seekbar will be rendered as expected.
