### ISSUE TITLE
Export json file

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#971]
It should be able to export json in album, playlist and favorite tracks view.

**Comment by nukeop** [comment]
The button for this should be placed under the ellipsis menu in playlist view.

**Comment by 3r3n-n** [comment]
Hi ! I am interested in working on this (trying to make my first OS contribution and I'm enthusiastic about this project) 
...if that’s okay, could you tell me about the relevant files that I should look into ?

**Comment by nukeop** [comment]
Ok, I assigned you.

The playlist view is here: https://github.com/nukeop/nuclear/blob/master/packages/app/app/components/PlaylistView/index.tsx
It should take another callback as a prop that will export the current playlist. Then you should add a popup button to the context popup that will fire this callback.

You can read how to open file save dialogs in electron here: https://www.electronjs.org/docs/api/dialog
You can also search by "dialog" to find examples that are already in the program.

The callback functionality should be defined in this container:
https://github.com/nukeop/nuclear/blob/master/packages/app/app/containers/PlaylistViewContainer/index.js
 
Of course, before writing the functionality, you should write a test for it here:
https://github.com/nukeop/nuclear/blob/master/packages/app/app/containers/PlaylistViewContainer/PlaylistViewContainer.test.tsx

We're using jest and testing-library for writing tests, you can read more about it here: https://testing-library.com/docs/react-testing-library/intro/

**Comment by nukeop** [comment]
Feel free to join our Discord or Matrix chat, or ask here if you have any more questions.

**Comment by 3r3n-n** [comment]
Great, thank you !!

**Comment by 3r3n-n** [comment]
Hii !! 
I was able to implement the export button functionality and manually tested it, now I am checking the testing-library docs for the test that I should write… although I am still not sure about what exactly I should be testing… I was thinking about:

A) Asserting that the save dialog does show.
B) Importing the exported file and asserting that a new playlist could actually be created with it (I did it manually and it worked fine but I am wondering if it is viable to write a test that does it)

What do you think ?

https://user-images.githubusercontent.com/82424931/123306672-3532fd00-d4e7-11eb-9e73-c6dcc544b966.mov

**Comment by HaiDang666** [comment]
nice work. I think make a test to check exported playlist data should be enough. btw it will be nice if you set the playlist name to be as default file name instead of 'untitled'

**Comment by nukeop** [comment]
A & B sounds good, you should check if the dialog window opens and that a callback exporting the playlist gets called with proper arguments. You should also check the function that generates the json for correctness with at least a few different cases.

**Comment by nukeop** [comment]
BTW, f you haven't already, make sure that the strings are localized through i18next (it's fine to only add English versions).

**Comment by 3r3n-n** [comment]
Ok !!
Wrote the test today considering that.
Everything was passing so I just [created a PR](https://github.com/nukeop/nuclear/pull/981).
Also incorporated what @HaiDang666 suggested so the default file name is the same as the playlist name (added another screen video in the PR so you can see it there).

**Comment by 3r3n-n** [comment]
Hi everyone, I wanted to ask if I can do another PR with the export-as-JSON functionality in **album** and/or **favorite tracks** view, what do you think ?

**Comment by HaiDang666** [comment]
Yes I expect this function in album and favorite tracks too

**Comment by nukeop** [comment]
What's the point of exporting albums?

And favorite tracks are already saved in config.json - we can't import them anyway (other than from last.fm).

**Comment by 3r3n-n** [comment]
Ooh, I see. I had not thought about what @nukeop mentioned.

**Comment by HaiDang666** [comment]
> What's the point of exporting albums?
> 
> And favorite tracks are already saved in config.json - we can't import them anyway (other than from last.fm).

I understand album but I don't get the favorite part?

**Comment by HaiDang666** [comment]
closes #981
