### ISSUE TITLE
Migrate Spotify playlists to Nuclear

### ISSUE THREAD

**Issue by cristiean** [nukeop/nuclear#978]
[This script](https://github.com/caseychu/spotify-backup) offers an option to export all of your spotify playlists as JSON.

What's cool is that it has everything you need (and much, much more, e.g. urls to thumbnails of 3 sizes, track name, artists, available markets, etc.)

Would this offer all of the data needed to import the playlists in Nuclear?

If yes, then I think it would be very beneficial for the users to have an easy way to migrate their playlists from Spotify.

We could even include the script's logic as a button in Nuclear itself, or we could add some guides on the Documentation to how users can do this themselves.

**Comment by nukeop** [comment]
We have this script as a temporary solution: https://github.com/HaiDang666/extract-sptf-playlist

Long term, I will integrate this into the playlist service I'm working on currently.
