### ISSUE TITLE
Replace dbus/mpris with pure js module

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#98]

**Comment by nukeop** [comment]
Moved to 0.6.0.

**Comment by acrisci** [comment]
I'm working on [mpris-service](https://github.com/emersion/mpris-service) and going around doing mpris implementations on electron players. Is this still needed?

**Comment by nukeop** [comment]
Yes, and in fact we were using your module originally, but dropped support due to problems with packaging the native dbus module in Appimage and other formats. Seeing as you've apparently transitioned to another dbus interface, we could be able to restore the code we've removed temporarily.

**Comment by acrisci** [comment]
Ok cool. I have commit access to the [underlying dbus library](https://github.com/acrisci/node-dbus-next) so if you have any problems with it we can fix it.

**Comment by acrisci** [comment]
I'm looking at this now. I tested some of the old mpris code and it doesn't work when I put it into the latest.

Trying to figure out how to programatically get the player to play, set the volume, set the position, etc. The actions seem to be tied up in the react components and I don't know much about react.

**Comment by nukeop** [comment]
I used to handle this on the server side, with no contact with React.

Some commented out code is here:
https://github.com/nukeop/nuclear/blob/master/server/main.dev.linux.js

**Comment by nukeop** [comment]
The idea is that the React part sends the relevant events via ipc, and the Electron part parses them and uses mpris to set everything as needed.

**Comment by acrisci** [comment]
Ah ok the only things that are not implemented to be fully compatible with [playerctl](https://github.com/acrisci/playerctl) are:

* [ ] a getter to return the position in the current track when requested from dbus
* [ ] a player event when the track seeks to a new position
* [ ] a way to set the volume on the player
* [ ] a way to know when the volume changes
* [ ] a way to set the shuffle status on the player
* [ ] a way to know when the shuffle status on the player changes
* [ ] a way to get the loop status of the player
* [ ] a way to know when the loop status of the player changes
* [ ] a way to open a file from a uri

**Comment by nukeop** [comment]
Done by @charjac
