### ISSUE TITLE
Cannot create a playlist on Nuclear

### ISSUE THREAD

**Issue by Nakk69** [nukeop/nuclear#988]
**Platform:** PC

**Nuclear version:** 6.15

**Description of the issue:** I just cannot create a playlist in the soft, i guess its a bug or functionnality not implemented ?
help me thx

**Comment by nukeop** [comment]
Add the songs you want to the queue, then use the ellipsis menu in the queue panel to save the queue as a playlist. From then on, you can add songs from pretty much anywhere.
