### ISSUE TITLE
DUDE IS THAT COOL!

### ISSUE THREAD

**Issue by UnixCro** [nukeop/nuclear#998]
Awesome program man ! Just crazy. Thanks for this amazing program. Have certainly made many a pleasure!

**Comment by HaiDang666** [comment]
Thank u, but here is not the place for discussion. You can join Nuclear discord: https://discord.gg/JqPjKxE

**Comment by nukeop** [comment]
Thanks!

**Comment by nukeop** [comment]
Thanks, you made my day. It's always great reading such positive feedback.
