### ISSUE TITLE
Add a button to create an empty one though on the playlist screen

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#999]
as title

**Comment by mezeru** [comment]
Can you elaborate , I could not understand wym exactly

**Comment by HaiDang666** [comment]
Currently to create a playlist, we need to add tracks to `play queue` then `save as playlist`. This behavior is counterintuitive for many users so we should have a button on the playlist screen to create an empty playlist.

**Comment by mezeru** [comment]
Ah ! I see , I will try to fix it
